/* Generated by tests/fbgen from sidereon-core's
 * broadcast_spp_fallback_arc integration-test inputs (ESBC00DNK DOY177 GPS
 * C1C first epoch). The C smoke test feeds these engine-extracted
 * observations and solve inputs, the committed broadcast NAV, and the
 * committed SP3 products through the C ABI and asserts the engine's
 * broadcast/fallback source + staleness provenance. Do not edit by hand;
 * rerun the generator. */
#ifndef SIDEREON_BROADCAST_FIXTURE_H
#define SIDEREON_BROADCAST_FIXTURE_H

#include <stdint.h>
#include <stddef.h>

#define BC_NAV_FILE "ESBC00DNK_R_20201770000_01D_MN.rnx"
#define BC_PRECISE_SP3_FILE "COD0MGXFIN_20201770000_01D_05M_ORB.SP3"
#define BC_PRIOR_SP3_FILE "GAP_G01_20201760000_15M.sp3"
#define BC_WRONG_EPOCH_SP3_FILE "IGS0OPSFIN_20261200945_02H30M_15M_ORB.SP3"

static const double BC_VS_PRECISE_POSITION_BOUND_M = 20.0;

static const uint64_t BC_T_RX_J2000_S_BITS = UINT64_C(0x41c342fe60000000);
static const uint64_t BC_T_RX_SOD_S_BITS = UINT64_C(0x0000000000000000);
static const uint64_t BC_DOY_BITS = UINT64_C(0x4066200000000000);
static const uint64_t BC_INITIAL_GUESS_BITS[4] = { UINT64_C(0x414b544ca53f7cee), UINT64_C(0x412040db766cf41f), UINT64_C(0x4153f61cb38bac71), UINT64_C(0x0000000000000000) };
static const uint64_t BC_PRESSURE_HPA_BITS = UINT64_C(0x408faa0000000000);
static const uint64_t BC_TEMPERATURE_K_BITS = UINT64_C(0x4072026666666666);
static const uint64_t BC_RELATIVE_HUMIDITY_BITS = UINT64_C(0x3fe0000000000000);

#define BC_OBS_COUNT 12
static const char *const BC_SAT_IDS[BC_OBS_COUNT] = {
    "G02",
    "G05",
    "G07",
    "G08",
    "G09",
    "G13",
    "G15",
    "G18",
    "G21",
    "G27",
    "G28",
    "G30",
};

static const uint64_t BC_PSEUDORANGE_BITS[BC_OBS_COUNT] = {
    UINT64_C(0x4178a663dbeb851f),
    UINT64_C(0x4173fa164ee56042),
    UINT64_C(0x4174c4b1e4c08312),
    UINT64_C(0x4177d413a483126f),
    UINT64_C(0x4177688b4e147ae1),
    UINT64_C(0x4174b0c52f0624dd),
    UINT64_C(0x4176efab1f26e979),
    UINT64_C(0x4177058e24a3d70a),
    UINT64_C(0x41791332888b4396),
    UINT64_C(0x41779bc953a5e354),
    UINT64_C(0x41765ace62cccccd),
    UINT64_C(0x4173aa8312083127),
};

#endif /* SIDEREON_BROADCAST_FIXTURE_H */
