/*
 * 0.18 domain exposure smoke: GNSS/INS fusion, deterministic scenarios, and
 * signal-analysis closed forms. Every numeric result is produced by
 * sidereon-core through the C ABI.
 */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Engine values regenerated by tests/pingen and tests/valgen (w4_d018). */
#include "engine_pins_fixture.h"
#include "w4_d018_pins.h"

#include "sidereon.h"

static int failures = 0;

static void check(int ok, const char *what) {
    if (!ok) {
        char msg[512];
        size_t n = sidereon_last_error_message(msg, sizeof(msg));
        if (n == 0) {
            msg[0] = '\0';
        }
        /* The last error is sticky and may come from an earlier call, so it is
           reported as context rather than as the cause of this failure. */
        if (msg[0] != '\0') {
            fprintf(stderr, "FAIL: %s (last ABI error, may predate this check: %s)\n",
                    what, msg);
        } else {
            fprintf(stderr, "FAIL: %s\n", what);
        }
        failures++;
    }
}

static uint64_t f64_bits(double value) {
    uint64_t bits = 0;
    memcpy(&bits, &value, sizeof(bits));
    return bits;
}

static void check_bits(double actual, uint64_t expected, const char *what) {
    check(f64_bits(actual) == expected, what);
}

/* FNV-1a 64 over the bytes of a double array; the generated pins carry the
 * same hash of the engine's values. */
static uint64_t fnv1a64(const void *data, size_t len) {
    const uint8_t *bytes = (const uint8_t *)data;
    uint64_t hash = UINT64_C(0xcbf29ce484222325);
    for (size_t i = 0; i < len; i++) {
        hash ^= bytes[i];
        hash *= UINT64_C(0x00000100000001b3);
    }
    return hash;
}

static void check_vec_bits(const double *actual,
                           const uint64_t *expected,
                           size_t count,
                           const char *label) {
    char what[160];
    for (size_t i = 0; i < count; i++) {
        snprintf(what, sizeof(what), "%s[%zu] bits", label, i);
        check_bits(actual[i], expected[i], what);
    }
}

static void check_label(SidereonStatus (*fn)(uint32_t, uint8_t *, size_t, size_t *, size_t *),
                        uint32_t value,
                        const char *expected,
                        const char *what) {
    uint8_t buf[64];
    size_t written = 0;
    size_t required = 0;
    memset(buf, 0, sizeof(buf));
    check(fn(value, buf, sizeof(buf), &written, &required) == SIDEREON_STATUS_OK &&
              written == strlen(expected) && required == strlen(expected) &&
              memcmp(buf, expected, strlen(expected)) == 0,
          what);
}

static void copy_state_position(const SidereonFusionState *state,
                                SidereonFusionLooseMeasurement *measurement,
                                double t_j2000_s,
                                const double *covariance,
                                size_t covariance_len) {
    memset(measurement, 0, sizeof(*measurement));
    measurement->t_j2000_s = t_j2000_s;
    measurement->position_ecef_m[0] = state->position_ecef_m[0];
    measurement->position_ecef_m[1] = state->position_ecef_m[1];
    measurement->position_ecef_m[2] = state->position_ecef_m[2];
    measurement->has_velocity = false;
    measurement->covariance = covariance;
    measurement->covariance_len = covariance_len;
    measurement->satellites_used = 4;
    measurement->solution_valid = true;
    measurement->fix_status = SIDEREON_FUSION_GNSS_FIX_STATUS_SINGLE;
}

static void identity_matrix(double *matrix, size_t dimension) {
    memset(matrix, 0, dimension * dimension * sizeof(double));
    for (size_t i = 0; i < dimension; i++) {
        matrix[i * dimension + i] = 1.0;
    }
}

static void set_zero_imu_spec(SidereonFusionFilterConfig *config) {
    config->imu_spec.accel_vrw_mps_sqrt_s = 0.0;
    config->imu_spec.gyro_arw_rad_sqrt_s = 0.0;
    config->imu_spec.accel_bias_instab_mps2 = 0.0;
    config->imu_spec.gyro_bias_instab_rps = 0.0;
    config->imu_spec.accel_bias_tau_s = INFINITY;
    config->imu_spec.gyro_bias_tau_s = INFINITY;
    config->imu_spec.has_accel_scale_instab_ppm = false;
    config->imu_spec.accel_scale_instab_ppm = 0.0;
    config->imu_spec.has_gyro_scale_instab_ppm = false;
    config->imu_spec.gyro_scale_instab_ppm = 0.0;
}

static void init_field_config(SidereonFusionFilterConfig *config) {
    check(sidereon_fusion_filter_config_init(config) == SIDEREON_STATUS_OK,
          "fusion field config init");
    set_zero_imu_spec(config);
}

static SidereonFusionFilter *create_field_filter(const SidereonFusionFilterConfig *config,
                                                 const SidereonFusionNavState *nav,
                                                 const char *label) {
    double diag[15];
    for (size_t i = 0; i < 15; i++) {
        diag[i] = 1.0;
    }
    SidereonFusionFilter *filter = NULL;
    check(sidereon_fusion_filter_create(nav, diag, 15, config, &filter) == SIDEREON_STATUS_OK &&
              filter != NULL,
          label);
    return filter;
}

static void init_position_velocity_fix(SidereonFusionLooseMeasurement *measurement,
                                       double t_j2000_s,
                                       const double position[3],
                                       const double velocity[3],
                                       const double *covariance,
                                       uint32_t fix_status) {
    memset(measurement, 0, sizeof(*measurement));
    measurement->t_j2000_s = t_j2000_s;
    memcpy(measurement->position_ecef_m, position, sizeof(measurement->position_ecef_m));
    measurement->has_velocity = true;
    memcpy(measurement->velocity_ecef_mps, velocity, sizeof(measurement->velocity_ecef_mps));
    measurement->covariance = covariance;
    measurement->covariance_len = 36;
    measurement->satellites_used = 8;
    measurement->solution_valid = true;
    measurement->fix_status = fix_status;
}

static void init_default_position_velocity_fix(SidereonFusionLooseMeasurement *measurement,
                                               const double *covariance,
                                               uint32_t fix_status) {
    const double position[3] = {6378138.0, 2.0, -3.0};
    const double velocity[3] = {0.4, -0.2, 0.1};
    init_position_velocity_fix(measurement, 0.0, position, velocity, covariance, fix_status);
}

static void check_filter_cov_diag_bits(SidereonFusionFilter *filter,
                                       size_t offset,
                                       const uint64_t *expected,
                                       size_t count,
                                       const char *label) {
    double covariance[225];
    size_t written = 0, required = 0;
    check(sidereon_fusion_filter_covariance(filter, covariance, 225, &written, &required) ==
              SIDEREON_STATUS_OK &&
              written == W4_D018_FIFTEEN_COVARIANCE_LEN &&
                  required == W4_D018_FIFTEEN_COVARIANCE_LEN,
          label);
    char what[160];
    for (size_t i = 0; i < count; i++) {
        const size_t index = (offset + i) * 15 + (offset + i);
        snprintf(what, sizeof(what), "%s diag[%zu] bits", label, offset + i);
        check_bits(covariance[index], expected[i], what);
    }
}

static void test_signal_analysis(void) {
    SidereonSignalAnalysisModulation bpsk = {
        SIDEREON_SIGNAL_ANALYSIS_MODULATION_KIND_BPSK, 1.0, 0.0, 0.0};
    SidereonSignalAnalysisModulation boc = {
        SIDEREON_SIGNAL_ANALYSIS_MODULATION_KIND_BOC_SINE, 0.0, 1.0, 1.0};
    SidereonSignalAnalysisModulation boc_cosine = {
        SIDEREON_SIGNAL_ANALYSIS_MODULATION_KIND_BOC_COSINE, 0.0, 10.0, 5.0};
    SidereonSignalAnalysisModulation mboc = {
        SIDEREON_SIGNAL_ANALYSIS_MODULATION_KIND_MBOC611_OVER11, 0.0, 0.0, 0.0};
    SidereonSignalAnalysisModulation tmboc = {
        SIDEREON_SIGNAL_ANALYSIS_MODULATION_KIND_TMBOC614_OVER33, 0.0, 0.0, 0.0};
    SidereonSignalAnalysisModulation cboc_plus = {
        SIDEREON_SIGNAL_ANALYSIS_MODULATION_KIND_CBOC611_OVER11_PLUS, 0.0, 0.0, 0.0};
    SidereonSignalAnalysisModulation cboc_minus = {
        SIDEREON_SIGNAL_ANALYSIS_MODULATION_KIND_CBOC611_OVER11_MINUS, 0.0, 0.0, 0.0};
    double value = 0.0;

    check(sidereon_signal_reference_chip_rate_hz(&value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_REFERENCE_CHIP_RATE_BITS,
          "signal reference chip rate");
    check(sidereon_signal_betz_l1_receiver_bandwidth_hz(&value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_BETZ_L1_BANDWIDTH_BITS,
          "signal Betz L1 bandwidth");
    uint8_t label[32];
    size_t written = 0;
    size_t required = 0;
    memset(label, 0, sizeof(label));
    check(sidereon_signal_modulation_label(&bpsk, label, sizeof(label), &written, &required) ==
                  SIDEREON_STATUS_OK &&
              written == strlen(W4_D018_BPSK_LABEL) && required == strlen(W4_D018_BPSK_LABEL) &&
              memcmp(label, W4_D018_BPSK_LABEL, strlen(W4_D018_BPSK_LABEL)) == 0,
          "signal modulation label");
    check(sidereon_signal_modulation_code_rate_hz(&bpsk, &value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_BPSK_CODE_RATE_BITS,
          "signal modulation code rate");

    check(sidereon_signal_analysis_psd(&bpsk, 0.0, &value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_PSD_BPSK_0_BITS,
          "signal BPSK(1) PSD");
    check(sidereon_signal_psd_hz(&bpsk, 0.0, &value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_PSD_BPSK_0_BITS,
          "signal BPSK(1) PSD canonical");
    check(sidereon_signal_analysis_psd(&boc, 0.5 * 1023000.0, &value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_PSD_BOC_HALF_BITS,
          "signal BOCsin(1,1) PSD");
    check(sidereon_signal_analysis_psd(&boc_cosine, 0.5 * 1023000.0, &value) ==
                  SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_PSD_BOC_COSINE_HALF_BITS,
          "signal BOCcos(10,5) PSD");
    check(sidereon_signal_analysis_psd(&mboc, 0.5 * 1023000.0, &value) ==
                  SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_PSD_MBOC_HALF_BITS,
          "signal MBOC PSD");
    check(sidereon_signal_analysis_psd(&tmboc, 0.5 * 1023000.0, &value) ==
                  SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_PSD_TMBOC_HALF_BITS,
          "signal TMBOC PSD");
    check(sidereon_signal_analysis_psd(&cboc_plus, 0.5 * 1023000.0, &value) ==
                  SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_PSD_CBOC_PLUS_HALF_BITS,
          "signal CBOC plus PSD");
    check(sidereon_signal_analysis_psd(&cboc_minus, 0.5 * 1023000.0, &value) ==
                  SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_PSD_CBOC_MINUS_HALF_BITS,
          "signal CBOC minus PSD");
    check(sidereon_signal_analysis_fraction_power(&bpsk, 24000000.0, &value) ==
              SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_FRACTION_POWER_BITS,
          "signal fraction power");
    check(sidereon_signal_power_in_band(&bpsk, 24000000.0, &value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_POWER_IN_BAND_BITS,
          "signal power in band canonical");
    check(sidereon_signal_fraction_power_in_band(&bpsk, 24000000.0, &value) ==
                  SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_FRACTION_POWER_BITS,
          "signal fraction power canonical");
    check(sidereon_signal_analysis_rms_bandwidth_hz(&boc, 24000000.0, &value) ==
              SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_RMS_BANDWIDTH_BITS,
          "signal RMS bandwidth");
    check(sidereon_signal_rms_bandwidth_hz(&boc, 24000000.0, &value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_RMS_BANDWIDTH_BITS,
          "signal RMS bandwidth canonical");

    SidereonSignalAnalysisSpectralSeparation ssc;
    check(sidereon_signal_analysis_spectral_separation(&bpsk, &boc, 24000000.0, &ssc) ==
              SIDEREON_STATUS_OK &&
              f64_bits(ssc.hz) == W4_D018_SSC_HZ_BITS &&
              f64_bits(ssc.db_hz) == W4_D018_SSC_DB_HZ_BITS,
          "signal SSC");
    check(sidereon_signal_spectral_separation_coefficient_hz(&bpsk, &boc, 24000000.0,
                                                             &value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_SSC_HZ_BITS,
          "signal SSC scalar hz");
    check(sidereon_signal_spectral_separation_coefficient_db_hz(&bpsk, &boc, 24000000.0,
                                                                &value) == SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_SSC_DB_HZ_BITS,
          "signal SSC scalar db hz");
    check(sidereon_signal_white_noise_spectral_separation_hz(&bpsk, 24000000.0, &value) ==
              SIDEREON_STATUS_OK &&
              f64_bits(value) == W4_D018_WHITE_NOISE_SSC_BITS,
          "signal white-noise SSC scalar");

    SidereonSignalAnalysisInterference interference = {boc, 0.01};
    SidereonSignalAnalysisCn0Degradation degradation;
    check(sidereon_signal_analysis_effective_cn0_degradation(
              &bpsk, 45.0, 24000000.0, &interference, 1, &degradation) == SIDEREON_STATUS_OK &&
              f64_bits(degradation.effective_cn0_hz) == W4_D018_EFFECTIVE_CN0_HZ_BITS &&
              f64_bits(degradation.effective_cn0_db_hz) == W4_D018_EFFECTIVE_CN0_DB_HZ_BITS &&
              f64_bits(degradation.degradation_db) == W4_D018_CN0_DEGRADATION_DB_BITS,
          "signal effective C/N0 degradation");
    check(sidereon_signal_effective_cn0_degradation(&bpsk, 45.0, 24000000.0, &interference, 1,
                                                    &degradation) == SIDEREON_STATUS_OK &&
              f64_bits(degradation.effective_cn0_hz) == W4_D018_EFFECTIVE_CN0_HZ_BITS,
          "signal effective C/N0 degradation canonical");

    SidereonSignalAnalysisDllTrackingOptions dll = {45.0, 1.0, 0.02, 0.5, 100000000.0};
    SidereonSignalAnalysisDllJitter jitter;
    check(sidereon_signal_analysis_dll_jitter(
              &bpsk, &dll, SIDEREON_SIGNAL_ANALYSIS_DLL_PROCESSING_COHERENT, &jitter) ==
              SIDEREON_STATUS_OK &&
              f64_bits(jitter.chips) == W4_D018_DLL_JITTER_CHIPS_BITS &&
              f64_bits(jitter.meters) == W4_D018_DLL_JITTER_METERS_BITS,
          "signal DLL jitter coherent");
    check(sidereon_signal_dll_thermal_noise_jitter(
              &bpsk, &dll, SIDEREON_SIGNAL_ANALYSIS_DLL_PROCESSING_COHERENT, &jitter) ==
                  SIDEREON_STATUS_OK &&
              f64_bits(jitter.chips) == W4_D018_DLL_JITTER_CHIPS_BITS,
          "signal DLL jitter canonical");
    check(sidereon_signal_analysis_dll_lower_bound(&boc, &dll, &jitter) == SIDEREON_STATUS_OK &&
              f64_bits(jitter.seconds) == W4_D018_DLL_LOWER_BOUND_SECONDS_BITS,
          "signal DLL lower bound");
    check(sidereon_signal_dll_lower_bound(&boc, &dll, &jitter) == SIDEREON_STATUS_OK &&
              f64_bits(jitter.seconds) == W4_D018_DLL_LOWER_BOUND_SECONDS_BITS,
          "signal DLL lower bound canonical");

    const double delays[3] = {0.0, 0.5, 1.0};
    SidereonSignalAnalysisMultipathOptions mp = {0.5, 1.0, 100000000.0};
    SidereonSignalAnalysisMultipathEnvelopePoint points[3];
    written = 0;
    required = 0;
    check(sidereon_signal_analysis_multipath_envelope(&bpsk, &mp, delays, 3, points, 3, &written,
                                                       &required) == SIDEREON_STATUS_OK &&
              written == W4_D018_MULTIPATH_POINT_COUNT &&
              required == W4_D018_MULTIPATH_POINT_COUNT &&
              f64_bits(points[1].in_phase_chips) == W4_D018_MULTIPATH_1_IN_PHASE_BITS &&
              f64_bits(points[1].anti_phase_chips) == W4_D018_MULTIPATH_1_ANTI_PHASE_BITS &&
              f64_bits(points[1].running_average_chips) ==
                  W4_D018_MULTIPATH_1_RUNNING_AVERAGE_BITS,
          "signal multipath envelope");
    check(sidereon_signal_multipath_error_envelope(&bpsk, &mp, delays, 3, points, 3, &written,
                                                   &required) == SIDEREON_STATUS_OK &&
              written == W4_D018_MULTIPATH_POINT_COUNT &&
              required == W4_D018_MULTIPATH_POINT_COUNT &&
              f64_bits(points[1].in_phase_chips) == W4_D018_MULTIPATH_1_IN_PHASE_BITS,
          "signal multipath envelope canonical");
}

static void test_fusion_labels(void) {
    check_label(sidereon_fusion_filter_kind_label, SIDEREON_FUSION_FILTER_KIND_EKF,
                "FusionFilterKind.EKF", "fusion filter kind label");
    check_label(sidereon_fusion_error_state_layout_label,
                SIDEREON_FUSION_ERROR_STATE_LAYOUT_TWENTY_ONE, "ErrorStateLayout.TWENTY_ONE",
                "fusion layout label");
    check_label(sidereon_fusion_gnss_fix_status_label, SIDEREON_FUSION_GNSS_FIX_STATUS_FIXED,
                "GnssFixStatus.FIXED", "fusion fix status label");
    size_t dimension = 0;
    check(sidereon_fusion_error_state_layout_dimension(
              SIDEREON_FUSION_ERROR_STATE_LAYOUT_TWENTY_ONE, &dimension) == SIDEREON_STATUS_OK &&
              dimension == W4_D018_LAYOUT_TWENTY_ONE_DIMENSION,
          "fusion layout dimension");
}

static const char *scenario_json =
    "{"
    "\"schema_version\":1,"
    "\"seed\":5855056816869359901,"
    "\"epochs\":{\"start_j2000_s\":0.0,\"count\":2,\"cadence_s\":30.0},"
    "\"receiver\":{\"kind\":\"static_geodetic\",\"position\":{\"lat_rad\":0.0,\"lon_rad\":0.0,"
    "\"height_m\":0.0}},"
    "\"constellation\":{\"kind\":\"synthetic_keplerian\",\"satellites\":["
    "{\"satellite_id\":{\"system\":\"Gps\",\"prn\":1},\"semi_major_axis_m\":26560000.0,"
    "\"eccentricity\":0.0,\"inclination_rad\":0.0,\"raan_rad\":0.0,\"arg_perigee_rad\":0.0,"
    "\"mean_anomaly_rad\":0.0,\"epoch_j2000_s\":0.0,\"clock_bias_s\":0.0,"
    "\"clock_drift_s_s\":0.0},"
    "{\"satellite_id\":{\"system\":\"Gps\",\"prn\":2},\"semi_major_axis_m\":26560000.0,"
    "\"eccentricity\":0.0,\"inclination_rad\":0.0,\"raan_rad\":0.0,\"arg_perigee_rad\":0.0,"
    "\"mean_anomaly_rad\":1.0471975511965976,\"epoch_j2000_s\":0.0,\"clock_bias_s\":0.0,"
    "\"clock_drift_s_s\":0.0},"
    "{\"satellite_id\":{\"system\":\"Gps\",\"prn\":3},\"semi_major_axis_m\":26560000.0,"
    "\"eccentricity\":0.0,\"inclination_rad\":0.0,\"raan_rad\":0.0,\"arg_perigee_rad\":0.0,"
    "\"mean_anomaly_rad\":-1.0471975511965976,\"epoch_j2000_s\":0.0,\"clock_bias_s\":0.0,"
    "\"clock_drift_s_s\":0.0},"
    "{\"satellite_id\":{\"system\":\"Gps\",\"prn\":4},\"semi_major_axis_m\":26560000.0,"
    "\"eccentricity\":0.0,\"inclination_rad\":1.5707963267948966,"
    "\"raan_rad\":0.0,\"arg_perigee_rad\":0.0,\"mean_anomaly_rad\":1.0471975511965976,"
    "\"epoch_j2000_s\":0.0,\"clock_bias_s\":0.0,\"clock_drift_s_s\":0.0},"
    "{\"satellite_id\":{\"system\":\"Gps\",\"prn\":5},\"semi_major_axis_m\":26560000.0,"
    "\"eccentricity\":0.0,\"inclination_rad\":1.5707963267948966,"
    "\"raan_rad\":0.0,\"arg_perigee_rad\":0.0,\"mean_anomaly_rad\":-1.0471975511965976,"
    "\"epoch_j2000_s\":0.0,\"clock_bias_s\":0.0,\"clock_drift_s_s\":0.0}"
    "]},"
    "\"signals\":[{\"system\":\"Gps\",\"code_observable\":\"C1C\",\"phase_observable\":\"L1C\","
    "\"doppler_observable\":\"D1C\",\"carrier_hz\":1575420000.0,"
    "\"carrier_phase_bias_cycles\":0.0}],"
    "\"error_budget\":{\"receiver_clock\":{\"enabled\":true,\"bias_s\":1.0e-7,"
    "\"drift_s_s\":1.0e-10,\"power_law_coefficients\":[1.0e-24,1.0e-26,1.0e-22,"
    "1.0e-26,1.0e-28]},\"satellite_clock\":{\"enabled\":false,\"bias_s\":0.0,"
    "\"drift_s_s\":0.0,\"power_law_coefficients\":[0.0,0.0,0.0,0.0,0.0]},"
    "\"ionosphere\":{\"kind\":\"off\"},\"troposphere\":{\"kind\":\"off\"},"
    "\"thermal_noise\":{\"enabled\":true,\"pseudorange_sigma_m\":0.25,"
    "\"carrier_phase_sigma_m\":0.002,\"doppler_sigma_hz\":0.02},"
    "\"multipath\":{\"enabled\":true,\"amplitude_m\":0.15,\"reflector_height_m\":1.25,"
    "\"phase_rad\":0.3},\"elevation_mask_deg\":-5.0}}";

static void test_scenario(void) {
    SidereonScenarioSimulation *first = NULL;
    SidereonScenarioSimulation *second = NULL;
    const size_t len = strlen(scenario_json);
    check(sidereon_scenario_simulate_json((const uint8_t *)scenario_json, len, &first) ==
              SIDEREON_STATUS_OK &&
              first != NULL,
          "scenario simulate first");
    check(sidereon_scenario_simulate_json((const uint8_t *)scenario_json, len, &second) ==
              SIDEREON_STATUS_OK &&
              second != NULL,
          "scenario simulate second");
    if (first == NULL || second == NULL) {
        sidereon_scenario_simulation_free(first);
        sidereon_scenario_simulation_free(second);
        return;
    }

    SidereonScenarioSummary a, b;
    check(sidereon_scenario_simulation_summary(first, &a) == SIDEREON_STATUS_OK,
          "scenario summary first");
    check(sidereon_scenario_simulation_summary(second, &b) == SIDEREON_STATUS_OK,
          "scenario summary second");
    check(a.determinism_fingerprint == b.determinism_fingerprint &&
              a.observation_count == b.observation_count && a.json_len == b.json_len,
          "scenario deterministic summary");
    /* The fingerprint and payload stamp the engine version, so tests/valgen
     * (w4_d018) writes them with the counts from the same core revision. */
    check(a.observation_count == W4_D018_SCENARIO_OBSERVATION_COUNT &&
              a.epoch_offset_count == W4_D018_SCENARIO_EPOCH_OFFSET_COUNT &&
              a.determinism_fingerprint == W4_D018_SCENARIO_FINGERPRINT &&
              a.json_len == W4_D018_SCENARIO_JSON_LEN,
          "scenario pinned summary");

    uint8_t *json_a = (uint8_t *)malloc(a.json_len);
    uint8_t *json_b = (uint8_t *)malloc(b.json_len);
    size_t written = 0, required = 0;
    check(json_a != NULL && json_b != NULL, "scenario json alloc");
    if (json_a != NULL && json_b != NULL) {
        check(sidereon_scenario_simulation_json(first, json_a, a.json_len, &written, &required) ==
                  SIDEREON_STATUS_OK &&
                  written == a.json_len && required == a.json_len,
              "scenario json first");
        check(sidereon_scenario_simulation_json(second, json_b, b.json_len, &written, &required) ==
                  SIDEREON_STATUS_OK &&
                  written == b.json_len && required == b.json_len,
              "scenario json second");
        check(memcmp(json_a, json_b, a.json_len) == 0, "scenario deterministic bytes");
        check(fnv1a64(json_a, a.json_len) == W4_D018_SCENARIO_JSON_FNV1A64,
              "scenario JSON bytes");
    }

    SidereonScenarioObservation observations[16];
    check(sidereon_scenario_observations(first, observations, 16, &written, &required) ==
              SIDEREON_STATUS_OK &&
              written == a.observation_count && required == a.observation_count,
          "scenario observations");
    SidereonScenarioTerms terms[16];
    check(sidereon_scenario_terms(first, terms, 16, &written, &required) == SIDEREON_STATUS_OK &&
              written == a.observation_count && required == a.observation_count,
          "scenario terms");
    if (a.observation_count > 0) {
        check(f64_bits(observations[0].pseudorange_m) == PIN_SCENARIO_PSEUDORANGE_M_BITS &&
                  f64_bits(observations[0].carrier_phase_cycles) ==
                      PIN_SCENARIO_CARRIER_PHASE_CYCLES_BITS &&
                  f64_bits(observations[0].doppler_hz) == PIN_SCENARIO_DOPPLER_HZ_BITS &&
                  f64_bits(terms[0].geometric_range_m) == PIN_SCENARIO_GEOMETRIC_RANGE_M_BITS &&
                  f64_bits(terms[0].thermal_noise_m) == PIN_SCENARIO_THERMAL_NOISE_M_BITS,
              "scenario pinned first rows");
    }
    free(json_a);
    free(json_b);
    sidereon_scenario_simulation_free(first);
    sidereon_scenario_simulation_free(second);
}

static void init_nav(SidereonFusionNavState *nav) {
    memset(nav, 0, sizeof(*nav));
    nav->position_ecef_m[0] = 6378137.0;
    nav->attitude_body_to_ecef[0] = 1.0;
    nav->attitude_body_to_ecef[4] = 1.0;
    nav->attitude_body_to_ecef[8] = 1.0;
}

static void test_fusion(void) {
    SidereonFusionFilterConfig config;
    check(sidereon_fusion_filter_config_init(&config) == SIDEREON_STATUS_OK,
          "fusion config init");
    config.time_sync_imu_capacity = 8;
    config.time_sync_checkpoint_capacity = 4;

    SidereonFusionNavState nav;
    init_nav(&nav);
    double diag[15];
    for (size_t i = 0; i < 15; i++) {
        diag[i] = 10.0;
    }

    SidereonFusionFilter *filter = NULL;
    check(sidereon_fusion_filter_create(&nav, diag, 15, &config, &filter) == SIDEREON_STATUS_OK &&
              filter != NULL,
          "fusion create EKF");

    SidereonFusionFilterConfig ukf_config = config;
    ukf_config.filter_kind = SIDEREON_FUSION_FILTER_KIND_UKF;
    SidereonFusionFilter *ukf_filter = NULL;
    check(sidereon_fusion_filter_create(&nav, diag, 15, &ukf_config, &ukf_filter) ==
              SIDEREON_STATUS_OK &&
              ukf_filter != NULL,
          "fusion create UKF");
    sidereon_fusion_filter_free(ukf_filter);

    if (filter == NULL) {
        return;
    }

    SidereonFusionImuSample sample;
    memset(&sample, 0, sizeof(sample));
    sample.kind = SIDEREON_FUSION_IMU_SAMPLE_KIND_INCREMENT;
    sample.t_j2000_s = 1.0;
    sample.dt_s = 1.0;
    sample.delta_velocity_mps[0] = 9.7803253359;
    check(sidereon_fusion_filter_propagate(filter, &sample) == SIDEREON_STATUS_OK,
          "fusion propagate first");
    SidereonFusionState state1;
    check(sidereon_fusion_filter_state(filter, &state1) == SIDEREON_STATUS_OK,
          "fusion state after first propagate");

    sample.t_j2000_s = 2.0;
    check(sidereon_fusion_filter_propagate(filter, &sample) == SIDEREON_STATUS_OK,
          "fusion propagate second");

    double loose_cov[9] = {1.0e12, 0.0, 0.0, 0.0, 1.0e12, 0.0, 0.0, 0.0, 1.0e12};
    SidereonFusionLooseMeasurement late;
    copy_state_position(&state1, &late, 1.5, loose_cov, 9);
    SidereonFusionTimeSyncUpdate sync_update;
    check(sidereon_fusion_filter_update_loose_time_sync(filter, &late, &sync_update) ==
              SIDEREON_STATUS_OK &&
              sync_update.update.rows == W4_D018_SYNC_ROWS &&
              sync_update.replayed_imu_segments == W4_D018_SYNC_REPLAYED_IMU_SEGMENTS &&
              sync_update.late_measurement == W4_D018_SYNC_LATE_MEASUREMENT &&
              f64_bits(sync_update.update.nis) == W4_D018_SYNC_NIS_BITS &&
              f64_bits(sync_update.current_epoch_j2000_s) == W4_D018_SYNC_CURRENT_EPOCH_BITS,
          "fusion loose time-sync update");

    SidereonFusionState state2;
    check(sidereon_fusion_filter_state(filter, &state2) == SIDEREON_STATUS_OK,
          "fusion state after time-sync");
    check_vec_bits(state2.position_ecef_m, W4_D018_SYNC_STATE_POSITION_BITS, 3,
                   "fusion pinned state position");
    check_bits(state2.tight_clock_bias_m, W4_D018_SYNC_STATE_CLOCK_BIAS_BITS,
               "fusion pinned clock bias");
    check_bits(state2.tight_clock_drift_m_s, W4_D018_SYNC_STATE_CLOCK_DRIFT_BITS,
               "fusion pinned clock drift");
    check(state2.covariance_dimension == W4_D018_SYNC_STATE_COVARIANCE_DIMENSION,
          "fusion pinned covariance dimension");

    size_t written = 0, required = 0;
    check(sidereon_fusion_filter_encode_state(filter, NULL, 0, &written, &required) ==
              SIDEREON_STATUS_OK &&
              required == W4_D018_ENCODED_STATE_LEN && written == 0,
          "fusion encode query");
    uint8_t *bytes = (uint8_t *)malloc(required);
    check(bytes != NULL, "fusion encode alloc");
    if (bytes != NULL) {
        const size_t byte_count = required;
        check(sidereon_fusion_filter_encode_state(filter, bytes, byte_count, &written, &required) ==
                  SIDEREON_STATUS_OK &&
                  written == byte_count && required == byte_count &&
                  fnv1a64(bytes, byte_count) == W4_D018_ENCODED_STATE_FNV1A64,
              "fusion encode bytes");
        check(sidereon_fusion_filter_restore_state(filter, bytes, byte_count) ==
                  SIDEREON_STATUS_OK,
              "fusion restore bytes");
        uint8_t *roundtrip = (uint8_t *)malloc(byte_count);
        check(roundtrip != NULL, "fusion roundtrip alloc");
        if (roundtrip != NULL) {
            check(sidereon_fusion_filter_encode_state(filter, roundtrip, byte_count, &written,
                                                      &required) == SIDEREON_STATUS_OK &&
                      written == byte_count && required == byte_count &&
                      memcmp(bytes, roundtrip, byte_count) == 0,
                  "fusion encode restore byte roundtrip");
            free(roundtrip);
        }
        free(bytes);
    }

    SidereonFusionTimeSyncStatus status;
    check(sidereon_fusion_filter_time_sync_status(filter, &status) == SIDEREON_STATUS_OK &&
              status.imu_capacity == W4_D018_TIME_SYNC_IMU_CAPACITY &&
              status.checkpoint_capacity == W4_D018_TIME_SYNC_CHECKPOINT_CAPACITY,
          "fusion time-sync status");
    sidereon_fusion_filter_free(filter);
}

static void test_fusion_field_mode(void) {
    double cov6[36];
    identity_matrix(cov6, 6);

    SidereonFusionNavState nav;
    init_nav(&nav);

    SidereonFusionFilterConfig config;
    init_field_config(&config);
    /* The multipliers and capacity are sidereon-core's defaults; the
     * optional stationary and non-holonomic updates start off. */
    check(f64_bits(config.loose_fix_status_weighting.single_sigma_multiplier) ==
                  W4_D018_DEFAULT_SINGLE_SIGMA_MULTIPLIER_BITS &&
              f64_bits(config.loose_fix_status_weighting.float_sigma_multiplier) ==
                  W4_D018_DEFAULT_FLOAT_SIGMA_MULTIPLIER_BITS &&
              f64_bits(config.loose_fix_status_weighting.fixed_sigma_multiplier) ==
                  W4_D018_DEFAULT_FIXED_SIGMA_MULTIPLIER_BITS &&
              !config.has_loose_stationary_updates && !config.has_loose_non_holonomic &&
              config.time_sync_imu_capacity == W4_D018_DEFAULT_TIME_SYNC_IMU_CAPACITY,
          "fusion field defaults omitted");
    /* sidereon_fusion_filter_config_init writes the identity IMU-to-body
     * rotation (src/fusion.rs). */
    const uint64_t imu_to_body_bits[9] = {
        UINT64_C(0x3FF0000000000000), UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000),
        UINT64_C(0x3FF0000000000000), UINT64_C(0x0000000000000000),
        UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000),
        UINT64_C(0x3FF0000000000000),
    };
    check_vec_bits(config.imu_to_body_dcm, imu_to_body_bits, 9, "fusion field imu_to_body");

    SidereonFusionFilter *filter = create_field_filter(&config, &nav, "fusion field create");
    if (filter != NULL) {
        SidereonFusionLooseMeasurement fix;
        init_default_position_velocity_fix(&fix, cov6, SIDEREON_FUSION_GNSS_FIX_STATUS_SINGLE);
        SidereonFusionUpdate update;
        check(sidereon_fusion_filter_update_loose(filter, &fix, &update) ==
                  SIDEREON_STATUS_OK &&
                  update.applied == W4_D018_FIELD_UPDATE_APPLIED &&
                  update.rows == W4_D018_FIELD_UPDATE_ROWS &&
                  update.accepted_rows == W4_D018_FIELD_UPDATE_ACCEPTED_ROWS &&
                  update.rejected_rows == W4_D018_FIELD_UPDATE_REJECTED_ROWS,
              "fusion field default loose update");
        check_bits(update.nis, W4_D018_FIELD_UPDATE_NIS_BITS, "fusion field default NIS bits");

        SidereonFusionState state;
        check(sidereon_fusion_filter_state(filter, &state) == SIDEREON_STATUS_OK,
              "fusion field default state");
        check_vec_bits(state.position_ecef_m, W4_D018_FIELD_POSITION_BITS, 3,
                       "fusion field position");
        check_vec_bits(state.velocity_ecef_mps, W4_D018_FIELD_VELOCITY_BITS, 3,
                       "fusion field velocity");
        check_filter_cov_diag_bits(filter, 0, W4_D018_FIELD_COV_DIAG_BITS, 6,
                                   "fusion field covariance");
    }
    sidereon_fusion_filter_free(filter);

    init_field_config(&config);
    config.has_loose_stationary_updates = true;
    config.loose_stationary_updates.detector.window_len = 1;
    config.loose_stationary_updates.detector.max_specific_force_norm_error_mps2 = 100.0;
    config.loose_stationary_updates.detector.max_body_rate_wrt_ecef_norm_rps = 1.0;
    config.loose_stationary_updates.zero_velocity_sigma_mps = 0.5;
    config.loose_stationary_updates.zero_angular_rate_sigma_rps = 0.05;
    filter = create_field_filter(&config, &nav, "fusion stationary create");
    if (filter != NULL) {
        SidereonFusionImuSample sample;
        memset(&sample, 0, sizeof(sample));
        sample.kind = SIDEREON_FUSION_IMU_SAMPLE_KIND_INCREMENT;
        sample.t_j2000_s = 1.0;
        sample.dt_s = 1.0;
        check(sidereon_fusion_filter_propagate(filter, &sample) == SIDEREON_STATUS_OK,
              "fusion stationary propagate");
        SidereonFusionUpdate update;
        bool present = false;
        check(sidereon_fusion_filter_update_stationary(filter, &update, &present) ==
                  SIDEREON_STATUS_OK &&
                  present == W4_D018_STATIONARY_PRESENT &&
                  update.applied == W4_D018_STATIONARY_UPDATE_APPLIED &&
                  update.rows == W4_D018_STATIONARY_UPDATE_ROWS &&
                  update.accepted_rows == W4_D018_STATIONARY_UPDATE_ACCEPTED_ROWS &&
                  update.rejected_rows == W4_D018_STATIONARY_UPDATE_REJECTED_ROWS,
              "fusion stationary update");
        check_bits(update.nis, W4_D018_STATIONARY_UPDATE_NIS_BITS, "fusion stationary NIS bits");
        SidereonFusionState state;
        check(sidereon_fusion_filter_state(filter, &state) == SIDEREON_STATUS_OK,
              "fusion stationary state");
        check_vec_bits(state.velocity_ecef_mps, W4_D018_STATIONARY_VELOCITY_BITS, 3,
                       "fusion stationary velocity");
        check_vec_bits(state.gyro_bias_rps, W4_D018_STATIONARY_GYRO_BIAS_BITS, 3,
                       "fusion stationary gyro bias");
        check_filter_cov_diag_bits(filter, 3, W4_D018_STATIONARY_COV_DIAG_BITS, 6,
                                   "fusion stationary covariance");
    }
    sidereon_fusion_filter_free(filter);

    init_field_config(&config);
    SidereonFusionFilter *plain = create_field_filter(&config, &nav, "fusion no stationary create");
    if (plain != NULL) {
        SidereonFusionUpdate update;
        bool present = true;
        check(sidereon_fusion_filter_update_stationary(plain, &update, &present) ==
                  SIDEREON_STATUS_OK &&
                  present == W4_D018_PLAIN_STATIONARY_PRESENT,
              "fusion stationary absent without config");
    }
    sidereon_fusion_filter_free(plain);

    init_field_config(&config);
    config.loose_fix_status_weighting.single_sigma_multiplier = 3.0;
    config.loose_fix_status_weighting.float_sigma_multiplier = 2.0;
    config.loose_fix_status_weighting.fixed_sigma_multiplier = 1.0;
    const uint32_t statuses[3] = {
        SIDEREON_FUSION_GNSS_FIX_STATUS_SINGLE,
        SIDEREON_FUSION_GNSS_FIX_STATUS_FLOAT,
        SIDEREON_FUSION_GNSS_FIX_STATUS_FIXED,
    };
    const bool applied[3] = {
        W4_D018_WEIGHTING_SINGLE_APPLIED,
        W4_D018_WEIGHTING_FLOAT_APPLIED,
        W4_D018_WEIGHTING_FIXED_APPLIED,
    };
    const size_t rows[3] = {
        W4_D018_WEIGHTING_SINGLE_ROWS,
        W4_D018_WEIGHTING_FLOAT_ROWS,
        W4_D018_WEIGHTING_FIXED_ROWS,
    };
    const uint64_t nis_bits[3] = {
        W4_D018_WEIGHTING_SINGLE_NIS_BITS,
        W4_D018_WEIGHTING_FLOAT_NIS_BITS,
        W4_D018_WEIGHTING_FIXED_NIS_BITS,
    };
    const uint64_t *diag_bits[3] = {
        W4_D018_WEIGHTING_SINGLE_COV_DIAG_BITS,
        W4_D018_WEIGHTING_FLOAT_COV_DIAG_BITS,
        W4_D018_WEIGHTING_FIXED_COV_DIAG_BITS,
    };
    double cov_x[3] = {0.0, 0.0, 0.0};
    for (size_t i = 0; i < 3; i++) {
        filter = create_field_filter(&config, &nav, "fusion fix weighting create");
        if (filter == NULL) {
            continue;
        }
        SidereonFusionLooseMeasurement fix;
        init_default_position_velocity_fix(&fix, cov6, statuses[i]);
        SidereonFusionUpdate update;
        check(sidereon_fusion_filter_update_loose(filter, &fix, &update) ==
                  SIDEREON_STATUS_OK &&
                  update.applied == applied[i] && update.rows == rows[i],
              "fusion fix weighting update");
        check_bits(update.nis, nis_bits[i], "fusion fix weighting NIS bits");
        double covariance[225];
        size_t written = 0, required = 0;
        check(sidereon_fusion_filter_covariance(filter, covariance, 225, &written, &required) ==
                  SIDEREON_STATUS_OK &&
                  written == W4_D018_FIFTEEN_COVARIANCE_LEN &&
                  required == W4_D018_FIFTEEN_COVARIANCE_LEN,
              "fusion fix weighting covariance");
        cov_x[i] = covariance[0];
        check_filter_cov_diag_bits(filter, 0, diag_bits[i], 6, "fusion fix weighting diag");
        sidereon_fusion_filter_free(filter);
    }
    check(cov_x[2] < cov_x[1] && cov_x[1] < cov_x[0],
          "fusion fix weighting covariance order");

    SidereonFusionVelocityMatchState states[3] = {
        {0.0, {0.0, 0.0, 0.0}, {1.0, 0.0, 0.0}},
        {1.0, {1.0, 0.0, 0.0}, {1.0, 0.0, 0.0}},
        {2.0, {2.0, 0.0, 0.0}, {1.0, 0.0, 0.0}},
    };
    const double first_good_position[3] = {4.0, 1.0, 0.0};
    const double first_good_velocity[3] = {2.0, 0.0, 0.0};
    SidereonFusionLooseMeasurement first_good;
    init_position_velocity_fix(&first_good, 2.0, first_good_position, first_good_velocity, cov6,
                               SIDEREON_FUSION_GNSS_FIX_STATUS_SINGLE);
    SidereonFusionVelocityMatchingConfig vm_config = {5.0};
    SidereonFusionVelocityMatchState matched[3];
    SidereonFusionVelocityMatchedTrajectory trajectory;
    size_t written = 0, required = 0;
    check(sidereon_fusion_velocity_match_outage(states, 3, &first_good, &vm_config, matched, 3,
                                                &written, &required, &trajectory) ==
                  SIDEREON_STATUS_OK &&
              written == W4_D018_VM_STATE_COUNT && required == W4_D018_VM_STATE_COUNT &&
              trajectory.state_count == W4_D018_VM_STATE_COUNT,
          "fusion velocity matching outage");
    check_vec_bits(trajectory.endpoint_position_correction_ecef_m, W4_D018_VM_ENDPOINT_POSITION_BITS,
                   3, "fusion velocity matching endpoint position");
    check_vec_bits(trajectory.endpoint_velocity_correction_ecef_mps,
                   W4_D018_VM_ENDPOINT_VELOCITY_BITS, 3,
                   "fusion velocity matching endpoint velocity");
    const uint64_t *matched_position_bits[3] = {
        W4_D018_VM_STATE0_POSITION_BITS,
        W4_D018_VM_STATE1_POSITION_BITS,
        W4_D018_VM_STATE2_POSITION_BITS,
    };
    const uint64_t *matched_velocity_bits[3] = {
        W4_D018_VM_STATE0_VELOCITY_BITS,
        W4_D018_VM_STATE1_VELOCITY_BITS,
        W4_D018_VM_STATE2_VELOCITY_BITS,
    };
    for (size_t i = 0; i < W4_D018_VM_STATE_COUNT; i++) {
        check_vec_bits(matched[i].position_ecef_m, matched_position_bits[i], 3,
                       "fusion velocity matching position");
        check_vec_bits(matched[i].velocity_ecef_mps, matched_velocity_bits[i], 3,
                       "fusion velocity matching velocity");
    }

    init_field_config(&config);
    config.imu_to_body_dcm[0] = 0.0;
    config.imu_to_body_dcm[1] = -1.0;
    config.imu_to_body_dcm[2] = 0.0;
    config.imu_to_body_dcm[3] = 1.0;
    config.imu_to_body_dcm[4] = 0.0;
    config.imu_to_body_dcm[5] = 0.0;
    config.imu_to_body_dcm[6] = 0.0;
    config.imu_to_body_dcm[7] = 0.0;
    config.imu_to_body_dcm[8] = 1.0;
    config.has_loose_non_holonomic = true;
    config.loose_non_holonomic.lateral_velocity_sigma_mps = 0.5;
    config.loose_non_holonomic.vertical_velocity_sigma_mps = 0.5;
    config.loose_non_holonomic.min_speed_mps = 0.1;
    config.loose_non_holonomic.max_body_rate_wrt_ecef_norm_rps = 1.0;
    nav.velocity_ecef_mps[0] = 2.0;
    nav.velocity_ecef_mps[1] = 0.4;
    nav.velocity_ecef_mps[2] = -0.2;
    filter = create_field_filter(&config, &nav, "fusion non-holonomic create");
    if (filter != NULL) {
        SidereonFusionUpdate update;
        bool present = false;
        check(sidereon_fusion_filter_update_non_holonomic(filter, &update, &present) ==
                  SIDEREON_STATUS_OK &&
                  present == W4_D018_NHC_PRESENT &&
                  update.applied == W4_D018_NHC_UPDATE_APPLIED &&
                  update.rows == W4_D018_NHC_UPDATE_ROWS &&
                  update.accepted_rows == W4_D018_NHC_UPDATE_ACCEPTED_ROWS &&
                  update.rejected_rows == W4_D018_NHC_UPDATE_REJECTED_ROWS,
              "fusion non-holonomic update");
        check_bits(update.nis, W4_D018_NHC_UPDATE_NIS_BITS, "fusion non-holonomic NIS bits");
        SidereonFusionState state;
        check(sidereon_fusion_filter_state(filter, &state) == SIDEREON_STATUS_OK,
              "fusion non-holonomic state");
        check_vec_bits(state.velocity_ecef_mps, W4_D018_NHC_VELOCITY_BITS, 3,
                       "fusion non-holonomic velocity");
    }
    sidereon_fusion_filter_free(filter);
}

static void test_fusion_recorded_rts(void) {
    SidereonFusionFilterConfig config;
    check(sidereon_fusion_filter_config_init(&config) == SIDEREON_STATUS_OK,
          "fusion recorded config init");
    config.has_loose_innovation_gate = true;
    config.loose_innovation_gate.threshold_sigma = 4.0;
    config.loose_innovation_gate.min_rows = 2;
    config.has_loose_measurement_reweighting = true;
    config.loose_measurement_reweighting.k0_sigma = 2.0;
    config.loose_measurement_reweighting.k1_sigma = 5.0;
    config.has_loose_prediction_adaptation = true;
    config.loose_prediction_adaptation.threshold = 1.0;
    config.loose_prediction_adaptation.outlier_gate_probability = 0.99;

    SidereonFusionNavState nav;
    init_nav(&nav);
    double diag[15];
    for (size_t i = 0; i < 15; i++) {
        diag[i] = 1.0;
    }

    SidereonFusionFilter *filter = NULL;
    check(sidereon_fusion_filter_create(&nav, diag, 15, &config, &filter) ==
              SIDEREON_STATUS_OK &&
              filter != NULL,
          "fusion recorded create");
    if (filter == NULL) {
        return;
    }

    SidereonFusionRtsHistoryBuilder *builder = NULL;
    check(sidereon_fusion_rts_history_builder_from_filter(filter, &builder) ==
              SIDEREON_STATUS_OK &&
              builder != NULL,
          "fusion recorded history from filter");
    if (builder == NULL) {
        sidereon_fusion_filter_free(filter);
        return;
    }

    SidereonFusionImuSample sample;
    memset(&sample, 0, sizeof(sample));
    sample.kind = SIDEREON_FUSION_IMU_SAMPLE_KIND_RATE;
    sample.t_j2000_s = 1.0;
    check(sidereon_fusion_filter_propagate_recorded(filter, &sample, builder) ==
              SIDEREON_STATUS_OK,
          "fusion recorded propagate");

    double loose_cov[9] = {0.5, 0.0, 0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.5};
    SidereonFusionLooseMeasurement measurement;
    memset(&measurement, 0, sizeof(measurement));
    measurement.t_j2000_s = 1.0;
    measurement.position_ecef_m[0] = 6378137.35;
    measurement.position_ecef_m[1] = 0.2;
    measurement.position_ecef_m[2] = -0.1;
    measurement.covariance = loose_cov;
    measurement.covariance_len = 9;
    measurement.satellites_used = 7;
    measurement.solution_valid = true;
    measurement.fix_status = SIDEREON_FUSION_GNSS_FIX_STATUS_SINGLE;

    SidereonFusionUpdate update;
    check(sidereon_fusion_filter_update_loose_recorded(filter, &measurement, builder, &update) ==
              SIDEREON_STATUS_OK &&
              update.applied == W4_D018_RECORDED_UPDATE_APPLIED &&
              update.rows == W4_D018_RECORDED_UPDATE_ROWS &&
              update.accepted_rows == W4_D018_RECORDED_UPDATE_ACCEPTED_ROWS &&
              update.rejected_rows == W4_D018_RECORDED_UPDATE_REJECTED_ROWS,
          "fusion recorded loose update");
    check_bits(update.nis, W4_D018_RECORDED_UPDATE_NIS_BITS, "fusion recorded NIS bits");

    SidereonFusionState state;
    check(sidereon_fusion_filter_state(filter, &state) == SIDEREON_STATUS_OK,
          "fusion recorded state");
    check_vec_bits(state.position_ecef_m, W4_D018_RECORDED_STATE_POSITION_BITS, 3,
                   "fusion recorded state position");

    SidereonFusionRtsHistory *history = NULL;
    check(sidereon_fusion_rts_history_builder_finish(builder, &history) ==
              SIDEREON_STATUS_OK &&
              history != NULL,
          "fusion recorded history finish");
    size_t count = 0;
    check(sidereon_fusion_rts_history_epoch_count(history, &count) == SIDEREON_STATUS_OK &&
              count == W4_D018_HISTORY_EPOCH_COUNT,
          "fusion recorded history count");

    SidereonFusionRtsEpoch epoch0, epoch1;
    check(sidereon_fusion_rts_history_epoch(history, 0, &epoch0) == SIDEREON_STATUS_OK &&
              epoch0.covariance_dimension == W4_D018_HISTORY_EPOCH0_COVARIANCE_DIMENSION &&
              epoch0.augmented_dimension == W4_D018_HISTORY_EPOCH0_AUGMENTED_DIMENSION &&
              epoch0.has_transition_from_previous == W4_D018_HISTORY_EPOCH0_HAS_TRANSITION,
          "fusion recorded epoch 0 summary");
    check(sidereon_fusion_rts_history_epoch(history, 1, &epoch1) == SIDEREON_STATUS_OK &&
              epoch1.covariance_dimension == W4_D018_HISTORY_EPOCH1_COVARIANCE_DIMENSION &&
              epoch1.augmented_dimension == W4_D018_HISTORY_EPOCH1_AUGMENTED_DIMENSION &&
              epoch1.has_transition_from_previous == W4_D018_HISTORY_EPOCH1_HAS_TRANSITION,
          "fusion recorded epoch 1 summary");

    size_t written = 0, required = 0;
    double transition[225];
    check(sidereon_fusion_rts_history_epoch_transition_from_previous(
              history, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W4_D018_HISTORY_EPOCH0_TRANSITION_LEN,
          "fusion recorded first transition size");
    check(sidereon_fusion_rts_history_epoch_transition_from_previous(
              history, 1, transition, 225, &written, &required) == SIDEREON_STATUS_OK &&
              written == W4_D018_HISTORY_EPOCH1_TRANSITION_LEN &&
              required == W4_D018_HISTORY_EPOCH1_TRANSITION_LEN,
          "fusion recorded transition copy");
    check(fnv1a64(transition, written * sizeof(double)) ==
              W4_D018_HISTORY_EPOCH1_TRANSITION_FNV1A64,
          "fusion recorded transition values");

    SidereonSmoothedFusionTrajectory *smoothed = NULL;
    check(sidereon_smooth_fusion_rts(history, &smoothed) == SIDEREON_STATUS_OK &&
              smoothed != NULL,
          "fusion recorded smooth");
    check(sidereon_smoothed_fusion_trajectory_epoch_count(smoothed, &count) ==
              SIDEREON_STATUS_OK &&
              count == W4_D018_SMOOTHED_EPOCH_COUNT,
          "fusion recorded smoothed count");

    SidereonSmoothedFusionEpoch smoothed0, smoothed1;
    check(sidereon_smoothed_fusion_trajectory_epoch(smoothed, 0, &smoothed0) ==
              SIDEREON_STATUS_OK &&
              smoothed0.covariance_dimension == W4_D018_SMOOTHED_EPOCH0_COVARIANCE_DIMENSION &&
              smoothed0.correction_len == W4_D018_SMOOTHED_EPOCH0_CORRECTION_LEN &&
              smoothed0.has_rts_gain_to_next == W4_D018_SMOOTHED_EPOCH0_HAS_RTS_GAIN,
          "fusion recorded smoothed epoch 0 summary");
    check(sidereon_smoothed_fusion_trajectory_epoch(smoothed, 1, &smoothed1) ==
              SIDEREON_STATUS_OK &&
              smoothed1.covariance_dimension == W4_D018_SMOOTHED_EPOCH1_COVARIANCE_DIMENSION &&
              smoothed1.correction_len == W4_D018_SMOOTHED_EPOCH1_CORRECTION_LEN &&
              smoothed1.has_rts_gain_to_next == W4_D018_SMOOTHED_EPOCH1_HAS_RTS_GAIN,
          "fusion recorded smoothed epoch 1 summary");

    const uint64_t *smoothed_position_bits[2] = {
        W4_D018_SMOOTHED_EPOCH0_POSITION_BITS,
        W4_D018_SMOOTHED_EPOCH1_POSITION_BITS,
    };
    const size_t correction_len[2] = {
        W4_D018_SMOOTHED_EPOCH0_CORRECTION_LEN,
        W4_D018_SMOOTHED_EPOCH1_CORRECTION_LEN,
    };
    const uint64_t correction_hash[2] = {
        W4_D018_SMOOTHED_EPOCH0_CORRECTION_FNV1A64,
        W4_D018_SMOOTHED_EPOCH1_CORRECTION_FNV1A64,
    };
    const size_t covariance_len[2] = {
        W4_D018_SMOOTHED_EPOCH0_COVARIANCE_LEN,
        W4_D018_SMOOTHED_EPOCH1_COVARIANCE_LEN,
    };
    const uint64_t covariance_hash[2] = {
        W4_D018_SMOOTHED_EPOCH0_COVARIANCE_FNV1A64,
        W4_D018_SMOOTHED_EPOCH1_COVARIANCE_FNV1A64,
    };
    const size_t gain_len[2] = {
        W4_D018_SMOOTHED_EPOCH0_RTS_GAIN_LEN,
        W4_D018_SMOOTHED_EPOCH1_RTS_GAIN_LEN,
    };
    const uint64_t gain_hash[2] = {
        W4_D018_SMOOTHED_EPOCH0_RTS_GAIN_FNV1A64,
        W4_D018_SMOOTHED_EPOCH1_RTS_GAIN_FNV1A64,
    };
    for (size_t i = 0; i < 2; i++) {
        double position[3];
        check(sidereon_smoothed_fusion_trajectory_epoch_position_ecef_m(
                  smoothed, i, position, 3, &written, &required) == SIDEREON_STATUS_OK &&
                  written == 3 && required == 3,
              "fusion recorded smoothed position");
        check_vec_bits(position, smoothed_position_bits[i], 3,
                       "fusion recorded smoothed position");

        double correction[17];
        check(sidereon_smoothed_fusion_trajectory_epoch_error_state_correction(
                  smoothed, i, correction, 17, &written, &required) == SIDEREON_STATUS_OK &&
                  written == correction_len[i] && required == correction_len[i],
              "fusion recorded smoothed correction");
        check(fnv1a64(correction, written * sizeof(double)) == correction_hash[i],
              "fusion recorded smoothed correction values");

        double covariance[289];
        check(sidereon_smoothed_fusion_trajectory_epoch_covariance(
                  smoothed, i, covariance, 289, &written, &required) == SIDEREON_STATUS_OK &&
                  written == covariance_len[i] && required == covariance_len[i],
              "fusion recorded smoothed covariance");
        check(fnv1a64(covariance, written * sizeof(double)) == covariance_hash[i],
              "fusion recorded smoothed covariance values");

        double rts_gain[289];
        check(sidereon_smoothed_fusion_trajectory_epoch_rts_gain_to_next(
                  smoothed, i, rts_gain, 289, &written, &required) == SIDEREON_STATUS_OK &&
                  written == gain_len[i] && required == gain_len[i],
              "fusion recorded RTS gain");
        check(fnv1a64(rts_gain, written * sizeof(double)) == gain_hash[i],
              "fusion recorded RTS gain values");
    }

    sidereon_smoothed_fusion_trajectory_free(smoothed);
    sidereon_fusion_rts_history_free(history);
    sidereon_fusion_rts_history_builder_free(builder);
    sidereon_fusion_filter_free(filter);
}

int main(void) {
    test_signal_analysis();
    test_scenario();
    test_fusion_labels();
    test_fusion();
    test_fusion_field_mode();
    test_fusion_recorded_rts();
    if (failures != 0) {
        fprintf(stderr, "domain018_smoke failures: %d\n", failures);
        return 1;
    }
    return 0;
}
