/* Generated by tests/gen_dop_fixture_header.py from the committed core
 * golden sidereon-core/tests/fixtures/dop_golden.json. Every value is the
 * golden's own IEEE-754 float64 bit pattern, so the C smoke test asserts
 * the engine's 0-ULP DOP scalars. Do not edit by hand; rerun the
 * generator. */
#ifndef SIDEREON_DOP_FIXTURE_H
#define SIDEREON_DOP_FIXTURE_H

#include <stdint.h>
#include <stddef.h>

typedef struct {
    const char *name;
    size_t sat_count;
    const uint64_t (*los_bits)[3]; /* sat_count entries of {e_x,e_y,e_z} */
    const uint64_t *weight_bits;   /* sat_count entries */
    uint64_t lat_rad_bits;
    uint64_t lon_rad_bits;
    uint64_t gdop_bits;
    uint64_t pdop_bits;
    uint64_t hdop_bits;
    uint64_t vdop_bits;
    uint64_t tdop_bits;
} DopGoldenCase;

typedef struct {
    const char *name;
    size_t sat_count;
    const uint64_t (*los_bits)[3];
    const uint64_t *weight_bits;
    uint64_t lat_rad_bits;
    uint64_t lon_rad_bits;
} DopSingularCase;

static const uint64_t DOP_CASE_0_LOS[4][3] = {
    { UINT64_C(0x3fdaa2fbd945ccc0), UINT64_C(0x3fb2c97bb8ccdf37), UINT64_C(0x3fed0079302dd766) },
    { UINT64_C(0x3fe09f95aba18faf), UINT64_C(0x3feb4d27ce94dbce), UINT64_C(0x3fa8408293b0d4f0) },
    { UINT64_C(0x3fe8f55f9ae5db06), UINT64_C(0xbfe3f829842cce52), UINT64_C(0x3fa8408293b0d4b8) },
    { UINT64_C(0xbfd3493dd2a6d2aa), UINT64_C(0x3fe97b2bf4a3bea0), UINT64_C(0x3fe0c8dc2e423980) },
};
static const uint64_t DOP_CASE_0_W[4] = { UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000) };

static const uint64_t DOP_CASE_1_LOS[6][3] = {
    { UINT64_C(0x3fe2135a910d83fb), UINT64_C(0x3fb97f6b26ba6e6a), UINT64_C(0x3fea367e59158747) },
    { UINT64_C(0xbfbac1a70d2589e0), UINT64_C(0x3fe23b435392bda2), UINT64_C(0x3fea15c1a309e33e) },
    { UINT64_C(0x3fe423145c43b7eb), UINT64_C(0x3fe85fdcfa18d7e1), UINT64_C(0xbfc3c0ae5041608a) },
    { UINT64_C(0x3fefc071b94563e4), UINT64_C(0xbfa8b7ffeac1f982), UINT64_C(0x3fbd543cf378fbcc) },
    { UINT64_C(0x3fd9afa944095fed), UINT64_C(0xbfec44fb700cd0c8), UINT64_C(0x3fcef4c4e9241676) },
    { UINT64_C(0x3fd91913c5469dfa), UINT64_C(0xbfd07608a65d157b), UINT64_C(0x3fec4341b6d53a9e) },
};
static const uint64_t DOP_CASE_1_W[6] = { UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000) };

static const uint64_t DOP_CASE_2_LOS[5][3] = {
    { UINT64_C(0xbfeb415ca9570907), UINT64_C(0x3fdaed5121d39724), UINT64_C(0xbfd3fcf6b960c20d) },
    { UINT64_C(0xbfe8c394008a8c89), UINT64_C(0xbfdbbfe8d6e35fc8), UINT64_C(0xbfdd8ba8703b5070) },
    { UINT64_C(0x3fd138345efc3f17), UINT64_C(0x3fa329c23317453c), UINT64_C(0xbfeecbf52566ed70) },
    { UINT64_C(0x3fcde66827fce05f), UINT64_C(0x3fef19c41329f243), UINT64_C(0x3f9dea5dc9c45e90) },
    { UINT64_C(0xbfe659a77635f40f), UINT64_C(0x3fe6e1b9b29b2a74), UINT64_C(0xbf9e41cbd33c4470) },
};
static const uint64_t DOP_CASE_2_W[5] = { UINT64_C(0x4010000000000000), UINT64_C(0x4000000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3fe0000000000000), UINT64_C(0x4008000000000000) };

static const uint64_t DOP_CASE_3_LOS[5][3] = {
    { UINT64_C(0x3febb67ae8584caa), UINT64_C(0x3fb63a1a7e0b738a), UINT64_C(0x3fdf838b8c811c19) },
    { UINT64_C(0x3fec411b4f6d2707), UINT64_C(0x3fc48d84249d1144), UINT64_C(0x3fdc3bf2cdd7264a) },
    { UINT64_C(0x3feb2335c2cda945), UINT64_C(0x3fd0f5193eacdd29), UINT64_C(0x3fdd5f00dc0ca4ca) },
    { UINT64_C(0x3fed0079302dd767), UINT64_C(0x3fbc006fa6c72f78), UINT64_C(0x3fda203df1bef2ff) },
    { UINT64_C(0x3fea367e59158747), UINT64_C(0x3fcf07171902382e), UINT64_C(0x3fe0a280c3ed94c6) },
};
static const uint64_t DOP_CASE_3_W[5] = { UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000) };

static const uint64_t DOP_CASE_4_LOS[5][3] = {
    { UINT64_C(0x3fd491b7523c161b), UINT64_C(0x3fe1d03e70ea8500), UINT64_C(0x3fe8836fa2cf5038) },
    { UINT64_C(0x3fe74d814a39ebf9), UINT64_C(0xbfde20ce06c88b4e), UINT64_C(0x3fdfe0d3b41815a1) },
    { UINT64_C(0xbfdbb67ae8584ca6), UINT64_C(0xbfe8000000000000), UINT64_C(0x3fe0000000000000) },
    { UINT64_C(0xbfe9b4a72cc8a7aa), UINT64_C(0x3fdaf5d7c0cf3e47), UINT64_C(0x3fdaf1d43a4505fb) },
    { UINT64_C(0x3fd27e41e3fbcc7d), UINT64_C(0x3f913348459579f0), UINT64_C(0x3feea15756ab91a3) },
};
static const uint64_t DOP_CASE_4_W[5] = { UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000) };

static const uint64_t DOP_CASE_5_LOS[4][3] = {
    { UINT64_C(0x3fe8836fa2cf5039), UINT64_C(0x3fd491b7523c161c), UINT64_C(0x3fe1d03e70ea8500) },
    { UINT64_C(0x3fe491b7523c161c), UINT64_C(0x3fd8836fa2cf5038), UINT64_C(0xbfe53aafe3631109) },
    { UINT64_C(0x3fe6a09e667f3bcc), UINT64_C(0xbfe6a09e667f3bcd), UINT64_C(0xbca2b8388e82ab21) },
    { UINT64_C(0x3fef838b8c811c17), UINT64_C(0x0000000000000000), UINT64_C(0x3fc63a1a7e0b738c) },
};
static const uint64_t DOP_CASE_5_W[4] = { UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000) };

static const uint64_t DOP_SING_0_LOS[3][3] = {
    { UINT64_C(0x3fdaa2fbd945ccc0), UINT64_C(0x3fb2c97bb8ccdf37), UINT64_C(0x3fed0079302dd766) },
    { UINT64_C(0x3fe09f95aba18faf), UINT64_C(0x3feb4d27ce94dbce), UINT64_C(0x3fa8408293b0d4f0) },
    { UINT64_C(0x3fe8f55f9ae5db06), UINT64_C(0xbfe3f829842cce52), UINT64_C(0x3fa8408293b0d4b8) },
};
static const uint64_t DOP_SING_0_W[3] = { UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000) };

static const uint64_t DOP_SING_1_LOS[4][3] = {
    { UINT64_C(0x3fdaa2fbd945ccc0), UINT64_C(0x3fb2c97bb8ccdf37), UINT64_C(0x3fed0079302dd766) },
    { UINT64_C(0x3fdaa2fbd945ccc0), UINT64_C(0x3fb2c97bb8ccdf37), UINT64_C(0x3fed0079302dd766) },
    { UINT64_C(0x3fdaa2fbd945ccc0), UINT64_C(0x3fb2c97bb8ccdf37), UINT64_C(0x3fed0079302dd766) },
    { UINT64_C(0x3fdaa2fbd945ccc0), UINT64_C(0x3fb2c97bb8ccdf37), UINT64_C(0x3fed0079302dd766) },
};
static const uint64_t DOP_SING_1_W[4] = { UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x3ff0000000000000) };

#define DOP_CASE_COUNT 6
static const DopGoldenCase DOP_CASES[DOP_CASE_COUNT] = {
    {
        .name = "four_sats_symmetric",
        .sat_count = 4,
        .los_bits = DOP_CASE_0_LOS,
        .weight_bits = DOP_CASE_0_W,
        .lat_rad_bits = UINT64_C(0x3fe921fb54442d18),
        .lon_rad_bits = UINT64_C(0x3fc657184ae74487),
        .gdop_bits = UINT64_C(0x40094512188a0ee8),
        .pdop_bits = UINT64_C(0x400670b4a1e5da09),
        .hdop_bits = UINT64_C(0x3ff9ebd66303910a),
        .vdop_bits = UINT64_C(0x400251acf780e6a6),
        .tdop_bits = UINT64_C(0x3ff73cdc1aa52898),
    },
    {
        .name = "six_sats_good",
        .sat_count = 6,
        .los_bits = DOP_CASE_1_LOS,
        .weight_bits = DOP_CASE_1_W,
        .lat_rad_bits = UINT64_C(0x3fe921fb54442d18),
        .lon_rad_bits = UINT64_C(0x3fc657184ae74487),
        .gdop_bits = UINT64_C(0x40042c84c6b1f151),
        .pdop_bits = UINT64_C(0x40016799f91eab89),
        .hdop_bits = UINT64_C(0x3ff2fa3851086f0e),
        .vdop_bits = UINT64_C(0x3ffd2e6c90994e09),
        .tdop_bits = UINT64_C(0x3ff466f9c2e85f34),
    },
    {
        .name = "weighted_elevation",
        .sat_count = 5,
        .los_bits = DOP_CASE_2_LOS,
        .weight_bits = DOP_CASE_2_W,
        .lat_rad_bits = UINT64_C(0xbfe26e40d7653223),
        .lon_rad_bits = UINT64_C(0x40051565537d7579),
        .gdop_bits = UINT64_C(0x4008c5c48082767e),
        .pdop_bits = UINT64_C(0x40055b618ce07038),
        .hdop_bits = UINT64_C(0x3ff8a382c459076f),
        .vdop_bits = UINT64_C(0x4001721a8d8e98b5),
        .tdop_bits = UINT64_C(0x3ff91abe890067e9),
    },
    {
        .name = "poor_geometry_clustered",
        .sat_count = 5,
        .los_bits = DOP_CASE_3_LOS,
        .weight_bits = DOP_CASE_3_W,
        .lat_rad_bits = UINT64_C(0x0000000000000000),
        .lon_rad_bits = UINT64_C(0x0000000000000000),
        .gdop_bits = UINT64_C(0x407a46057cd51c8d),
        .pdop_bits = UINT64_C(0x40729f358a55677b),
        .hdop_bits = UINT64_C(0x4062f1f89f22ec55),
        .vdop_bits = UINT64_C(0x4070085ad0c24191),
        .tdop_bits = UINT64_C(0x407288cb9149dca7),
    },
    {
        .name = "polar_site",
        .sat_count = 5,
        .los_bits = DOP_CASE_4_LOS,
        .weight_bits = DOP_CASE_4_W,
        .lat_rad_bits = UINT64_C(0x3ff7bc89cf95b8d0),
        .lon_rad_bits = UINT64_C(0xc000c152382d7365),
        .gdop_bits = UINT64_C(0x400c925300481812),
        .pdop_bits = UINT64_C(0x4008ad9a8dbf741f),
        .hdop_bits = UINT64_C(0x3ff48b63279c6bba),
        .vdop_bits = UINT64_C(0x400670495bf64cd2),
        .tdop_bits = UINT64_C(0x3ffccc2b7a1f4df4),
    },
    {
        .name = "equatorial_prime_meridian",
        .sat_count = 4,
        .los_bits = DOP_CASE_5_LOS,
        .weight_bits = DOP_CASE_5_W,
        .lat_rad_bits = UINT64_C(0x0000000000000000),
        .lon_rad_bits = UINT64_C(0x0000000000000000),
        .gdop_bits = UINT64_C(0x40183c99fc86fd39),
        .pdop_bits = UINT64_C(0x4013992998d0e1b4),
        .hdop_bits = UINT64_C(0x3ffc56a5716195a8),
        .vdop_bits = UINT64_C(0x401245e100aca480),
        .tdop_bits = UINT64_C(0x400c84ba965d84ea),
    },
};

#define DOP_SINGULAR_COUNT 2
static const DopSingularCase DOP_SINGULAR[DOP_SINGULAR_COUNT] = {
    {
        .name = "only_three_sats",
        .sat_count = 3,
        .los_bits = DOP_SING_0_LOS,
        .weight_bits = DOP_SING_0_W,
        .lat_rad_bits = UINT64_C(0x3fe921fb54442d18),
        .lon_rad_bits = UINT64_C(0x3fc657184ae74487),
    },
    {
        .name = "duplicate_directions",
        .sat_count = 4,
        .los_bits = DOP_SING_1_LOS,
        .weight_bits = DOP_SING_1_W,
        .lat_rad_bits = UINT64_C(0x3fe921fb54442d18),
        .lon_rad_bits = UINT64_C(0x3fc657184ae74487),
    },
};

#endif /* SIDEREON_DOP_FIXTURE_H */
