/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/pingen from sidereon-core. Every value is an exact
 * IEEE-754 float64 bit pattern of the engine's result. Do not edit by hand;
 * rerun the generator. */
#ifndef SIDEREON_ENGINE_PINS_FIXTURE_H
#define SIDEREON_ENGINE_PINS_FIXTURE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* WTZR/WTZZ single-frequency RINEX RTK arc, epoch 0, G05: the base and
 * rover transmit-time satellite positions (ECEF metres). */
static const uint64_t PIN_RTK_BASE_G05_POSITION_BITS[3] = { UINT64_C(0x41737544d6a7cc93), UINT64_C(0xc151590275e5541a), UINT64_C(0x416f3456ed5737f9) };
static const uint64_t PIN_RTK_ROVER_G05_POSITION_BITS[3] = { UINT64_C(0x41737544d18f90bc), UINT64_C(0xc15159028007c7aa), UINT64_C(0x416f3456f86ff660) };

/* WTZR/WTZZ carrier static reference-station solve (rtk_rinex_smoke.c):
 * the WTZR antenna reference point it is given, the integer ratio, position
 * and baseline (ECEF metres), position covariance (ECEF square metres,
 * row-major). */
static const uint64_t PIN_STATIC_REFERENCE_ARP_BITS[3] = { UINT64_C(0x414f181e2da372f7), UINT64_C(0x412c701c211f4e38), UINT64_C(0x415251081565efd8) };
static const uint64_t PIN_STATIC_REFERENCE_RATIO_BITS = UINT64_C(0x4055ce6634521828);
static const uint64_t PIN_STATIC_REFERENCE_POSITION_BITS[3] = { UINT64_C(0x414f181daf5f86cc), UINT64_C(0x412c701ad35a97cf), UINT64_C(0x4152510859bc8a81) };
static const uint64_t PIN_STATIC_REFERENCE_BASELINE_BITS[3] = { UINT64_C(0xbfef90fb0ac567c9), UINT64_C(0xbfe4dc4b6688b506), UINT64_C(0x3ff115a6aa24c512) };
static const uint64_t PIN_STATIC_REFERENCE_COVARIANCE_BITS[9] = { UINT64_C(0x3f04714c22717de7), UINT64_C(0x3eded47420268df8), UINT64_C(0x3ef2f6943b05405f), UINT64_C(0x3eded47420268df6), UINT64_C(0x3eec2a218bb40a65), UINT64_C(0x3ed80783fb505d72), UINT64_C(0x3ef2f6943b05405d), UINT64_C(0x3ed80783fb505d72), UINT64_C(0x3f090f65270bcd58) };

/* domain018 synthetic scenario, first observation row. */
static const uint64_t PIN_SCENARIO_PSEUDORANGE_M_BITS = UINT64_C(0x41733f384e5d34c4);
static const uint64_t PIN_SCENARIO_CARRIER_PHASE_CYCLES_BITS = UINT64_C(0x4199492dcd9c0c4b);
static const uint64_t PIN_SCENARIO_DOPPLER_HZ_BITS = UINT64_C(0xbfb6eacf6a1f4358);
static const uint64_t PIN_SCENARIO_GEOMETRIC_RANGE_M_BITS = UINT64_C(0x41733f3670013e3d);
static const uint64_t PIN_SCENARIO_THERMAL_NOISE_M_BITS = UINT64_C(0xbfc20e80d98bf56c);

/* round2_parity_smoke.c TLE fit: sidereon_core::astro::sgp4::fit_tle of the
 * three samples that test builds. */
static const uint64_t PIN_FIT_RMS_POSITION_KM_BITS = UINT64_C(0x3dad268f5b6752f7);
static const uint64_t PIN_FIT_MAX_POSITION_KM_BITS = UINT64_C(0x3db3c549d2d8f3ac);
static const uint64_t PIN_FIT_RMS_VELOCITY_KM_S_BITS = UINT64_C(0x3d124e26eed4727e);
static const uint64_t PIN_FIT_TLE_RMS_POSITION_KM_BITS = UINT64_C(0x0000000000000000);
#define PIN_FIT_STATUS 3
#define PIN_FIT_NFEV 36
#define PIN_FIT_NJEV 36
#define PIN_FIT_SEED_REFINE_PASSES 2
#define PIN_FIT_LINE1 "1 25544U          26168.18949189  .00000000  00000-0  17172-3 0  9993"
#define PIN_FIT_LINE2 "2 25544  51.6332 300.0813 0004737 195.1146 164.9702 15.49273435571752"

/* round2_parity_smoke.c observation QC of the 120-epoch ESBC file under the
 * default options. */
#define PIN_QC_SATELLITE_SIGNAL_COUNT 659
#define PIN_QC_SYSTEM_SIGNAL_COUNT 78
#define PIN_QC_CYCLE_SLIP_OBSERVATIONS 4271
#define PIN_QC_CYCLE_SLIP_TOTAL 29
#define PIN_QC_CYCLE_SLIP_SYSTEM_COUNT 4
#define PIN_QC_SLIPS_GPS_OBSERVATIONS 1282
#define PIN_QC_SLIPS_GPS_SLIPS 4
#define PIN_QC_SLIPS_GLONASS_OBSERVATIONS 920
#define PIN_QC_SLIPS_GLONASS_SLIPS 12
#define PIN_QC_SLIPS_GALILEO_OBSERVATIONS 1023
#define PIN_QC_SLIPS_GALILEO_SLIPS 9
#define PIN_QC_SLIPS_BEIDOU_OBSERVATIONS 1046
#define PIN_QC_SLIPS_BEIDOU_SLIPS 4
#define PIN_QC_MULTIPATH_SYSTEM_COUNT 4
#define PIN_QC_MP_GPS_MP1_N 1282
#define PIN_QC_MP_GPS_MP2_N 1282
static const uint64_t PIN_QC_MP_GPS_MP1_RMS_M_BITS = UINT64_C(0x3fd2b6c297ccd505);
static const uint64_t PIN_QC_MP_GPS_MP2_RMS_M_BITS = UINT64_C(0x3fd1fbd832ba5172);
#define PIN_QC_MP_GLONASS_MP1_N 920
#define PIN_QC_MP_GLONASS_MP2_N 920
static const uint64_t PIN_QC_MP_GLONASS_MP1_RMS_M_BITS = UINT64_C(0x3fe0ca404fa0cdcb);
static const uint64_t PIN_QC_MP_GLONASS_MP2_RMS_M_BITS = UINT64_C(0x3fd8f848782e1926);
#define PIN_QC_MP_GALILEO_MP1_N 1023
#define PIN_QC_MP_GALILEO_MP2_N 1023
static const uint64_t PIN_QC_MP_GALILEO_MP1_RMS_M_BITS = UINT64_C(0x3fd8badc90a5fe68);
static const uint64_t PIN_QC_MP_GALILEO_MP2_RMS_M_BITS = UINT64_C(0x3fdef0f4dd0cdf49);
#define PIN_QC_MP_BEIDOU_MP1_N 1046
#define PIN_QC_MP_BEIDOU_MP2_N 1046
static const uint64_t PIN_QC_MP_BEIDOU_MP1_RMS_M_BITS = UINT64_C(0x3ff04737d194d6f4);
static const uint64_t PIN_QC_MP_BEIDOU_MP2_RMS_M_BITS = UINT64_C(0x3ff2c72448aa458d);
#define PIN_QC_MULTIPATH_SATELLITE_COUNT 41
#define PIN_QC_MP_G08_MP1_N 120
#define PIN_QC_MP_G08_MP2_N 120
static const uint64_t PIN_QC_MP_G08_MP1_RMS_M_BITS = UINT64_C(0x3fdd34cb05025023);
static const uint64_t PIN_QC_MP_G08_MP2_RMS_M_BITS = UINT64_C(0x3fe45ad2afdbe8f3);

/* rinex_nav_clock_smoke.c: the broadcast store of the ESBC mixed NAV file
 * followed by that test's GLONASS record, and the NAV text written for the
 * file's first raw record. */
#define PIN_NAV_STORE_RECORD_COUNT 1435
#define PIN_NAV_ENCODED_FIRST_RECORD_LEN 883

/* smoke.c constellation checks: the merged GPS catalog of the committed
 * CelesTrak and NAVCEN fixtures, its CSV with lowercase booleans, and its
 * validation against PIN_CONSTELLATION_VALIDATE_SP3_IDS. */
static const char *const PIN_CONSTELLATION_VALIDATE_SP3_IDS[] = { "G03", "G05", "G13" };
#define PIN_CONSTELLATION_VALIDATE_SP3_ID_COUNT ((size_t)3)
#define PIN_CONSTELLATION_RECORD_COUNT ((size_t)4)
static const char PIN_CONSTELLATION_CSV[] = "prn,norad_cat_id,active,sp3_id\n3,40294,true,G03\n5,35752,true,G05\n13,68791,true,G13\n19,28190,false,G19\n";
#define PIN_CONSTELLATION_VALID false
static const unsigned short PIN_CONSTELLATION_INACTIVE_UNUSABLE_PRNS[] = { 19 };
#define PIN_CONSTELLATION_INACTIVE_UNUSABLE_PRN_COUNT ((size_t)1)
#define PIN_CONSTELLATION_MISSING_SP3_ID_COUNT ((size_t)0)
#define PIN_CONSTELLATION_EXTRA_SP3_ID_COUNT ((size_t)0)

#endif /* SIDEREON_ENGINE_PINS_FIXTURE_H */
