#!/usr/bin/env python3
"""Bake the constellation parity fixtures into a C header.

The C constellation surface (sidereon_constellation_build / _to_csv /
_validate_against_sp3_ids) calls the engine's sidereon_core::constellation
module: it parses CelesTrak gps-ops OMM/JSON and a NAVCEN GPS status HTML
overlay, merges them, and exports the compact mapping CSV. The engine certifies
that merge and CSV against the identity/status fixtures, so the C smoke test
feeds the SAME bytes and asserts the SAME CSV plus the SAME SP3-id validation
result. A third shared fixture covers explicit-time forecast behavior.

The fixtures under tests/fixtures/constellation mirror the same cases certified
by the core suite. This script emits the binding copies as byte arrays. The
expected CSV and SP3-id validation findings are sidereon-core's own results for
the same bytes, written into engine_pins_fixture.h by tests/pingen.

tests/run_generators.sh runs it from the binding root.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures", "constellation")
GPS_OPS = os.path.join(FIXTURES, "gps_ops_sample.json")
NAVCEN = os.path.join(FIXTURES, "navcen_gps_sample.html")
NAVCEN_FORECAST = os.path.join(FIXTURES, "navcen_forecast_cases.html")
OUT = os.path.join(HERE, "constellation_fixture.h")


def byte_array(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"#define {name}_LEN ((size_t){len(data)})")
    return lines


def main():
    with open(GPS_OPS, "rb") as fh:
        gps_ops = fh.read()
    with open(NAVCEN, "rb") as fh:
        navcen = fh.read()
    with open(NAVCEN_FORECAST, "rb") as fh:
        navcen_forecast = fh.read()

    lines = []
    w = lines.append
    w("/* Generated by tests/gen_constellation_fixture_header.py from the copied")
    w(" * core constellation fixtures. The bytes are fed verbatim to the C")
    w(" * constellation surface; the expected merged-catalog CSV and SP3-id")
    w(" * validation are sidereon-core's, in engine_pins_fixture.h (tests/pingen).")
    w(" * Do not edit by hand; rerun the generator. */")
    w("#ifndef SIDEREON_CONSTELLATION_FIXTURE_H")
    w("#define SIDEREON_CONSTELLATION_FIXTURE_H")
    w("")
    w("#include <stddef.h>")
    w("")
    w("/* CelesTrak gps-ops OMM/JSON array. */")
    lines.extend(byte_array("CONSTELLATION_GPS_OPS_JSON", gps_ops))
    w("")
    w("/* NAVCEN GPS constellation status HTML overlay. */")
    lines.extend(byte_array("CONSTELLATION_NAVCEN_HTML", navcen))
    w("")
    w("/* Time-aware NAVCEN forecast and ambiguity cases. */")
    lines.extend(byte_array("CONSTELLATION_NAVCEN_FORECAST_HTML", navcen_forecast))
    w("")
    w("#endif /* SIDEREON_CONSTELLATION_FIXTURE_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(
        f"wrote {OUT} ({len(gps_ops)} json bytes, {len(navcen)} navcen bytes, "
        f"{len(navcen_forecast)} forecast bytes)"
    )


if __name__ == "__main__":
    main()
