#!/usr/bin/env python3
"""Transcribe committed propagation fixtures into a C header.

The C smoke test exercises the propagation ABI against the engine's own
propagation fixtures. This script copies their JSON values into exact
IEEE-754 bit patterns, avoiding any C-side parsing or invented reference
values. Run it through tests/run_generators.sh from the binding root.

The fixtures are the ones sidereon-core's own emitters write
(tests/tle_python_fixture.rs, sgp4_topocentric_arc.rs, pass_finder_arc.rs and
numerical_propagation.rs under SIDEREON_DUMP_FIXTURES=1), read from where they
write them in the core checkout the generators resolve. tests/run_generators.sh
runs the emitters first. No fixture is read from another binding.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
from generator_support import emitted_fixtures_dir, revision_comment  # noqa: E402

EMITTED = emitted_fixtures_dir()
TLE_FIXTURE = os.path.join(EMITTED, "tle_roundtrip.json")
SGP4_FIXTURE = os.path.join(EMITTED, "sgp4_topocentric.json")
PASS_FIXTURE = os.path.join(EMITTED, "pass_finder.json")
NUM_FIXTURE = os.path.join(EMITTED, "numerical_propagation.json")
OUT = os.path.join(HERE, "prop_fixture.h")


def bits(hex_str):
    return f"UINT64_C({int(hex_str, 16):#018x})"


def cstr(text):
    return json.dumps(text)


def int64(value):
    return f"INT64_C({value})"


def opmode_value(name):
    return {"afspc": 0, "improved": 1}[name]


def tle_int_field(line, start, end, default=0):
    value = line[start : end + 1].strip()
    return int(value) if value else default


def force_model_value(name):
    return {"two_body": 0, "two_body_j2": 1}[name]


def integrator_value(name):
    return {"dp54": 0, "rk4": 1}[name]


def write_u64_vec(w, name, values):
    w(f"static const uint64_t {name}[3] = {{")
    w(f"    {', '.join(bits(v) for v in values)},")
    w("};")


def write_u64_matrix(w, name, rows):
    w(f"static const uint64_t {name}[{len(rows)}][3] = {{")
    for row in rows:
        w(f"    {{ {', '.join(bits(v) for v in row)} }},")
    w("};")


def main():
    with open(TLE_FIXTURE) as fh:
        tle = json.load(fh)
    with open(SGP4_FIXTURE) as fh:
        sgp4 = json.load(fh)
    with open(PASS_FIXTURE) as fh:
        passes = json.load(fh)
    with open(NUM_FIXTURE) as fh:
        num = json.load(fh)

    lines = []
    w = lines.append
    w(revision_comment())
    w("/* Generated by tests/gen_prop_fixture_header.py from committed")
    w(" * Python/Core propagation fixtures. Numeric references are copied as")
    w(" * exact IEEE-754 float64 bit patterns where available. Do not edit by")
    w(" * hand; rerun the generator. */")
    w("#ifndef SIDEREON_PROP_FIXTURE_H")
    w("#define SIDEREON_PROP_FIXTURE_H")
    w("")
    w("#include <stdint.h>")
    w("")

    w(f"#define PROP_TLE_LINE1 {cstr(tle['tle']['line1'])}")
    w(f"#define PROP_TLE_LINE2 {cstr(tle['tle']['line2'])}")
    w(f"#define PROP_TLE_ENCODED_LINE1 {cstr(tle['encoded']['line1'])}")
    w(f"#define PROP_TLE_ENCODED_LINE2 {cstr(tle['encoded']['line2'])}")
    w(f"#define PROP_TLE_BAD_CHECKSUM_LINE1 {cstr(tle['checksum_case']['line1'])}")
    w(f"#define PROP_TLE_BAD_CHECKSUM_LINE2 {cstr(tle['checksum_case']['line2'])}")
    w(f"#define PROP_TLE_OPSMODE {opmode_value(tle['opsmode'])}")
    el = tle["elements"]
    w(f"#define PROP_TLE_CATALOG_NUMBER {cstr(el['catalog_number'])}")
    w(f"#define PROP_TLE_CLASSIFICATION {cstr(el['classification'])}")
    w(f"#define PROP_TLE_INTERNATIONAL_DESIGNATOR {cstr(el['international_designator'])}")
    w(f"#define PROP_TLE_EPOCH_YEAR {el['epoch_year']}")
    w(f"#define PROP_TLE_EPOCH_DAY_OF_YEAR {el['epoch_day_of_year']:.17g}")
    w(f"#define PROP_TLE_INCLINATION_DEG {el['inclination_deg']:.17g}")
    w(f"#define PROP_TLE_RAAN_DEG {el['raan_deg']:.17g}")
    w(f"#define PROP_TLE_ECCENTRICITY {el['eccentricity']:.17g}")
    w(f"#define PROP_TLE_ARG_PERIGEE_DEG {el['arg_perigee_deg']:.17g}")
    w(f"#define PROP_TLE_MEAN_ANOMALY_DEG {el['mean_anomaly_deg']:.17g}")
    w(f"#define PROP_TLE_MEAN_MOTION_REV_PER_DAY {el['mean_motion']:.17g}")
    w(f"#define PROP_TLE_MEAN_MOTION_DOT {el['mean_motion_dot']:.17g}")
    w(f"#define PROP_TLE_MEAN_MOTION_DOUBLE_DOT {el['mean_motion_double_dot']:.17g}")
    w(f"#define PROP_TLE_BSTAR {el['bstar']:.17g}")
    w(f"#define PROP_TLE_EPHEMERIS_TYPE {tle_int_field(tle['tle']['line1'], 62, 62)}")
    w(f"#define PROP_TLE_ELSET_NUMBER {tle_int_field(tle['tle']['line1'], 64, 67)}")
    w(f"#define PROP_TLE_REV_NUMBER {el['rev_number']}")
    # A blank field is read as absent; presence is read from the committed lines.
    line1, line2 = tle["tle"]["line1"], tle["tle"]["line2"]
    w(f"#define PROP_TLE_HAS_EPHEMERIS_TYPE {int(bool(line1[62:63].strip()))}")
    w(f"#define PROP_TLE_HAS_ELSET_NUMBER {int(bool(line1[64:68].strip()))}")
    w(f"#define PROP_TLE_HAS_REV_NUMBER {int(bool(line2[63:68].strip()))}")
    warnings = tle["checksum_case"]["warnings"]
    w(f"#define PROP_TLE_CHECKSUM_WARNING_COUNT {len(warnings)}")
    if warnings:
        first = warnings[0]
        # The warning is on line 1. What its column 69 holds is read from the
        # committed line itself: a digit is a mismatch, anything else is not a
        # digit, and a line shorter than 69 columns carries no checksum.
        bad_line1 = tle["checksum_case"]["line1"]
        if len(bad_line1) < 69:
            kind, found = "SIDEREON_TLE_CHECKSUM_WARNING_KIND_MISSING", 0
        elif bad_line1[68].isdigit():
            kind, found = "SIDEREON_TLE_CHECKSUM_WARNING_KIND_MISMATCH", int(bad_line1[68])
        else:
            kind, found = "SIDEREON_TLE_CHECKSUM_WARNING_KIND_NOT_DIGIT", ord(bad_line1[68])
        w(f"#define PROP_TLE_CHECKSUM_WARNING_LINE_NUMBER 1")
        w(f"#define PROP_TLE_CHECKSUM_WARNING_KIND {kind}")
        w(f"#define PROP_TLE_CHECKSUM_WARNING_FOUND {found}")
        w(f"#define PROP_TLE_CHECKSUM_WARNING_COMPUTED {first['computed']}")
    w("")

    epochs = sgp4["epochs"]
    station = sgp4["station"]
    w(f"#define PROP_EPOCH_COUNT {len(epochs)}")
    w(f"#define PROP_STATION_LATITUDE_DEG {station['latitude_deg']:.17g}")
    w(f"#define PROP_STATION_LONGITUDE_DEG {station['longitude_deg']:.17g}")
    w(f"#define PROP_STATION_ALTITUDE_M {station['altitude_m']:.17g}")
    w("static const int64_t PROP_EPOCHS_UNIX_US[PROP_EPOCH_COUNT] = {")
    for row in epochs:
        w(f"    {int64(row['unix_microseconds'])},")
    w("};")
    write_u64_matrix(w, "PROP_TEME_POSITION_BITS", [row["position_km_hex"] for row in epochs])
    write_u64_matrix(w, "PROP_TEME_VELOCITY_BITS", [row["velocity_km_s_hex"] for row in epochs])
    w("static const uint64_t PROP_LOOK_AZIMUTH_BITS[PROP_EPOCH_COUNT] = {")
    for row in epochs:
        w(f"    {bits(row['azimuth_deg_hex'])},")
    w("};")
    w("static const uint64_t PROP_LOOK_ELEVATION_BITS[PROP_EPOCH_COUNT] = {")
    for row in epochs:
        w(f"    {bits(row['elevation_deg_hex'])},")
    w("};")
    w("static const uint64_t PROP_LOOK_RANGE_BITS[PROP_EPOCH_COUNT] = {")
    for row in epochs:
        w(f"    {bits(row['range_km_hex'])},")
    w("};")
    w("")

    pwindow = passes["window"]
    popts = passes["options"]
    pass_rows = passes["passes"]
    w(f"#define PROP_PASS_START_UNIX_US {int64(pwindow['start_unix_us'])}")
    w(f"#define PROP_PASS_END_UNIX_US {int64(pwindow['end_unix_us'])}")
    w(f"#define PROP_PASS_ELEVATION_MASK_DEG {popts['elevation_mask_deg']:.17g}")
    w(f"#define PROP_PASS_STEP_SECONDS {popts['coarse_step_seconds']:.17g}")
    w(f"#define PROP_PASS_TIME_TOLERANCE_S {popts['time_tolerance_seconds']:.17g}")
    w(f"#define PROP_PASS_COUNT {len(pass_rows)}")
    w("static const int64_t PROP_PASS_AOS_UNIX_US[PROP_PASS_COUNT] = {")
    for row in pass_rows:
        w(f"    {int64(row['aos_unix_us'])},")
    w("};")
    w("static const int64_t PROP_PASS_LOS_UNIX_US[PROP_PASS_COUNT] = {")
    for row in pass_rows:
        w(f"    {int64(row['los_unix_us'])},")
    w("};")
    w("static const int64_t PROP_PASS_CULMINATION_UNIX_US[PROP_PASS_COUNT] = {")
    for row in pass_rows:
        w(f"    {int64(row['culmination_unix_us'])},")
    w("};")
    w("static const uint64_t PROP_PASS_MAX_ELEVATION_BITS[PROP_PASS_COUNT] = {")
    for row in pass_rows:
        w(f"    {bits(row['max_elevation_deg_hex'])},")
    w("};")
    w("")

    samples = num["samples"]
    nopts = num["options"]
    w(f"#define PROP_NUM_FORCE_MODEL {force_model_value(num['force_model'])}")
    w(f"#define PROP_NUM_INTEGRATOR {integrator_value(num['integrator'])}")
    w(f"#define PROP_NUM_ABS_TOL {nopts['abs_tol']:.17g}")
    w(f"#define PROP_NUM_REL_TOL {nopts['rel_tol']:.17g}")
    w(f"#define PROP_NUM_INITIAL_STEP_S {nopts['initial_step_s']:.17g}")
    w(f"#define PROP_NUM_MIN_STEP_S {nopts['min_step_s']:.17g}")
    w(f"#define PROP_NUM_MAX_STEP_S {nopts['max_step_s']:.17g}")
    w(f"#define PROP_NUM_MAX_STEPS {nopts['max_steps']}")
    w(f"static const uint64_t PROP_NUM_EPOCH_S_BITS = {bits(num['epoch_s_hex'])};")
    write_u64_vec(w, "PROP_NUM_INITIAL_POSITION_BITS", num["position_km_hex"])
    write_u64_vec(w, "PROP_NUM_INITIAL_VELOCITY_BITS", num["velocity_km_s_hex"])
    w(f"#define PROP_NUM_SAMPLE_COUNT {len(samples)}")
    w("static const uint64_t PROP_NUM_TIME_BITS[PROP_NUM_SAMPLE_COUNT] = {")
    for row in samples:
        w(f"    {bits(row['time_s_hex'])},")
    w("};")
    write_u64_matrix(w, "PROP_NUM_POSITION_BITS", [row["position_km_hex"] for row in samples])
    write_u64_matrix(w, "PROP_NUM_VELOCITY_BITS", [row["velocity_km_s_hex"] for row in samples])
    w("")
    w("#endif /* SIDEREON_PROP_FIXTURE_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
