#!/usr/bin/env python3
"""Transcribe the committed ANTEX golden into a C header.

The C ANTEX accessors call the engine's ANTEX parser/lookup directly, and the
engine certifies those values bit-for-bit against the oracle
`sidereon-core/tests/fixtures/antex/antex_golden.json` (the trimmed real
`igs20.atx`). So the C smoke test parses the SAME trimmed `.atx`, looks up each
antenna/frequency, and asserts the SAME PCO and PCV node values bit-for-bit.

The golden stores PCO/PCV in millimeters; the engine returns meters. The engine
test asserts `value_m.to_bits() == (value_mm / 1000.0).to_bits()`, so this script
emits the expected meters (value_mm / 1000.0) as exact IEEE-754 bit patterns.
PCV is asserted at each stored grid node, where the linear interpolation returns
the node value exactly.

Run from the binding root:
    python3 tests/gen_antex_fixture_header.py
"""

import json
import os
import struct
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
BINDING_ROOT = os.path.normpath(os.path.join(HERE, ".."))


def core_fixtures_dir():
    metadata = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1", "--quiet"],
            cwd=BINDING_ROOT,
        )
    )
    manifest = next(
        p["manifest_path"] for p in metadata["packages"] if p["name"] == "sidereon-core"
    )
    return os.path.join(os.path.dirname(manifest), "tests", "fixtures")


GOLDEN = os.path.join(core_fixtures_dir(), "antex", "antex_golden.json")
OUT = os.path.join(HERE, "antex_fixture.h")


def bits_of(value):
    raw = struct.unpack("<Q", struct.pack("<d", value))[0]
    return f"UINT64_C({raw:#018x})"


def mm_to_m_bits(mm):
    return bits_of(mm / 1000.0)


def cstr(text):
    return json.dumps(text)


def main():
    with open(GOLDEN) as fh:
        doc = json.load(fh)
    antennas = doc["antennas"]

    pcv_rows = []  # (antenna_idx, freq_code, zenith, has_az, az, value_mm)
    pco_rows = []  # (antenna_idx, freq_code, north_mm, east_mm, up_mm)

    lines = []
    w = lines.append
    w("/* Generated by tests/gen_antex_fixture_header.py from the committed core")
    w(" * golden sidereon-core/tests/fixtures/antex/antex_golden.json. The C smoke")
    w(" * test parses the trimmed igs20 .atx and asserts every PCO triple and PCV")
    w(" * grid node bit-for-bit against the engine oracle (golden mm / 1000 ->")
    w(" * meters). Do not edit by hand; rerun the generator. */")
    w("#ifndef SIDEREON_ANTEX_FIXTURE_H")
    w("#define SIDEREON_ANTEX_FIXTURE_H")
    w("")
    w("#include <stdbool.h>")
    w("#include <stddef.h>")
    w("#include <stdint.h>")
    w("")
    trimmed = doc["_source"]["trimmed_file"]
    w(f'#define ANTEX_FILE "{trimmed}"')
    w(f"#define ANTEX_ANTENNA_COUNT {len(antennas)}")
    w("")
    w("typedef struct {")
    w("    const char *antenna_id;")
    w("    const char *frequency;")
    w("    uint64_t north_m_bits;")
    w("    uint64_t east_m_bits;")
    w("    uint64_t up_m_bits;")
    w("} AntexPcoCase;")
    w("")
    w("typedef struct {")
    w("    const char *antenna_id;")
    w("    const char *frequency;")
    w("    double zenith_deg;")
    w("    bool has_azimuth;")
    w("    double azimuth_deg;")
    w("    uint64_t value_m_bits;")
    w("} AntexPcvCase;")
    w("")

    for ai, ant in enumerate(antennas):
        aid = ant["id"]
        for freq in ant["frequencies"]:
            code = freq["frequency"]
            pco = freq["pco_neu_mm"]
            pco_rows.append((aid, code, pco["north"], pco["east"], pco["up"]))
            for s in freq["pcv_samples_mm"]:
                az = s["azimuth_deg"]
                pcv_rows.append(
                    (aid, code, s["zenith_deg"], az is not None,
                     az if az is not None else 0.0, s["value"])
                )

    w(f"#define ANTEX_PCO_CASE_COUNT {len(pco_rows)}")
    w("static const AntexPcoCase ANTEX_PCO_CASES[ANTEX_PCO_CASE_COUNT] = {")
    for aid, code, n, e, u in pco_rows:
        w("    {")
        w(f"        .antenna_id = {cstr(aid)},")
        w(f"        .frequency = {cstr(code)},")
        w(f"        .north_m_bits = {mm_to_m_bits(n)},")
        w(f"        .east_m_bits = {mm_to_m_bits(e)},")
        w(f"        .up_m_bits = {mm_to_m_bits(u)},")
        w("    },")
    w("};")
    w("")
    w(f"#define ANTEX_PCV_CASE_COUNT {len(pcv_rows)}")
    w("static const AntexPcvCase ANTEX_PCV_CASES[ANTEX_PCV_CASE_COUNT] = {")
    for aid, code, zen, has_az, az, val in pcv_rows:
        w("    {")
        w(f"        .antenna_id = {cstr(aid)},")
        w(f"        .frequency = {cstr(code)},")
        w(f"        .zenith_deg = {zen!r},")
        w(f"        .has_azimuth = {'true' if has_az else 'false'},")
        w(f"        .azimuth_deg = {az!r},")
        w(f"        .value_m_bits = {mm_to_m_bits(val)},")
        w("    },")
    w("};")
    w("")
    w("#endif /* SIDEREON_ANTEX_FIXTURE_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(
        f"wrote {OUT} ({len(antennas)} antennas, "
        f"{len(pco_rows)} PCO triples, {len(pcv_rows)} PCV nodes)"
    )


if __name__ == "__main__":
    main()
