#!/usr/bin/env python3
"""Transcribe committed SPP/SP3 fixtures into a C header.

The C smoke test feeds the binding the inputs of the crate's own SPP reference
fixture (spp_trace_L0_minimal) and asserts the engine's default solution of
them, so no truth is invented on the C side. The fixture's final_solution pins
the replay range model the engine builds only for its own tests; the expected
solution comes from tests/sppgen, which solves the same inputs with the default
range model and writes `tests/fixtures/spp_expected.json`. Every value is copied
into `spp_fixture.h` as an exact IEEE-754 float64 bit pattern.

The SP3 constants, the writer's text included, are transcribed from the
`sp3_bodies.json` sidereon-core's own fixture emitter writes
(tests/sp3_bodies_python_fixture.rs); tests/run_generators.sh runs it first.

Run from the binding root:
    cargo run --release --manifest-path tests/sppgen/Cargo.toml \
        > tests/fixtures/spp_expected.json
    python3 tests/gen_fixture_header.py
"""

import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
BINDING_ROOT = os.path.normpath(os.path.join(HERE, ".."))


from generator_support import core_fixtures_dir, emitted_fixtures_dir, revision_comment


CORE_FIXTURES = core_fixtures_dir()
FIXTURE = os.path.join(CORE_FIXTURES, "spp_trace_L0_minimal.json")
# The SP3 surface values, the writer's text included, as sidereon-core's
# sp3_bodies_python_fixture emitter writes them.
SP3_FIXTURE = os.path.join(emitted_fixtures_dir(), "sp3_bodies.json")
# The engine's default-range-model solution of the fixture inputs, written by
# tests/sppgen. The core fixture's own final_solution pins a replay range model
# the engine builds only for its own tests.
EXPECTED = os.path.join(HERE, "fixtures", "spp_expected.json")
OUT = os.path.join(HERE, "spp_fixture.h")


def bits(hex_str):
    """Normalize a `0x...` float64 bit pattern to a `UINT64_C(0x...)` literal."""
    return f"UINT64_C({int(hex_str, 16):#018x})"


def c_string_literal(text):
    """Return C string literal fragments preserving text bytes."""
    return [json.dumps(chunk) for chunk in text.splitlines(True)]


def main():
    with open(FIXTURE) as fh:
        fx = json.load(fh)["fixture"]
    with open(SP3_FIXTURE) as fh:
        sp3_fx = json.load(fh)
    with open(EXPECTED) as fh:
        expected = json.load(fh)
    inp = fx["inputs"]
    obs = inp["observations"]
    used = fx["used_sats"]
    rejected = fx["rejected_sats"]

    lines = []
    w = lines.append
    w(revision_comment())
    w("/* Generated by tests/gen_fixture_header.py from committed SPP/SP3")
    w(" * fixtures and the engine solution tests/sppgen writes. Every numeric")
    w(" * value is an exact IEEE-754 float64 bit pattern. Do not edit by hand;")
    w(" * rerun the generators. */")
    w("#ifndef SIDEREON_SPP_FIXTURE_H")
    w("#define SIDEREON_SPP_FIXTURE_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w(f'#define SPP_SP3_FILE "{inp["sp3_file"]}"')
    w(f"#define SPP_OBS_COUNT {len(obs)}")
    w("")
    w("static const char *const SPP_SAT_IDS[SPP_OBS_COUNT] = {")
    for o in obs:
        w(f'    "{o["sat_id"]}",')
    w("};")
    w("")
    w(f"#define SPP_USED_SAT_COUNT {len(used)}")
    w("static const char *const SPP_USED_SAT_IDS[SPP_USED_SAT_COUNT] = {")
    for sat_id in used:
        w(f'    "{sat_id}",')
    w("};")
    w("")
    w(f"#define SPP_REJECTED_SAT_COUNT {len(rejected)}")
    w("static const char *const SPP_REJECTED_SAT_IDS[SPP_REJECTED_SAT_COUNT] = {")
    for sat in rejected:
        w(f'    "{sat["id"]}",')
    w("};")
    w("static const char *const SPP_REJECTED_SAT_REASONS[SPP_REJECTED_SAT_COUNT] = {")
    for sat in rejected:
        w(f'    "{sat["reason"]}",')
    w("};")
    w("")
    w("static const uint64_t SPP_PSEUDORANGE_BITS[SPP_OBS_COUNT] = {")
    for o in obs:
        w(f"    {bits(o['p_meas_m'])},")
    w("};")
    w("")

    def scalar(name, value):
        w(f"static const uint64_t {name} = {bits(value)};")

    def vec4(name, values):
        joined = ", ".join(bits(v) for v in values)
        w(f"static const uint64_t {name}[4] = {{ {joined} }};")

    scalar("SPP_T_RX_J2000_S_BITS", inp["t_rx_j2000_s"])
    scalar("SPP_T_RX_SOD_S_BITS", inp["t_rx_sod_s"])
    scalar("SPP_DOY_BITS", inp["doy"])
    vec4("SPP_INITIAL_GUESS_BITS", fx["frozen"]["initial_guess_x0"])
    vec4("SPP_KLOB_ALPHA_BITS", inp["klobuchar_alpha"])
    vec4("SPP_KLOB_BETA_BITS", inp["klobuchar_beta"])
    scalar("SPP_PRESSURE_HPA_BITS", inp["met"]["pressure_hpa"])
    scalar("SPP_TEMPERATURE_K_BITS", inp["met"]["temperature_k"])
    scalar("SPP_RELATIVE_HUMIDITY_BITS", inp["met"]["relative_humidity"])
    w("")
    w("/* The engine's default SPP solution of these inputs (tests/sppgen):")
    w(" * position [x_m, y_m, z_m] and receiver clock. The binding calls the")
    w(" * same engine path, so the tests compare these bits exactly. */")
    joined = ", ".join(bits(v) for v in expected["position_m"])
    w(f"static const uint64_t SPP_EXPECTED_X_BITS[3] = {{ {joined} }};")
    scalar("SPP_EXPECTED_RX_CLOCK_S_BITS", expected["rx_clock_s"])
    w("")

    sp3_file = sp3_fx["sp3_fixture"].replace("tests/fixtures/", "")
    satellites = sp3_fx["satellites"]
    queries = sp3_fx["query_j2000_seconds_hex"]
    interpolation = sp3_fx["interpolation"]
    state = sp3_fx["state_g01_epoch0"]
    sp3_text = sp3_fx["to_sp3_string"]

    w("/* SP3 surface constants transcribed from")
    w(" * the sp3_bodies.json sidereon-core's emitter writes. */")
    w(f'#define SP3_SURFACE_FILE "{sp3_file}"')
    w(f"#define SP3_SURFACE_EPOCH_COUNT {sp3_fx['epoch_count']}")
    w(f"#define SP3_SURFACE_SAT_COUNT {len(satellites)}")
    w("static const char *const SP3_SURFACE_SAT_IDS[SP3_SURFACE_SAT_COUNT] = {")
    for sat_id in satellites:
        w(f'    "{sat_id}",')
    w("};")
    w("")
    w("static const uint64_t SP3_SURFACE_EPOCH_BITS[SP3_SURFACE_EPOCH_COUNT] = {")
    for value in sp3_fx["epochs_j2000_seconds_hex"]:
        w(f"    {bits(value)},")
    w("};")
    w("")
    w(f"#define SP3_INTERP_QUERY_COUNT {len(queries)}")
    w("static const uint64_t SP3_INTERP_QUERY_BITS[SP3_INTERP_QUERY_COUNT] = {")
    for value in queries:
        w(f"    {bits(value)},")
    w("};")
    w("")
    w(f"#define SP3_INTERP_SAT_COUNT {len(interpolation)}")
    w("static const char *const SP3_INTERP_SAT_IDS[SP3_INTERP_SAT_COUNT] = {")
    for entry in interpolation:
        w(f'    "{entry["satellite"]}",')
    w("};")
    w("static const uint64_t")
    w("    SP3_INTERP_POSITION_BITS[SP3_INTERP_SAT_COUNT][SP3_INTERP_QUERY_COUNT][3] = {")
    for entry in interpolation:
        w("    {")
        for st in entry["states"]:
            joined = ", ".join(bits(v) for v in st["position_m_hex"])
            w(f"        {{ {joined} }},")
        w("    },")
    w("};")
    w("static const uint64_t")
    w("    SP3_INTERP_CLOCK_BITS[SP3_INTERP_SAT_COUNT][SP3_INTERP_QUERY_COUNT] = {")
    for entry in interpolation:
        joined = ", ".join(bits(st["clock_s_hex"]) for st in entry["states"])
        w(f"    {{ {joined} }},")
    w("};")
    w("")
    joined = ", ".join(bits(v) for v in state["position_m_hex"])
    w(f"static const uint64_t SP3_STATE_G01_EPOCH0_POSITION_BITS[3] = {{ {joined} }};")
    w(f"static const uint64_t SP3_STATE_G01_EPOCH0_CLOCK_BITS = {bits(state['clock_s_hex'])};")
    w(f"#define SP3_STATE_G01_EPOCH0_CLOCK_EVENT {int(state['clock_event'])}")
    w(f"#define SP3_STATE_G01_EPOCH0_CLOCK_PREDICTED {int(state['clock_predicted'])}")
    w(f"#define SP3_STATE_G01_EPOCH0_MANEUVER {int(state['maneuver'])}")
    w(f"#define SP3_STATE_G01_EPOCH0_ORBIT_PREDICTED {int(state['orbit_predicted'])}")
    w("")
    w(f"#define SP3_TO_SP3_TEXT_LEN {len(sp3_text.encode('ascii'))}")
    w("static const char SP3_TO_SP3_TEXT[SP3_TO_SP3_TEXT_LEN + 1] =")
    for fragment in c_string_literal(sp3_text):
        w(f"    {fragment}")
    w("    ;")
    w("")
    w("#endif /* SIDEREON_SPP_FIXTURE_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(obs)} observations)")


if __name__ == "__main__":
    main()
