#!/usr/bin/env python3
"""Bake the constellation parity fixtures into a C header.

The C constellation surface (sidereon_constellation_build / _to_csv /
_validate_against_sp3_ids) calls the engine's sidereon_core::constellation
module: it parses CelesTrak gps-ops OMM/JSON and a NAVCEN GPS status HTML
overlay, merges them, and exports the compact mapping CSV. The engine certifies
that merge and CSV against the identity/status fixtures, so the C smoke test
feeds the SAME bytes and asserts the SAME CSV plus the SAME SP3-id validation
result. A third shared fixture covers explicit-time forecast behavior.

The fixtures under tests/fixtures/constellation mirror the same cases certified
by the core suite. This script emits the binding copies as byte arrays alongside
the expected CSV and SP3-id validation findings.

Run from the binding root:
    python3 tests/gen_constellation_fixture_header.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures", "constellation")
GPS_OPS = os.path.join(FIXTURES, "gps_ops_sample.json")
NAVCEN = os.path.join(FIXTURES, "navcen_gps_sample.html")
NAVCEN_FORECAST = os.path.join(FIXTURES, "navcen_forecast_cases.html")
OUT = os.path.join(HERE, "constellation_fixture.h")

# The merged catalog (CelesTrak gps-ops OMM + NAVCEN overlay) renders exactly
# this CSV with lowercase booleans. PRN 19 is present in CelesTrak but carries an
# active NANU in NAVCEN that marks it unusable, so its operational column is
# false.
EXPECTED_CSV = (
    "prn,norad_cat_id,active,sp3_id\n"
    "3,40294,true,G03\n"
    "5,35752,true,G05\n"
    "13,68791,true,G13\n"
    "19,28190,false,G19\n"
)

# Validating the merged catalog against the SP3 ids present in the matching SP3
# product (G03, G05, G13: the operational PRNs) reports PRN 19 as inactive or
# unusable, with no missing and no extra SP3 ids.
VALIDATE_SP3_IDS = ["G03", "G05", "G13"]
EXPECTED_INACTIVE_UNUSABLE_PRNS = [19]


def byte_array(name, data):
    lines = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"#define {name}_LEN ((size_t){len(data)})")
    return lines


def c_string(text):
    escaped = (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def main():
    with open(GPS_OPS, "rb") as fh:
        gps_ops = fh.read()
    with open(NAVCEN, "rb") as fh:
        navcen = fh.read()
    with open(NAVCEN_FORECAST, "rb") as fh:
        navcen_forecast = fh.read()

    lines = []
    w = lines.append
    w("/* Generated by tests/gen_constellation_fixture_header.py from the copied")
    w(" * core constellation fixtures. The bytes are fed verbatim to the C")
    w(" * constellation surface, which asserts the same merged-catalog CSV,")
    w(" * SP3-id validation, and explicit-time NAVCEN behavior the engine")
    w(" * certifies. Do not")
    w(" * edit by hand; rerun the generator. */")
    w("#ifndef SIDEREON_CONSTELLATION_FIXTURE_H")
    w("#define SIDEREON_CONSTELLATION_FIXTURE_H")
    w("")
    w("#include <stddef.h>")
    w("")
    w("/* CelesTrak gps-ops OMM/JSON array. */")
    lines.extend(byte_array("CONSTELLATION_GPS_OPS_JSON", gps_ops))
    w("")
    w("/* NAVCEN GPS constellation status HTML overlay. */")
    lines.extend(byte_array("CONSTELLATION_NAVCEN_HTML", navcen))
    w("")
    w("/* Time-aware NAVCEN forecast and ambiguity cases. */")
    lines.extend(byte_array("CONSTELLATION_NAVCEN_FORECAST_HTML", navcen_forecast))
    w("")
    w("/* Merged catalog CSV with lowercase booleans (BoolStyle::Lower). */")
    w(f"static const char CONSTELLATION_EXPECTED_CSV[] = {c_string(EXPECTED_CSV)};")
    w("")
    w("/* SP3/RINEX ids to validate the merged catalog against. */")
    ids = ", ".join(c_string(i) for i in VALIDATE_SP3_IDS)
    w(f"static const char *const CONSTELLATION_VALIDATE_SP3_IDS[] = {{ {ids} }};")
    w(
        "#define CONSTELLATION_VALIDATE_SP3_ID_COUNT "
        f"((size_t){len(VALIDATE_SP3_IDS)})"
    )
    w("")
    w("/* Expected validation findings: only the inactive/unusable PRN list is")
    w(" * non-empty (missing and extra SP3 ids are empty). */")
    prns = ", ".join(str(p) for p in EXPECTED_INACTIVE_UNUSABLE_PRNS)
    w(
        "static const unsigned short CONSTELLATION_EXPECTED_INACTIVE_UNUSABLE_PRNS[] "
        f"= {{ {prns} }};"
    )
    w(
        "#define CONSTELLATION_EXPECTED_INACTIVE_UNUSABLE_PRN_COUNT "
        f"((size_t){len(EXPECTED_INACTIVE_UNUSABLE_PRNS)})"
    )
    w("")
    w("#endif /* SIDEREON_CONSTELLATION_FIXTURE_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(
        f"wrote {OUT} ({len(gps_ops)} json bytes, {len(navcen)} navcen bytes, "
        f"{len(navcen_forecast)} forecast bytes)"
    )


if __name__ == "__main__":
    main()
