#!/usr/bin/env python3
"""Transcribe committed SPP/SP3 fixtures into a C header.

The C smoke test must feed the binding the SAME inputs the crate's own SPP
reference test uses and assert the SAME converged answer, so no truth is invented
on the C side. Rather than parse JSON in C, this script copies the fixture's
inputs and frozen reference solution into `spp_fixture.h` as exact IEEE-754
float64 bit patterns (the fixture already stores every value as a `0x...` bit
pattern, so this is a byte-faithful transcription, not a re-derivation).

The SP3 constants are likewise transcribed from the Python binding's committed
`sp3_bodies.json` golden so the C smoke test exercises the same SP3 surface
without modifying that 0-ULP reference fixture.

Run from the binding root:
    python3 tests/gen_fixture_header.py
"""

import json
import os
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
BINDING_ROOT = os.path.normpath(os.path.join(HERE, ".."))


def core_fixtures_dir():
    """Locate the canonical sidereon-core test fixtures.

    The engine is a git dependency, so its parity fixtures live inside the cargo
    checkout. Resolve the sidereon-core source directory from cargo metadata so
    this tracks whatever revision the lockfile pins, with no checkout-hash path
    hardcoded.
    """
    metadata = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1", "--quiet"],
            cwd=BINDING_ROOT,
        )
    )
    manifest = next(
        p["manifest_path"] for p in metadata["packages"] if p["name"] == "sidereon-core"
    )
    return os.path.join(os.path.dirname(manifest), "tests", "fixtures")


CORE_FIXTURES = core_fixtures_dir()
FIXTURE = os.path.join(CORE_FIXTURES, "spp_trace_L0_minimal.json")
SP3_FIXTURE = os.path.join(HERE, "fixtures", "sp3_bodies.json")
OUT = os.path.join(HERE, "spp_fixture.h")


def bits(hex_str):
    """Normalize a `0x...` float64 bit pattern to a `UINT64_C(0x...)` literal."""
    return f"UINT64_C({int(hex_str, 16):#018x})"


def c_string_literal(text):
    """Return C string literal fragments preserving text bytes."""
    return [json.dumps(chunk) for chunk in text.splitlines(True)]


def main():
    with open(FIXTURE) as fh:
        fx = json.load(fh)["fixture"]
    with open(SP3_FIXTURE) as fh:
        sp3_fx = json.load(fh)
    inp = fx["inputs"]
    obs = inp["observations"]
    final = fx["final_solution"]
    used = fx["used_sats"]
    rejected = fx["rejected_sats"]

    lines = []
    w = lines.append
    w("/* Generated by tests/gen_fixture_header.py from committed SPP/SP3")
    w(" * fixtures. Every numeric value is the fixture's own exact IEEE-754")
    w(" * float64 bit pattern, so the C smoke test asserts the same reference")
    w(" * answers. Do not edit by hand; rerun the generator. */")
    w("#ifndef SIDEREON_SPP_FIXTURE_H")
    w("#define SIDEREON_SPP_FIXTURE_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w(f'#define SPP_SP3_FILE "{inp["sp3_file"]}"')
    w(f"#define SPP_OBS_COUNT {len(obs)}")
    w("")
    w("static const char *const SPP_SAT_IDS[SPP_OBS_COUNT] = {")
    for o in obs:
        w(f'    "{o["sat_id"]}",')
    w("};")
    w("")
    w(f"#define SPP_USED_SAT_COUNT {len(used)}")
    w("static const char *const SPP_USED_SAT_IDS[SPP_USED_SAT_COUNT] = {")
    for sat_id in used:
        w(f'    "{sat_id}",')
    w("};")
    w("")
    w(f"#define SPP_REJECTED_SAT_COUNT {len(rejected)}")
    w("static const char *const SPP_REJECTED_SAT_IDS[SPP_REJECTED_SAT_COUNT] = {")
    for sat in rejected:
        w(f'    "{sat["id"]}",')
    w("};")
    w("static const char *const SPP_REJECTED_SAT_REASONS[SPP_REJECTED_SAT_COUNT] = {")
    for sat in rejected:
        w(f'    "{sat["reason"]}",')
    w("};")
    w("")
    w("static const uint64_t SPP_PSEUDORANGE_BITS[SPP_OBS_COUNT] = {")
    for o in obs:
        w(f"    {bits(o['p_meas_m'])},")
    w("};")
    w("")

    def scalar(name, value):
        w(f"static const uint64_t {name} = {bits(value)};")

    def vec4(name, values):
        joined = ", ".join(bits(v) for v in values)
        w(f"static const uint64_t {name}[4] = {{ {joined} }};")

    scalar("SPP_T_RX_J2000_S_BITS", inp["t_rx_j2000_s"])
    scalar("SPP_T_RX_SOD_S_BITS", inp["t_rx_sod_s"])
    scalar("SPP_DOY_BITS", inp["doy"])
    vec4("SPP_INITIAL_GUESS_BITS", fx["frozen"]["initial_guess_x0"])
    vec4("SPP_KLOB_ALPHA_BITS", inp["klobuchar_alpha"])
    vec4("SPP_KLOB_BETA_BITS", inp["klobuchar_beta"])
    scalar("SPP_PRESSURE_HPA_BITS", inp["met"]["pressure_hpa"])
    scalar("SPP_TEMPERATURE_K_BITS", inp["met"]["temperature_k"])
    scalar("SPP_RELATIVE_HUMIDITY_BITS", inp["met"]["relative_humidity"])
    w("")
    w("/* The crate's frozen converged reference: state x = [x_m, y_m, z_m, clk]. */")
    vec4("SPP_EXPECTED_X_BITS", final["x"])
    scalar("SPP_EXPECTED_RX_CLOCK_S_BITS", final["rx_clock_s"])
    w("")
    w("/* The crate's documented independent-solve agreement bound for this")
    w(" * fixture (AGREEMENT_BOUND_M); the binding calls the same reference path,")
    w(" * so the position must agree to well within it. */")
    w("#define SPP_AGREEMENT_BOUND_M 1.0e-6")
    w("")

    sp3_file = sp3_fx["sp3_fixture"].replace("tests/fixtures/", "")
    satellites = sp3_fx["satellites"]
    queries = sp3_fx["query_j2000_seconds_hex"]
    interpolation = sp3_fx["interpolation"]
    state = sp3_fx["state_g01_epoch0"]
    sp3_text = sp3_fx["to_sp3_string"]

    w("/* SP3 surface constants transcribed from")
    w(" * bindings/c/tests/fixtures/sp3_bodies.json. */")
    w(f'#define SP3_SURFACE_FILE "{sp3_file}"')
    w(f"#define SP3_SURFACE_EPOCH_COUNT {sp3_fx['epoch_count']}")
    w(f"#define SP3_SURFACE_SAT_COUNT {len(satellites)}")
    w("static const char *const SP3_SURFACE_SAT_IDS[SP3_SURFACE_SAT_COUNT] = {")
    for sat_id in satellites:
        w(f'    "{sat_id}",')
    w("};")
    w("")
    w("static const uint64_t SP3_SURFACE_EPOCH_BITS[SP3_SURFACE_EPOCH_COUNT] = {")
    for value in sp3_fx["epochs_j2000_seconds_hex"]:
        w(f"    {bits(value)},")
    w("};")
    w("")
    w(f"#define SP3_INTERP_QUERY_COUNT {len(queries)}")
    w("static const uint64_t SP3_INTERP_QUERY_BITS[SP3_INTERP_QUERY_COUNT] = {")
    for value in queries:
        w(f"    {bits(value)},")
    w("};")
    w("")
    w(f"#define SP3_INTERP_SAT_COUNT {len(interpolation)}")
    w("static const char *const SP3_INTERP_SAT_IDS[SP3_INTERP_SAT_COUNT] = {")
    for entry in interpolation:
        w(f'    "{entry["satellite"]}",')
    w("};")
    w("static const uint64_t")
    w("    SP3_INTERP_POSITION_BITS[SP3_INTERP_SAT_COUNT][SP3_INTERP_QUERY_COUNT][3] = {")
    for entry in interpolation:
        w("    {")
        for st in entry["states"]:
            joined = ", ".join(bits(v) for v in st["position_m_hex"])
            w(f"        {{ {joined} }},")
        w("    },")
    w("};")
    w("static const uint64_t")
    w("    SP3_INTERP_CLOCK_BITS[SP3_INTERP_SAT_COUNT][SP3_INTERP_QUERY_COUNT] = {")
    for entry in interpolation:
        joined = ", ".join(bits(st["clock_s_hex"]) for st in entry["states"])
        w(f"    {{ {joined} }},")
    w("};")
    w("")
    joined = ", ".join(bits(v) for v in state["position_m_hex"])
    w(f"static const uint64_t SP3_STATE_G01_EPOCH0_POSITION_BITS[3] = {{ {joined} }};")
    w(f"static const uint64_t SP3_STATE_G01_EPOCH0_CLOCK_BITS = {bits(state['clock_s_hex'])};")
    w(f"#define SP3_STATE_G01_EPOCH0_CLOCK_EVENT {int(state['clock_event'])}")
    w(f"#define SP3_STATE_G01_EPOCH0_CLOCK_PREDICTED {int(state['clock_predicted'])}")
    w(f"#define SP3_STATE_G01_EPOCH0_MANEUVER {int(state['maneuver'])}")
    w(f"#define SP3_STATE_G01_EPOCH0_ORBIT_PREDICTED {int(state['orbit_predicted'])}")
    w("")
    w(f"#define SP3_TO_SP3_TEXT_LEN {len(sp3_text.encode('ascii'))}")
    w("static const char SP3_TO_SP3_TEXT[SP3_TO_SP3_TEXT_LEN + 1] =")
    for fragment in c_string_literal(sp3_text):
        w(f"    {fragment}")
    w("    ;")
    w("")
    w("#endif /* SIDEREON_SPP_FIXTURE_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(obs)} observations)")


if __name__ == "__main__":
    main()
