#!/usr/bin/env python3
"""Transcribe the committed Python PPP fixture into a C header.

The PPP smoke test uses the same JSON fixture as the Python binding. Numeric
values are emitted as exact IEEE-754 float64 bit patterns after JSON parsing, so
the C test asserts the same engine-derived reference values without parsing
JSON at runtime.
"""

import json
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures")
FIXTURE = os.path.join(FIXTURES, "ppp_esbc.json")
OUT = os.path.join(HERE, "ppp_fixture.h")


def bits(value):
    raw = struct.unpack("<Q", struct.pack("<d", float(value)))[0]
    return f"UINT64_C(0x{raw:016x})"


def main():
    with open(FIXTURE) as fh:
        fx = json.load(fh)

    epochs = fx["epochs"]
    observations = []
    offsets = []
    counts = []
    for epoch in epochs:
        offsets.append(len(observations))
        rows = epoch["observations"]
        counts.append(len(rows))
        observations.extend(rows)

    initial = fx["initial_state"]
    initial_ambiguities = list(initial["ambiguities_m"])
    config = fx["config"]
    fixed_config = fx["fixed_config"]
    ambiguity = fixed_config["ambiguity"]
    wavelengths = sorted(ambiguity["wavelengths_m"].items())
    offsets_m = sorted(ambiguity["offsets_m"].items())
    expected = fx["expected"]
    fixed_cycles = sorted(expected["fixed_ambiguities_cycles"].items())
    fixed_m = dict(expected["fixed_ambiguities_m"])
    used_ids = sorted({obs["ambiguity_id"] for obs in observations})

    lines = []
    w = lines.append
    w("/* Generated by tests/gen_ppp_fixture_header.py from")
    w(" * bindings/c/tests/fixtures/ppp_esbc.json. Numeric values are")
    w(" * exact float64 bit patterns after JSON parsing. Do not edit by hand;")
    w(" * rerun the generator. */")
    w("#ifndef SIDEREON_PPP_FIXTURE_H")
    w("#define SIDEREON_PPP_FIXTURE_H")
    w("")
    w("#include <stddef.h>")
    w("#include <stdint.h>")
    w("")
    w(f'#define PPP_SP3_FILE "{fx["sp3_file"]}"')
    w(f"#define PPP_EPOCH_COUNT {len(epochs)}")
    w(f"#define PPP_OBS_COUNT {len(observations)}")
    w(f"#define PPP_INITIAL_AMBIGUITY_COUNT {len(initial_ambiguities)}")
    w(f"#define PPP_USED_SAT_COUNT {len(used_ids)}")
    w(f"#define PPP_FIXED_AMBIGUITY_COUNT {len(fixed_cycles)}")
    w("")

    w("static const int32_t PPP_EPOCH_YEARS[PPP_EPOCH_COUNT] = {")
    for epoch in epochs:
        w(f"    {epoch['civil']['year']},")
    w("};")
    for name, field in [
        ("MONTHS", "month"),
        ("DAYS", "day"),
        ("HOURS", "hour"),
        ("MINUTES", "minute"),
    ]:
        w(f"static const uint8_t PPP_EPOCH_{name}[PPP_EPOCH_COUNT] = {{")
        for epoch in epochs:
            w(f"    {epoch['civil'][field]},")
        w("};")
    w("static const uint64_t PPP_EPOCH_SECOND_BITS[PPP_EPOCH_COUNT] = {")
    for epoch in epochs:
        w(f"    {bits(epoch['civil']['second'])},")
    w("};")
    for name, field in [
        ("JD_WHOLE", "jd_whole"),
        ("JD_FRACTION", "jd_fraction"),
        ("T_RX_J2000_S", "t_rx_j2000_s"),
    ]:
        w(f"static const uint64_t PPP_EPOCH_{name}_BITS[PPP_EPOCH_COUNT] = {{")
        for epoch in epochs:
            w(f"    {bits(epoch[field])},")
        w("};")
    w("static const size_t PPP_EPOCH_OBS_OFFSETS[PPP_EPOCH_COUNT] = {")
    for offset in offsets:
        w(f"    {offset},")
    w("};")
    w("static const size_t PPP_EPOCH_OBS_COUNTS[PPP_EPOCH_COUNT] = {")
    for count in counts:
        w(f"    {count},")
    w("};")
    w("")

    w("static const char *const PPP_OBS_SAT_IDS[PPP_OBS_COUNT] = {")
    for obs in observations:
        w(f"    {json.dumps(obs['satellite_id'])},")
    w("};")
    w("static const char *const PPP_OBS_AMBIGUITY_IDS[PPP_OBS_COUNT] = {")
    for obs in observations:
        w(f"    {json.dumps(obs['ambiguity_id'])},")
    w("};")
    for name, field in [
        ("CODE", "code_m"),
        ("PHASE", "phase_m"),
        ("FREQ1_HZ", "freq1_hz"),
        ("FREQ2_HZ", "freq2_hz"),
    ]:
        w(f"static const uint64_t PPP_OBS_{name}_BITS[PPP_OBS_COUNT] = {{")
        for obs in observations:
            w(f"    {bits(obs[field])},")
        w("};")
    w("")

    joined = ", ".join(bits(v) for v in initial["position_m"])
    w(f"static const uint64_t PPP_INITIAL_POSITION_BITS[3] = {{ {joined} }};")
    w("static const uint64_t PPP_INITIAL_CLOCK_BITS[PPP_EPOCH_COUNT] = {")
    for value in initial["clocks_m"]:
        w(f"    {bits(value)},")
    w("};")
    w("static const char *const PPP_INITIAL_AMBIGUITY_IDS[PPP_INITIAL_AMBIGUITY_COUNT] = {")
    for key, _ in initial_ambiguities:
        w(f"    {json.dumps(key)},")
    w("};")
    w("static const uint64_t PPP_INITIAL_AMBIGUITY_BITS[PPP_INITIAL_AMBIGUITY_COUNT] = {")
    for _, value in initial_ambiguities:
        w(f"    {bits(value)},")
    w("};")
    w(f"static const uint64_t PPP_INITIAL_ZTD_BITS = {bits(initial['ztd_m'])};")
    w("")

    weights = config["weights"]
    w(f"static const uint64_t PPP_WEIGHT_CODE_BITS = {bits(weights['code'])};")
    w(f"static const uint64_t PPP_WEIGHT_PHASE_BITS = {bits(weights['phase'])};")
    w(f"#define PPP_WEIGHT_ELEVATION_WEIGHTING {int(weights['elevation_weighting'])}")
    tropo = config["tropo"]
    w(f"#define PPP_TROPO_ENABLED {int(tropo['enabled'])}")
    w(f"#define PPP_TROPO_ESTIMATE_ZTD {int(tropo['estimate_ztd'])}")
    w(f"static const uint64_t PPP_TROPO_PRESSURE_HPA_BITS = {bits(tropo['pressure_hpa'])};")
    w(f"static const uint64_t PPP_TROPO_TEMPERATURE_K_BITS = {bits(tropo['temperature_k'])};")
    w(
        "static const uint64_t PPP_TROPO_RELATIVE_HUMIDITY_BITS = "
        f"{bits(tropo['relative_humidity'])};"
    )
    opts = config["opts"]
    w(f"#define PPP_OPTS_MAX_ITERATIONS {opts['max_iterations']}")
    w(f"static const uint64_t PPP_OPTS_POSITION_TOLERANCE_BITS = {bits(opts['position_tolerance_m'])};")
    w(f"static const uint64_t PPP_OPTS_CLOCK_TOLERANCE_BITS = {bits(opts['clock_tolerance_m'])};")
    w(
        "static const uint64_t PPP_OPTS_AMBIGUITY_TOLERANCE_BITS = "
        f"{bits(opts['ambiguity_tolerance_m'])};"
    )
    w(f"static const uint64_t PPP_OPTS_ZTD_TOLERANCE_BITS = {bits(opts['ztd_tolerance_m'])};")
    w(f"#define PPP_RESIDUAL_SCREEN {int(config['residual_screen'])}")
    w("")

    w("static const char *const PPP_USED_SAT_IDS[PPP_USED_SAT_COUNT] = {")
    for sat in used_ids:
        w(f"    {json.dumps(sat)},")
    w("};")
    w("static const char *const PPP_FIXED_AMBIGUITY_IDS[PPP_FIXED_AMBIGUITY_COUNT] = {")
    for key, _ in fixed_cycles:
        w(f"    {json.dumps(key)},")
    w("};")
    w("static const int64_t PPP_FIXED_AMBIGUITY_CYCLES[PPP_FIXED_AMBIGUITY_COUNT] = {")
    for _, value in fixed_cycles:
        w(f"    {value},")
    w("};")
    w("static const uint64_t PPP_FIXED_AMBIGUITY_M_BITS[PPP_FIXED_AMBIGUITY_COUNT] = {")
    for key, _ in fixed_cycles:
        w(f"    {bits(fixed_m[key])},")
    w("};")
    w("")

    w("static const char *const PPP_WAVELENGTH_IDS[PPP_FIXED_AMBIGUITY_COUNT] = {")
    for key, _ in wavelengths:
        w(f"    {json.dumps(key)},")
    w("};")
    w("static const uint64_t PPP_WAVELENGTH_BITS[PPP_FIXED_AMBIGUITY_COUNT] = {")
    for _, value in wavelengths:
        w(f"    {bits(value)},")
    w("};")
    w("static const char *const PPP_OFFSET_IDS[PPP_FIXED_AMBIGUITY_COUNT] = {")
    for key, _ in offsets_m:
        w(f"    {json.dumps(key)},")
    w("};")
    w("static const uint64_t PPP_OFFSET_BITS[PPP_FIXED_AMBIGUITY_COUNT] = {")
    for _, value in offsets_m:
        w(f"    {bits(value)},")
    w("};")
    w(
        "static const uint64_t PPP_FIXED_RATIO_THRESHOLD_BITS = "
        f"{bits(ambiguity['ratio_threshold'])};"
    )
    w("")

    joined = ", ".join(bits(v) for v in expected["position_m"])
    w(f"static const uint64_t PPP_EXPECTED_FLOAT_POSITION_BITS[3] = {{ {joined} }};")
    joined = ", ".join(bits(v) for v in expected["fixed_position_m"])
    w(f"static const uint64_t PPP_EXPECTED_FIXED_POSITION_BITS[3] = {{ {joined} }};")
    joined = ", ".join(bits(v) for v in expected["fixed_float_position_m"])
    w(f"static const uint64_t PPP_EXPECTED_FIXED_FLOAT_POSITION_BITS[3] = {{ {joined} }};")
    w(f'#define PPP_EXPECTED_FIXED_INTEGER_STATUS "{expected["fixed_integer_status"]}"')
    w(f"static const uint64_t PPP_EXPECTED_FIXED_INTEGER_RATIO_BITS = {bits(expected['fixed_integer_ratio'])};")
    w(f"#define PPP_EXPECTED_FIXED_INTEGER_CANDIDATES {expected['fixed_integer_candidates']}")
    w("")
    w("#endif /* SIDEREON_PPP_FIXTURE_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(epochs)} epochs, {len(observations)} observations)")


if __name__ == "__main__":
    main()
