#!/usr/bin/env python3
"""Transcribe the committed DOP golden into a C header.

The standalone DOP entry point (`sidereon_dop`) calls the engine's `dop` kernel
directly, and the engine certifies that kernel 0-ULP against the reference recipe
`parity/generator/dop.py` via the committed golden
`sidereon-core/tests/fixtures/dop_golden.json`. So the C smoke test feeds the
SAME line-of-sight geometry/weights/receiver as the golden and asserts the SAME
DOP scalars bit-for-bit, inventing no truth on the C side.

The golden stores every value as a Python `float.hex()` string. This script
converts each to its exact IEEE-754 float64 bit pattern (via `float.fromhex`) so
the C side reconstructs the same `double` with `bits_to_f64`, with no decimal
round-trip.

Run from the binding root:
    python3 tests/gen_dop_fixture_header.py
"""

import json
import os
import struct
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
BINDING_ROOT = os.path.normpath(os.path.join(HERE, ".."))


def core_fixtures_dir():
    """Locate the canonical sidereon-core test fixtures via cargo metadata, so
    this tracks whatever core revision the lockfile pins."""
    metadata = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1", "--quiet"],
            cwd=BINDING_ROOT,
        )
    )
    manifest = next(
        p["manifest_path"] for p in metadata["packages"] if p["name"] == "sidereon-core"
    )
    return os.path.join(os.path.dirname(manifest), "tests", "fixtures")


GOLDEN = os.path.join(core_fixtures_dir(), "dop_golden.json")
OUT = os.path.join(HERE, "dop_fixture.h")


def bits(hexfloat):
    """`float.hex()` string -> `UINT64_C(0x...)` IEEE-754 bit pattern literal."""
    value = float.fromhex(hexfloat)
    raw = struct.unpack("<Q", struct.pack("<d", value))[0]
    return f"UINT64_C({raw:#018x})"


def main():
    with open(GOLDEN) as fh:
        doc = json.load(fh)
    cases = doc["cases"]
    singular = doc["singular_cases"]

    lines = []
    w = lines.append
    w("/* Generated by tests/gen_dop_fixture_header.py from the committed core")
    w(" * golden sidereon-core/tests/fixtures/dop_golden.json. Every value is the")
    w(" * golden's own IEEE-754 float64 bit pattern, so the C smoke test asserts")
    w(" * the engine's 0-ULP DOP scalars. Do not edit by hand; rerun the")
    w(" * generator. */")
    w("#ifndef SIDEREON_DOP_FIXTURE_H")
    w("#define SIDEREON_DOP_FIXTURE_H")
    w("")
    w("#include <stdint.h>")
    w("#include <stddef.h>")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    size_t sat_count;")
    w("    const uint64_t (*los_bits)[3]; /* sat_count entries of {e_x,e_y,e_z} */")
    w("    const uint64_t *weight_bits;   /* sat_count entries */")
    w("    uint64_t lat_rad_bits;")
    w("    uint64_t lon_rad_bits;")
    w("    uint64_t gdop_bits;")
    w("    uint64_t pdop_bits;")
    w("    uint64_t hdop_bits;")
    w("    uint64_t vdop_bits;")
    w("    uint64_t tdop_bits;")
    w("} DopGoldenCase;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    size_t sat_count;")
    w("    const uint64_t (*los_bits)[3];")
    w("    const uint64_t *weight_bits;")
    w("    uint64_t lat_rad_bits;")
    w("    uint64_t lon_rad_bits;")
    w("} DopSingularCase;")
    w("")

    def emit_geometry(prefix, case):
        inp = case["inputs"]
        los = inp["los_ecef"]
        weights = inp["weights"]
        w(f"static const uint64_t {prefix}_LOS[{len(los)}][3] = {{")
        for vec in los:
            joined = ", ".join(bits(c) for c in vec)
            w(f"    {{ {joined} }},")
        w("};")
        joined = ", ".join(bits(x) for x in weights)
        w(f"static const uint64_t {prefix}_W[{len(weights)}] = {{ {joined} }};")
        w("")

    for idx, case in enumerate(cases):
        emit_geometry(f"DOP_CASE_{idx}", case)
    for idx, case in enumerate(singular):
        emit_geometry(f"DOP_SING_{idx}", case)

    w(f"#define DOP_CASE_COUNT {len(cases)}")
    w("static const DopGoldenCase DOP_CASES[DOP_CASE_COUNT] = {")
    for idx, case in enumerate(cases):
        inp = case["inputs"]
        exp = case["expect"]
        w("    {")
        w(f'        .name = "{case["name"]}",')
        w(f"        .sat_count = {len(inp['los_ecef'])},")
        w(f"        .los_bits = DOP_CASE_{idx}_LOS,")
        w(f"        .weight_bits = DOP_CASE_{idx}_W,")
        w(f"        .lat_rad_bits = {bits(inp['lat_rad'])},")
        w(f"        .lon_rad_bits = {bits(inp['lon_rad'])},")
        w(f"        .gdop_bits = {bits(exp['gdop'])},")
        w(f"        .pdop_bits = {bits(exp['pdop'])},")
        w(f"        .hdop_bits = {bits(exp['hdop'])},")
        w(f"        .vdop_bits = {bits(exp['vdop'])},")
        w(f"        .tdop_bits = {bits(exp['tdop'])},")
        w("    },")
    w("};")
    w("")
    w(f"#define DOP_SINGULAR_COUNT {len(singular)}")
    w("static const DopSingularCase DOP_SINGULAR[DOP_SINGULAR_COUNT] = {")
    for idx, case in enumerate(singular):
        inp = case["inputs"]
        w("    {")
        w(f'        .name = "{case["name"]}",')
        w(f"        .sat_count = {len(inp['los_ecef'])},")
        w(f"        .los_bits = DOP_SING_{idx}_LOS,")
        w(f"        .weight_bits = DOP_SING_{idx}_W,")
        w(f"        .lat_rad_bits = {bits(inp['lat_rad'])},")
        w(f"        .lon_rad_bits = {bits(inp['lon_rad'])},")
        w("    },")
    w("};")
    w("")
    w("#endif /* SIDEREON_DOP_FIXTURE_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(cases)} cases, {len(singular)} singular)")


if __name__ == "__main__":
    main()
