#!/usr/bin/env python3
"""Generate the dependency-free C representation of the shared EOF corpus."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


HERE = Path(__file__).resolve().parent
DEFAULT_INPUT = HERE / "fixtures" / "sp3-terminal-record-v1.json"
DEFAULT_OUTPUT = HERE / "sp3_terminal_record_fixture.h"
EXPECTATIONS = {
    "accept",
    "malformed_eof_record",
    "missing_eof",
    "trailing_content_after_eof",
}


def decode_hex(value: str) -> bytes:
    if len(value) % 2:
        raise ValueError(f"odd-length fixture hex {value!r}")
    return bytes.fromhex(value)


def require_hex_field(case: dict[str, object], field: str) -> bytes:
    value = case.get(field)
    if not isinstance(value, str):
        raise ValueError(f"{field} must be a hex string")
    return decode_hex(value)


def case_bytes(case: dict[str, object]) -> bytes:
    marker = case.get("marker")
    if marker is not None and marker != "EOF":
        raise ValueError(f"unsupported marker {marker!r}")
    padding_spaces = case["padding_spaces"]
    if not isinstance(padding_spaces, int) or padding_spaces < 0:
        raise ValueError(f"invalid padding_spaces {padding_spaces!r}")
    return b"".join(
        [
            require_hex_field(case, "leading_hex"),
            b"" if marker is None else marker.encode("ascii"),
            b" " * padding_spaces,
            require_hex_field(case, "suffix_hex"),
            require_hex_field(case, "separator_hex"),
            require_hex_field(case, "trailing_hex"),
        ]
    )


def c_bytes(value: bytes) -> str:
    return ", ".join(f"0x{byte:02x}" for byte in value) if value else "0x00"


def generate(source: Path) -> str:
    corpus = json.loads(source.read_text(encoding="utf-8"))
    if corpus.get("schema") != "sidereon-sp3-terminal-record-v1":
        raise ValueError("unexpected terminal-record corpus schema")
    if corpus.get("record_width") != 80:
        raise ValueError("unexpected terminal-record policy width")
    if corpus.get("record_width_authority") != "sidereon-interoperability-policy":
        raise ValueError("unexpected terminal-record width authority")

    cases = corpus.get("cases")
    if not isinstance(cases, list) or not cases:
        raise ValueError("terminal-record corpus has no cases")

    lines = [
        "/* Generated by gen_sp3_terminal_record_fixture.py; do not edit. */",
        "#ifndef SIDEREON_SP3_TERMINAL_RECORD_FIXTURE_H",
        "#define SIDEREON_SP3_TERMINAL_RECORD_FIXTURE_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "struct Sp3TerminalRecordCase {",
        "    const char *name;",
        "    const uint8_t *terminal_bytes;",
        "    size_t terminal_len;",
        "    const char *expected;",
        "};",
        "",
    ]
    records: list[tuple[str, int, str, str]] = []
    names: set[str] = set()
    for index, case in enumerate(cases):
        if not isinstance(case, dict):
            raise ValueError(f"case {index} is not an object")
        name = case.get("name")
        expected = case.get("expect")
        valid_name = isinstance(name, str) and all(
            character.isascii() and (character.isalnum() or character == "_")
            for character in name
        )
        if (
            not isinstance(name, str)
            or not name
            or not valid_name
        ):
            raise ValueError(f"case {index} has invalid name")
        if name in names:
            raise ValueError(f"duplicate terminal-record case name {name!r}")
        names.add(name)
        if expected not in EXPECTATIONS:
            raise ValueError(f"case {name!r} has invalid expectation {expected!r}")
        terminal = case_bytes(case)
        symbol = f"SP3_TERMINAL_CASE_{index}_BYTES"
        lines.append(f"static const uint8_t {symbol}[] = {{{c_bytes(terminal)}}};")
        records.append((symbol, len(terminal), name, expected))

    lines.extend(["", "static const struct Sp3TerminalRecordCase SP3_TERMINAL_RECORD_CASES[] = {"])
    for symbol, length, name, expected in records:
        lines.append(f'    {{"{name}", {symbol}, {length}, "{expected}"}},')
    lines.extend(
        [
            "};",
            "",
            "#define SP3_TERMINAL_RECORD_CASE_COUNT \\",
            "    (sizeof(SP3_TERMINAL_RECORD_CASES) / sizeof(SP3_TERMINAL_RECORD_CASES[0]))",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    args.output.write_text(generate(args.input), encoding="utf-8")


if __name__ == "__main__":
    main()
