#!/usr/bin/env python3
"""Transcribe the committed Klobuchar and IONEX goldens into a C header.

The C standalone Klobuchar entry calls the engine's `klobuchar_native` (the
0-ULP native-units kernel), and the C IONEX slant-delay entry calls the engine's
`ionex_slant_delay` after a single deg->rad multiply that mirrors the Python and
Elixir bindings. The engine certifies both kernels bit-for-bit against
`klobuchar_golden.json` and `ionex_golden.json`, so the C smoke test feeds the
SAME inputs and asserts the SAME delays bit-for-bit.

The goldens store every value as a Python `float.hex()` string; this script
converts each to its exact IEEE-754 bit pattern. Klobuchar inputs are in native
degree / second-of-day units (fed straight through). IONEX inputs are baked as
degrees; the binding applies the same `pi/180` boundary multiply the goldens'
`math.radians` used, so the reconstructed radians match the golden bit-for-bit.

Run from the binding root:
    python3 tests/gen_iono_fixture_header.py
"""

import json
import os
import struct
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
BINDING_ROOT = os.path.normpath(os.path.join(HERE, ".."))


def core_fixtures_dir():
    metadata = json.loads(
        subprocess.check_output(
            ["cargo", "metadata", "--format-version", "1", "--quiet"],
            cwd=BINDING_ROOT,
        )
    )
    manifest = next(
        p["manifest_path"] for p in metadata["packages"] if p["name"] == "sidereon-core"
    )
    return os.path.join(os.path.dirname(manifest), "tests", "fixtures")


FIXTURES = core_fixtures_dir()
KLOB = os.path.join(FIXTURES, "klobuchar_golden.json")
IONEX = os.path.join(FIXTURES, "ionex_golden.json")
OUT = os.path.join(HERE, "iono_fixture.h")


def bits(hexfloat):
    raw = struct.unpack("<Q", struct.pack("<d", float.fromhex(hexfloat)))[0]
    return f"UINT64_C({raw:#018x})"


def main():
    klob = json.load(open(KLOB))
    ionex = json.load(open(IONEX))

    lines = []
    w = lines.append
    w("/* Generated by tests/gen_iono_fixture_header.py from the committed core")
    w(" * goldens klobuchar_golden.json and ionex_golden.json. Every value is the")
    w(" * golden's own IEEE-754 bit pattern, so the C smoke test asserts the")
    w(" * engine's bit-exact ionospheric delays. Do not edit by hand; rerun the")
    w(" * generator. */")
    w("#ifndef SIDEREON_IONO_FIXTURE_H")
    w("#define SIDEREON_IONO_FIXTURE_H")
    w("")
    w("#include <stdint.h>")
    w("#include <stddef.h>")
    w("")
    w(f"static const uint64_t KLOB_F_L1_HZ_BITS = {bits(klob['constants']['f_l1'])};")
    w(f"static const uint64_t KLOB_F_B1I_HZ_BITS = {bits(klob['constants']['f_b1i'])};")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    uint64_t alpha_bits[4];")
    w("    uint64_t beta_bits[4];")
    w("    uint64_t lat_deg_bits;")
    w("    uint64_t lon_deg_bits;")
    w("    uint64_t az_deg_bits;")
    w("    uint64_t el_deg_bits;")
    w("    uint64_t t_gps_s_bits;")
    w("    uint64_t delay_l1_m_bits;")
    w("    uint64_t delay_b1i_m_bits;")
    w("} KlobucharCase;")
    w("")
    cases = klob["cases"]
    w(f"#define KLOB_CASE_COUNT {len(cases)}")
    w("static const KlobucharCase KLOB_CASES[KLOB_CASE_COUNT] = {")
    for c in cases:
        i = c["inputs"]
        e = c["expect"]
        a = ", ".join(bits(x) for x in i["alpha"])
        b = ", ".join(bits(x) for x in i["beta"])
        w("    {")
        w(f'        .name = "{c["name"]}",')
        w(f"        .alpha_bits = {{ {a} }},")
        w(f"        .beta_bits = {{ {b} }},")
        w(f"        .lat_deg_bits = {bits(i['lat_deg'])},")
        w(f"        .lon_deg_bits = {bits(i['lon_deg'])},")
        w(f"        .az_deg_bits = {bits(i['az_deg'])},")
        w(f"        .el_deg_bits = {bits(i['el_deg'])},")
        w(f"        .t_gps_s_bits = {bits(i['t_gps_s'])},")
        w(f"        .delay_l1_m_bits = {bits(e['delay_l1_m'])},")
        w(f"        .delay_b1i_m_bits = {bits(e['delay_b1i_m'])},")
        w("    },")
    w("};")
    w("")

    fname = ionex["ionex_file"]["name"]
    w(f'#define IONEX_FILE "{fname}"')
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    uint64_t lat_deg_bits;")
    w("    uint64_t lon_deg_bits;")
    w("    uint64_t az_deg_bits;")
    w("    uint64_t el_deg_bits;")
    w("    int64_t epoch_j2000_s;")
    w("    uint64_t frequency_hz_bits;")
    w("    uint64_t delay_m_bits;")
    w("} IonexCase;")
    w("")
    icases = ionex["cases"]
    w(f"#define IONEX_CASE_COUNT {len(icases)}")
    w("static const IonexCase IONEX_CASES[IONEX_CASE_COUNT] = {")
    for c in icases:
        i = c["inputs"]
        e = c["expect"]
        w("    {")
        w(f'        .name = "{c["name"]}",')
        w(f"        .lat_deg_bits = {bits(i['lat_deg'])},")
        w(f"        .lon_deg_bits = {bits(i['lon_deg'])},")
        w(f"        .az_deg_bits = {bits(i['az_deg'])},")
        w(f"        .el_deg_bits = {bits(i['el_deg'])},")
        w(f"        .epoch_j2000_s = INT64_C({i['epoch_s']}),")
        w(f"        .frequency_hz_bits = {bits(i['frequency_hz'])},")
        w(f"        .delay_m_bits = {bits(e['delay_m'])},")
        w("    },")
    w("};")
    w("")
    # Expose the parsed map-epoch axis the core test asserts, for the handle
    # accessor check.
    epochs = ionex["ionex_file"].get("map_epochs_s") or []
    w(f"#define IONEX_EXPONENT {int(ionex['ionex_file']['exponent'])}")
    w(f"#define IONEX_LAT_NODE_COUNT {len(ionex['ionex_file']['lat_arr'])}")
    w(f"#define IONEX_LON_NODE_COUNT {len(ionex['ionex_file']['lon_arr'])}")
    w("")
    w("#endif /* SIDEREON_IONO_FIXTURE_H */")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(cases)} klobuchar, {len(icases)} ionex cases)")


if __name__ == "__main__":
    main()
