/* Generated by tests/gen_iono_fixture_header.py from the committed core
 * goldens klobuchar_golden.json and ionex_golden.json. Every value is the
 * golden's own IEEE-754 bit pattern, so the C smoke test asserts the
 * engine's bit-exact ionospheric delays. Do not edit by hand; rerun the
 * generator. */
#ifndef SIDEREON_IONO_FIXTURE_H
#define SIDEREON_IONO_FIXTURE_H

#include <stdint.h>
#include <stddef.h>

static const uint64_t KLOB_F_L1_HZ_BITS = UINT64_C(0x41d779c018000000);
static const uint64_t KLOB_F_B1I_HZ_BITS = UINT64_C(0x41d7431dc4000000);

typedef struct {
    const char *name;
    uint64_t alpha_bits[4];
    uint64_t beta_bits[4];
    uint64_t lat_deg_bits;
    uint64_t lon_deg_bits;
    uint64_t az_deg_bits;
    uint64_t el_deg_bits;
    uint64_t t_gps_s_bits;
    uint64_t delay_l1_m_bits;
    uint64_t delay_b1i_m_bits;
} KlobucharCase;

#define KLOB_CASE_COUNT 11
static const KlobucharCase KLOB_CASES[KLOB_CASE_COUNT] = {
    {
        .name = "zenith_midlat_day",
        .alpha_bits = { UINT64_C(0x3e45ffffffffff61), UINT64_C(0x3e57fffffffffe3f), UINT64_C(0xbe6fffffffffffa2), UINT64_C(0xbe800000000002c4) },
        .beta_bits = { UINT64_C(0x40f7800000000000), UINT64_C(0x4100000000000000), UINT64_C(0xc0f0000000000000), UINT64_C(0xc122000000000000) },
        .lat_deg_bits = UINT64_C(0x4044000000000000),
        .lon_deg_bits = UINT64_C(0xc059000000000000),
        .az_deg_bits = UINT64_C(0x403e000000000000),
        .el_deg_bits = UINT64_C(0x4055400000000000),
        .t_gps_s_bits = UINT64_C(0x40e89c0000000000),
        .delay_l1_m_bits = UINT64_C(0x4001f0aca5af4b35),
        .delay_b1i_m_bits = UINT64_C(0x4002455488ef75b9),
    },
    {
        .name = "low_el_midlat_day",
        .alpha_bits = { UINT64_C(0x3e45ffffffffff61), UINT64_C(0x3e57fffffffffe3f), UINT64_C(0xbe6fffffffffffa2), UINT64_C(0xbe800000000002c4) },
        .beta_bits = { UINT64_C(0x40f7800000000000), UINT64_C(0x4100000000000000), UINT64_C(0xc0f0000000000000), UINT64_C(0xc122000000000000) },
        .lat_deg_bits = UINT64_C(0x4044000000000000),
        .lon_deg_bits = UINT64_C(0xc059000000000000),
        .az_deg_bits = UINT64_C(0x405e000000000000),
        .el_deg_bits = UINT64_C(0x401c000000000000),
        .t_gps_s_bits = UINT64_C(0x40e89c0000000000),
        .delay_l1_m_bits = UINT64_C(0x402053b47600845e),
        .delay_b1i_m_bits = UINT64_C(0x4020a0bfa1658475),
    },
    {
        .name = "low_el_mask_5deg",
        .alpha_bits = { UINT64_C(0x3e45ffffffffff61), UINT64_C(0x3e57fffffffffe3f), UINT64_C(0xbe6fffffffffffa2), UINT64_C(0xbe800000000002c4) },
        .beta_bits = { UINT64_C(0x40f7800000000000), UINT64_C(0x4100000000000000), UINT64_C(0xc0f0000000000000), UINT64_C(0xc122000000000000) },
        .lat_deg_bits = UINT64_C(0x4041800000000000),
        .lon_deg_bits = UINT64_C(0x4024000000000000),
        .az_deg_bits = UINT64_C(0x4069000000000000),
        .el_deg_bits = UINT64_C(0x4014000000000000),
        .t_gps_s_bits = UINT64_C(0x40e5180000000000),
        .delay_l1_m_bits = UINT64_C(0x402d66eea426da8b),
        .delay_b1i_m_bits = UINT64_C(0x402df1acb0665093),
    },
    {
        .name = "clamp_lat_pos",
        .alpha_bits = { UINT64_C(0x3e45ffffffffff61), UINT64_C(0x3e57fffffffffe3f), UINT64_C(0xbe6fffffffffffa2), UINT64_C(0xbe800000000002c4) },
        .beta_bits = { UINT64_C(0x40f7800000000000), UINT64_C(0x4100000000000000), UINT64_C(0xc0f0000000000000), UINT64_C(0xc122000000000000) },
        .lat_deg_bits = UINT64_C(0x4054800000000000),
        .lon_deg_bits = UINT64_C(0x4034000000000000),
        .az_deg_bits = UINT64_C(0x0000000000000000),
        .el_deg_bits = UINT64_C(0x4034000000000000),
        .t_gps_s_bits = UINT64_C(0x40e3880000000000),
        .delay_l1_m_bits = UINT64_C(0x400cba73de8c38a8),
        .delay_b1i_m_bits = UINT64_C(0x400d4204057dce2d),
    },
    {
        .name = "clamp_lat_neg",
        .alpha_bits = { UINT64_C(0x3e45ffffffffff61), UINT64_C(0x3e57fffffffffe3f), UINT64_C(0xbe6fffffffffffa2), UINT64_C(0xbe800000000002c4) },
        .beta_bits = { UINT64_C(0x40f7800000000000), UINT64_C(0x4100000000000000), UINT64_C(0xc0f0000000000000), UINT64_C(0xc122000000000000) },
        .lat_deg_bits = UINT64_C(0xc054800000000000),
        .lon_deg_bits = UINT64_C(0x4034000000000000),
        .az_deg_bits = UINT64_C(0x4066800000000000),
        .el_deg_bits = UINT64_C(0x4034000000000000),
        .t_gps_s_bits = UINT64_C(0x40e3880000000000),
        .delay_l1_m_bits = UINT64_C(0x400a181fb3d48687),
        .delay_b1i_m_bits = UINT64_C(0x400a9341d5e47cda),
    },
    {
        .name = "night_floor",
        .alpha_bits = { UINT64_C(0x3e55798ee2308c3a), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000) },
        .beta_bits = { UINT64_C(0x40ed4c0000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000) },
        .lat_deg_bits = UINT64_C(0x4044000000000000),
        .lon_deg_bits = UINT64_C(0xc059000000000000),
        .az_deg_bits = UINT64_C(0x4046800000000000),
        .el_deg_bits = UINT64_C(0x403e000000000000),
        .t_gps_s_bits = UINT64_C(0x40bc200000000000),
        .delay_l1_m_bits = UINT64_C(0x400531c5ac9335d6),
        .delay_b1i_m_bits = UINT64_C(0x400595c8c77531a2),
    },
    {
        .name = "time_wrap_high",
        .alpha_bits = { UINT64_C(0x3e45ffffffffff61), UINT64_C(0x3e57fffffffffe3f), UINT64_C(0xbe6fffffffffffa2), UINT64_C(0xbe800000000002c4) },
        .beta_bits = { UINT64_C(0x40f7800000000000), UINT64_C(0x4100000000000000), UINT64_C(0xc0f0000000000000), UINT64_C(0xc122000000000000) },
        .lat_deg_bits = UINT64_C(0x403e000000000000),
        .lon_deg_bits = UINT64_C(0x4065e00000000000),
        .az_deg_bits = UINT64_C(0x4056800000000000),
        .el_deg_bits = UINT64_C(0x4044000000000000),
        .t_gps_s_bits = UINT64_C(0x40f3880000000000),
        .delay_l1_m_bits = UINT64_C(0x4017afbfc41c4135),
        .delay_b1i_m_bits = UINT64_C(0x40181f855a6ad19b),
    },
    {
        .name = "time_wrap_low",
        .alpha_bits = { UINT64_C(0x3e45ffffffffff61), UINT64_C(0x3e57fffffffffe3f), UINT64_C(0xbe6fffffffffffa2), UINT64_C(0xbe800000000002c4) },
        .beta_bits = { UINT64_C(0x40f7800000000000), UINT64_C(0x4100000000000000), UINT64_C(0xc0f0000000000000), UINT64_C(0xc122000000000000) },
        .lat_deg_bits = UINT64_C(0x403e000000000000),
        .lon_deg_bits = UINT64_C(0xc065e00000000000),
        .az_deg_bits = UINT64_C(0x4070e00000000000),
        .el_deg_bits = UINT64_C(0x4044000000000000),
        .t_gps_s_bits = UINT64_C(0x407f400000000000),
        .delay_l1_m_bits = UINT64_C(0x401c4fe9b0eccc6b),
        .delay_b1i_m_bits = UINT64_C(0x401cd5831a9ee59a),
    },
    {
        .name = "amp_clamp",
        .alpha_bits = { UINT64_C(0xbe6ad7f29abcaf48), UINT64_C(0x3e45798ee2308c3a), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000) },
        .beta_bits = { UINT64_C(0x40e86a0000000000), UINT64_C(0x40c3880000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000) },
        .lat_deg_bits = UINT64_C(0x4034000000000000),
        .lon_deg_bits = UINT64_C(0x0000000000000000),
        .az_deg_bits = UINT64_C(0x404e000000000000),
        .el_deg_bits = UINT64_C(0x4049000000000000),
        .t_gps_s_bits = UINT64_C(0x40e89c0000000000),
        .delay_l1_m_bits = UINT64_C(0x3ffe23fbc6e1b8b7),
        .delay_b1i_m_bits = UINT64_C(0x3ffeb235eb470f28),
    },
    {
        .name = "equator_noon",
        .alpha_bits = { UINT64_C(0x3e45ffffffffff61), UINT64_C(0x3e57fffffffffe3f), UINT64_C(0xbe6fffffffffffa2), UINT64_C(0xbe800000000002c4) },
        .beta_bits = { UINT64_C(0x40f7800000000000), UINT64_C(0x4100000000000000), UINT64_C(0xc0f0000000000000), UINT64_C(0xc122000000000000) },
        .lat_deg_bits = UINT64_C(0x0000000000000000),
        .lon_deg_bits = UINT64_C(0x0000000000000000),
        .az_deg_bits = UINT64_C(0x4056800000000000),
        .el_deg_bits = UINT64_C(0x404e000000000000),
        .t_gps_s_bits = UINT64_C(0x40e89c0000000000),
        .delay_l1_m_bits = UINT64_C(0x40151ab8b5f03005),
        .delay_b1i_m_bits = UINT64_C(0x40157e4f0b62ce69),
    },
    {
        .name = "antimeridian_lon",
        .alpha_bits = { UINT64_C(0x3e45ffffffffff61), UINT64_C(0x3e57fffffffffe3f), UINT64_C(0xbe6fffffffffffa2), UINT64_C(0xbe800000000002c4) },
        .beta_bits = { UINT64_C(0x40f7800000000000), UINT64_C(0x4100000000000000), UINT64_C(0xc0f0000000000000), UINT64_C(0xc122000000000000) },
        .lat_deg_bits = UINT64_C(0x4024000000000000),
        .lon_deg_bits = UINT64_C(0x4066700000000000),
        .az_deg_bits = UINT64_C(0x4060e00000000000),
        .el_deg_bits = UINT64_C(0x4039000000000000),
        .t_gps_s_bits = UINT64_C(0x40ed4c0000000000),
        .delay_l1_m_bits = UINT64_C(0x4007787aa1ecc629),
        .delay_b1i_m_bits = UINT64_C(0x4007e73b69600ffd),
    },
};

#define IONEX_FILE "synthetic_2map_7x7.20i"

typedef struct {
    const char *name;
    uint64_t lat_deg_bits;
    uint64_t lon_deg_bits;
    uint64_t az_deg_bits;
    uint64_t el_deg_bits;
    int64_t epoch_j2000_s;
    uint64_t frequency_hz_bits;
    uint64_t delay_m_bits;
} IonexCase;

#define IONEX_CASE_COUNT 12
static const IonexCase IONEX_CASES[IONEX_CASE_COUNT] = {
    {
        .name = "interior_l1",
        .lat_deg_bits = UINT64_C(0x4046800000000000),
        .lon_deg_bits = UINT64_C(0x4024000000000000),
        .az_deg_bits = UINT64_C(0x404e000000000000),
        .el_deg_bits = UINT64_C(0x404e000000000000),
        .epoch_j2000_s = INT64_C(646232400),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x400788254ae08283),
    },
    {
        .name = "interior_l2",
        .lat_deg_bits = UINT64_C(0x4046800000000000),
        .lon_deg_bits = UINT64_C(0x4024000000000000),
        .az_deg_bits = UINT64_C(0x404e000000000000),
        .el_deg_bits = UINT64_C(0x404e000000000000),
        .epoch_j2000_s = INT64_C(646232400),
        .frequency_hz_bits = UINT64_C(0x41d24aec20000000),
        .delay_m_bits = UINT64_C(0x401360b774bc13dd),
    },
    {
        .name = "interior_l5",
        .lat_deg_bits = UINT64_C(0x4046800000000000),
        .lon_deg_bits = UINT64_C(0x4024000000000000),
        .az_deg_bits = UINT64_C(0x404e000000000000),
        .el_deg_bits = UINT64_C(0x404e000000000000),
        .epoch_j2000_s = INT64_C(646232400),
        .frequency_hz_bits = UINT64_C(0x41d187ccf4000000),
        .delay_m_bits = UINT64_C(0x40151975f892b743),
    },
    {
        .name = "epoch_coincident",
        .lat_deg_bits = UINT64_C(0x403e000000000000),
        .lon_deg_bits = UINT64_C(0xc034000000000000),
        .az_deg_bits = UINT64_C(0x405e000000000000),
        .el_deg_bits = UINT64_C(0x4049000000000000),
        .epoch_j2000_s = INT64_C(646228800),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x40033ff22a448b8e),
    },
    {
        .name = "epoch_last_map",
        .lat_deg_bits = UINT64_C(0x403e000000000000),
        .lon_deg_bits = UINT64_C(0xc034000000000000),
        .az_deg_bits = UINT64_C(0x405e000000000000),
        .el_deg_bits = UINT64_C(0x4049000000000000),
        .epoch_j2000_s = INT64_C(646236000),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x4011bf156788af16),
    },
    {
        .name = "epoch_before_hold",
        .lat_deg_bits = UINT64_C(0x403e000000000000),
        .lon_deg_bits = UINT64_C(0xc034000000000000),
        .az_deg_bits = UINT64_C(0x405e000000000000),
        .el_deg_bits = UINT64_C(0x4049000000000000),
        .epoch_j2000_s = INT64_C(646227000),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x40033ff22a448b8e),
    },
    {
        .name = "epoch_after_hold",
        .lat_deg_bits = UINT64_C(0x403e000000000000),
        .lon_deg_bits = UINT64_C(0xc034000000000000),
        .az_deg_bits = UINT64_C(0x405e000000000000),
        .el_deg_bits = UINT64_C(0x4049000000000000),
        .epoch_j2000_s = INT64_C(646237800),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x4011bf156788af16),
    },
    {
        .name = "lon_wrap_seam",
        .lat_deg_bits = UINT64_C(0x0000000000000000),
        .lon_deg_bits = UINT64_C(0x4065400000000000),
        .az_deg_bits = UINT64_C(0x4054000000000000),
        .el_deg_bits = UINT64_C(0x4044000000000000),
        .epoch_j2000_s = INT64_C(646232400),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x40113fa3c9bde53f),
    },
    {
        .name = "lon_wrap_negative",
        .lat_deg_bits = UINT64_C(0x0000000000000000),
        .lon_deg_bits = UINT64_C(0xc066400000000000),
        .az_deg_bits = UINT64_C(0x4071800000000000),
        .el_deg_bits = UINT64_C(0x4044000000000000),
        .epoch_j2000_s = INT64_C(646232400),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x4011410735dc2530),
    },
    {
        .name = "low_el_lat_clamp",
        .lat_deg_bits = UINT64_C(0x4054000000000000),
        .lon_deg_bits = UINT64_C(0x403e000000000000),
        .az_deg_bits = UINT64_C(0x0000000000000000),
        .el_deg_bits = UINT64_C(0x4020000000000000),
        .epoch_j2000_s = INT64_C(646232400),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x401a3a4be17d7a9b),
    },
    {
        .name = "south_mid",
        .lat_deg_bits = UINT64_C(0xc041800000000000),
        .lon_deg_bits = UINT64_C(0x4059000000000000),
        .az_deg_bits = UINT64_C(0x4069000000000000),
        .el_deg_bits = UINT64_C(0x404b800000000000),
        .epoch_j2000_s = INT64_C(646232400),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x400f492eb5dee898),
    },
    {
        .name = "equator_node",
        .lat_deg_bits = UINT64_C(0x0000000000000000),
        .lon_deg_bits = UINT64_C(0x0000000000000000),
        .az_deg_bits = UINT64_C(0x4056800000000000),
        .el_deg_bits = UINT64_C(0x4051800000000000),
        .epoch_j2000_s = INT64_C(646232400),
        .frequency_hz_bits = UINT64_C(0x41d779c018000000),
        .delay_m_bits = UINT64_C(0x400916c3ce302c22),
    },
};

#define IONEX_EXPONENT -1
#define IONEX_LAT_NODE_COUNT 7
#define IONEX_LON_NODE_COUNT 7

#endif /* SIDEREON_IONO_FIXTURE_H */
