/*
 * G07/G11 C ABI smoke test, plus the RINEX observation contracts that need no
 * fixture: a refused write, an event with blank epoch fields, and an ambiguous
 * phase-shift correction.
 *
 * argv: <sp3> <wtzr_obs> <wtzz_obs> <dted_tile_root>
 */
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Engine values regenerated by tests/valgen (bin w3_rinex_rtk_dted). */
#include "w3_rinex_rtk_dted_pins.h"

#include "sidereon.h"

/* Copy one text of the last terrain error into a NUL-terminated buffer
 * through the two-call convention. Returns false when the call fails or the
 * text does not fit. */
static bool last_terrain_text(uint32_t family, uint32_t part, char *buf, size_t cap) {
    size_t written = 0;
    size_t required = 0;
    if (sidereon_last_terrain_error_text(family, part, NULL, 0, &written, &required) !=
            SIDEREON_STATUS_OK ||
        required + 1 > cap) {
        return false;
    }
    if (sidereon_last_terrain_error_text(family, part, (uint8_t *)buf, required, &written,
                                         &required) != SIDEREON_STATUS_OK) {
        return false;
    }
    buf[written] = 0;
    return true;
}

static int failures = 0;

/* Frozen from the public 120-epoch WTZR/WTZZ + matching SP3 fixtures and the
 * two public DTED mini tiles. Core-produced float64 fields are checked by
 * their IEEE-754 bit pattern; no binding-side numerical model is involved. */

static uint64_t f64_bits(double value) {
    uint64_t bits = 0;
    memcpy(&bits, &value, sizeof(bits));
    return bits;
}

static uint64_t fnv1a64(const uint8_t *bytes, size_t length) {
    uint64_t hash = UINT64_C(14695981039346656037);
    for (size_t i = 0; i < length; i++) {
        hash ^= bytes[i];
        hash *= UINT64_C(1099511628211);
    }
    return hash;
}

static void check(int ok, const char *what) {
    if (!ok) {
        char message[512];
        size_t message_len = sidereon_last_error_message(message, sizeof(message));
        if (message_len == 0) {
            message[0] = '\0';
        }
        /* The last error is sticky and may come from an earlier call, so it is
           reported as context rather than as the cause of this failure. */
        if (message[0] != '\0') {
            fprintf(stderr, "FAIL: %s (last ABI error, may predate this check: %s)\n",
                    what, message);
        } else {
            fprintf(stderr, "FAIL: %s\n", what);
        }
        failures++;
    }
}

static void check_bits(double actual, uint64_t expected, const char *what) {
    check(f64_bits(actual) == expected, what);
}

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *file = fopen(path, "rb");
    if (!file) {
        fprintf(stderr, "FAIL: cannot open %s\n", path);
        failures++;
        return NULL;
    }
    if (fseek(file, 0, SEEK_END) != 0) {
        fclose(file);
        failures++;
        return NULL;
    }
    long size = ftell(file);
    if (size < 0) {
        fclose(file);
        failures++;
        return NULL;
    }
    rewind(file);
    size_t allocation = (size_t)size == 0 ? 1 : (size_t)size;
    uint8_t *bytes = (uint8_t *)malloc(allocation);
    if (!bytes) {
        fclose(file);
        failures++;
        return NULL;
    }
    size_t read_count = fread(bytes, 1, (size_t)size, file);
    fclose(file);
    if (read_count != (size_t)size) {
        free(bytes);
        failures++;
        return NULL;
    }
    *out_len = read_count;
    return bytes;
}

static SidereonSp3 *load_sp3(const char *path) {
    size_t length = 0;
    uint8_t *bytes = read_file(path, &length);
    if (!bytes) {
        return NULL;
    }
    SidereonSp3 *sp3 = NULL;
    check(sidereon_sp3_load(bytes, length, &sp3) == SIDEREON_STATUS_OK && sp3 != NULL,
          "sp3 load");
    free(bytes);
    return sp3;
}

static SidereonRinexObs *load_obs(const char *path) {
    size_t length = 0;
    uint8_t *bytes = read_file(path, &length);
    if (!bytes) {
        return NULL;
    }
    SidereonRinexObs *obs = NULL;
    check(sidereon_rinex_obs_parse(bytes, length, &obs) == SIDEREON_STATUS_OK && obs != NULL,
          "RINEX observation parse");
    free(bytes);
    return obs;
}

static void check_single_arc(const SidereonRtkRinexArc *arc) {
    size_t epoch_count = 0;
    size_t skipped_count = 0;
    check(sidereon_rtk_rinex_arc_epoch_count(arc, &epoch_count) == SIDEREON_STATUS_OK &&
              epoch_count == W3RD_SINGLE_EPOCH_COUNT,
          "single RINEX arc epoch count");
    check(sidereon_rtk_rinex_arc_skipped_epoch_count(arc, &skipped_count) == SIDEREON_STATUS_OK &&
              skipped_count == W3RD_SINGLE_SKIPPED_COUNT,
          "single RINEX arc skipped count");
    printf("single RINEX arc: %zu epochs, %zu skipped\n", epoch_count, skipped_count);
    /* Every GPS carrier resolves, so no measurement is left out for want of one. */
    size_t unresolved_written = 1;
    size_t unresolved_required = 1;
    check(sidereon_rtk_rinex_arc_unresolved_carriers(arc, NULL, 0, &unresolved_written,
                                                     &unresolved_required) ==
                  SIDEREON_STATUS_OK &&
              unresolved_written == 0 && unresolved_required == W3RD_SINGLE_UNRESOLVED_COUNT,
          "single RINEX arc unresolved carriers");

    if (epoch_count != W3RD_SINGLE_EPOCH_COUNT) {
        return;
    }

    SidereonRtkArcEpochOutMetadata metadata;
    memset(&metadata, 0, sizeof(metadata));
    check(sidereon_rtk_rinex_arc_epoch_metadata(arc, 0, &metadata) == SIDEREON_STATUS_OK,
          "single RINEX arc epoch metadata");
    check(metadata.base_count == W3RD_SINGLE_E0_BASE_COUNT &&
              metadata.rover_count == W3RD_SINGLE_E0_ROVER_COUNT &&
              metadata.satellite_position_count == W3RD_SINGLE_E0_POSITION_COUNT &&
              metadata.base_satellite_position_count == W3RD_SINGLE_E0_BASE_POSITION_COUNT &&
              metadata.rover_satellite_position_count == W3RD_SINGLE_E0_ROVER_POSITION_COUNT &&
              metadata.has_velocity_mps == W3RD_SINGLE_E0_HAS_VELOCITY &&
              metadata.has_prediction_time == W3RD_SINGLE_E0_HAS_PREDICTION_TIME,
          "single RINEX arc frozen metadata");
    check_bits(metadata.prediction_time_s, W3RD_SINGLE_E0_PREDICTION_TIME,
          "single RINEX arc prediction time");

    size_t written = 0;
    size_t required = 0;
    check(sidereon_rtk_rinex_arc_epoch_base_observations(
              arc, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_SINGLE_E0_BASE_COUNT,
          "single RINEX base observation query");
    SidereonRtkArcObservationOut observations[W3RD_SINGLE_E0_BASE_COUNT] = {0};
    SidereonStatus status = sidereon_rtk_rinex_arc_epoch_base_observations(
        arc, 0, observations, W3RD_SINGLE_E0_BASE_COUNT, &written, &required);
    check(status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_BASE_COUNT && required == W3RD_SINGLE_E0_BASE_COUNT,
              "single RINEX base observation fill");
    if (status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_BASE_COUNT) {
        check(strcmp(observations[0].sat_id.bytes, W3RD_SINGLE_E0_BASE0_SAT) == 0 &&
                  strcmp(observations[0].ambiguity_id.bytes, W3RD_SINGLE_E0_BASE0_AMBIGUITY) ==
                      0 &&
                  observations[0].has_lli == W3RD_SINGLE_E0_BASE0_HAS_LLI &&
                  observations[0].lli == W3RD_SINGLE_E0_BASE0_LLI,
              "single RINEX base observation identity");
        check_bits(observations[0].code_m, W3RD_SINGLE_E0_BASE0_CODE,
                   "single RINEX base code");
        check_bits(observations[0].phase_m, W3RD_SINGLE_E0_BASE0_PHASE,
                   "single RINEX base phase");
    }

    written = 0;
    required = 0;
    check(sidereon_rtk_rinex_arc_epoch_rover_observations(
              arc, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_SINGLE_E0_ROVER_COUNT,
          "single RINEX rover observation query");
    SidereonRtkArcObservationOut rover_observations[W3RD_SINGLE_E0_ROVER_COUNT] = {0};
    status = sidereon_rtk_rinex_arc_epoch_rover_observations(
        arc, 0, rover_observations, W3RD_SINGLE_E0_ROVER_COUNT, &written, &required);
    check(status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_ROVER_COUNT && required == W3RD_SINGLE_E0_ROVER_COUNT,
          "single RINEX rover observation fill");
    if (status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_ROVER_COUNT) {
        check(strcmp(rover_observations[0].sat_id.bytes, W3RD_SINGLE_E0_ROVER0_SAT) == 0 &&
                  strcmp(rover_observations[0].ambiguity_id.bytes,
                         W3RD_SINGLE_E0_ROVER0_AMBIGUITY) == 0 &&
                  rover_observations[0].has_lli == W3RD_SINGLE_E0_ROVER0_HAS_LLI &&
                  rover_observations[0].lli == W3RD_SINGLE_E0_ROVER0_LLI,
              "single RINEX rover observation identity");
        check_bits(rover_observations[0].code_m, W3RD_SINGLE_E0_ROVER0_CODE,
                   "single RINEX rover code");
        check_bits(rover_observations[0].phase_m, W3RD_SINGLE_E0_ROVER0_PHASE,
                   "single RINEX rover phase");
    }

    written = 0;
    required = 0;
    check(sidereon_rtk_rinex_arc_epoch_base_satellite_positions(
              arc, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_SINGLE_E0_BASE_POSITION_COUNT,
          "single RINEX base position query");
    SidereonRtkArcPositionOut base_positions[W3RD_SINGLE_E0_BASE_POSITION_COUNT] = {0};
    status = sidereon_rtk_rinex_arc_epoch_base_satellite_positions(
        arc, 0, base_positions, W3RD_SINGLE_E0_BASE_POSITION_COUNT, &written, &required);
    check(status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_BASE_POSITION_COUNT && required == W3RD_SINGLE_E0_BASE_POSITION_COUNT,
          "single RINEX base position fill");
    if (status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_BASE_POSITION_COUNT) {
        check(strcmp(base_positions[0].id.bytes, W3RD_SINGLE_E0_BASE_POSITION0_ID) == 0,
              "single RINEX base position identity");
        check_bits(base_positions[0].pos[0], W3RD_SINGLE_E0_BASE_POSITION0_0,
                   "single RINEX base transmit-time position x");
        check_bits(base_positions[0].pos[1], W3RD_SINGLE_E0_BASE_POSITION0_1,
                   "single RINEX base transmit-time position y");
        check_bits(base_positions[0].pos[2], W3RD_SINGLE_E0_BASE_POSITION0_2,
                   "single RINEX base transmit-time position z");
    }

    written = 0;
    required = 0;
    check(sidereon_rtk_rinex_arc_epoch_rover_satellite_positions(
              arc, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_SINGLE_E0_ROVER_POSITION_COUNT,
          "single RINEX rover position query");
    SidereonRtkArcPositionOut rover_positions[W3RD_SINGLE_E0_ROVER_POSITION_COUNT] = {0};
    status = sidereon_rtk_rinex_arc_epoch_rover_satellite_positions(
        arc, 0, rover_positions, W3RD_SINGLE_E0_ROVER_POSITION_COUNT, &written, &required);
    check(status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_ROVER_POSITION_COUNT && required == W3RD_SINGLE_E0_ROVER_POSITION_COUNT,
          "single RINEX rover position fill");
    if (status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_ROVER_POSITION_COUNT) {
        check(strcmp(rover_positions[0].id.bytes, W3RD_SINGLE_E0_ROVER_POSITION0_ID) == 0,
              "single RINEX rover position identity");
        check_bits(rover_positions[0].pos[0], W3RD_SINGLE_E0_ROVER_POSITION0_0,
                   "single RINEX rover transmit-time position x");
        check_bits(rover_positions[0].pos[1], W3RD_SINGLE_E0_ROVER_POSITION0_1,
                   "single RINEX rover transmit-time position y");
        check_bits(rover_positions[0].pos[2], W3RD_SINGLE_E0_ROVER_POSITION0_2,
                   "single RINEX rover transmit-time position z");
    }

    written = 0;
    required = 0;
    check(sidereon_rtk_rinex_arc_epoch_satellite_positions(
              arc, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_SINGLE_E0_POSITION_COUNT,
          "single RINEX position query");
    SidereonRtkArcPositionOut positions[W3RD_SINGLE_E0_POSITION_COUNT] = {0};
    status = sidereon_rtk_rinex_arc_epoch_satellite_positions(
        arc, 0, positions, W3RD_SINGLE_E0_POSITION_COUNT, &written, &required);
    check(status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_POSITION_COUNT && required == W3RD_SINGLE_E0_POSITION_COUNT,
          "single RINEX position fill");
    if (status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_E0_POSITION_COUNT) {
        check(strcmp(positions[0].id.bytes, W3RD_SINGLE_E0_POSITION0_ID) == 0,
              "single RINEX position identity");
        check_bits(positions[0].pos[0], W3RD_SINGLE_E0_POSITION0_0,
                   "single RINEX position x");
        check_bits(positions[0].pos[1], W3RD_SINGLE_E0_POSITION0_1,
                   "single RINEX position y");
        check_bits(positions[0].pos[2], W3RD_SINGLE_E0_POSITION0_2,
                   "single RINEX position z");
    }

    written = 0;
    required = 0;
    check(sidereon_rtk_rinex_arc_wavelengths_m(
              arc, NULL, 0, &written, &required) == SIDEREON_STATUS_OK && written == 0 &&
              required == W3RD_SINGLE_WAVELENGTH_COUNT,
          "single RINEX wavelength query");
    SidereonRtkMapValue wavelengths[W3RD_SINGLE_WAVELENGTH_COUNT] = {0};
    status = sidereon_rtk_rinex_arc_wavelengths_m(arc, wavelengths, W3RD_SINGLE_WAVELENGTH_COUNT, &written, &required);
    check(status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_WAVELENGTH_COUNT && required == W3RD_SINGLE_WAVELENGTH_COUNT,
          "single RINEX wavelength fill");
    if (status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_WAVELENGTH_COUNT) {
        check(strcmp(wavelengths[0].id.bytes, W3RD_SINGLE_WAVELENGTH0_ID) == 0,
              "single RINEX wavelength identity");
        check_bits(wavelengths[0].value, W3RD_SINGLE_WAVELENGTH0,
                   "single RINEX wavelength value");
    }

    written = 0;
    required = 0;
    check(sidereon_rtk_rinex_arc_offsets_m(
              arc, NULL, 0, &written, &required) == SIDEREON_STATUS_OK && written == 0 &&
              required == W3RD_SINGLE_OFFSET_COUNT,
          "single RINEX offset query");
    SidereonRtkMapValue offsets[W3RD_SINGLE_OFFSET_COUNT] = {0};
    status = sidereon_rtk_rinex_arc_offsets_m(arc, offsets, W3RD_SINGLE_OFFSET_COUNT, &written, &required);
    check(status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_OFFSET_COUNT && required == W3RD_SINGLE_OFFSET_COUNT,
          "single RINEX offset fill");
    if (status == SIDEREON_STATUS_OK && written == W3RD_SINGLE_OFFSET_COUNT) {
        check(strcmp(offsets[0].id.bytes, W3RD_SINGLE_OFFSET0_ID) == 0,
              "single RINEX offset identity");
        check_bits(offsets[0].value, W3RD_SINGLE_OFFSET0,
                   "single RINEX offset value");
    }
}

static void check_dual_arc(const SidereonRtkRinexDualFrequencyArc *arc) {
    size_t epoch_count = 0;
    size_t skipped_count = 0;
    check(sidereon_rtk_rinex_dual_frequency_arc_epoch_count(arc, &epoch_count) ==
              SIDEREON_STATUS_OK &&
              epoch_count == W3RD_DUAL_EPOCH_COUNT,
          "dual RINEX arc epoch count");
    check(sidereon_rtk_rinex_dual_frequency_arc_skipped_epoch_count(arc, &skipped_count) ==
              SIDEREON_STATUS_OK && skipped_count == W3RD_DUAL_SKIPPED_COUNT,
          "dual RINEX arc skipped count");
    printf("dual RINEX arc: %zu epochs, %zu skipped\n", epoch_count, skipped_count);
    size_t unresolved_written = 1;
    size_t unresolved_required = 1;
    check(sidereon_rtk_rinex_dual_frequency_arc_unresolved_carriers(
              arc, NULL, 0, &unresolved_written, &unresolved_required) == SIDEREON_STATUS_OK &&
              unresolved_written == 0 && unresolved_required == W3RD_DUAL_UNRESOLVED_COUNT,
          "dual RINEX arc unresolved carriers");

    if (epoch_count != W3RD_DUAL_EPOCH_COUNT) {
        return;
    }

    SidereonRtkRinexDualFrequencyArcEpochOutMetadata metadata;
    memset(&metadata, 0, sizeof(metadata));
    check(sidereon_rtk_rinex_dual_frequency_arc_epoch_metadata(arc, 0, &metadata) ==
              SIDEREON_STATUS_OK,
          "dual RINEX arc epoch metadata");
    check(metadata.observation_count == W3RD_DUAL_E0_OBSERVATION_COUNT &&
              metadata.satellite_position_count == W3RD_DUAL_E0_POSITION_COUNT &&
              metadata.base_satellite_position_count == W3RD_DUAL_E0_BASE_POSITION_COUNT &&
              metadata.rover_satellite_position_count == W3RD_DUAL_E0_ROVER_POSITION_COUNT &&
              metadata.has_velocity_mps == W3RD_DUAL_E0_HAS_VELOCITY &&
              metadata.has_gap_time_s == W3RD_DUAL_E0_HAS_GAP_TIME &&
              metadata.has_prediction_time == W3RD_DUAL_E0_HAS_PREDICTION_TIME,
          "dual RINEX arc frozen metadata flags and counts");
    check_bits(metadata.jd_whole, W3RD_DUAL_E0_JD_WHOLE,
               "dual RINEX Julian day whole");
    check_bits(metadata.jd_fraction, W3RD_DUAL_E0_JD_FRACTION,
               "dual RINEX Julian day fraction");
    check_bits(metadata.gap_time_s, W3RD_DUAL_E0_GAP_TIME,
               "dual RINEX gap time");
    check_bits(metadata.prediction_time_s, W3RD_DUAL_E0_PREDICTION_TIME,
               "dual RINEX prediction time");

    size_t written = 0;
    size_t required = 0;
    static const char expected_sort_key[] = W3RD_DUAL_E0_SORT_KEY;
    check(sidereon_rtk_rinex_dual_frequency_arc_epoch_sort_key(
              arc, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == sizeof(expected_sort_key) - 1,
          "dual RINEX sort-key query");
    uint8_t sort_key[sizeof(expected_sort_key) - 1] = {0};
    SidereonStatus status = sidereon_rtk_rinex_dual_frequency_arc_epoch_sort_key(
        arc, 0, sort_key, sizeof(sort_key), &written, &required);
    check(status == SIDEREON_STATUS_OK && written == sizeof(sort_key) &&
              required == sizeof(sort_key) &&
              memcmp(sort_key, expected_sort_key, sizeof(sort_key)) == 0,
          "dual RINEX frozen sort key");

    written = 0;
    required = 0;
    check(sidereon_rtk_rinex_dual_frequency_arc_epoch_observations(
              arc, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_DUAL_E0_OBSERVATION_COUNT,
          "dual RINEX observation query");
    SidereonRtkDualFrequencySatelliteObservationOut
        observations[W3RD_DUAL_E0_OBSERVATION_COUNT] = {0};
    status = sidereon_rtk_rinex_dual_frequency_arc_epoch_observations(
        arc, 0, observations, W3RD_DUAL_E0_OBSERVATION_COUNT, &written, &required);
    check(status == SIDEREON_STATUS_OK && written == W3RD_DUAL_E0_OBSERVATION_COUNT &&
              required == W3RD_DUAL_E0_OBSERVATION_COUNT,
          "dual RINEX observation fill");
    if (status == SIDEREON_STATUS_OK && written == W3RD_DUAL_E0_OBSERVATION_COUNT) {
        check(strcmp(observations[0].sat_id.bytes, W3RD_DUAL_E0_OBS0_SAT) == 0 &&
                  strcmp(observations[0].base.ambiguity_id.bytes,
                         W3RD_DUAL_E0_OBS0_BASE_AMBIGUITY) == 0 &&
                  strcmp(observations[0].rover.ambiguity_id.bytes,
                         W3RD_DUAL_E0_OBS0_ROVER_AMBIGUITY) == 0 &&
                  observations[0].base.has_lli1 == W3RD_DUAL_E0_OBS0_BASE_HAS_LLI1 &&
                  observations[0].base.lli1 == W3RD_DUAL_E0_OBS0_BASE_LLI1 &&
                  observations[0].base.has_lli2 == W3RD_DUAL_E0_OBS0_BASE_HAS_LLI2 &&
                  observations[0].base.lli2 == W3RD_DUAL_E0_OBS0_BASE_LLI2 &&
                  observations[0].rover.has_lli1 == W3RD_DUAL_E0_OBS0_ROVER_HAS_LLI1 &&
                  observations[0].rover.lli1 == W3RD_DUAL_E0_OBS0_ROVER_LLI1 &&
                  observations[0].rover.has_lli2 == W3RD_DUAL_E0_OBS0_ROVER_HAS_LLI2 &&
                  observations[0].rover.lli2 == W3RD_DUAL_E0_OBS0_ROVER_LLI2,
              "dual RINEX observation identity");
        check_bits(observations[0].base.p1_m, W3RD_DUAL_E0_OBS0_BASE_P1,
                   "dual RINEX base P1");
        check_bits(observations[0].base.p2_m, W3RD_DUAL_E0_OBS0_BASE_P2,
                   "dual RINEX base P2");
        check_bits(observations[0].base.phi1_cycles, W3RD_DUAL_E0_OBS0_BASE_PHI1,
                   "dual RINEX base phase 1");
        check_bits(observations[0].base.phi2_cycles, W3RD_DUAL_E0_OBS0_BASE_PHI2,
                   "dual RINEX base phase 2");
        check_bits(observations[0].base.f1_hz, W3RD_DUAL_E0_OBS0_BASE_F1,
                   "dual RINEX base frequency 1");
        check_bits(observations[0].base.f2_hz, W3RD_DUAL_E0_OBS0_BASE_F2,
                   "dual RINEX base frequency 2");
        check_bits(observations[0].rover.p1_m, W3RD_DUAL_E0_OBS0_ROVER_P1,
                   "dual RINEX rover P1");
        check_bits(observations[0].rover.p2_m, W3RD_DUAL_E0_OBS0_ROVER_P2,
                   "dual RINEX rover P2");
        check_bits(observations[0].rover.phi1_cycles, W3RD_DUAL_E0_OBS0_ROVER_PHI1,
                   "dual RINEX rover phase 1");
        check_bits(observations[0].rover.phi2_cycles, W3RD_DUAL_E0_OBS0_ROVER_PHI2,
                   "dual RINEX rover phase 2");
    }

    written = 0;
    required = 0;
    check(sidereon_rtk_rinex_dual_frequency_arc_epoch_base_satellite_positions(
              arc, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_DUAL_E0_BASE_POSITION_COUNT,
          "dual RINEX base position query");
    written = 0;
    required = 0;
    check(sidereon_rtk_rinex_dual_frequency_arc_epoch_rover_satellite_positions(
              arc, 0, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_DUAL_E0_ROVER_POSITION_COUNT,
          "dual RINEX rover position query");
    SidereonRtkArcPositionOut positions[W3RD_DUAL_E0_POSITION_COUNT] = {0};
    status = sidereon_rtk_rinex_dual_frequency_arc_epoch_satellite_positions(
        arc, 0, positions, W3RD_DUAL_E0_POSITION_COUNT, &written, &required);
    check(status == SIDEREON_STATUS_OK && written == W3RD_DUAL_E0_POSITION_COUNT &&
              required == W3RD_DUAL_E0_POSITION_COUNT,
          "dual RINEX position fill");
    if (status == SIDEREON_STATUS_OK && written == W3RD_DUAL_E0_POSITION_COUNT) {
        check(strcmp(positions[0].id.bytes, W3RD_DUAL_E0_POSITION0_ID) == 0,
              "dual RINEX position identity");
        check_bits(positions[0].pos[0], W3RD_DUAL_E0_POSITION0_0,
                   "dual RINEX position x");
        check_bits(positions[0].pos[1], W3RD_DUAL_E0_POSITION0_1,
                   "dual RINEX position y");
        check_bits(positions[0].pos[2], W3RD_DUAL_E0_POSITION0_2,
                   "dual RINEX position z");
    }
}

/* POSIX leaves TMPDIR unset on many systems; /tmp is the standard fallback. */
static const char *smoke_tmpdir(void) {
    const char *tmpdir = getenv("TMPDIR");
    if (!tmpdir || !*tmpdir) {
        tmpdir = "/tmp";
    }
    return tmpdir;
}

static void check_dted_store(const char *tile_root) {
    char tile_w107[1024];
    char tile_w106[1024];
    int path_result = snprintf(tile_w107, sizeof(tile_w107), "%s/n36_w107_1arc_v3.dt2", tile_root);
    check(path_result > 0 && (size_t)path_result < sizeof(tile_w107), "DTED w107 path");
    path_result = snprintf(tile_w106, sizeof(tile_w106), "%s/n36_w106_1arc_v3.dt2", tile_root);
    check(path_result > 0 && (size_t)path_result < sizeof(tile_w106), "DTED w106 path");

    SidereonDtedTileListEntry entries[2] = {
        {{36, -107}, tile_w107},
        {{36, -106}, tile_w106},
    };
    size_t written = 0;
    size_t required = 0;
    check(sidereon_dted_tile_list_to_mmap_store(
              entries, 2, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_STORE_LEN,
          "DTED tile-list query");
    uint8_t *list_bytes = (uint8_t *)malloc(required);
    check(list_bytes != NULL, "DTED tile-list allocation");
    if (!list_bytes) {
        return;
    }
    check(sidereon_dted_tile_list_to_mmap_store(
              entries, 2, list_bytes, required, &written, &required) == SIDEREON_STATUS_OK &&
              written == W3RD_STORE_LEN && required == W3RD_STORE_LEN,
          "DTED tile-list fill");
    check(fnv1a64(list_bytes, required) == W3RD_STORE_FNV1A64,
          "DTED tile-list FNV-1a-64 equals the engine store's");

    size_t repeat_written = 0;
    size_t repeat_required = 0;
    check(sidereon_dted_tile_list_to_mmap_store(
              entries, 2, NULL, 0, &repeat_written, &repeat_required) == SIDEREON_STATUS_OK &&
              repeat_written == 0 && repeat_required == W3RD_STORE_LEN,
          "DTED deterministic query");
    uint8_t *repeat_bytes = (uint8_t *)malloc(repeat_required);
    check(repeat_bytes != NULL, "DTED repeat allocation");
    if (repeat_bytes) {
        check(sidereon_dted_tile_list_to_mmap_store(
                  entries, 2, repeat_bytes, repeat_required, &repeat_written, &repeat_required) ==
                  SIDEREON_STATUS_OK &&
                  repeat_written == required && memcmp(list_bytes, repeat_bytes, required) == 0,
              "DTED deterministic bytes");
        free(repeat_bytes);
    }

    const char *tmpdir = smoke_tmpdir();
    char output_path[1024];
    path_result = snprintf(output_path, sizeof(output_path), "%s/sidereon-g11-smoke.store", tmpdir);
    check(path_result > 0 && (size_t)path_result < sizeof(output_path), "DTED output path");
    char missing_parent_path[1024];
    path_result = snprintf(missing_parent_path, sizeof(missing_parent_path),
                           "%s/sidereon-g11-smoke-missing-parent", tmpdir);
    check(path_result > 0 && (size_t)path_result < sizeof(missing_parent_path),
          "DTED missing-parent path");
    char missing_output_path[1024];
    path_result = snprintf(missing_output_path, sizeof(missing_output_path),
                           "%s/sidereon-g11-smoke-missing-parent/store", tmpdir);
    check(path_result > 0 && (size_t)path_result < sizeof(missing_output_path),
          "DTED missing-parent output path");
    remove(output_path);
    remove(missing_output_path);
    remove(missing_parent_path);
    check(sidereon_write_dted_tile_list_to_mmap_store(entries, 2, output_path) ==
              SIDEREON_STATUS_OK,
          "DTED tile-list writer");
    check(sidereon_write_dted_tile_list_to_mmap_store(entries, 2, output_path) ==
              SIDEREON_STATUS_OK,
          "DTED tile-list deterministic overwrite");
    size_t written_file = 0;
    uint8_t *file_bytes = read_file(output_path, &written_file);
    check(file_bytes != NULL && written_file == required &&
              (!file_bytes || memcmp(list_bytes, file_bytes, required) == 0),
          "DTED writer bytes equal conversion");
    free(file_bytes);
    remove(output_path);

    check(sidereon_write_dted_tile_list_to_mmap_store(entries, 2, missing_output_path) ==
              SIDEREON_STATUS_INVALID_ARGUMENT,
          "DTED writer I/O error status");
    SidereonTerrainStoreError io_error;
    memset(&io_error, 0, sizeof(io_error));
    check(sidereon_last_terrain_store_error(&io_error) == SIDEREON_STATUS_OK &&
              io_error.kind == W3RD_WRITE_MISSING_PARENT_KIND,
          "DTED writer I/O typed error");
    remove(missing_output_path);
    remove(missing_parent_path);

    size_t tree_written = 0;
    size_t tree_required = 0;
    check(sidereon_dted_tree_to_mmap_store(
              tile_root, NULL, 0, &tree_written, &tree_required) == SIDEREON_STATUS_OK &&
              tree_written == 0 && tree_required == W3RD_STORE_LEN,
          "DTED tree/list size equivalence");
    uint8_t *tree_bytes = (uint8_t *)malloc(tree_required);
    check(tree_bytes != NULL, "DTED tree allocation");
    if (tree_bytes) {
        check(sidereon_dted_tree_to_mmap_store(
                  tile_root, tree_bytes, tree_required, &tree_written, &tree_required) ==
                  SIDEREON_STATUS_OK &&
                  tree_written == W3RD_STORE_LEN && tree_required == W3RD_STORE_LEN &&
                      (memcmp(list_bytes, tree_bytes, W3RD_STORE_LEN) == 0) ==
                          W3RD_TREE_EQUALS_LIST,
              "DTED tree/list bytes equal");
        free(tree_bytes);
    }

    SidereonDtedTileListEntry mismatch = entries[0];
    mismatch.tile_id.lat_index = 35;
    written = 0;
    required = 0;
    check(sidereon_dted_tile_list_to_mmap_store(
              &mismatch, 1, NULL, 0, &written, &required) == SIDEREON_STATUS_INVALID_ARGUMENT,
          "DTED tile-id mismatch status");
    SidereonTerrainStoreError terrain_error;
    memset(&terrain_error, 0, sizeof(terrain_error));
    check(sidereon_last_terrain_store_error(&terrain_error) == SIDEREON_STATUS_OK &&
              terrain_error.kind == W3RD_MISMATCH_KIND,
          "DTED tile-id mismatch typed error");
    check(sidereon_dted_tile_list_to_mmap_store(
              NULL, 1, NULL, 0, &written, &required) == SIDEREON_STATUS_NULL_POINTER,
          "DTED null entry pointer status");

    free(list_bytes);
}

/* DTED data records of the 5 x 5 fixture tiles: a sentinel, block and position
 * counts, five two-byte postings and a four-byte checksum each. */
enum {
    DTED_DATA_OFFSET = 3428,
    DTED_BLOCK_LEN = 12 + 2 * 5,
    DTED_DSI_DATUM_OFFSET = 80 + 144
};

static bool write_bytes(const char *path, const uint8_t *bytes, size_t length) {
    FILE *file = fopen(path, "wb");
    if (!file) {
        return false;
    }
    bool ok = fwrite(bytes, 1, length, file) == length;
    return fclose(file) == 0 && ok;
}

/* Restate a data block's checksum: the signed 32-bit sum of the bytes before
 * it, big-endian. */
static void set_dted_block_checksum(uint8_t *tile, size_t block) {
    size_t offset = DTED_DATA_OFFSET + block * DTED_BLOCK_LEN;
    int32_t sum = 0;
    for (size_t i = 0; i < DTED_BLOCK_LEN - 4; i++) {
        sum += tile[offset + i];
    }
    uint32_t bits = (uint32_t)sum;
    tile[offset + DTED_BLOCK_LEN - 4] = (uint8_t)(bits >> 24);
    tile[offset + DTED_BLOCK_LEN - 3] = (uint8_t)(bits >> 16);
    tile[offset + DTED_BLOCK_LEN - 2] = (uint8_t)(bits >> 8);
    tile[offset + DTED_BLOCK_LEN - 1] = (uint8_t)bits;
}

/* A DTED null posting is an unknown elevation, not a height, in the tile reader,
 * the lazy terrain reader and the terrain store; a tile on a datum other than
 * WGS84 is refused by the terrain reader and the store converter. Both tiles are
 * edited copies of the public n36_w106 mini tile, written where the terrain
 * reader finds them by name. */
static void check_dted_nulls_and_datum(const char *tile_root) {
    char source_path[1024];
    int path_result =
        snprintf(source_path, sizeof(source_path), "%s/n36_w106_1arc_v3.dt2", tile_root);
    check(path_result > 0 && (size_t)path_result < sizeof(source_path), "DTED source path");
    size_t tile_len = 0;
    uint8_t *tile = read_file(source_path, &tile_len);
    if (!tile) {
        return;
    }
    check(tile_len == W3RD_TILE_LEN, "DTED fixture tile length");
    const char *tmpdir = smoke_tmpdir();
    char tile_path[1024];
    path_result = snprintf(tile_path, sizeof(tile_path), "%s/n36_w106_1arc_v3.dt2", tmpdir);
    check(path_result > 0 && (size_t)path_result < sizeof(tile_path), "DTED temp tile path");

    /* Posting (longitude 0, latitude 0), the tile's south-west corner, holds the
     * DTED null value. */
    uint8_t *null_tile = (uint8_t *)malloc(tile_len);
    check(null_tile != NULL, "DTED null tile allocation");
    if (!null_tile) {
        free(tile);
        return;
    }
    memcpy(null_tile, tile, tile_len);
    null_tile[DTED_DATA_OFFSET + 8] = 0xFF;
    null_tile[DTED_DATA_OFFSET + 9] = 0xFF;
    set_dted_block_checksum(null_tile, 0);
    check(write_bytes(tile_path, null_tile, tile_len), "DTED null tile write");

    SidereonDtedTile *loaded = NULL;
    check(sidereon_dted_tile_load(tile_path, &loaded) == SIDEREON_STATUS_OK && loaded != NULL,
          "DTED null tile load");
    if (loaded) {
        SidereonDtedHorizontalDatumValue datum;
        memset(&datum, 0, sizeof(datum));
        datum.text[0] = 'x';
        check(sidereon_dted_tile_horizontal_datum(loaded, &datum) == SIDEREON_STATUS_OK &&
                  datum.kind == W3RD_NULL_TILE_DATUM &&
                  datum.wgs84_compatible == W3RD_NULL_TILE_DATUM_WGS84_COMPATIBLE &&
                  datum.text[0] == '\0',
              "DTED blank datum reads as unstated WGS84");
        int16_t elevation = 99;
        check(sidereon_dted_tile_get_elevation(loaded, -106.0, 36.0, &elevation) ==
                      SIDEREON_STATUS_INVALID_ARGUMENT &&
                  elevation == 0,
              "DTED null posting refused");
        SidereonDtedTileError tile_error;
        memset(&tile_error, 0, sizeof(tile_error));
        check(sidereon_last_dted_tile_error(&tile_error) == SIDEREON_STATUS_OK &&
                  tile_error.kind == W3RD_NULL_TILE_ERROR_KIND &&
                  tile_error.has_longitude_index &&
                  tile_error.longitude_index == W3RD_NULL_TILE_LONGITUDE_INDEX &&
                  tile_error.has_latitude_index &&
                  tile_error.latitude_index == W3RD_NULL_TILE_LATITUDE_INDEX,
              "DTED null posting typed");
        check(sidereon_dted_tile_get_elevation(loaded, -105.5, 36.5, &elevation) ==
                      SIDEREON_STATUS_OK &&
                  elevation == W3RD_NULL_TILE_KNOWN_ELEVATION,
              "DTED known posting beside a null");
        sidereon_dted_tile_free(loaded);
    }

    SidereonDtedTerrain *terrain = NULL;
    check(sidereon_dted_terrain_new(tmpdir, &terrain) == SIDEREON_STATUS_OK && terrain != NULL,
          "DTED null terrain");
    if (terrain) {
        double height = 42.0;
        check(sidereon_dted_terrain_height_m(terrain, -106.0, 36.0, &height) ==
                      SIDEREON_STATUS_INVALID_ARGUMENT &&
                  height == 0.0,
              "DTED terrain null corner refused");
        SidereonTerrainLookupError lookup_error;
        memset(&lookup_error, 0, sizeof(lookup_error));
        check(sidereon_last_terrain_lookup_error(&lookup_error) == SIDEREON_STATUS_OK &&
                  lookup_error.kind == W3RD_NULL_TERRAIN_ERROR_KIND &&
                  lookup_error.has_tile &&
                  lookup_error.lat_index == W3RD_NULL_TERRAIN_ERROR_LAT_INDEX &&
                  lookup_error.lon_index == W3RD_NULL_TERRAIN_ERROR_LON_INDEX &&
                  lookup_error.has_posting &&
                  lookup_error.latitude_posting == W3RD_NULL_TERRAIN_ERROR_LATITUDE_POSTING &&
                  lookup_error.longitude_posting == W3RD_NULL_TERRAIN_ERROR_LONGITUDE_POSTING,
              "DTED terrain unknown elevation typed");
        SidereonDtedLookupOptions options;
        check(sidereon_dted_lookup_options_init(&options) == SIDEREON_STATUS_OK,
              "DTED null options");
        SidereonLonLatDeg points[2] = {{-106.0, 36.0}, {-105.5, 36.5}};
        SidereonDtedHeightResult results[2];
        memset(results, 0, sizeof(results));
        check(sidereon_dted_terrain_height_batch_m(terrain, points, 2, &options, results) ==
                  SIDEREON_STATUS_OK,
              "DTED null batch");
        check(results[0].status == SIDEREON_STATUS_INVALID_ARGUMENT && !results[0].has_height_m &&
                  results[0].error.kind == W3RD_NULL_BATCH0_KIND &&
                  results[1].status == SIDEREON_STATUS_OK && results[1].has_height_m &&
                  f64_bits(results[1].height_m) == W3RD_NULL_BATCH1_HEIGHT &&
                  results[1].error.kind == SIDEREON_TERRAIN_LOOKUP_ERROR_KIND_NONE,
              "DTED null batch per point");
        sidereon_dted_terrain_free(terrain);
    }

    /* The store keeps the null as an unknown elevation. */
    SidereonDtedTileListEntry null_entry = {{36, -106}, tile_path};
    size_t written = 0;
    size_t required = 0;
    check(sidereon_dted_tile_list_to_mmap_store(&null_entry, 1, NULL, 0, &written, &required) ==
              SIDEREON_STATUS_OK,
          "DTED null store query");
    uint8_t *store = (uint8_t *)malloc(required == 0 ? 1 : required);
    if (store) {
        check(sidereon_dted_tile_list_to_mmap_store(&null_entry, 1, store, required, &written,
                                                    &required) == SIDEREON_STATUS_OK,
              "DTED null store fill");
        SidereonMmapTerrain *mmap = NULL;
        check(sidereon_mmap_terrain_from_bytes(store, written, &mmap) == SIDEREON_STATUS_OK &&
                  mmap != NULL,
              "DTED null store open");
        if (mmap) {
            SidereonOrthometricHeightM stored = {0.0};
            check(sidereon_mmap_terrain_height_m(mmap, -106.0, 36.0, &stored) ==
                      SIDEREON_STATUS_INVALID_ARGUMENT,
                  "DTED store null corner refused");
            SidereonTerrainLookupError store_lookup;
            memset(&store_lookup, 0, sizeof(store_lookup));
            check(sidereon_last_terrain_lookup_error(&store_lookup) == SIDEREON_STATUS_OK &&
                      store_lookup.kind == W3RD_NULL_STORE_ERROR_KIND &&
                      store_lookup.has_posting &&
                      store_lookup.latitude_posting == W3RD_NULL_STORE_ERROR_LATITUDE_POSTING &&
                      store_lookup.longitude_posting ==
                          W3RD_NULL_STORE_ERROR_LONGITUDE_POSTING,
                  "DTED store unknown elevation typed");
            sidereon_mmap_terrain_free(mmap);
        }
        free(store);
    }

    /* A tile whose DSI states WGS72 loads, but neither the terrain reader nor
     * the store converter treats its positions as WGS84. */
    uint8_t *wgs72_tile = null_tile;
    memcpy(wgs72_tile, tile, tile_len);
    memcpy(wgs72_tile + DTED_DSI_DATUM_OFFSET, "WGS72", 5);
    check(write_bytes(tile_path, wgs72_tile, tile_len), "DTED WGS72 tile write");
    loaded = NULL;
    check(sidereon_dted_tile_load(tile_path, &loaded) == SIDEREON_STATUS_OK && loaded != NULL,
          "DTED WGS72 tile load");
    if (loaded) {
        SidereonDtedHorizontalDatumValue datum;
        memset(&datum, 0, sizeof(datum));
        check(sidereon_dted_tile_horizontal_datum(loaded, &datum) == SIDEREON_STATUS_OK &&
                  datum.kind == W3RD_WGS72_TILE_DATUM &&
                  datum.wgs84_compatible == W3RD_WGS72_TILE_DATUM_WGS84_COMPATIBLE,
              "DTED WGS72 datum");
        sidereon_dted_tile_free(loaded);
    }
    SidereonDtedTileListEntry wgs72_entry = {{36, -106}, tile_path};
    check(sidereon_dted_tile_list_to_mmap_store(&wgs72_entry, 1, NULL, 0, &written, &required) ==
              SIDEREON_STATUS_INVALID_ARGUMENT,
          "DTED WGS72 store refused");
    SidereonTerrainStoreError store_error;
    memset(&store_error, 0, sizeof(store_error));
    check(sidereon_last_terrain_store_error(&store_error) == SIDEREON_STATUS_OK &&
              store_error.kind == W3RD_WGS72_STORE_KIND &&
              store_error.has_horizontal_datum &&
              store_error.horizontal_datum.kind == W3RD_WGS72_STORE_DATUM,
          "DTED WGS72 store refusal typed");
    terrain = NULL;
    check(sidereon_dted_terrain_new(tmpdir, &terrain) == SIDEREON_STATUS_OK && terrain != NULL,
          "DTED WGS72 terrain");
    if (terrain) {
        double height = 42.0;
        check(sidereon_dted_terrain_height_m(terrain, -105.5, 36.5, &height) ==
                  SIDEREON_STATUS_INVALID_ARGUMENT,
              "DTED WGS72 lookup refused");
        SidereonTerrainLookupError lookup_error;
        memset(&lookup_error, 0, sizeof(lookup_error));
        check(sidereon_last_terrain_lookup_error(&lookup_error) == SIDEREON_STATUS_OK &&
                  lookup_error.kind == W3RD_WGS72_TERRAIN_ERROR_KIND &&
                  lookup_error.has_tile &&
                  lookup_error.lat_index == W3RD_WGS72_TERRAIN_ERROR_LAT_INDEX &&
                  lookup_error.lon_index == W3RD_WGS72_TERRAIN_ERROR_LON_INDEX &&
                  lookup_error.has_horizontal_datum &&
                  lookup_error.horizontal_datum.kind == W3RD_WGS72_TERRAIN_ERROR_DATUM,
              "DTED WGS72 lookup typed");
        sidereon_dted_terrain_free(terrain);
    }
    remove(tile_path);

    char missing_path[1024];
    path_result = snprintf(missing_path, sizeof(missing_path), "%s/sidereon-missing-tile.dt2",
                           tmpdir);
    check(path_result > 0 && (size_t)path_result < sizeof(missing_path), "DTED missing path");
    remove(missing_path);
    loaded = NULL;
    check(sidereon_dted_tile_load(missing_path, &loaded) == SIDEREON_STATUS_INVALID_ARGUMENT &&
              loaded == NULL,
          "DTED missing tile refused");
    SidereonDtedTileError io_error;
    memset(&io_error, 0, sizeof(io_error));
    char io_path[4096];
    check(sidereon_last_dted_tile_error(&io_error) == SIDEREON_STATUS_OK &&
              io_error.kind == W3RD_MISSING_TILE_KIND &&
              last_terrain_text(SIDEREON_TERRAIN_ERROR_FAMILY_DTED_TILE,
                                SIDEREON_TERRAIN_ERROR_TEXT_PATH, io_path, sizeof(io_path)) &&
              strstr(io_path, "sidereon-missing-tile.dt2") != NULL,
          "DTED missing tile typed");

    free(null_tile);
    free(tile);
}

/* A version 2 file carrying SYS / SCALE FACTOR. This reader applies the
 * factor, but a version 2 reader that does not know the record reads the
 * scaled number as a physical one, so the writer refuses the product. */
static const char SCALE_FACTOR_V2_OBS[] =
    "     2.11           OBSERVATION DATA    G (GPS)             RINEX VERSION / TYPE\n"
    "     1     Z                                                # / TYPES OF OBSERV\n"
    "G   10  0                                                   SYS / SCALE FACTOR\n"
    "                                                            END OF HEADER\n"
    " 15  1  1  0  0  0.0000000  0  1G 1\n"
    "      1234.567\n";

/* A flag 4 event whose epoch fields are blank, between two timed epochs. */
static const char UNTIMED_EVENT_OBS[] =
    "     3.05           OBSERVATION DATA    M                   RINEX VERSION / TYPE\n"
    "G    1 C1C                                                  SYS / # / OBS TYPES\n"
    "                                                            END OF HEADER\n"
    "> 2020 01 01 00 00  0.0000000  0  1\n"
    "G01  20000000.000\n"
    ">                              4  1\n"
    "an event without a significant epoch                        COMMENT\n"
    "> 2020 01 01 00 01  0.0000000  0  1\n"
    "G01  20000100.000\n";

/* Two SYS / PHASE SHIFT records in one header block give G01's L1W 0.25 and
 * 0.5 cycles; G02's L1W has only the 0.5 record. */
static const char AMBIGUOUS_PHASE_SHIFT_OBS[] =
    "     3.05           OBSERVATION DATA    M (MIXED)           RINEX VERSION / TYPE\n"
    "G    2 C1C L1W                                              SYS / # / OBS TYPES\n"
    "G L1W  0.25000  01 G01                                      SYS / PHASE SHIFT\n"
    "G L1W  0.50000  02 G02 G01                                  SYS / PHASE SHIFT\n"
    "                                                            END OF HEADER\n"
    "> 2020 01 01 00 00  0.0000000  0  2\n"
    "G01  20000000.000   105000000.000\n"
    "G02  21000000.000   110000000.000\n";

static SidereonRinexObs *parse_obs_text(const char *text, const char *what) {
    SidereonRinexObs *obs = NULL;
    check(sidereon_rinex_obs_parse((const uint8_t *)text, strlen(text), &obs) ==
                  SIDEREON_STATUS_OK &&
              obs != NULL,
          what);
    return obs;
}

/* Copy an observation product's text into a NUL-terminated buffer the caller
 * frees, or NULL when the writer refuses it. */
static char *obs_text(const SidereonRinexObs *obs) {
    size_t written = 0;
    size_t required = 0;
    if (sidereon_rinex_obs_to_rinex_text(obs, NULL, 0, &written, &required) !=
            SIDEREON_STATUS_OK ||
        required == 0) {
        return NULL;
    }
    char *text = (char *)malloc(required + 1);
    if (!text) {
        return NULL;
    }
    if (sidereon_rinex_obs_to_rinex_text(obs, (uint8_t *)text, required, &written, &required) !=
            SIDEREON_STATUS_OK ||
        written != required) {
        free(text);
        return NULL;
    }
    text[written] = '\0';
    return text;
}

static void check_obs_writer_refusal(void) {
    SidereonRinexObs *obs = parse_obs_text(SCALE_FACTOR_V2_OBS, "version 2 scale-factor parse");
    if (!obs) {
        return;
    }
    size_t written = 99;
    size_t required = 99;
    check(sidereon_rinex_obs_to_rinex_text(obs, NULL, 0, &written, &required) ==
                  SIDEREON_STATUS_INVALID_ARGUMENT &&
              written == 0 && required == 0,
          "OBS writer refuses version 2 scale factors and writes nothing");

    SidereonRinexObsWriteResult *result = NULL;
    check(sidereon_rinex_obs_to_rinex_text_result(obs, &result) == SIDEREON_STATUS_OK &&
              result != NULL,
          "OBS writer result route");
    if (result) {
        SidereonRinexObsWriteOutcome outcome;
        check(sidereon_rinex_obs_write_result_get_outcome(result, &outcome) ==
                      SIDEREON_STATUS_OK &&
                  !outcome.is_ok && outcome.status == SIDEREON_STATUS_INVALID_ARGUMENT &&
                  outcome.error.kind == W3RD_SCALE_WRITE_ERROR_KIND &&
                  outcome.error.has_count && outcome.error.count == W3RD_SCALE_WRITE_ERROR_COUNT &&
                  !outcome.error.has_satellite && !outcome.error.has_epoch_index &&
                  !outcome.error.has_code && !outcome.error.has_detail,
              "OBS writer refusal is typed with its record count");
        written = 99;
        required = 99;
        check(sidereon_rinex_obs_write_result_get_text(result, NULL, 0, &written, &required) ==
                      SIDEREON_STATUS_INVALID_ARGUMENT &&
                  written == 0 && required == 0,
              "refused OBS write result has no text");
        check(sidereon_rinex_obs_write_result_get_message(result, NULL, 0, &written,
                                                          &required) == SIDEREON_STATUS_OK &&
                  written == 0 && required > 0,
              "refused OBS write result owns its message");
        check(sidereon_rinex_obs_write_result_get_code(result, NULL, 0, &written, &required) ==
                      SIDEREON_STATUS_OK &&
                  required == 0,
              "scale-factor refusal names no code");
        sidereon_rinex_obs_write_result_free(result);
    }
    sidereon_rinex_obs_write_result_free(NULL);
    sidereon_rinex_obs_free(obs);
}

static void check_untimed_event_epoch(void) {
    SidereonRinexObs *obs = parse_obs_text(UNTIMED_EVENT_OBS, "untimed event parse");
    if (!obs) {
        return;
    }
    SidereonRinexObsEpoch epochs[W3RD_UNTIMED_EPOCH_COUNT];
    size_t written = 0;
    size_t required = 0;
    check(sidereon_rinex_obs_epochs(obs, epochs, W3RD_UNTIMED_EPOCH_COUNT, &written,
                                    &required) == SIDEREON_STATUS_OK &&
              written == W3RD_UNTIMED_EPOCH_COUNT && required == W3RD_UNTIMED_EPOCH_COUNT,
          "untimed event epochs copy");
    if (written == W3RD_UNTIMED_EPOCH_COUNT) {
        check(epochs[0].has_epoch == W3RD_UNTIMED_E0_HAS_EPOCH &&
                  epochs[0].flag == W3RD_UNTIMED_E0_FLAG &&
                  epochs[0].epoch.year == W3RD_UNTIMED_E0_YEAR &&
                  epochs[0].satellite_count == W3RD_UNTIMED_E0_SATELLITE_COUNT,
              "timed epoch before the event");
        /* An epoch without a time reads as zero fields and a NaN second
         * (sidereon_rinex_obs_epochs, src/rinex.rs). */
        check(epochs[1].has_epoch == W3RD_UNTIMED_E1_HAS_EPOCH &&
                  epochs[1].flag == W3RD_UNTIMED_E1_FLAG && epochs[1].epoch.year == 0 &&
                  epochs[1].epoch.month == 0 && isnan(epochs[1].epoch.second) &&
                  epochs[1].satellite_count == W3RD_UNTIMED_E1_SATELLITE_COUNT,
              "event with blank epoch fields reports no time");
        check(epochs[2].has_epoch == W3RD_UNTIMED_E2_HAS_EPOCH &&
                  epochs[2].flag == W3RD_UNTIMED_E2_FLAG &&
                  epochs[2].epoch.minute == W3RD_UNTIMED_E2_MINUTE,
              "timed epoch after the event");
    }

    char *text = obs_text(obs);
    check(text != NULL, "untimed event product writes back");
    if (text) {
        check(strstr(text, W3RD_UNTIMED_EVENT_LINE) != NULL,
              "untimed event written with blank epoch fields");
        SidereonRinexObs *reread = parse_obs_text(text, "untimed event reparse");
        if (reread) {
            check(sidereon_rinex_obs_epochs(reread, epochs, W3RD_UNTIMED_EPOCH_COUNT, &written,
                                            &required) == SIDEREON_STATUS_OK &&
                      written == W3RD_UNTIMED_REREAD_EPOCH_COUNT &&
                      epochs[1].has_epoch == W3RD_UNTIMED_REREAD_E1_HAS_EPOCH &&
                      epochs[1].flag == W3RD_UNTIMED_REREAD_E1_FLAG,
                  "untimed event survives the round trip");
            sidereon_rinex_obs_free(reread);
        }
        free(text);
    }
    sidereon_rinex_obs_free(obs);
}

static void check_ambiguous_phase_correction(void) {
    SidereonRinexObs *obs =
        parse_obs_text(AMBIGUOUS_PHASE_SHIFT_OBS, "ambiguous phase-shift parse");
    if (!obs) {
        return;
    }
    size_t written = 0;
    size_t required = 0;
    check(sidereon_rinex_obs_carrier_phase(obs, 0, NULL, 0, &written, &required) ==
                  SIDEREON_STATUS_OK &&
              required == W3RD_PHASE_ROW_COUNT,
          "every carrier-phase row is kept, the ambiguous one included");
    SidereonRinexObsCarrierPhase rows[W3RD_PHASE_ROW_COUNT];
    check(sidereon_rinex_obs_carrier_phase(obs, 0, rows, W3RD_PHASE_ROW_COUNT, &written,
                                           &required) == SIDEREON_STATUS_OK &&
              written == W3RD_PHASE_ROW_COUNT,
          "carrier-phase rows copy");
    if (written == W3RD_PHASE_ROW_COUNT) {
        /* An ambiguous correction reads as a NaN shift (sidereon_rinex_obs_carrier_phase). */
        check(strcmp(rows[0].sat_id.bytes, W3RD_PHASE_ROW0_SAT) == 0 &&
                  strcmp(rows[0].code, W3RD_PHASE_ROW0_CODE) == 0 &&
                  rows[0].has_value_cycles == W3RD_PHASE_ROW0_HAS_VALUE &&
                  f64_bits(rows[0].value_cycles) == W3RD_PHASE_ROW0_VALUE &&
                  rows[0].phase_shift_status == W3RD_PHASE_ROW0_STATUS &&
                  isnan(rows[0].phase_shift_cycles) &&
                  rows[0].phase_shift_conflict_count == W3RD_PHASE_ROW0_CONFLICT_COUNT,
              "G01 L1W row keeps its phase and reports the ambiguous correction");
        check(strcmp(rows[1].sat_id.bytes, W3RD_PHASE_ROW1_SAT) == 0 &&
                  strcmp(rows[1].code, W3RD_PHASE_ROW1_CODE) == 0 &&
                  rows[1].has_value_cycles == W3RD_PHASE_ROW1_HAS_VALUE &&
                  f64_bits(rows[1].value_cycles) == W3RD_PHASE_ROW1_VALUE &&
                  rows[1].phase_shift_status == W3RD_PHASE_ROW1_STATUS &&
                  f64_bits(rows[1].phase_shift_cycles) == W3RD_PHASE_ROW1_SHIFT &&
                  rows[1].phase_shift_conflict_count == W3RD_PHASE_ROW1_CONFLICT_COUNT,
              "G02 L1W row reports its one correction");
    }

    SidereonRinexPhaseShiftCorrection conflicts[2];
    check(sidereon_rinex_obs_carrier_phase_conflicts(obs, 0, 0, NULL, 0, &written, &required) ==
                  SIDEREON_STATUS_OK &&
              written == 0 && required == W3RD_PHASE_ROW0_CONFLICT_COUNT,
          "ambiguous row conflict size query");
    check(sidereon_rinex_obs_carrier_phase_conflicts(obs, 0, 0, conflicts, 2, &written,
                                                     &required) == SIDEREON_STATUS_OK &&
              written == W3RD_PHASE_ROW0_CONFLICT_COUNT &&
              conflicts[0].has_cycles == W3RD_PHASE_ROW0_CONFLICT0_HAS_CYCLES &&
              f64_bits(conflicts[0].cycles) == W3RD_PHASE_ROW0_CONFLICT0_CYCLES &&
              conflicts[1].has_cycles == W3RD_PHASE_ROW0_CONFLICT1_HAS_CYCLES &&
              f64_bits(conflicts[1].cycles) == W3RD_PHASE_ROW0_CONFLICT1_CYCLES,
          "ambiguous row conflicts in record order");
    check(sidereon_rinex_obs_carrier_phase_conflicts(obs, 0, 1, NULL, 0, &written, &required) ==
                  SIDEREON_STATUS_OK &&
              required == W3RD_PHASE_ROW1_CONFLICT_COUNT,
          "available row has no conflicts");
    check(sidereon_rinex_obs_carrier_phase_conflicts(obs, 0, 2, NULL, 0, &written, &required) ==
                  SIDEREON_STATUS_INVALID_ARGUMENT,
          "conflict row index out of range");
    sidereon_rinex_obs_free(obs);
}

int main(int argc, char **argv) {
    if (argc != 5) {
        fprintf(stderr, "usage: %s <sp3> <wtzr_obs> <wtzz_obs> <dted_tile_root>\n", argv[0]);
        return 2;
    }

    SidereonSp3 *sp3 = load_sp3(argv[1]);
    SidereonRinexObs *base_obs = load_obs(argv[2]);
    SidereonRinexObs *rover_obs = load_obs(argv[3]);
    if (sp3 && base_obs && rover_obs) {
        SidereonRtkRinexArcOptions single_options;
        check(sidereon_rtk_rinex_arc_options_init(&single_options) == SIDEREON_STATUS_OK,
              "single RINEX option init");
        single_options.has_max_epochs = true;
        single_options.max_epochs = 120;
        single_options.include_prediction_time = true;
        SidereonRtkRinexArc *single_arc = NULL;
        check(sidereon_build_rinex_rtk_arc(
                  sp3, base_obs, rover_obs, &single_options, &single_arc) == SIDEREON_STATUS_OK &&
                  single_arc != NULL,
              "single RINEX arc build");
        if (single_arc) {
            check_single_arc(single_arc);
            sidereon_rtk_rinex_arc_free(single_arc);
        }

        SidereonRtkRinexDualArcOptions dual_options;
        check(sidereon_rtk_rinex_dual_arc_options_init(&dual_options) == SIDEREON_STATUS_OK,
              "dual RINEX option init");
        dual_options.has_max_epochs = true;
        dual_options.max_epochs = 120;
        dual_options.include_prediction_time = true;
        SidereonRtkRinexDualFrequencyArc *dual_arc = NULL;
        check(sidereon_build_dual_frequency_rinex_rtk_arc(
                  sp3, base_obs, rover_obs, &dual_options, &dual_arc) == SIDEREON_STATUS_OK &&
                  dual_arc != NULL,
              "dual RINEX arc build");
        if (dual_arc) {
            check_dual_arc(dual_arc);
            sidereon_rtk_rinex_dual_frequency_arc_free(dual_arc);
        }

        single_options.min_common_satellites = 0;
        single_arc = NULL;
        /* A refused build is SIDEREON_STATUS_INVALID_ARGUMENT
         * (map_rtk_rinex_arc_error, src/rtk.rs). */
        check(W3RD_SINGLE_MIN_ZERO_REFUSED &&
                  sidereon_build_rinex_rtk_arc(
                      sp3, base_obs, rover_obs, &single_options, &single_arc) ==
                      SIDEREON_STATUS_INVALID_ARGUMENT &&
                  single_arc == NULL,
              "single RINEX invalid option");
        check(sidereon_build_rinex_rtk_arc(
                  NULL, base_obs, rover_obs, &single_options, &single_arc) ==
                  SIDEREON_STATUS_NULL_POINTER,
              "single RINEX null input");
        sidereon_rtk_rinex_arc_free(NULL);
        sidereon_rtk_rinex_dual_frequency_arc_free(NULL);
    }

    if (sp3) {
        sidereon_sp3_free(sp3);
    }
    if (base_obs) {
        sidereon_rinex_obs_free(base_obs);
    }
    if (rover_obs) {
        sidereon_rinex_obs_free(rover_obs);
    }

    check_dted_store(argv[4]);
    check_dted_nulls_and_datum(argv[4]);
    check_obs_writer_refusal();
    check_untimed_event_epoch();
    check_ambiguous_phase_correction();
    if (failures != 0) {
        fprintf(stderr, "rinex_rtk_dted_smoke: %d failure(s)\n", failures);
        return 1;
    }
    return 0;
}
