/* Generated by tests/rinexgen from the committed reference RINEX-3
 * observation fixture (crx2rnx-decoded ESBC obs trim) via sidereon-core.
 * The C smoke test parses the same .rnx (and the decoded .crx) and asserts
 * the engine's version, epoch count, and sampled observation values
 * bit-for-bit. Do not edit by hand; rerun the generator. */
#ifndef SIDEREON_RINEX_FIXTURE_H
#define SIDEREON_RINEX_FIXTURE_H

#include <stdint.h>
#include <stddef.h>

#define RINEX_OBS_FILE "ESBC00DNK_R_20201770000_01D_30S_MO_trim.rnx"
static const uint64_t RINEX_VERSION_BITS = UINT64_C(0x4008666666666666);
#define RINEX_EPOCH_COUNT 2

typedef struct {
    size_t epoch_index;
    const char *sat;
    const char *code;
    uint64_t value_bits;
} RinexObsSample;

#define RINEX_SAMPLE_COUNT 16
static const RinexObsSample RINEX_SAMPLES[RINEX_SAMPLE_COUNT] = {
    {
        .epoch_index = 0,
        .sat = "G02",
        .code = "C1C",
        .value_bits = UINT64_C(0x4178a663dbeb851f),
    },
    {
        .epoch_index = 0,
        .sat = "G05",
        .code = "C1C",
        .value_bits = UINT64_C(0x4173fa164ee56042),
    },
    {
        .epoch_index = 0,
        .sat = "G07",
        .code = "C1C",
        .value_bits = UINT64_C(0x4174c4b1e4c08312),
    },
    {
        .epoch_index = 0,
        .sat = "G08",
        .code = "C1C",
        .value_bits = UINT64_C(0x4177d413a483126f),
    },
    {
        .epoch_index = 0,
        .sat = "G09",
        .code = "C1C",
        .value_bits = UINT64_C(0x4177688b4e147ae1),
    },
    {
        .epoch_index = 0,
        .sat = "G13",
        .code = "C1C",
        .value_bits = UINT64_C(0x4174b0c52f0624dd),
    },
    {
        .epoch_index = 0,
        .sat = "G15",
        .code = "C1C",
        .value_bits = UINT64_C(0x4176efab1f26e979),
    },
    {
        .epoch_index = 0,
        .sat = "G18",
        .code = "C1C",
        .value_bits = UINT64_C(0x4177058e24a3d70a),
    },
    {
        .epoch_index = 1,
        .sat = "G02",
        .code = "C1C",
        .value_bits = UINT64_C(0x4178aabeef126e98),
    },
    {
        .epoch_index = 1,
        .sat = "G05",
        .code = "C1C",
        .value_bits = UINT64_C(0x4173fb8be8978d50),
    },
    {
        .epoch_index = 1,
        .sat = "G07",
        .code = "C1C",
        .value_bits = UINT64_C(0x4174c745fd7ced91),
    },
    {
        .epoch_index = 1,
        .sat = "G08",
        .code = "C1C",
        .value_bits = UINT64_C(0x4177d15b3f810625),
    },
    {
        .epoch_index = 1,
        .sat = "G09",
        .code = "C1C",
        .value_bits = UINT64_C(0x41776d607c560419),
    },
    {
        .epoch_index = 1,
        .sat = "G13",
        .code = "C1C",
        .value_bits = UINT64_C(0x4174ad4a929ba5e3),
    },
    {
        .epoch_index = 1,
        .sat = "G15",
        .code = "C1C",
        .value_bits = UINT64_C(0x4176eab6e0a3d70a),
    },
    {
        .epoch_index = 1,
        .sat = "G18",
        .code = "C1C",
        .value_bits = UINT64_C(0x417703e68370a3d7),
    },
};

#endif /* SIDEREON_RINEX_FIXTURE_H */
