/*
 * Real-data RINEX RTK smoke test for the C binding.
 *
 * argv: <sp3> <wtzr_obs> <wtzz_obs>
 */
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Engine values regenerated by tests/pingen. */
#include "engine_pins_fixture.h"
/* Further engine values, from tests/valgen (w6_rtk_rinex). */
#include "w6_rtk_rinex_pins.h"

#include "sidereon.h"

static int failures = 0;

static void check(int ok, const char *what) {
    if (!ok) {
        char msg[512];
        size_t n = sidereon_last_error_message(msg, sizeof(msg));
        if (n == 0) {
            msg[0] = '\0';
        }
        /* The last error is sticky and may come from an earlier call, so it is
           reported as context rather than as the cause of this failure. */
        if (msg[0] != '\0') {
            fprintf(stderr, "FAIL: %s (last ABI error, may predate this check: %s)\n",
                    what, msg);
        } else {
            fprintf(stderr, "FAIL: %s\n", what);
        }
        failures++;
    }
}

static uint64_t f64_bits(double value) {
    uint64_t bits = 0;
    memcpy(&bits, &value, sizeof(bits));
    return bits;
}

static void check_exact_bits(double got, uint64_t expected, const char *what) {
    uint64_t bits = f64_bits(got);
    if (bits != expected) {
        fprintf(stderr, "FAIL: %s: got %016llx, expected %016llx\n", what,
                (unsigned long long)bits, (unsigned long long)expected);
        failures++;
    }
}

static uint8_t *read_file(const char *path, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "FAIL: cannot open %s\n", path);
        failures++;
        return NULL;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        failures++;
        return NULL;
    }
    long size = ftell(f);
    if (size < 0) {
        fclose(f);
        failures++;
        return NULL;
    }
    rewind(f);
    uint8_t *buf = (uint8_t *)malloc((size_t)size);
    if (!buf) {
        fclose(f);
        failures++;
        return NULL;
    }
    size_t got = fread(buf, 1, (size_t)size, f);
    fclose(f);
    if (got != (size_t)size) {
        free(buf);
        failures++;
        return NULL;
    }
    *out_len = got;
    return buf;
}

static SidereonSp3 *load_sp3(const char *path) {
    size_t len = 0;
    uint8_t *bytes = read_file(path, &len);
    if (!bytes) {
        return NULL;
    }
    SidereonSp3 *sp3 = NULL;
    check(sidereon_sp3_load(bytes, len, &sp3) == SIDEREON_STATUS_OK && sp3 != NULL,
          "sp3 load");
    free(bytes);
    return sp3;
}

static SidereonRinexObs *load_obs(const char *path) {
    size_t len = 0;
    uint8_t *bytes = read_file(path, &len);
    if (!bytes) {
        return NULL;
    }
    SidereonRinexObs *obs = NULL;
    check(sidereon_rinex_obs_parse(bytes, len, &obs) == SIDEREON_STATUS_OK && obs != NULL,
          "rinex obs parse");
    free(bytes);
    return obs;
}

static double norm3(const double v[3]) {
    return sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
}

static double vector_error(const double got[3], const double expected[3]) {
    double diff[3] = {
        got[0] - expected[0],
        got[1] - expected[1],
        got[2] - expected[2],
    };
    return norm3(diff);
}

static int arp_position(const double marker[3], const SidereonRinexObs *obs, double out[3]) {
    SidereonRinexObsHeader header;
    memset(&header, 0, sizeof(header));
    SidereonStatus status = sidereon_rinex_obs_header(obs, &header);
    check(status == SIDEREON_STATUS_OK, "rinex obs header");
    if (status != SIDEREON_STATUS_OK) {
        return 0;
    }
    check(header.has_antenna_delta_hen_m, "rinex antenna delta present");
    if (!header.has_antenna_delta_hen_m) {
        return 0;
    }
    int zero_east_north = fabs(header.antenna_delta_hen_m[1]) < 1.0e-12 &&
                          fabs(header.antenna_delta_hen_m[2]) < 1.0e-12;
    check(zero_east_north, "rinex antenna east/north offsets zero");
    if (!zero_east_north) {
        return 0;
    }

    double marker_norm = norm3(marker);
    check(marker_norm > 0.0, "marker norm nonzero");
    if (!(marker_norm > 0.0)) {
        return 0;
    }
    double height_m = header.antenna_delta_hen_m[0];
    out[0] = marker[0] + height_m * marker[0] / marker_norm;
    out[1] = marker[1] + height_m * marker[1] / marker_norm;
    out[2] = marker[2] + height_m * marker[2] / marker_norm;
    return 1;
}

static void set_wtzr_single_frequency_config(SidereonRtkRinexStaticBaselineConfig *config,
                                             const double base_arp[3]) {
    check(sidereon_rtk_rinex_static_baseline_config_init(config) == SIDEREON_STATUS_OK,
          "static rinex config init");
    memcpy(config->base_m, base_arp, sizeof(config->base_m));
    config->arc_options.has_max_epochs = true;
    config->arc_options.max_epochs = 120;
    config->arc_options.include_prediction_time = false;
    config->model.code_sigma_m = 2.0;
    config->model.phase_sigma_m = 0.01;
    config->model.sagnac = true;
    config->model.stochastic = SIDEREON_RTK_STOCHASTIC_MODEL_SIMPLE;
    config->model.elevation_weighting = true;
    config->preprocessing.has_cycle_slip = true;
    config->preprocessing.cycle_slip = SIDEREON_RTK_CYCLE_SLIP_POLICY_SPLIT_ARC;
}

static void set_wtzr_wide_lane_config(SidereonRtkRinexWideLaneFixedConfig *config,
                                      const double base_arp[3]) {
    check(sidereon_rtk_rinex_wide_lane_fixed_config_init(config) == SIDEREON_STATUS_OK,
          "wide lane rinex config init");
    memcpy(config->base_m, base_arp, sizeof(config->base_m));
    config->arc_options.has_max_epochs = true;
    config->arc_options.max_epochs = 120;
    config->arc_options.include_prediction_time = false;
    config->model.code_sigma_m = 2.0;
    config->model.phase_sigma_m = 0.01;
    config->model.sagnac = true;
    config->model.stochastic = SIDEREON_RTK_STOCHASTIC_MODEL_SIMPLE;
    config->model.elevation_weighting = true;
}

static void test_static_rinex_rtk(const SidereonSp3 *sp3, const SidereonRinexObs *base_obs,
                                  const SidereonRinexObs *rover_obs,
                                  const double base_arp[3], const double truth[3]) {
    SidereonRtkRinexStaticBaselineConfig config;
    set_wtzr_single_frequency_config(&config, base_arp);

    SidereonRtkStaticArcSolution *solution = NULL;
    check(sidereon_solve_static_rinex_rtk_baseline(sp3, base_obs, rover_obs, &config,
                                                   &solution) == SIDEREON_STATUS_OK &&
              solution != NULL,
          "solve static rinex rtk baseline");
    if (!solution) {
        return;
    }

    double float_baseline[3] = {0.0, 0.0, 0.0};
    double fixed_baseline[3] = {0.0, 0.0, 0.0};
    check(sidereon_rtk_static_arc_solution_float_baseline_ecef(solution, float_baseline, 3) ==
              SIDEREON_STATUS_OK,
          "static float baseline");
    check(sidereon_rtk_static_arc_solution_fixed_baseline_ecef(solution, fixed_baseline, 3) ==
              SIDEREON_STATUS_OK,
          "static fixed baseline");

    SidereonRtkFloatMetadata float_meta;
    SidereonRtkFixedMetadata fixed_meta;
    check(sidereon_rtk_static_arc_solution_float_metadata(solution, &float_meta) ==
              SIDEREON_STATUS_OK,
          "static float metadata");
    check(sidereon_rtk_static_arc_solution_fixed_metadata(solution, &fixed_meta) ==
              SIDEREON_STATUS_OK,
          "static fixed metadata");

    double float_err = vector_error(float_baseline, truth);
    double fixed_err = vector_error(fixed_baseline, truth);
    printf("static rinex rtk float baseline = %.9f %.9f %.9f, error = %.9f m\n",
           float_baseline[0], float_baseline[1], float_baseline[2], float_err);
    printf("static rinex rtk fixed baseline = %.9f %.9f %.9f, error = %.9f m\n",
           fixed_baseline[0], fixed_baseline[1], fixed_baseline[2], fixed_err);

    for (int i = 0; i < 3; i++) {
        check_exact_bits(float_baseline[i], W6_RTKR_STATIC_FLOAT_BASELINE_BITS[i],
                         "static float baseline");
        check_exact_bits(fixed_baseline[i], W6_RTKR_STATIC_FIXED_BASELINE_BITS[i],
                         "static fixed baseline");
    }
    check(float_meta.ambiguity_count == W6_RTKR_STATIC_AMBIGUITY_COUNT &&
              float_meta.n_observations == W6_RTKR_STATIC_N_OBSERVATIONS,
          "static float metadata counts");
    check(fixed_meta.integer_status == W6_RTKR_STATIC_INTEGER_STATUS,
          "static integer status");
    check(fixed_meta.has_integer_ratio == W6_RTKR_STATIC_HAS_RATIO,
          "static ratio presence");
    check_exact_bits(fixed_meta.integer_ratio, W6_RTKR_STATIC_RATIO_BITS, "static ratio");
    /* Accuracy against the IGS marker coordinates (WTZR_MARKER_M and
     * WTZZ_MARKER_M in main), an external reference. */
    check(float_err < 0.08, "static float baseline within dm");
    check(fixed_err < 0.01, "static fixed reported baseline within cm");

    size_t written = 99;
    size_t required = 99;
    check(sidereon_rtk_static_arc_solution_split_cycle_slip_arcs(
              solution, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W6_RTKR_STATIC_SPLIT_ARC_COUNT,
          "static split cycle slip arcs");

    written = 99;
    required = 99;
    check(sidereon_rtk_static_arc_solution_ambiguity_ids(solution, NULL, 0, &written,
                                                         &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == W6_RTKR_STATIC_AMBIGUITY_ID_COUNT,
          "static ambiguity id query");

    sidereon_rtk_static_arc_solution_free(solution);
}

static void test_static_reference_station(const SidereonSp3 *sp3,
                                          const SidereonRinexObs *base_obs,
                                          const SidereonRinexObs *rover_obs,
                                          const double base_arp[3],
                                          const double truth[3]) {
    SidereonStaticReferenceStationRinexConfig config;
    check(sidereon_static_reference_station_rinex_config_init(&config) == SIDEREON_STATUS_OK,
          "static reference config init");
    memcpy(config.reference_position_m, base_arp, sizeof(config.reference_position_m));
    config.enable_code_dgnss = false;
    config.enable_carrier_rtk = true;
    config.with_geodetic = true;
    set_wtzr_single_frequency_config(&config.carrier, base_arp);
    config.carrier.arc_options.max_epochs = 24;
    config.carrier.float_options.position_tol_m = 1.0e-4;
    config.carrier.float_options.ambiguity_tol_m = 1.0e-4;
    config.carrier.float_options.max_iterations = 10;
    config.carrier.fixed_options.position_tol_m = 1.0e-4;
    config.carrier.fixed_options.ambiguity_tol_m = 1.0e-4;
    config.carrier.fixed_options.max_iterations = 10;
    config.carrier.fixed_options.ratio_threshold = 3.0;
    config.carrier.fixed_options.partial_ambiguity_resolution = true;
    config.carrier.fixed_options.partial_min_ambiguities = 4;

    SidereonStaticReferenceStationSolution *solution = NULL;
    check(sidereon_solve_static_reference_station_rinex(sp3, base_obs, rover_obs, &config,
                                                        &solution) == SIDEREON_STATUS_OK &&
              solution != NULL,
          "solve static reference station rinex");
    if (!solution) {
        return;
    }

    SidereonStaticReferenceStationMetadata meta;
    check(sidereon_static_reference_station_solution_metadata(solution, &meta) ==
              SIDEREON_STATUS_OK,
          "static reference metadata");
    check(meta.mode == W6_RTKR_REF_MODE && meta.fix_status == W6_RTKR_REF_FIX_STATUS &&
              meta.has_carrier_solution == W6_RTKR_REF_HAS_CARRIER &&
              meta.has_code_solution == W6_RTKR_REF_HAS_CODE &&
              meta.has_geodetic == W6_RTKR_REF_HAS_GEODETIC &&
              meta.diagnostic_count == W6_RTKR_REF_DIAGNOSTIC_COUNT &&
              meta.carrier_diagnostic_count == W6_RTKR_REF_CARRIER_DIAGNOSTIC_COUNT &&
              meta.mode_report_count == W6_RTKR_REF_MODE_REPORT_COUNT,
          "static reference metadata values");
    check(meta.carrier_integer_status == W6_RTKR_REF_CARRIER_INTEGER_STATUS &&
              meta.has_carrier_integer_ratio == W6_RTKR_REF_HAS_CARRIER_RATIO,
          "static reference carrier fixed metadata");

    double position[3] = {0.0, 0.0, 0.0};
    double baseline[3] = {0.0, 0.0, 0.0};
    double covariance[9] = {0.0};
    check(sidereon_static_reference_station_solution_position_ecef(solution, position, 3) ==
              SIDEREON_STATUS_OK,
          "static reference position");
    check(sidereon_static_reference_station_solution_baseline_ecef(solution, baseline, 3) ==
              SIDEREON_STATUS_OK,
          "static reference baseline");
    check(sidereon_static_reference_station_solution_covariance_ecef(solution, covariance, 9) ==
              SIDEREON_STATUS_OK,
          "static reference covariance");

    printf("static reference position = %.9f %.9f %.9f m\n", position[0], position[1],
           position[2]);
    printf("static reference baseline = %.9f %.9f %.9f m, error = %.9f m\n", baseline[0],
           baseline[1], baseline[2], vector_error(baseline, truth));
    check(vector_error(baseline, truth) < 0.005, "static reference baseline within 5 mm");

    /* The engine's own solve of these inputs, written by tests/pingen through
     * sidereon-core's public static reference-station solve with the same
     * configuration and the same base ARP (checked bit for bit in main). The
     * library and the generator run the same engine code, which states
     * bit-identical results across x86_64 and arm64 (portable kernels since
     * sidereon-core 1.4.0), so every value is compared exactly. */
    check_exact_bits(meta.carrier_integer_ratio, PIN_STATIC_REFERENCE_RATIO_BITS,
                     "static reference ratio");
    for (int i = 0; i < 3; i++) {
        check_exact_bits(position[i], PIN_STATIC_REFERENCE_POSITION_BITS[i],
                         "static reference position");
        check_exact_bits(baseline[i], PIN_STATIC_REFERENCE_BASELINE_BITS[i],
                         "static reference baseline");
    }
    for (int i = 0; i < 9; i++) {
        check_exact_bits(covariance[i], PIN_STATIC_REFERENCE_COVARIANCE_BITS[i],
                         "static reference covariance");
    }

    size_t written = 0;
    size_t required = 0;
    SidereonStaticReferenceEpochDiagnostic diagnostics[W6_RTKR_REF_DIAGNOSTIC_COUNT];
    check(sidereon_static_reference_station_solution_diagnostics(
              solution, diagnostics, W6_RTKR_REF_DIAGNOSTIC_COUNT, &written, &required) ==
                  SIDEREON_STATUS_OK &&
              written == W6_RTKR_REF_DIAGNOSTIC_COUNT &&
              required == W6_RTKR_REF_DIAGNOSTIC_COUNT,
          "static reference diagnostics");
    check(diagnostics[0].mode == W6_RTKR_REF_DIAG0_MODE &&
              diagnostics[0].used_satellite_count == W6_RTKR_REF_DIAG0_USED_SATS &&
              diagnostics[0].has_code_residual_rms_m == W6_RTKR_REF_DIAG0_HAS_CODE_RMS &&
              diagnostics[0].has_phase_residual_rms_m == W6_RTKR_REF_DIAG0_HAS_PHASE_RMS,
          "static reference diagnostic row");

    SidereonStaticReferenceModeReport reports[1];
    check(sidereon_static_reference_station_solution_mode_reports(solution, reports, 1, &written,
                                                                  &required) ==
                  SIDEREON_STATUS_OK &&
              written == W6_RTKR_REF_MODE_REPORT_COUNT &&
              required == W6_RTKR_REF_MODE_REPORT_COUNT,
          "static reference mode reports");
    check(reports[0].mode == W6_RTKR_REF_REPORT0_MODE &&
              reports[0].status == W6_RTKR_REF_REPORT0_STATUS &&
              reports[0].used_epochs == W6_RTKR_REF_REPORT0_USED_EPOCHS &&
              reports[0].skipped_epochs == W6_RTKR_REF_REPORT0_SKIPPED_EPOCHS &&
              reports[0].used_measurements == W6_RTKR_REF_REPORT0_USED_MEASUREMENTS &&
              reports[0].has_error == W6_RTKR_REF_REPORT0_HAS_ERROR,
          "static reference mode report values");

    sidereon_static_reference_station_solution_free(solution);
}

static void test_wide_lane_rinex_rtk(const SidereonSp3 *sp3, const SidereonRinexObs *base_obs,
                                     const SidereonRinexObs *rover_obs,
                                     const double base_arp[3], const double truth[3]) {
    SidereonRtkRinexWideLaneFixedConfig config;
    set_wtzr_wide_lane_config(&config, base_arp);

    SidereonRtkWideLaneFixedRinexSolution *solution = NULL;
    check(sidereon_solve_wide_lane_fixed_rinex_rtk_baseline(
              sp3, base_obs, rover_obs, &config, &solution) == SIDEREON_STATUS_OK &&
              solution != NULL,
          "solve wide lane rinex rtk baseline");
    if (!solution) {
        return;
    }

    double float_baseline[3] = {0.0, 0.0, 0.0};
    double fixed_baseline[3] = {0.0, 0.0, 0.0};
    check(sidereon_rtk_wide_lane_fixed_rinex_solution_float_baseline_ecef(
              solution, float_baseline, 3) == SIDEREON_STATUS_OK,
          "wide lane float baseline");
    check(sidereon_rtk_wide_lane_fixed_rinex_solution_fixed_baseline_ecef(
              solution, fixed_baseline, 3) == SIDEREON_STATUS_OK,
          "wide lane fixed baseline");

    SidereonRtkFloatMetadata float_meta;
    SidereonRtkFixedMetadata fixed_meta;
    SidereonRtkWideLaneFixedRinexMetadata rinex_meta;
    check(sidereon_rtk_wide_lane_fixed_rinex_solution_float_metadata(solution, &float_meta) ==
              SIDEREON_STATUS_OK,
          "wide lane float metadata");
    check(sidereon_rtk_wide_lane_fixed_rinex_solution_fixed_metadata(solution, &fixed_meta) ==
              SIDEREON_STATUS_OK,
          "wide lane fixed metadata");
    check(sidereon_rtk_wide_lane_fixed_rinex_solution_metadata(solution, &rinex_meta) ==
              SIDEREON_STATUS_OK,
          "wide lane combined metadata");

    double float_err = vector_error(float_baseline, truth);
    double fixed_err = vector_error(fixed_baseline, truth);
    printf("wide lane rinex rtk float baseline = %.9f %.9f %.9f, error = %.9f m\n",
           float_baseline[0], float_baseline[1], float_baseline[2], float_err);
    printf("wide lane rinex rtk fixed baseline = %.9f %.9f %.9f, error = %.9f m\n",
           fixed_baseline[0], fixed_baseline[1], fixed_baseline[2], fixed_err);

    for (int i = 0; i < 3; i++) {
        check_exact_bits(float_baseline[i], W6_RTKR_WL_FLOAT_BASELINE_BITS[i],
                         "wide lane float baseline");
        check_exact_bits(fixed_baseline[i], W6_RTKR_WL_FIXED_BASELINE_BITS[i],
                         "wide lane fixed baseline");
    }
    check(float_meta.ambiguity_count == W6_RTKR_WL_AMBIGUITY_COUNT &&
              float_meta.n_observations == W6_RTKR_WL_N_OBSERVATIONS,
          "wide lane float metadata counts");
    check(fixed_meta.integer_status == W6_RTKR_WL_INTEGER_STATUS, "wide lane integer status");
    check(fixed_meta.has_integer_ratio == W6_RTKR_WL_HAS_RATIO, "wide lane ratio presence");
    check_exact_bits(fixed_meta.integer_ratio, W6_RTKR_WL_RATIO_BITS, "wide lane ratio");
    check(rinex_meta.wide_lane_fixed == W6_RTKR_WL_FIXED &&
              rinex_meta.wide_lane_ambiguity_count == W6_RTKR_WL_AMBIGUITY_CYCLE_COUNT,
          "wide lane metadata fixed");
    /* Accuracy against the IGS marker coordinates, an external reference. */
    check(float_err < 0.1, "wide lane float baseline within dm");
    check(fixed_err < 0.01, "wide lane fixed baseline within cm");

    size_t written = 99;
    size_t required = 99;
    check(sidereon_rtk_wide_lane_fixed_rinex_solution_wide_lane_cycles(
              solution, NULL, 0, &written, &required) == SIDEREON_STATUS_OK &&
              written == 0 && required == rinex_meta.wide_lane_ambiguity_count &&
              required > 0,
          "wide lane cycle query");

    sidereon_rtk_wide_lane_fixed_rinex_solution_free(solution);
}

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: %s <sp3> <wtzr_obs> <wtzz_obs>\n", argv[0]);
        return 2;
    }

    /* Station marker coordinates from the IGS station information (an external
     * reference; the RINEX headers' APPROX POSITION XYZ records are coarser).
     * The antenna heights come from the headers' ANTENNA: DELTA H/E/N records
     * (WTZR00DEU_R_20201770000_01D_30S_MO_120epoch.rnx line 44, 0.0710 m;
     * WTZZ00DEU_R_20201770000_01D_30S_MO_120epoch.rnx line 17, .2840 m, both
     * with zero east and north offsets). */
    static const double WTZR_MARKER_M[3] = {
        4075580.3111,
        931854.0543,
        4801568.2808,
    };
    static const double WTZZ_MARKER_M[3] = {
        4075579.1913,
        931853.3696,
        4801569.1897,
    };

    SidereonSp3 *sp3 = load_sp3(argv[1]);
    SidereonRinexObs *base_obs = load_obs(argv[2]);
    SidereonRinexObs *rover_obs = load_obs(argv[3]);

    if (sp3 && base_obs && rover_obs) {
        double base_arp[3] = {0.0, 0.0, 0.0};
        double rover_arp[3] = {0.0, 0.0, 0.0};
        double truth[3] = {0.0, 0.0, 0.0};
        if (arp_position(WTZR_MARKER_M, base_obs, base_arp) &&
            arp_position(WTZZ_MARKER_M, rover_obs, rover_arp)) {
            truth[0] = rover_arp[0] - base_arp[0];
            truth[1] = rover_arp[1] - base_arp[1];
            truth[2] = rover_arp[2] - base_arp[2];
            printf("truth arp baseline = %.9f %.9f %.9f m\n", truth[0], truth[1], truth[2]);
            /* The ARP tests/pingen formed from the same header in Rust. The
             * scripts compile with -ffp-contract=off, so the C arithmetic
             * rounds each operation as Rust does and the bits agree. */
            for (int i = 0; i < 3; i++) {
                check_exact_bits(base_arp[i], PIN_STATIC_REFERENCE_ARP_BITS[i],
                                 "static reference base ARP");
            }

            test_static_rinex_rtk(sp3, base_obs, rover_obs, base_arp, truth);
            test_static_reference_station(sp3, base_obs, rover_obs, base_arp, truth);
            test_wide_lane_rinex_rtk(sp3, base_obs, rover_obs, base_arp, truth);
        }
    }

    sidereon_rinex_obs_free(rover_obs);
    sidereon_rinex_obs_free(base_obs);
    sidereon_sp3_free(sp3);

    if (failures != 0) {
        fprintf(stderr, "rtk_rinex_smoke: %d failure(s)\n", failures);
        return 1;
    }
    return 0;
}
