/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/valgen (bin smoke_b_ionex) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_B_IONEX_PINS_H
#define SIDEREON_SMOKE_B_IONEX_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* A missing-node block, a node gap and a slant outcome, field for field
 * as the C view reports them. */
typedef struct {
    bool has_missing;
    size_t map_number;
    size_t lat_index;
    size_t lon_index;
    size_t lon_index_next;
    bool missing[4];
} SmokeBMissingPin;
typedef struct {
    bool has_gap;
    SmokeBMissingPin earlier;
    SmokeBMissingPin later;
} SmokeBGapPin;
typedef struct {
    bool ok;
    SidereonStatus status;
    uint64_t delay_bits;
    bool is_valid;
    bool has_held;
    SidereonIonexCoverageErrorKind coverage_error;
    bool has_degraded;
    SmokeBGapPin gap;
    bool has_assumed_mapping;
    SidereonIonexAssumedMappingKind assumed_mapping;
    SidereonIonexSlantErrorKind error_kind;
    SidereonIonexCoverageErrorKind error_coverage;
    bool error_has_gap;
    SmokeBGapPin error_gap;
    SidereonIonexSlantRefusalKind refusal;
    size_t refusal_map_number;
    size_t refusal_lat_index;
    size_t refusal_lon_index;
    bool has_mapping_declaration;
    SidereonIonexMappingDeclarationKind mapping_declaration;
    bool has_mapping_function;
    SidereonIonexMappingFunctionKind mapping_function;
} SmokeBSlantPin;

#define SMOKE_B_IONEX_KLOB_T1E9_OK false
#define SMOKE_B_IONEX_KLOB_T1E9_STATUS SIDEREON_STATUS_INVALID_ARGUMENT
#define SMOKE_B_IONEX_EPOCH_COUNT ((size_t)2)
#define SMOKE_B_IONEX_EXPONENT -1
#define SMOKE_B_IONEX_LAT_NODE_COUNT ((size_t)7)
#define SMOKE_B_IONEX_LON_NODE_COUNT ((size_t)7)
/* Every IONEX golden case under the strict default policy and under the
 * hold coverage policy. */
static const SmokeBSlantPin SMOKE_B_IONEX_CASE_DEFAULT[] = {
    { true, SIDEREON_STATUS_OK, UINT64_C(0x400788254ae08283), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x401360b774bc13dd), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x40151975f892b743), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x40033ff22a448b8e), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x4011bf156788af16), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { false, SIDEREON_STATUS_SOLVE, UINT64_C(0), false, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, false, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_NONE, SIDEREON_IONEX_SLANT_ERROR_KIND_OUT_OF_COVERAGE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_EPOCH_BEFORE_FIRST_MAP, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { false, SIDEREON_STATUS_SOLVE, UINT64_C(0), false, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, false, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_NONE, SIDEREON_IONEX_SLANT_ERROR_KIND_OUT_OF_COVERAGE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_EPOCH_AFTER_LAST_MAP, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x40113fa3c9bde53f), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x4011410735dc2530), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { false, SIDEREON_STATUS_SOLVE, UINT64_C(0), false, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, false, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_NONE, SIDEREON_IONEX_SLANT_ERROR_KIND_OUT_OF_COVERAGE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_LATITUDE_OUT_OF_RANGE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x400f492eb5dee898), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x400916c3ce302c22), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING }
};
static const SmokeBSlantPin SMOKE_B_IONEX_CASE_HOLD[] = {
    { true, SIDEREON_STATUS_OK, UINT64_C(0x400788254ae08283), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x401360b774bc13dd), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x40151975f892b743), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x40033ff22a448b8e), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x4011bf156788af16), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x40033ff22a448b8e), false, true, SIDEREON_IONEX_COVERAGE_ERROR_KIND_EPOCH_BEFORE_FIRST_MAP, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x4011bf156788af16), false, true, SIDEREON_IONEX_COVERAGE_ERROR_KIND_EPOCH_AFTER_LAST_MAP, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x40113fa3c9bde53f), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x4011410735dc2530), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x401a3a4be17d7a9b), false, true, SIDEREON_IONEX_COVERAGE_ERROR_KIND_LATITUDE_OUT_OF_RANGE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x400f492eb5dee898), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x400916c3ce302c22), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING }
};

#define SMOKE_B_IONEX_WARNING_COUNT ((size_t)8)
static const SidereonIonexWarningKind SMOKE_B_IONEX_WARNING_KIND[] = { SIDEREON_IONEX_WARNING_KIND_MISSING_RECORD, SIDEREON_IONEX_WARNING_KIND_MISSING_RECORD, SIDEREON_IONEX_WARNING_KIND_MISSING_RECORD, SIDEREON_IONEX_WARNING_KIND_MISSING_RECORD, SIDEREON_IONEX_WARNING_KIND_MISSING_RECORD, SIDEREON_IONEX_WARNING_KIND_MISSING_RECORD, SIDEREON_IONEX_WARNING_KIND_MISSING_RECORD, SIDEREON_IONEX_WARNING_KIND_MISSING_RECORD };
static const char *const SMOKE_B_IONEX_WARNING_LABEL[] = { "PGM / RUN BY / DATE", "EPOCH OF FIRST MAP", "EPOCH OF LAST MAP", "INTERVAL", "MAPPING FUNCTION", "ELEVATION CUTOFF", "OBSERVABLES USED", "END OF FILE" };
static const char *const SMOKE_B_IONEX_WARNING_MESSAGE[] = { "IONEX has no PGM / RUN BY / DATE record", "IONEX has no EPOCH OF FIRST MAP record", "IONEX has no EPOCH OF LAST MAP record", "IONEX has no INTERVAL record", "IONEX has no MAPPING FUNCTION record", "IONEX has no ELEVATION CUTOFF record", "IONEX has no OBSERVABLES USED record", "IONEX has no END OF FILE record" };
#define SMOKE_B_IONEX_GARBAGE_OK false
static const uint64_t SMOKE_B_IONEX_HEADER_VERSION_BITS = UINT64_C(0x3ff199999999999a);
#define SMOKE_B_IONEX_HEADER_DECLARATION SIDEREON_IONEX_MAPPING_DECLARATION_KIND_ABSENT
#define SMOKE_B_IONEX_HEADER_FUNCTION SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING
static const char SMOKE_B_IONEX_HEADER_MAPPING_CODE[] = "";
#define SMOKE_B_IONEX_INFO_EPOCH_COUNT ((size_t)2)
#define SMOKE_B_IONEX_INFO_LAT_COUNT ((size_t)7)
#define SMOKE_B_IONEX_INFO_LON_COUNT ((size_t)7)
#define SMOKE_B_IONEX_INFO_TEC_COUNT ((size_t)98)
#define SMOKE_B_IONEX_INFO_HAS_RMS false
#define SMOKE_B_IONEX_INFO_RMS_COUNT ((size_t)0)
#define SMOKE_B_IONEX_INFO_HAS_HEIGHT false
#define SMOKE_B_IONEX_INFO_HEIGHT_COUNT ((size_t)0)
#define SMOKE_B_IONEX_TEC_ALL_PRESENT true
#define SMOKE_B_IONEX_NODE_COUNT ((size_t)98)
#define SMOKE_B_IONEX_NODES_ALL_VTEC true
#define SMOKE_B_IONEX_NODES_ANY_RMS false
#define SMOKE_B_IONEX_NODES_ANY_HEIGHT false
#define SMOKE_B_IONEX_WRITER_OK true

#define SMOKE_B_IONEX_ROW_COUNT ((size_t)3)
static const SmokeBSlantPin SMOKE_B_IONEX_ROW[] = {
    { true, SIDEREON_STATUS_OK, UINT64_C(0x400788254ae08283), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { false, SIDEREON_STATUS_INVALID_ARGUMENT, UINT64_C(0), false, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, false, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_NONE, SIDEREON_IONEX_SLANT_ERROR_KIND_INVALID_INPUT, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING },
    { true, SIDEREON_STATUS_OK, UINT64_C(0x4007b0a8801e7e6d), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING }
};
static const SmokeBSlantPin SMOKE_B_IONEX_DECLARED = { false, SIDEREON_STATUS_SOLVE, UINT64_C(0), false, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, false, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_NONE, SIDEREON_IONEX_SLANT_ERROR_KIND_SLANT_UNAVAILABLE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_MAPPING_FUNCTION, 0, 0, 0, true, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_ABSENT, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING };

#define SMOKE_B_IONEX_GRID_PIERCE_OK true
static const uint64_t SMOKE_B_IONEX_GRID_PIERCE_VTEC_BITS = UINT64_C(0x401a400000000000);
static const SmokeBGapPin SMOKE_B_IONEX_GRID_PIERCE_GAP = { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } };
#define SMOKE_B_IONEX_GRID_NODE_OK true
static const uint64_t SMOKE_B_IONEX_GRID_NODE_VTEC_BITS = UINT64_C(0x402e000000000000);
static const SmokeBGapPin SMOKE_B_IONEX_GRID_NODE_GAP = { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } };
#define SMOKE_B_IONEX_GRID_SWAPPED_OK false
#define SMOKE_B_IONEX_GRID_SWAPPED_STATUS SIDEREON_STATUS_SOLVE
#define SMOKE_B_IONEX_GRID_SWAPPED_KIND SIDEREON_TEC_GRID_ERROR_KIND_OUT_OF_BOUNDS
static const SmokeBGapPin SMOKE_B_IONEX_GRID_SWAPPED_GAP = { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } };
#define SMOKE_B_IONEX_GRID_SWAPPED_AXIS SIDEREON_TEC_GRID_AXIS_LATITUDE
static const uint64_t SMOKE_B_IONEX_GRID_SWAPPED_AXIS_VALUE_BITS = UINT64_C(0x403e000000000000);
static const char SMOKE_B_IONEX_GRID_SWAPPED_MESSAGE[] = "latitude 30 is out of TEC grid bounds";
#define SMOKE_B_IONEX_GRID_NAN_LAT_OK false
#define SMOKE_B_IONEX_GRID_NAN_LAT_STATUS SIDEREON_STATUS_INVALID_ARGUMENT
#define SMOKE_B_IONEX_GRID_NAN_LAT_KIND SIDEREON_TEC_GRID_ERROR_KIND_INVALID_FIELD
static const SmokeBGapPin SMOKE_B_IONEX_GRID_NAN_LAT_GAP = { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } };
static const char SMOKE_B_IONEX_GRID_NAN_LAT_FIELD[] = "latitude";
static const char SMOKE_B_IONEX_GRID_NAN_LAT_REASON[] = "not finite";
static const char SMOKE_B_IONEX_GRID_NAN_LAT_MESSAGE[] = "latitude not finite";
#define SMOKE_B_IONEX_GRID_SPARSE_STRICT_OK false
#define SMOKE_B_IONEX_GRID_SPARSE_STRICT_STATUS SIDEREON_STATUS_SOLVE
#define SMOKE_B_IONEX_GRID_SPARSE_STRICT_KIND SIDEREON_TEC_GRID_ERROR_KIND_NODES_NOT_AVAILABLE
static const SmokeBGapPin SMOKE_B_IONEX_GRID_SPARSE_STRICT_GAP = { true, { true, 1, 0, 0, 1, { false, false, false, true } }, { false, 0, 0, 0, 0, { false, false, false, false } } };
static const char SMOKE_B_IONEX_GRID_SPARSE_STRICT_MESSAGE[] = "TEC grid nodes not available: map 1 cell [0][0] missing [1][1]";
#define SMOKE_B_IONEX_GRID_SPARSE_RENORMALIZE_OK true
static const uint64_t SMOKE_B_IONEX_GRID_SPARSE_RENORMALIZE_VTEC_BITS = UINT64_C(0x4014c92492492492);
static const SmokeBGapPin SMOKE_B_IONEX_GRID_SPARSE_RENORMALIZE_GAP = { true, { true, 1, 0, 0, 1, { false, false, false, true } }, { false, 0, 0, 0, 0, { false, false, false, false } } };

#define SMOKE_B_IONEX_UNIFORM_BUILD_OK true
static const SmokeBSlantPin SMOKE_B_IONEX_BLANK_CODE = { true, SIDEREON_STATUS_OK, UINT64_C(0x3ffa10ec31c84a96), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_OTHER, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING };
static const SmokeBSlantPin SMOKE_B_IONEX_BARE = { true, SIDEREON_STATUS_OK, UINT64_C(0x3ffa10ec31c84a96), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING };
static const bool SMOKE_B_IONEX_WRITER_CODE_OK[4] = { false, false, false, true };
static const char *const SMOKE_B_IONEX_WRITER_CODE_ERROR[4] = { "invalid input: IONEX MAPPING FUNCTION code \"\" cannot be written: the field holds a code of at most four characters other than a blank or a code the spec names", "invalid input: IONEX MAPPING FUNCTION code \"COSZ\" cannot be written: the field holds a code of at most four characters other than a blank or a code the spec names", "invalid input: IONEX MAPPING FUNCTION code \"ABCDE\" cannot be written: the field holds a code of at most four characters other than a blank or a code the spec names", "" };
static const SidereonStatus SMOKE_B_IONEX_WRITER_CODE_STATUS[4] = { SIDEREON_STATUS_INVALID_ARGUMENT, SIDEREON_STATUS_INVALID_ARGUMENT, SIDEREON_STATUS_INVALID_ARGUMENT, SIDEREON_STATUS_OK };
#define SMOKE_B_IONEX_ALL_MISSING_HEIGHT_HAS true
#define SMOKE_B_IONEX_ALL_MISSING_HEIGHT_COUNT ((size_t)8)
static const bool SMOKE_B_IONEX_ALL_MISSING_HEIGHT_PRESENT[] = { false, false, false, false, false, false, false, false };
#define SMOKE_B_IONEX_NO_HEIGHT_HAS false
static const SmokeBSlantPin SMOKE_B_IONEX_COMPLETE = { true, SIDEREON_STATUS_OK, UINT64_C(0x4007701d65cb59b0), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING };
static const SmokeBSlantPin SMOKE_B_IONEX_SPARSE_STRICT = { false, SIDEREON_STATUS_SOLVE, UINT64_C(0), false, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, false, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_NONE, SIDEREON_IONEX_SLANT_ERROR_KIND_NODES_NOT_AVAILABLE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, true, { true, { true, 1, 0, 0, 1, { true, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING };
static const SmokeBSlantPin SMOKE_B_IONEX_SPARSE_RENORMALIZE = { true, SIDEREON_STATUS_OK, UINT64_C(0x400817da21b8b67c), false, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, true, { true, { true, 1, 0, 0, 1, { true, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING };
static const SmokeBSlantPin SMOKE_B_IONEX_HEIGHTED = { true, SIDEREON_STATUS_OK, UINT64_C(0x4007701d65cb59b0), true, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, true, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_ABSENT, SIDEREON_IONEX_SLANT_ERROR_KIND_NONE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_NONE, 0, 0, 0, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING };
static const SmokeBSlantPin SMOKE_B_IONEX_UNKNOWN_HEIGHT = { false, SIDEREON_STATUS_SOLVE, UINT64_C(0), false, false, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, false, SIDEREON_IONEX_ASSUMED_MAPPING_KIND_NONE, SIDEREON_IONEX_SLANT_ERROR_KIND_SLANT_UNAVAILABLE, SIDEREON_IONEX_COVERAGE_ERROR_KIND_NONE, false, { false, { false, 0, 0, 0, 0, { false, false, false, false } }, { false, 0, 0, 0, 0, { false, false, false, false } } }, SIDEREON_IONEX_SLANT_REFUSAL_KIND_HEIGHT_NOT_AVAILABLE, 1, 0, 1, false, SIDEREON_IONEX_MAPPING_DECLARATION_KIND_DECLARED, false, SIDEREON_IONEX_MAPPING_FUNCTION_KIND_NO_MAPPING };
#define SMOKE_B_IONEX_FAR_BUILD_OK true
#define SMOKE_B_IONEX_FAR_EPOCH0 INT64_C(9007199254740993)
#define SMOKE_B_IONEX_FAR_EPOCH1 INT64_C(9007199254744593)


#endif /* SIDEREON_SMOKE_B_IONEX_PINS_H */
