/* sidereon-core revision 8694648892d8ab065d94014e2e21d6cd5054818e */
/* Generated by tests/valgen (bin smoke_a_tec_grid) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_A_TEC_GRID_PINS_H
#define SIDEREON_SMOKE_A_TEC_GRID_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Latitude axis [80, 89]: queries at 89, 87.5, +inf, -inf and NaN degrees. */
#define SMOKE_A_TEC_GRID_LAT_89_OK true
static const uint64_t SMOKE_A_TEC_GRID_LAT_89_VTEC_BITS = UINT64_C(0x4018000000000001);
#define SMOKE_A_TEC_GRID_LAT_89_HAS_GAP false
static const char SMOKE_A_TEC_GRID_LAT_89_ERROR[] = "";
static const char SMOKE_A_TEC_GRID_LAT_89_AXIS[] = "";
static const uint64_t SMOKE_A_TEC_GRID_LAT_89_AXIS_VALUE_BITS = UINT64_C(0x0000000000000000);
static const char SMOKE_A_TEC_GRID_LAT_89_FIELD[] = "";
static const char SMOKE_A_TEC_GRID_LAT_89_REASON[] = "";
#define SMOKE_A_TEC_GRID_LAT_87_5_OK true
static const uint64_t SMOKE_A_TEC_GRID_LAT_87_5_VTEC_BITS = UINT64_C(0x4018000000000001);
#define SMOKE_A_TEC_GRID_LAT_87_5_HAS_GAP false
static const char SMOKE_A_TEC_GRID_LAT_87_5_ERROR[] = "";
static const char SMOKE_A_TEC_GRID_LAT_87_5_AXIS[] = "";
static const uint64_t SMOKE_A_TEC_GRID_LAT_87_5_AXIS_VALUE_BITS = UINT64_C(0x0000000000000000);
static const char SMOKE_A_TEC_GRID_LAT_87_5_FIELD[] = "";
static const char SMOKE_A_TEC_GRID_LAT_87_5_REASON[] = "";
#define SMOKE_A_TEC_GRID_LAT_PLUS_INF_OK true
static const uint64_t SMOKE_A_TEC_GRID_LAT_PLUS_INF_VTEC_BITS = UINT64_C(0x4018000000000001);
#define SMOKE_A_TEC_GRID_LAT_PLUS_INF_HAS_GAP false
static const char SMOKE_A_TEC_GRID_LAT_PLUS_INF_ERROR[] = "";
static const char SMOKE_A_TEC_GRID_LAT_PLUS_INF_AXIS[] = "";
static const uint64_t SMOKE_A_TEC_GRID_LAT_PLUS_INF_AXIS_VALUE_BITS = UINT64_C(0x0000000000000000);
static const char SMOKE_A_TEC_GRID_LAT_PLUS_INF_FIELD[] = "";
static const char SMOKE_A_TEC_GRID_LAT_PLUS_INF_REASON[] = "";
#define SMOKE_A_TEC_GRID_LAT_MINUS_INF_OK false
static const uint64_t SMOKE_A_TEC_GRID_LAT_MINUS_INF_VTEC_BITS = UINT64_C(0x7ff8000000000000);
#define SMOKE_A_TEC_GRID_LAT_MINUS_INF_HAS_GAP false
static const char SMOKE_A_TEC_GRID_LAT_MINUS_INF_ERROR[] = "OutOfBounds";
static const char SMOKE_A_TEC_GRID_LAT_MINUS_INF_AXIS[] = "latitude";
static const uint64_t SMOKE_A_TEC_GRID_LAT_MINUS_INF_AXIS_VALUE_BITS = UINT64_C(0xc055e00000000000);
static const char SMOKE_A_TEC_GRID_LAT_MINUS_INF_FIELD[] = "";
static const char SMOKE_A_TEC_GRID_LAT_MINUS_INF_REASON[] = "";
#define SMOKE_A_TEC_GRID_LAT_NAN_OK false
static const uint64_t SMOKE_A_TEC_GRID_LAT_NAN_VTEC_BITS = UINT64_C(0x7ff8000000000000);
#define SMOKE_A_TEC_GRID_LAT_NAN_HAS_GAP false
static const char SMOKE_A_TEC_GRID_LAT_NAN_ERROR[] = "InvalidField";
static const char SMOKE_A_TEC_GRID_LAT_NAN_AXIS[] = "";
static const uint64_t SMOKE_A_TEC_GRID_LAT_NAN_AXIS_VALUE_BITS = UINT64_C(0x0000000000000000);
static const char SMOKE_A_TEC_GRID_LAT_NAN_FIELD[] = "latitude";
static const char SMOKE_A_TEC_GRID_LAT_NAN_REASON[] = "not finite";
/* Latitude axis [80, 85]: a query at 89 degrees. */
#define SMOKE_A_TEC_GRID_NARROW_LAT_89_OK false
static const uint64_t SMOKE_A_TEC_GRID_NARROW_LAT_89_VTEC_BITS = UINT64_C(0x7ff8000000000000);
#define SMOKE_A_TEC_GRID_NARROW_LAT_89_HAS_GAP false
static const char SMOKE_A_TEC_GRID_NARROW_LAT_89_ERROR[] = "OutOfBounds";
static const char SMOKE_A_TEC_GRID_NARROW_LAT_89_AXIS[] = "latitude";
static const uint64_t SMOKE_A_TEC_GRID_NARROW_LAT_89_AXIS_VALUE_BITS = UINT64_C(0x4055e00000000000);
static const char SMOKE_A_TEC_GRID_NARROW_LAT_89_FIELD[] = "";
static const char SMOKE_A_TEC_GRID_NARROW_LAT_89_REASON[] = "";

#endif /* SIDEREON_SMOKE_A_TEC_GRID_PINS_H */
