/* sidereon-core revision e2fb3dfdc392d23087ed8aa1ee028a0056b4021b */
/* Generated by tests/valgen (bin smoke_a_ppp) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_A_PPP_PINS_H
#define SIDEREON_SMOKE_A_PPP_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* solve_float_epochs of fixtures/ppp_esbc.json under the smoke's float config. */
#define SMOKE_A_PPP_FLOAT_ITERATIONS ((size_t)3)
#define SMOKE_A_PPP_FLOAT_CONVERGED true
#define SMOKE_A_PPP_FLOAT_STATUS "StateTolerance"
#define SMOKE_A_PPP_FLOAT_HAS_ZTD_RESIDUAL false
static const uint64_t SMOKE_A_PPP_FLOAT_CODE_RMS_BITS = UINT64_C(0x4018702f8d0312d7);
static const uint64_t SMOKE_A_PPP_FLOAT_PHASE_RMS_BITS = UINT64_C(0x3fea5557231cd41a);
static const uint64_t SMOKE_A_PPP_FLOAT_WEIGHTED_RMS_BITS = UINT64_C(0x404d2cb2b850783d);
#define SMOKE_A_PPP_FLOAT_AMBIGUITY_COUNT ((size_t)12)
#define SMOKE_A_PPP_FLOAT_RESIDUAL_COUNT ((size_t)1282)
#define SMOKE_A_PPP_FLOAT_USED_SAT_COUNT ((size_t)12)
static const uint64_t SMOKE_A_PPP_FLOAT_AMBIGUITY_BITS[12] = { UINT64_C(0x3ff90211d0f28233), UINT64_C(0xc024a94a8dec40d4), UINT64_C(0x3fd7ceefe2f29aba), UINT64_C(0xc01546f60df83172), UINT64_C(0xbfdafacd016a287b), UINT64_C(0xc00830b8a2dc57da), UINT64_C(0x400f35641f149ef6), UINT64_C(0x3ff8e8fc6f19bbfa), UINT64_C(0x401b077d3c67215b), UINT64_C(0x400a51286931a00d), UINT64_C(0x402581a7d115f01f), UINT64_C(0xc019caee0a29d306) };
/* solve_fixed_from_float of that float solution under the fixed config. */
#define SMOKE_A_PPP_FIXED_ITERATIONS ((size_t)2)
#define SMOKE_A_PPP_FIXED_CONVERGED true
#define SMOKE_A_PPP_FIXED_STATUS "StateTolerance"
#define SMOKE_A_PPP_FIXED_HAS_ZTD_RESIDUAL false
static const uint64_t SMOKE_A_PPP_FIXED_CODE_RMS_BITS = UINT64_C(0x401856fe13753fee);
static const uint64_t SMOKE_A_PPP_FIXED_PHASE_RMS_BITS = UINT64_C(0x3fea56954452534a);
static const uint64_t SMOKE_A_PPP_FIXED_WEIGHTED_RMS_BITS = UINT64_C(0x404d2de720d2bc70);
#define SMOKE_A_PPP_FIXED_RESIDUAL_COUNT ((size_t)1282)
#define SMOKE_A_PPP_FIXED_USED_SAT_COUNT ((size_t)12)
static const uint64_t SMOKE_A_PPP_FIXED_INTEGER_BEST_SCORE_BITS = UINT64_C(0x40a62cb1e9657781);
#define SMOKE_A_PPP_FIXED_HAS_INTEGER_SECOND_BEST_SCORE true
static const uint64_t SMOKE_A_PPP_FIXED_INTEGER_SECOND_BEST_SCORE_BITS = UINT64_C(0x40a6438bae167a04);
/* The same float solve with the smoke's VMF1 site series. */
static const uint64_t SMOKE_A_PPP_VMF1_POSITION_BITS[3] = { UINT64_C(0x414b544c2768ade2), UINT64_C(0x412040d6d6c72141), UINT64_C(0x4153f61c53844c8c) };
/* VmfSiteSeries::new of the smoke's non-ascending samples. */
#define SMOKE_A_PPP_VMF_UNSORTED_REFUSED true
static const char SMOKE_A_PPP_VMF_UNSORTED_ERROR_TEXT[] = "invalid input: vmf site series mjd not strictly increasing";

#endif /* SIDEREON_SMOKE_A_PPP_PINS_H */
