/* sidereon-core revision 47eaf24e39afa71168670664e88361ed41011bc2 */
/* Generated by tests/valgen (bin smoke_a_ionex) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_A_IONEX_PINS_H
#define SIDEREON_SMOKE_A_IONEX_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* exercise_ionex_rms_presence_distinction: RMS maps left out, then all absent. */
#define SMOKE_A_IONEX_NO_RMS_HAS_RMS_MAPS false
#define SMOKE_A_IONEX_NO_RMS_RMS_VALUE_COUNT ((size_t)0)
#define SMOKE_A_IONEX_MISSING_RMS_HAS_RMS_MAPS true
#define SMOKE_A_IONEX_MISSING_RMS_RMS_VALUE_COUNT ((size_t)8)
static const bool SMOKE_A_IONEX_MISSING_RMS_PRESENCE[8] = { false, false, false, false, false, false, false, false };
/* exercise_ionex_owned_mapping_code_lifetime: a header declaring SLAB_3D_CUSTOM. */
#define SMOKE_A_IONEX_CUSTOM_ROW_OK true
static const uint64_t SMOKE_A_IONEX_CUSTOM_ROW_DELAY_BITS = UINT64_C(0x3ffa10ec31c84a96);
#define SMOKE_A_IONEX_CUSTOM_ROW_IS_VALID true
#define SMOKE_A_IONEX_CUSTOM_ROW_HAS_HELD false
#define SMOKE_A_IONEX_CUSTOM_ROW_HAS_DEGRADED false
#define SMOKE_A_IONEX_CUSTOM_ROW_HAS_ASSUMED_MAPPING true
static const char SMOKE_A_IONEX_CUSTOM_ROW_ASSUMED_MAPPING[] = "Other";
static const char SMOKE_A_IONEX_CUSTOM_ROW_ERROR[] = "";
static const char SMOKE_A_IONEX_CUSTOM_ROW_REFUSAL[] = "";
static const char SMOKE_A_IONEX_CUSTOM_ROW_DECLARATION[] = "";
static const char SMOKE_A_IONEX_CUSTOM_ROW_DECLARED_FUNCTION[] = "";
/* exercise_ionex_undeclared_default_header: no header, then a declared COSZ. */
#define SMOKE_A_IONEX_BARE_HEADER_DECLARED false
static const char SMOKE_A_IONEX_BARE_HEADER_FUNCTION[] = "";
static const char SMOKE_A_IONEX_BARE_HEADER_CODE[] = "";
#define SMOKE_A_IONEX_BARE_SINGLE_LAYER_OK true
static const uint64_t SMOKE_A_IONEX_BARE_SINGLE_LAYER_DELAY_BITS = UINT64_C(0x3ffa10ec31c84a96);
#define SMOKE_A_IONEX_BARE_SINGLE_LAYER_IS_VALID true
#define SMOKE_A_IONEX_BARE_SINGLE_LAYER_HAS_HELD false
#define SMOKE_A_IONEX_BARE_SINGLE_LAYER_HAS_DEGRADED false
#define SMOKE_A_IONEX_BARE_SINGLE_LAYER_HAS_ASSUMED_MAPPING true
static const char SMOKE_A_IONEX_BARE_SINGLE_LAYER_ASSUMED_MAPPING[] = "Absent";
static const char SMOKE_A_IONEX_BARE_SINGLE_LAYER_ERROR[] = "";
static const char SMOKE_A_IONEX_BARE_SINGLE_LAYER_REFUSAL[] = "";
static const char SMOKE_A_IONEX_BARE_SINGLE_LAYER_DECLARATION[] = "";
static const char SMOKE_A_IONEX_BARE_SINGLE_LAYER_DECLARED_FUNCTION[] = "";
#define SMOKE_A_IONEX_BARE_DECLARED_OK false
static const uint64_t SMOKE_A_IONEX_BARE_DECLARED_DELAY_BITS = UINT64_C(0x7ff8000000000000);
#define SMOKE_A_IONEX_BARE_DECLARED_IS_VALID false
#define SMOKE_A_IONEX_BARE_DECLARED_HAS_HELD false
#define SMOKE_A_IONEX_BARE_DECLARED_HAS_DEGRADED false
#define SMOKE_A_IONEX_BARE_DECLARED_HAS_ASSUMED_MAPPING false
static const char SMOKE_A_IONEX_BARE_DECLARED_ASSUMED_MAPPING[] = "";
static const char SMOKE_A_IONEX_BARE_DECLARED_ERROR[] = "IonexSlantUnavailable";
static const char SMOKE_A_IONEX_BARE_DECLARED_REFUSAL[] = "MappingFunction";
static const char SMOKE_A_IONEX_BARE_DECLARED_DECLARATION[] = "Absent";
static const char SMOKE_A_IONEX_BARE_DECLARED_DECLARED_FUNCTION[] = "";
#define SMOKE_A_IONEX_BARE_TEXT_MAPPING_RECORD true
static const char SMOKE_A_IONEX_BARE_TEXT_MAPPING_FIELD[] = "";
#define SMOKE_A_IONEX_BARE_TEXT_REPARSED_DECLARED false
static const char SMOKE_A_IONEX_BARE_TEXT_REPARSED_FUNCTION[] = "";
static const char SMOKE_A_IONEX_BARE_TEXT_REPARSED_CODE[] = "";
#define SMOKE_A_IONEX_COSZ_SINGLE_LAYER_OK true
static const uint64_t SMOKE_A_IONEX_COSZ_SINGLE_LAYER_DELAY_BITS = UINT64_C(0x3ffa10ec31c84a96);
#define SMOKE_A_IONEX_COSZ_SINGLE_LAYER_IS_VALID true
#define SMOKE_A_IONEX_COSZ_SINGLE_LAYER_HAS_HELD false
#define SMOKE_A_IONEX_COSZ_SINGLE_LAYER_HAS_DEGRADED false
#define SMOKE_A_IONEX_COSZ_SINGLE_LAYER_HAS_ASSUMED_MAPPING false
static const char SMOKE_A_IONEX_COSZ_SINGLE_LAYER_ASSUMED_MAPPING[] = "";
static const char SMOKE_A_IONEX_COSZ_SINGLE_LAYER_ERROR[] = "";
static const char SMOKE_A_IONEX_COSZ_SINGLE_LAYER_REFUSAL[] = "";
static const char SMOKE_A_IONEX_COSZ_SINGLE_LAYER_DECLARATION[] = "";
static const char SMOKE_A_IONEX_COSZ_SINGLE_LAYER_DECLARED_FUNCTION[] = "";
#define SMOKE_A_IONEX_COSZ_DECLARED_OK true
static const uint64_t SMOKE_A_IONEX_COSZ_DECLARED_DELAY_BITS = UINT64_C(0x3ffa10ec31c84a96);
#define SMOKE_A_IONEX_COSZ_DECLARED_IS_VALID true
#define SMOKE_A_IONEX_COSZ_DECLARED_HAS_HELD false
#define SMOKE_A_IONEX_COSZ_DECLARED_HAS_DEGRADED false
#define SMOKE_A_IONEX_COSZ_DECLARED_HAS_ASSUMED_MAPPING false
static const char SMOKE_A_IONEX_COSZ_DECLARED_ASSUMED_MAPPING[] = "";
static const char SMOKE_A_IONEX_COSZ_DECLARED_ERROR[] = "";
static const char SMOKE_A_IONEX_COSZ_DECLARED_REFUSAL[] = "";
static const char SMOKE_A_IONEX_COSZ_DECLARED_DECLARATION[] = "";
static const char SMOKE_A_IONEX_COSZ_DECLARED_DECLARED_FUNCTION[] = "";
#define SMOKE_A_IONEX_COSZ_TEXT_MAPPING_RECORD true
static const char SMOKE_A_IONEX_COSZ_TEXT_MAPPING_FIELD[] = "COSZ";
#define SMOKE_A_IONEX_COSZ_TEXT_REPARSED_DECLARED true
static const char SMOKE_A_IONEX_COSZ_TEXT_REPARSED_FUNCTION[] = "CosZ";
static const char SMOKE_A_IONEX_COSZ_TEXT_REPARSED_CODE[] = "COSZ";

#endif /* SIDEREON_SMOKE_A_IONEX_PINS_H */
