/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/valgen (bin smoke_b_tle) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_B_TLE_PINS_H
#define SIDEREON_SMOKE_B_TLE_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

static const char SMOKE_B_TLE_ISS_L1[] = "1 25544U 98067A   18184.80969102  .00001614  00000-0  31745-4 0  9993";
static const char SMOKE_B_TLE_ISS_L2[] = "2 25544  51.6414 295.8524 0003435 262.6267 204.2868 15.54005638121106";
#define SMOKE_B_TLE_COUNT ((size_t)2)
#define SMOKE_B_TLE_SKIPPED ((size_t)1)
#define SMOKE_B_TLE_REJECTED0_LINE ((size_t)7)
#define SMOKE_B_TLE_REJECTED0_ISSUE SIDEREON_TLE_RECORD_ISSUE_INVALID
static const char SMOKE_B_TLE_REJECTED0_ERROR[] = "invalid TLE: TLE format error: line does not match the Two-Line Element fixed-width format";
#define SMOKE_B_TLE_RECORD0_LINE ((size_t)2)
static const char SMOKE_B_TLE_RECORD0_NAME[] = "ISS (ZARYA)";
static const char SMOKE_B_TLE_RECORD1_NAME[] = "";
#define SMOKE_B_TLE_LOOK_UNIX_US INT64_C(1530645960000000)
#define SMOKE_B_TLE_LOOK_COUNT ((size_t)1)
static const uint64_t SMOKE_B_TLE_LOOK_BITS[3] = { UINT64_C(0x40735aa63657ae90), UINT64_C(0xc03a3e7de579ae2b), UINT64_C(0x40b956a7918d8577) };

#endif /* SIDEREON_SMOKE_B_TLE_PINS_H */
