/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/valgen (bin smoke_a_spk) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_A_SPK_PINS_H
#define SIDEREON_SMOKE_A_SPK_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Spk::spk_state(target, center, et) at each SPK_REFERENCE epoch. */
#define SMOKE_A_SPK_STATE_COUNT ((size_t)11)
static const uint64_t SMOKE_A_SPK_POSITION_KM_BITS[33] = { UINT64_C(0x41a79d0864ac7e10), UINT64_C(0x418ad955900b986b), UINT64_C(0x419027cdf01dc422), UINT64_C(0x41a710ab0c571398), UINT64_C(0x418da7ab594a53bb), UINT64_C(0x4190c1044a74a8f9), UINT64_C(0x41a0c2c1bacbe6b2), UINT64_C(0x419a428f39f41f75), UINT64_C(0x4194f7935506489f), UINT64_C(0x416b52794f29a4c1), UINT64_C(0x41a21a430df06bc3), UINT64_C(0x41952c81726c1462), UINT64_C(0xc18dc8ff421c251c), UINT64_C(0x41a0f5fd2e9630d2), UINT64_C(0x419091b61a686449), UINT64_C(0xc1a445c4adf1651e), UINT64_C(0x4188c343d9e9c614), UINT64_C(0xc132fa62dcc3f5f4), UINT64_C(0xc1a4e88e1d89ffdb), UINT64_C(0xc1919a9f61eef16c), UINT64_C(0xc1918d3069a0cbc6), UINT64_C(0xc1a17c11c181b2bb), UINT64_C(0xc19e99fd9b7f8a13), UINT64_C(0xc197b1a2eda673c2), UINT64_C(0xc18f5de9f29b2ec0), UINT64_C(0xc1a78a4f6d4911dc), UINT64_C(0xc19d90b57c61b6f7), UINT64_C(0xc160e60d63e99d91), UINT64_C(0xc1aa239a778158f4), UINT64_C(0xc19e105d2a76c9e9), UINT64_C(0xc1427cfb3e915c67), UINT64_C(0xc1aa51d7b43ff443), UINT64_C(0xc19dfde0dc8fc8c0) };
static const uint64_t SMOKE_A_SPK_VELOCITY_KM_S_BITS[33] = { UINT64_C(0xc02c461540c8bf18), UINT64_C(0x4032baddb12f1db8), UINT64_C(0x40202941e7b93402), UINT64_C(0xc02de8068579c4b4), UINT64_C(0x40327b9ec3cfd0db), UINT64_C(0x401f2bd07cdaa488), UINT64_C(0xc0361c49c2ba0ccf), UINT64_C(0x402d751162cbe772), UINT64_C(0x4011788349d1d1de), UINT64_C(0xc03d8b0b5298d017), UINT64_C(0x3ff6264bbe8e2eea), UINT64_C(0xc01235985601606c), UINT64_C(0xc03bd6c82f2511ed), UINT64_C(0xc02174d884d1212a), UINT64_C(0xc023f8f3de7bc2c0), UINT64_C(0xc025c9deb2e5640c), UINT64_C(0xc0372ba27d478428), UINT64_C(0xc02e3fb2dee159fc), UINT64_C(0x401ebd78146044e3), UINT64_C(0xc03674d876b952f2), UINT64_C(0xc026b9284523512c), UINT64_C(0x402b7316bc0d6836), UINT64_C(0xc032b64ea605f16e), UINT64_C(0xc02049dbf28ee6af), UINT64_C(0x403366175b20cdc9), UINT64_C(0xc0248961f8736f6e), UINT64_C(0xc00298cd8f441d42), UINT64_C(0x40345871ea86e671), UINT64_C(0xc0144c837868aa05), UINT64_C(0x3fe97384510dd382), UINT64_C(0x40345c299331a45e), UINT64_C(0xc01208d832a94458), UINT64_C(0x3ff1e907227420d4) };
/* Spk::from_bytes of smoke.c's 64 bytes of 0xAB. */
#define SMOKE_A_SPK_GARBAGE_REFUSED true
static const char SMOKE_A_SPK_GARBAGE_ERROR_TEXT[] = "truncated SPK/DAF input while reading DAF file record: need 1024 bytes, have 64";
/* Spk::spk_state at a NaN epoch. */
#define SMOKE_A_SPK_NAN_REFUSED true
static const char SMOKE_A_SPK_NAN_ERROR_TEXT[] = "invalid SPK field ET: NaN";

#endif /* SIDEREON_SMOKE_A_SPK_PINS_H */
