/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/valgen (bin smoke_a_prop) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_A_PROP_PINS_H
#define SIDEREON_SMOKE_A_PROP_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* tle::parse_with_policy under the strict policy sidereon_tle_load applies. */
#define SMOKE_A_PROP_CLEAN_CHECKSUM_WARNING_COUNT ((size_t)0)
#define SMOKE_A_PROP_BAD_CHECKSUM_STRICT_REFUSED true
static const char SMOKE_A_PROP_BAD_CHECKSUM_STRICT_ERROR_TEXT[] = "TLE line 1 checksum digit 0 does not match the computed checksum 3";
#define SMOKE_A_PROP_NOT_A_TLE_REFUSED true
static const char SMOKE_A_PROP_NOT_A_TLE_ERROR_TEXT[] = "TLE format error: line does not match the Two-Line Element fixed-width format";
/* find_passes_for_satellite over the smoke's window with its options. */
#define SMOKE_A_PROP_PASS_COUNT ((size_t)6)
static const uint64_t SMOKE_A_PROP_PASS_MAX_ELEVATION_BITS[6] = { UINT64_C(0x40213c92daf70622), UINT64_C(0x40422d853524b593), UINT64_C(0x40561f393bd7494a), UINT64_C(0x4053c418a8d87584), UINT64_C(0x403b3c9a628f188e), UINT64_C(0x401440bbc090ea05) };

#endif /* SIDEREON_SMOKE_A_PROP_PINS_H */
