/* sidereon-core revision 8694648892d8ab065d94014e2e21d6cd5054818e */
/* Generated by tests/valgen (bin smoke_a_rtk) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_A_RTK_PINS_H
#define SIDEREON_SMOKE_A_RTK_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* sidereon_core::rtk_filter::solve_float_baseline of rtk_fixture.h's float inputs. */
#define SMOKE_A_RTK_FLOAT_CONVERGED true
#define SMOKE_A_RTK_FLOAT_STATUS "StateTolerance"
#define SMOKE_A_RTK_FLOAT_RESIDUAL_COUNT ((size_t)4)
#define SMOKE_A_RTK_FLOAT_USED_SAT_COUNT ((size_t)4)
#define SMOKE_A_RTK_FLOAT_GEOMETRY_TIER "Nominal"
static const uint64_t SMOKE_A_RTK_FLOAT_GEOMETRY_CONDITION_NUMBER_BITS = UINT64_C(0x401ecf045ce665c8);
static const uint64_t SMOKE_A_RTK_FLOAT_GEOMETRY_GDOP_BITS = UINT64_C(0x4001625e69e6e048);
#define SMOKE_A_RTK_FLOAT_GEOMETRY_RAIM_CHECKABLE true
#define SMOKE_A_RTK_FLOAT_GEOMETRY_COVARIANCE_VALIDATED true
/* solve_fixed_baseline_validated of rtk_fixture.h's fixed inputs. */
#define SMOKE_A_RTK_FIXED_CONVERGED true
#define SMOKE_A_RTK_FIXED_STATUS "StateTolerance"
#define SMOKE_A_RTK_FIXED_RESIDUAL_COUNT ((size_t)4)
#define SMOKE_A_RTK_FIXED_USED_SAT_COUNT ((size_t)4)
#define SMOKE_A_RTK_FIXED_INTEGER_STATUS "Fixed"
#define SMOKE_A_RTK_FIXED_HAS_INTEGER_RATIO true
#define SMOKE_A_RTK_FIXED_HAS_INTEGER_BEST_SCORE true
#define SMOKE_A_RTK_FIXED_HAS_INTEGER_SECOND_BEST_SCORE true
#define SMOKE_A_RTK_FIXED_GEOMETRY_TIER "Nominal"
static const uint64_t SMOKE_A_RTK_FIXED_GEOMETRY_CONDITION_NUMBER_BITS = UINT64_C(0x401ecf045ce665cf);
static const uint64_t SMOKE_A_RTK_FIXED_GEOMETRY_GDOP_BITS = UINT64_C(0x4001625e69e6ba65);
#define SMOKE_A_RTK_FIXED_GEOMETRY_RAIM_CHECKABLE true
#define SMOKE_A_RTK_FIXED_GEOMETRY_COVARIANCE_VALIDATED true
/* The singular-geometry float solve: the engine's refusal and its text. */
#define SMOKE_A_RTK_SINGULAR_REFUSED true
static const char SMOKE_A_RTK_SINGULAR_ERROR_TEXT[] = "RTK float geometry is singular";

#endif /* SIDEREON_SMOKE_A_RTK_PINS_H */
