/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/valgen (bin smoke_a_glonass) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_A_GLONASS_PINS_H
#define SIDEREON_SMOKE_A_GLONASS_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* The scenario the smoke passes to sidereon_solve_spp_v2. */
static const uint64_t SMOKE_A_GLONASS_T_RX_BITS = UINT64_C(0x41c342aa00000000);
static const uint64_t SMOKE_A_GLONASS_RX_BITS[3] = { UINT64_C(0x4145be30b60edac9), UINT64_C(0x4140c1a3c1537c4d), UINT64_C(0x415405f80bff3387) };
#define SMOKE_A_GLONASS_SAT_COUNT ((size_t)8)
static const char *const SMOKE_A_GLONASS_SAT_IDS[8] = { "R01", "R02", "R03", "R09", "R16", "R17", "R18", "R19" };
static const uint64_t SMOKE_A_GLONASS_PSEUDORANGE_BITS[8] = { UINT64_C(0x417510b3c83c8db9), UINT64_C(0x4173552d3baa4172), UINT64_C(0x4175f1fcaa7b53fc), UINT64_C(0x417562c5373dc4e1), UINT64_C(0x4174ee52128fd1c6), UINT64_C(0x4172c75098cd4ef1), UINT64_C(0x4172e6ac5cd069c3), UINT64_C(0x417646a2fc2593c2) };
static const uint8_t SMOKE_A_GLONASS_SLOTS[8] = { 1, 2, 3, 9, 16, 17, 18, 19 };
/* Ionosphere off, no channel map. */
static const uint64_t SMOKE_A_GLONASS_OFF_POSITION_BITS[3] = { UINT64_C(0x4145be39d7a3f516), UINT64_C(0x4140c199c5c76580), UINT64_C(0x415405ead2fee6a3) };
#define SMOKE_A_GLONASS_OFF_USED_COUNT ((size_t)8)
static const char *const SMOKE_A_GLONASS_OFF_USED_IDS[8] = { "R01", "R02", "R03", "R09", "R16", "R17", "R18", "R19" };
#define SMOKE_A_GLONASS_OFF_TDOP_COUNT ((size_t)1)
static const char *const SMOKE_A_GLONASS_OFF_TDOP_SYSTEMS[1] = { "Glonass" };
static const uint64_t SMOKE_A_GLONASS_OFF_TDOP_BITS[1] = { UINT64_C(0x3fee2042143858a7) };
#define SMOKE_A_GLONASS_OFF_HAS_DOP true
static const uint64_t SMOKE_A_GLONASS_OFF_DOP_TDOP_BITS = UINT64_C(0x3fee2042143858a7);
#define SMOKE_A_GLONASS_OFF_REJECTED_COUNT ((size_t)0)
static const char *const SMOKE_A_GLONASS_OFF_REJECTED_IDS[1] = { "" };
static const char *const SMOKE_A_GLONASS_OFF_REJECTED_REASONS[1] = { "" };
/* Ionosphere on, no channel map. */
#define SMOKE_A_GLONASS_GATED_REFUSED true
static const char SMOKE_A_GLONASS_GATED_ERROR_TEXT[] = "SPP solve failed: only 0 usable satellites; need at least 4 (3 position + 1 clock per GNSS)";
/* Ionosphere on, every channel 0. */
static const uint64_t SMOKE_A_GLONASS_ON_POSITION_BITS[3] = { UINT64_C(0x4145be3ab9ed76c2), UINT64_C(0x4140c19a67c2fc26), UINT64_C(0x415405ebb4f3cd4e) };
#define SMOKE_A_GLONASS_ON_USED_COUNT ((size_t)8)
static const char *const SMOKE_A_GLONASS_ON_USED_IDS[8] = { "R01", "R02", "R03", "R09", "R16", "R17", "R18", "R19" };
#define SMOKE_A_GLONASS_ON_TDOP_COUNT ((size_t)1)
static const char *const SMOKE_A_GLONASS_ON_TDOP_SYSTEMS[1] = { "Glonass" };
static const uint64_t SMOKE_A_GLONASS_ON_TDOP_BITS[1] = { UINT64_C(0x3fee20415e1d002e) };
#define SMOKE_A_GLONASS_ON_HAS_DOP true
static const uint64_t SMOKE_A_GLONASS_ON_DOP_TDOP_BITS = UINT64_C(0x3fee20415e1d002e);
#define SMOKE_A_GLONASS_ON_REJECTED_COUNT ((size_t)0)
static const char *const SMOKE_A_GLONASS_ON_REJECTED_IDS[1] = { "" };
static const char *const SMOKE_A_GLONASS_ON_REJECTED_REASONS[1] = { "" };
/* Ionosphere on, the first used satellite's channel withheld. */
static const char SMOKE_A_GLONASS_WITHHELD_ID[] = "R01";
#define SMOKE_A_GLONASS_PARTIAL_REFUSED false
static const char SMOKE_A_GLONASS_PARTIAL_ERROR_TEXT[] = "";
static const uint64_t SMOKE_A_GLONASS_PARTIAL_POSITION_BITS[3] = { UINT64_C(0x4145be1c1c0e9dd3), UINT64_C(0x4140c195409ae848), UINT64_C(0x415405e62c8e35ee) };
#define SMOKE_A_GLONASS_PARTIAL_USED_COUNT ((size_t)7)
static const char *const SMOKE_A_GLONASS_PARTIAL_USED_IDS[7] = { "R02", "R03", "R09", "R16", "R17", "R18", "R19" };
#define SMOKE_A_GLONASS_PARTIAL_TDOP_COUNT ((size_t)1)
static const char *const SMOKE_A_GLONASS_PARTIAL_TDOP_SYSTEMS[1] = { "Glonass" };
static const uint64_t SMOKE_A_GLONASS_PARTIAL_TDOP_BITS[1] = { UINT64_C(0x3ff28c631df38931) };
#define SMOKE_A_GLONASS_PARTIAL_HAS_DOP true
static const uint64_t SMOKE_A_GLONASS_PARTIAL_DOP_TDOP_BITS = UINT64_C(0x3ff28c631df38931);
#define SMOKE_A_GLONASS_PARTIAL_REJECTED_COUNT ((size_t)1)
static const char *const SMOKE_A_GLONASS_PARTIAL_REJECTED_IDS[1] = { "R01" };
static const char *const SMOKE_A_GLONASS_PARTIAL_REJECTED_REASONS[1] = { "IonosphereCarrierUnresolved" };
/* Ionosphere on, every channel 9 (outside the FDMA allocation). */
#define SMOKE_A_GLONASS_BAD_CHANNEL_REFUSED true
static const char SMOKE_A_GLONASS_BAD_CHANNEL_ERROR_TEXT[] = "SPP solve failed: only 0 usable satellites; need at least 4 (3 position + 1 clock per GNSS)";

#endif /* SIDEREON_SMOKE_A_GLONASS_PINS_H */
