/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/valgen (bin smoke_b_geometry) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_B_GEOMETRY_PINS_H
#define SIDEREON_SMOKE_B_GEOMETRY_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

static const uint64_t SMOKE_B_GEOMETRY_LOS_AZ_DEG_BITS[4] = { UINT64_C(0x0000000000000000), UINT64_C(0x4056800000000000), UINT64_C(0x4066800000000000), UINT64_C(0x4070e00000000000) };
static const uint64_t SMOKE_B_GEOMETRY_LOS_EL_DEG_BITS[4] = { UINT64_C(0x4054000000000000), UINT64_C(0x403e000000000000), UINT64_C(0x403e000000000000), UINT64_C(0x403e000000000000) };
static const uint64_t SMOKE_B_GEOMETRY_SITE_BITS[3] = { UINT64_C(0x3fe3333333333333), UINT64_C(0x3fb999999999999a), UINT64_C(0x0000000000000000) };
static const uint64_t SMOKE_B_GEOMETRY_LOS_XYZ_BITS[12] = { UINT64_C(0x3fe6c1f64c2805b0), UINT64_C(0x3fb2445e33977d2f), UINT64_C(0x3fe661570320d5a0), UINT64_C(0x3fd4bed6e2a1cd97), UINT64_C(0x3fece488158162e2), UINT64_C(0x3fd2118d17a54159), UINT64_C(0x3fecb584a50a3fb9), UINT64_C(0x3fb70b4abcc97aec), UINT64_C(0xbfdbad1a624c865a), UINT64_C(0x3fdfcfe776594d4c), UINT64_C(0xbfea418afdf11782), UINT64_C(0x3fd2118d17a54156) };
static const uint64_t SMOKE_B_GEOMETRY_BUILT_DOP_BITS[5] = { UINT64_C(0x400daf85513ef9db), UINT64_C(0x40097f660c9bdf06), UINT64_C(0x3ffa20bd700c2c37), UINT64_C(0x4005e58b3bd0a08e), UINT64_C(0x3ffe678446c99bf6) };
#define SMOKE_B_GEOMETRY_LOS_EL91_OK false
static const char SMOKE_B_GEOMETRY_LOS_EL91_ERROR[] = "InvalidInput";

#define SMOKE_B_GEOMETRY_ANTEX_NO_SUCH_ANTENNA_FOUND false
#define SMOKE_B_GEOMETRY_ANTEX_PCO_ZZ9_OK false
static const char SMOKE_B_GEOMETRY_ANTEX_PCO_ZZ9_ERROR[] = "UnknownFrequency";

#define SMOKE_B_GEOMETRY_VELOCITY_DEFAULT_RANGE_RATE true
#define SMOKE_B_GEOMETRY_VELOCITY_DEFAULT_LIGHT_TIME true
#define SMOKE_B_GEOMETRY_VELOCITY_DEFAULT_SAGNAC true
#define SMOKE_B_GEOMETRY_VELOCITY_THREE_SATS_OK false
static const char SMOKE_B_GEOMETRY_VELOCITY_THREE_SATS_ERROR[] = "TooFewSatellites";

#endif /* SIDEREON_SMOKE_B_GEOMETRY_PINS_H */
