/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/valgen (bin smoke_b_constellation) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_SMOKE_B_CONSTELLATION_PINS_H
#define SIDEREON_SMOKE_B_CONSTELLATION_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define SMOKE_B_CONSTELLATION_EVAL_BEFORE_US INT64_C(1784855640000000)
#define SMOKE_B_CONSTELLATION_EVAL_START_US INT64_C(1784855700000000)
#define SMOKE_B_CONSTELLATION_EVAL_END_US INT64_C(1784898900000000)

#define SMOKE_B_CONSTELLATION_ASSESSMENT_COUNT ((size_t)6)
static const uint16_t SMOKE_B_CONSTELLATION_ASSESSMENT_PRN[] = { 4, 7, 8, 13, 19, 20 };
static const bool SMOKE_B_CONSTELLATION_ASSESSMENT_USABLE[] = { true, false, true, false, false, false };
static const bool SMOKE_B_CONSTELLATION_ASSESSMENT_ACTIVE_NANU[] = { true, true, false, true, true, true };
static const uint32_t SMOKE_B_CONSTELLATION_ASSESSMENT_TIMING[] = { SIDEREON_NAVCEN_TIMING_UNPARSEABLE, SIDEREON_NAVCEN_TIMING_PARSED, SIDEREON_NAVCEN_TIMING_PARSED, SIDEREON_NAVCEN_TIMING_NOT_APPLICABLE, SIDEREON_NAVCEN_TIMING_NOT_APPLICABLE, SIDEREON_NAVCEN_TIMING_NOT_APPLICABLE };
static const bool SMOKE_B_CONSTELLATION_ASSESSMENT_START_PRESENT[] = { false, true, true, false, false, false };
static const int64_t SMOKE_B_CONSTELLATION_ASSESSMENT_START_US[] = { INT64_C(0), INT64_C(1784855700000000), INT64_C(1784855700000000), INT64_C(0), INT64_C(0), INT64_C(0) };
static const bool SMOKE_B_CONSTELLATION_ASSESSMENT_END_PRESENT[] = { false, true, true, false, false, false };
static const int64_t SMOKE_B_CONSTELLATION_ASSESSMENT_END_US[] = { INT64_C(0), INT64_C(1784898900000000), INT64_C(1784898900000000), INT64_C(0), INT64_C(0), INT64_C(0) };
static const char SMOKE_B_CONSTELLATION_ROW1_NANU_TYPE[] = "FCSTDV";

#define SMOKE_B_CONSTELLATION_ROW1_USABLE_BEFORE true
#define SMOKE_B_CONSTELLATION_ROW1_USABLE_END true

static const char SMOKE_B_CONSTELLATION_MERGE_FORECAST_HTML[] = "<table><tr><td class=\"views-field-field-gps-prn\">19</td><td class=\"views-field-field-gps-svn\">59</td><td class=\"views-field-field-gps-con-block-type\">IIR</td><td class=\"views-field-field-nanu-outage-start-date\">24 JUL 2026</td><td class=\"views-field-field-nanu-type\">FCSTDV</td><td class=\"views-field-field-nanu-subject\">SVN59 (PRN19) FORECAST OUTAGE JDAY 205/0115 - JDAY 205/1315</td><td class=\"nanu-active-check\">1</td></tr></table>";
#define SMOKE_B_CONSTELLATION_TIMED_RECORD3_PRN_START 19
#define SMOKE_B_CONSTELLATION_TIMED_RECORD3_USABLE_START false
#define SMOKE_B_CONSTELLATION_TIMED_RECORD3_PRN_END 19
#define SMOKE_B_CONSTELLATION_TIMED_RECORD3_USABLE_END true

#define SMOKE_B_CONSTELLATION_RECORD0_SYSTEM SIDEREON_GNSS_SYSTEM_GPS
#define SMOKE_B_CONSTELLATION_RECORD0_PRN 3
#define SMOKE_B_CONSTELLATION_RECORD0_ACTIVE true
#define SMOKE_B_CONSTELLATION_RECORD0_USABLE true
#define SMOKE_B_CONSTELLATION_RECORD0_FDMA_CHANNEL_PRESENT false
#define SMOKE_B_CONSTELLATION_RECORD3_SYSTEM SIDEREON_GNSS_SYSTEM_GPS
#define SMOKE_B_CONSTELLATION_RECORD3_PRN 19
#define SMOKE_B_CONSTELLATION_RECORD3_ACTIVE true
#define SMOKE_B_CONSTELLATION_RECORD3_USABLE false
#define SMOKE_B_CONSTELLATION_RECORD3_FDMA_CHANNEL_PRESENT false

static const char SMOKE_B_CONSTELLATION_SP3_ID_GPS_5[] = "G05";
static const char SMOKE_B_CONSTELLATION_SP3_ID_GLONASS_12[] = "R12";

static const char *const SMOKE_B_CONSTELLATION_ALL_IDS[] = { "G03", "G05", "G13", "G19" };
#define SMOKE_B_CONSTELLATION_ALL_ID_COUNT ((size_t)4)
#define SMOKE_B_CONSTELLATION_CELESTRAK_ONLY_VALID true

#endif /* SIDEREON_SMOKE_B_CONSTELLATION_PINS_H */
