/* Generated by tests/velgen from sidereon-core's velocity
 * range_rate/doppler golden scenario (velocity.rs module test). The C
 * smoke test feeds these engine-synthesized observations through the C
 * ABI and asserts the engine's frozen velocity solution bit-for-bit. Do
 * not edit by hand; rerun the generator. */
#ifndef SIDEREON_VELOCITY_FIXTURE_H
#define SIDEREON_VELOCITY_FIXTURE_H

#include <stdint.h>
#include <stddef.h>

#define VEL_SP3_FILE "GRG0MGXFIN_20201760000_01D_15M_ORB.SP3"
static const uint64_t VEL_T_RX_J2000_S_BITS = UINT64_C(0x41c342aa00000000);
static const uint64_t VEL_RECEIVER_BITS[3] = { UINT64_C(0x41512a8800000000), UINT64_C(0x411e848000000000), UINT64_C(0x41512a8800000000) };

static const uint64_t VEL_F_L1_HZ_BITS = UINT64_C(0x41d779c018000000);

#define VEL_OBS_COUNT 9
static const char *const VEL_SAT_IDS[VEL_OBS_COUNT] = {
    "G07",
    "G08",
    "G10",
    "G16",
    "G18",
    "G20",
    "G21",
    "G26",
    "G27",
};

static const uint64_t VEL_RANGE_RATE_BITS[VEL_OBS_COUNT] = {
    UINT64_C(0xc0768a0b93c45f82),
    UINT64_C(0xc081bbf2879835fd),
    UINT64_C(0xc081c9b51570e844),
    UINT64_C(0xc045eb58a1b7b54e),
    UINT64_C(0x407ec07dd774b2f8),
    UINT64_C(0xc0689f0e9e24fbc3),
    UINT64_C(0x4063a9470c18c1a7),
    UINT64_C(0x4079ef7d9618f6b0),
    UINT64_C(0xc0775231a845d789),
};

static const uint64_t VEL_DOPPLER_BITS[VEL_OBS_COUNT] = {
    UINT64_C(0x409e0965a10b1ef0),
    UINT64_C(0x40a7a43f85f7622c),
    UINT64_C(0x40a7b8ba4c360261),
    UINT64_C(0x406d3dcdfdee3ef8),
    UINT64_C(0xc0a484fca0c0745e),
    UINT64_C(0x40906f3f24f92377),
    UINT64_C(0xc08a41b75e19cdff),
    UINT64_C(0xc0a152ed95f36ada),
    UINT64_C(0x409f2a86eed51786),
};
static const uint64_t VEL_DOPPLER_CARRIER_BITS[VEL_OBS_COUNT] = {
    UINT64_C(0x41d7d01fe9000000),
    UINT64_C(0x41d7d2453a000000),
    UINT64_C(0x41d7d46a8b000000),
    UINT64_C(0x41d7d68fdc000000),
    UINT64_C(0x41d7d8b52d000000),
    UINT64_C(0x41d7dada7e000000),
    UINT64_C(0x41d7dcffcf000000),
    UINT64_C(0x41d7df2520000000),
    UINT64_C(0x41d7e14a71000000),
};

static const uint64_t VEL_RR_VELOCITY_BITS[3] = { UINT64_C(0x4028000000000000), UINT64_C(0xc01c000000000016), UINT64_C(0x4007ffffffffff00) };
static const uint64_t VEL_RR_SPEED_BITS = UINT64_C(0x402c6ce322982a37);
static const uint64_t VEL_RR_CLOCK_DRIFT_BITS = UINT64_C(0x3e112e0be826d2ee);
#define VEL_RR_USED_COUNT 9
static const char *const VEL_RR_USED_IDS[VEL_RR_USED_COUNT] = {
    "G07",
    "G08",
    "G10",
    "G16",
    "G18",
    "G20",
    "G21",
    "G26",
    "G27",
};
static const uint64_t VEL_RR_RESIDUAL_BITS[VEL_RR_USED_COUNT] = {
    UINT64_C(0xbd01000000000000),
    UINT64_C(0xbd24000000000000),
    UINT64_C(0x3cfc000000000000),
    UINT64_C(0xbd16000000000000),
    UINT64_C(0xbd1a800000000000),
    UINT64_C(0x3cf0000000000000),
    UINT64_C(0xbd14000000000000),
    UINT64_C(0x3d31800000000000),
    UINT64_C(0x3d18000000000000),
};

static const uint64_t VEL_DOP_VELOCITY_BITS[3] = { UINT64_C(0x402800000000000c), UINT64_C(0xc01c00000000000f), UINT64_C(0x4007ffffffffff60) };
static const uint64_t VEL_DOP_SPEED_BITS = UINT64_C(0x402c6ce322982a44);
static const uint64_t VEL_DOP_CLOCK_DRIFT_BITS = UINT64_C(0x3e112e0be826d4b8);
#define VEL_DOP_USED_COUNT 9
static const char *const VEL_DOP_USED_IDS[VEL_DOP_USED_COUNT] = {
    "G07",
    "G08",
    "G10",
    "G16",
    "G18",
    "G20",
    "G21",
    "G26",
    "G27",
};
static const uint64_t VEL_DOP_RESIDUAL_BITS[VEL_DOP_USED_COUNT] = {
    UINT64_C(0x3d24c00000000000),
    UINT64_C(0xbd2b000000000000),
    UINT64_C(0xbd00000000000000),
    UINT64_C(0xbd00000000000000),
    UINT64_C(0xbd0b000000000000),
    UINT64_C(0x3d06000000000000),
    UINT64_C(0x0000000000000000),
    UINT64_C(0x3d40c00000000000),
    UINT64_C(0x3d22000000000000),
};

#endif /* SIDEREON_VELOCITY_FIXTURE_H */
