/* sidereon-core revision 47eaf24e39afa71168670664e88361ed41011bc2 */
/* Generated by tests/velgen from sidereon-core's velocity
 * range_rate/doppler golden scenario (velocity.rs module test). The C
 * smoke test feeds these engine-synthesized observations through the C
 * ABI and asserts the engine's frozen velocity solution bit-for-bit. Do
 * not edit by hand; rerun the generator. */
#ifndef SIDEREON_VELOCITY_FIXTURE_H
#define SIDEREON_VELOCITY_FIXTURE_H

#include <stdint.h>
#include <stddef.h>

#define VEL_SP3_FILE "GRG0MGXFIN_20201760000_01D_15M_ORB.SP3"
static const uint64_t VEL_T_RX_J2000_S_BITS = UINT64_C(0x41c342aa00000000);
static const uint64_t VEL_RECEIVER_BITS[3] = { UINT64_C(0x41512a8800000000), UINT64_C(0x411e848000000000), UINT64_C(0x41512a8800000000) };

static const uint64_t VEL_F_L1_HZ_BITS = UINT64_C(0x41d779c018000000);

#define VEL_OBS_COUNT 9
static const char *const VEL_SAT_IDS[VEL_OBS_COUNT] = {
    "G07",
    "G08",
    "G10",
    "G16",
    "G18",
    "G20",
    "G21",
    "G26",
    "G27",
};

static const uint64_t VEL_RANGE_RATE_BITS[VEL_OBS_COUNT] = {
    UINT64_C(0xc0768a0b93bc4249),
    UINT64_C(0xc081bbf28799d04b),
    UINT64_C(0xc081c9b515750656),
    UINT64_C(0xc045eb58a17c07cd),
    UINT64_C(0x407ec07dd76ef98b),
    UINT64_C(0xc0689f0e9e3b2fa5),
    UINT64_C(0x4063a9470c139736),
    UINT64_C(0x4079ef7d9618f6b0),
    UINT64_C(0xc0775231a840d16e),
};

static const uint64_t VEL_DOPPLER_BITS[VEL_OBS_COUNT] = {
    UINT64_C(0x409e0965a1004ebf),
    UINT64_C(0x40a7a43f85f98528),
    UINT64_C(0x40a7b8ba4c3b8010),
    UINT64_C(0x406d3dcdfd9ea20c),
    UINT64_C(0xc0a484fca0bca28d),
    UINT64_C(0x40906f3f2507f56a),
    UINT64_C(0xc08a41b75e12e7ef),
    UINT64_C(0xc0a152ed95f36ada),
    UINT64_C(0x409f2a86eece60c8),
};
static const uint64_t VEL_DOPPLER_CARRIER_BITS[VEL_OBS_COUNT] = {
    UINT64_C(0x41d7d01fe9000000),
    UINT64_C(0x41d7d2453a000000),
    UINT64_C(0x41d7d46a8b000000),
    UINT64_C(0x41d7d68fdc000000),
    UINT64_C(0x41d7d8b52d000000),
    UINT64_C(0x41d7dada7e000000),
    UINT64_C(0x41d7dcffcf000000),
    UINT64_C(0x41d7df2520000000),
    UINT64_C(0x41d7e14a71000000),
};

static const uint64_t VEL_RR_VELOCITY_BITS[3] = { UINT64_C(0x4027ffffffffffec), UINT64_C(0xc01bffffffffffe4), UINT64_C(0x4007ffffffffff20) };
static const uint64_t VEL_RR_SPEED_BITS = UINT64_C(0x402c6ce322982a1c);
static const uint64_t VEL_RR_CLOCK_DRIFT_BITS = UINT64_C(0x3e112e0be826d27b);
#define VEL_RR_USED_COUNT 9
static const char *const VEL_RR_USED_IDS[VEL_RR_USED_COUNT] = {
    "G07",
    "G08",
    "G10",
    "G16",
    "G18",
    "G20",
    "G21",
    "G26",
    "G27",
};
static const uint64_t VEL_RR_RESIDUAL_BITS[VEL_RR_USED_COUNT] = {
    UINT64_C(0x3d0a000000000000),
    UINT64_C(0x0000000000000000),
    UINT64_C(0xbd24800000000000),
    UINT64_C(0xbd23000000000000),
    UINT64_C(0xbd04000000000000),
    UINT64_C(0x3d26800000000000),
    UINT64_C(0xbd10000000000000),
    UINT64_C(0x3d28000000000000),
    UINT64_C(0xbd00000000000000),
};

static const uint64_t VEL_DOP_VELOCITY_BITS[3] = { UINT64_C(0x4027fffffffffff8), UINT64_C(0xc01bffffffffffe8), UINT64_C(0x4007ffffffffff40) };
static const uint64_t VEL_DOP_SPEED_BITS = UINT64_C(0x402c6ce322982a29);
static const uint64_t VEL_DOP_CLOCK_DRIFT_BITS = UINT64_C(0x3e112e0be826d445);
#define VEL_DOP_USED_COUNT 9
static const char *const VEL_DOP_USED_IDS[VEL_DOP_USED_COUNT] = {
    "G07",
    "G08",
    "G10",
    "G16",
    "G18",
    "G20",
    "G21",
    "G26",
    "G27",
};
static const uint64_t VEL_DOP_RESIDUAL_BITS[VEL_DOP_USED_COUNT] = {
    UINT64_C(0x3d27800000000000),
    UINT64_C(0xbd14000000000000),
    UINT64_C(0xbd2c800000000000),
    UINT64_C(0xbd26000000000000),
    UINT64_C(0xbd1c800000000000),
    UINT64_C(0x3d30200000000000),
    UINT64_C(0xbd16000000000000),
    UINT64_C(0x3d3a800000000000),
    UINT64_C(0xbd10000000000000),
};

#endif /* SIDEREON_VELOCITY_FIXTURE_H */
