/* sidereon-core revision 47eaf24e39afa71168670664e88361ed41011bc2 */
/* Generated by tests/valgen (bin w4_r2) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W4_R2_PINS_H
#define SIDEREON_W4_R2_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* exercise_frames: sidereon_core::astro::frames::transforms. */
static const uint64_t W4_R2_TS_JD_WHOLE_BITS = UINT64_C(0x4142c2c900000000);
static const uint64_t W4_R2_TS_JD_TT_BITS = UINT64_C(0x4142c2c9001a3d1a);
static const uint64_t W4_R2_GCRS_TO_ITRS_MATRIX_BITS[9] = { UINT64_C(0xbfb11400a47c4f00), UINT64_C(0x3fefedc02c7c3e36), UINT64_C(0x3f21dfde357e3376), UINT64_C(0xbfefedbc2a7b5bbf), UINT64_C(0xbfb11402fa0fa5ba), UINT64_C(0x3f5ffee73e99c49b), UINT64_C(0x3f6009683cdb69a2), UINT64_C(0xbed847f2c8cf8963), UINT64_C(0x3feffffbfb47f16d) };
static const uint64_t W4_R2_ITRS_TO_GCRS_MATRIX_BITS[9] = { UINT64_C(0xbfb11400a47c4f00), UINT64_C(0xbfefedbc2a7b5bbf), UINT64_C(0x3f6009683cdb69a2), UINT64_C(0x3fefedc02c7c3e36), UINT64_C(0xbfb11402fa0fa5ba), UINT64_C(0xbed847f2c8cf8963), UINT64_C(0x3f21dfde357e3376), UINT64_C(0x3f5ffee73e99c49b), UINT64_C(0x3feffffbfb47f16d) };
static const uint64_t W4_R2_POLAR_MOTION_ZERO_BITS[9] = { UINT64_C(0x3ff0000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x3ff0000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x3ff0000000000000) };
static const uint64_t W4_R2_GMST_BITS = UINT64_C(0x3ffa4632273988fc);
static const uint64_t W4_R2_GAST_BITS = UINT64_C(0x3ffa45e3ec027e62);
static const uint64_t W4_R2_GCRS_TO_ITRS_BITS[3] = { UINT64_C(0x4090158342932be7), UINT64_C(0xc0bbb0c1a50b243a), UINT64_C(0xc0a1149a35ffb7b8) };
static const uint64_t W4_R2_ITRS_TO_GCRS_BACK_BITS[3] = { UINT64_C(0x40bb57fffffffffd), UINT64_C(0x409770000000008b), UINT64_C(0xc0a12fffffffffee) };
static const uint64_t W4_R2_GEODETIC_TO_ITRS_BITS[3] = { UINT64_C(0xc0a51d40fbde4fd4), UINT64_C(0xc0b0e51b704380e9), UINT64_C(0x40add2e81c6c4b6f) };
static const uint64_t W4_R2_ITRS_TO_GEODETIC_BITS[3] = { UINT64_C(0x40427fffffe0d89a), UINT64_C(0xc05e800000000000), UINT64_C(0x3fb99999999a5b7b) };
static const uint64_t W4_R2_TEME_TO_GCRS_POSITION_BITS[3] = { UINT64_C(0xc0af065a0038d886), UINT64_C(0x40b39a4067ad972e), UINT64_C(0x40a77f9e1f0737a0) };
static const uint64_t W4_R2_TEME_TO_GCRS_VELOCITY_BITS[3] = { UINT64_C(0xc007faa13940937b), UINT64_C(0xbfffc7c5e37d1b00), UINT64_C(0x401806022f3d2a0c) };
static const uint64_t W4_R2_MAT3_VEC3_IDENTITY_BITS[3] = { UINT64_C(0x3ff8000000000000), UINT64_C(0xc004000000000000), UINT64_C(0x400c000000000000) };
static const uint64_t W4_R2_TOPOCENTRIC_BITS[3] = { UINT64_C(0x4061294766d9f0c6), UINT64_C(0xc039f1daf1347f1e), UINT64_C(0x40bda62070a5880c) };

/* exercise_nutation_precession: sidereon_core::astro::frames nutation and
 * precession. */
static const uint64_t W4_R2_NUTATION_DPSI_BITS = UINT64_C(0xbf16b15d313979ed);
static const uint64_t W4_R2_NUTATION_DEPS_BITS = UINT64_C(0xbeb962d3d125e6ff);
static const uint64_t W4_R2_MEAN_OBLIQUITY_BITS = UINT64_C(0x3fda2dd056c43de1);
static const uint64_t W4_R2_FUNDAMENTAL_ARGUMENTS_BITS[5] = { UINT64_C(0x400865de6f920373), UINT64_C(0x4018f26d41fd8df1), UINT64_C(0x4011b5bb2205b555), UINT64_C(0x3ff3e72bd690c967), UINT64_C(0xc012469fb0b0d3de) };
static const uint64_t W4_R2_EQUATION_OF_EQUINOXES_BITS = UINT64_C(0x3e4b77c65ee18059);
static const uint64_t W4_R2_NUTATION_MATRIX_BITS[9] = { UINT64_C(0x3feffffffdfd091a), UINT64_C(0x3f14d218480a9eaf), UINT64_C(0x3f020d2b1a3d4baf), UINT64_C(0xbf14d2192d2b1c50), UINT64_C(0x3feffffffe4e5770), UINT64_C(0x3eb95cf471600000), UINT64_C(0xbf020d26f92127f4), UINT64_C(0xbeb968b32f500000), UINT64_C(0x3fefffffffae611c) };
static const uint64_t W4_R2_PRECESSION_MATRIX_BITS[9] = { UINT64_C(0x3fefffe6084ed3de), UINT64_C(0xbf72b1e093f1e6fa), UINT64_C(0xbf603eebe8dcac18), UINT64_C(0x3f72b1e097659e6d), UINT64_C(0x3fefffea28044d12), UINT64_C(0xbed2e03a70230000), UINT64_C(0x3f603eebd8f8ed0f), UINT64_C(0xbed3169fe5d70000), UINT64_C(0x3feffffbe04a86c6) };
static const uint64_t W4_R2_ICRS_TO_J2000_MATRIX_BITS[9] = { UINT64_C(0x3fefffffffffffcc), UINT64_C(0xbe730028242f1a78), UINT64_C(0x3e75a024b598dac6), UINT64_C(0x3e730028242f1a78), UINT64_C(0x3fefffffffffffe5), UINT64_C(0x3e61bfc9ed39e35d), UINT64_C(0xbe75a024b598dac6), UINT64_C(0xbe61bfc9ed39e35d), UINT64_C(0x3fefffffffffffde) };

/* exercise_broadcast_keplerian: sidereon_core::ephemeris. */
static const uint64_t W4_R2_ORBIT_ECEF_BITS[3] = { UINT64_C(0x41715cc6332e9244), UINT64_C(0xc1654a085c62d842), UINT64_C(0x416db69f86da0b36) };
static const uint64_t W4_R2_CLOCK_TOTAL_BITS = UINT64_C(0x3f1a3674fa08a9de);

/* exercise_rinex_encode_nav: sidereon_core::rinex::nav::encode_nav of the
 * store read from fixtures/nav/ESBC00DNK_R_20201770000_01D_MN.rnx. */
#define W4_R2_ENCODED_NAV_LEN (930115)
#define W4_R2_ENCODED_NAV_FNV1A64 UINT64_C(0x06a986c411dc5dd3)

/* exercise_iod_gauss: sidereon_core::astro::iod::gauss_angles. */
static const uint64_t W4_R2_IOD_POSITION_BITS[3] = { UINT64_C(0x40b8a960cd243751), UINT64_C(0x40b47f817131970a), UINT64_C(0x40b943b508ba6adf) };
static const uint64_t W4_R2_IOD_VELOCITY_BITS[3] = { UINT64_C(0xc010bdf0a3c911e9), UINT64_C(0x4013276aafecb102), UINT64_C(0x3ffb8c24abc4c5c1) };

/* exercise_combination_and_covariance: sidereon_core::combinations and
 * sidereon_core::astro::conjunction. */
static const uint64_t W4_R2_IONO_FREE_PHASE_BITS = UINT64_C(0x416b99825d9a8898);
#define W4_R2_IONO_FREE_COMBINED_COUNT (1)
#define W4_R2_IONO_FREE_DROPPED_COUNT (1)
#define W4_R2_IONO_FREE_DROPPED0_REASON SIDEREON_PSEUDORANGE_DROP_MISSING_BAND2
static const uint64_t W4_R2_ENCOUNTER_PLANE_COVARIANCE_BITS[4] = { UINT64_C(0x4007d75a8859382e), UINT64_C(0x3fc958b5c3b68b92), UINT64_C(0x3fc958b5c3b68b94), UINT64_C(0x3ff0511c555e54ca) };

/* exercise_signal: sidereon_core::signal. */
#define W4_R2_CA_CODE_LEN (1023)
#define W4_R2_CA_CODE_FNV1A64 UINT64_C(0xbde630d2d617e66e)
#define W4_R2_AUTOCORRELATION_0 (1023)
#define W4_R2_CORRELATION_AT_0 (1023)
#define W4_R2_CROSS_CORRELATION_0 (1023)
static const uint64_t W4_R2_CORRELATE_AGAINST_I_BITS = UINT64_C(0x409ff80000000000);
static const uint64_t W4_R2_CORRELATE_AGAINST_Q_BITS = UINT64_C(0x0000000000000000);
static const uint64_t W4_R2_CORRELATE_POWER_BITS = UINT64_C(0x414ff00200000000);
#define W4_R2_ACQUIRE_BIN_COUNT (5)
static const uint64_t W4_R2_ACQUIRE_PEAK_POWER_BITS = UINT64_C(0x414ff00200000000);
static const uint64_t W4_R2_ACQUIRE_CODE_PHASE_BITS = UINT64_C(0x0000000000000000);
static const uint64_t W4_R2_ACQUIRE_DOPPLER_BITS = UINT64_C(0x0000000000000000);

/* exercise_quality: sidereon_core::quality sigmas, weight_vector,
 * raim_for_solution and validate_receiver_solution on the spp_fixture.h
 * inputs (the tests/sppgen solve). */
#define W4_R2_SIGMA0_PRESENT true
static const uint64_t W4_R2_SIGMA0_BITS = UINT64_C(0x3fe5775c544ff263);
#define W4_R2_WEIGHT0_PRESENT true
static const uint64_t W4_R2_WEIGHT0_BITS = UINT64_C(0x4001c71c71c71c71);
#define W4_R2_SIGMA1_PRESENT true
static const uint64_t W4_R2_SIGMA1_BITS = UINT64_C(0x3fdb27247aff148f);
#define W4_R2_WEIGHT1_PRESENT true
static const uint64_t W4_R2_WEIGHT1_BITS = UINT64_C(0x401638e38e38e38e);
static const uint64_t W4_R2_RAIM_TEST_STATISTIC_BITS = UINT64_C(0x404a2ce18aa200f0);
#define W4_R2_SOLUTION_VALID true

/* exercise_tca: sidereon_core::astro::tca on the test's TLE pair. */
#define W4_R2_CANDIDATE_COUNT (32)
static const uint64_t W4_R2_CANDIDATE0_MISS_DISTANCE_BITS = UINT64_C(0x407f84f1c49a5131);
static const uint64_t W4_R2_CANDIDATE0_PC_BITS = UINT64_C(0x0000000000000000);
#define W4_R2_CONJUNCTION_COUNT (32)
#define W4_R2_SCREEN_CANDIDATE_COUNT (32)
#define W4_R2_SCREEN_CONJUNCTION_COUNT (32)
#define W4_R2_PROPAGATED_OK true
#define W4_R2_PROPAGATED_CONJUNCTION_COUNT (32)


#endif /* SIDEREON_W4_R2_PINS_H */
