/* sidereon-core revision 8694648892d8ab065d94014e2e21d6cd5054818e */
/* Generated by tests/valgen (bin w5_cap015) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W5_CAP015_PINS_H
#define SIDEREON_W5_CAP015_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


/* sidereon_core::error_metrics on the isotropic, elongated and rotated
 * covariances cap015_smoke.c builds.
 */
static const uint64_t W5_CAP015_ISO_CEP_M_BITS = UINT64_C(0x400c4201d6707a66);
static const uint64_t W5_CAP015_ISO_R95_M_BITS = UINT64_C(0x401d5f7a6f7ff0e8);
#define W5_CAP015_ISO_R95_APPROX_VALID (false)
static const uint64_t W5_CAP015_ISO_SEP_M_BITS = UINT64_C(0x401273721d53cddd);
static const uint64_t W5_CAP015_ISO_DRMS_M_BITS = UINT64_C(0x4010f876ccdf6cd9);
static const uint64_t W5_CAP015_ISO_ELLIPSE_SEMI_MAJOR_M_BITS = UINT64_C(0x4008000000000000);
static const uint64_t W5_CAP015_ISO_ELLIPSE_SEMI_MINOR_M_BITS = UINT64_C(0x4008000000000000);
static const uint64_t W5_CAP015_ISO_ELLIPSE_ORIENTATION_RAD_BITS = UINT64_C(0x0000000000000000);
static const uint64_t W5_CAP015_ISO_HORIZONTAL_R95_M_BITS = UINT64_C(0x401d5f7a6f7ff0e8);
#define W5_CAP015_ISO_HORIZONTAL_R95_APPROX_VALID (false)
static const uint64_t W5_CAP015_ISO_SPHERICAL_R50_M_BITS = UINT64_C(0x401273721d53cddd);
static const uint64_t W5_CAP015_ISO_VERTICAL_R50_M_BITS = UINT64_C(0x40003010a57de7b8);
static const uint64_t W5_CAP015_POSITION_COV_CEP_M_BITS = UINT64_C(0x400c4201d6707a66);
static const uint64_t W5_CAP015_POSITION_COV_R95_M_BITS = UINT64_C(0x401d5f7a6f7ff0e8);
#define W5_CAP015_POSITION_COV_R95_APPROX_VALID (false)
static const uint64_t W5_CAP015_POSITION_COV_SEP_M_BITS = UINT64_C(0x401273721d53cddd);
static const uint64_t W5_CAP015_POSITION_COV_DRMS_M_BITS = UINT64_C(0x4010f876ccdf6cd9);
static const uint64_t W5_CAP015_ELONGATED_SEMI_MAJOR_M_BITS = UINT64_C(0x4008eaf92c7132e6);
static const uint64_t W5_CAP015_ELONGATED_SEMI_MINOR_M_BITS = UINT64_C(0x3ffd0efe00232c29);
static const uint64_t W5_CAP015_ELONGATED_ORIENTATION_RAD_BITS = UINT64_C(0x3fd5977a5103ea93);
static const uint64_t W5_CAP015_ROTATED_ENU_CEP_M_BITS = UINT64_C(0x40010ced31708aac);
static const uint64_t W5_CAP015_ROTATED_ENU_R95_M_BITS = UINT64_C(0x4012cc309b07ab24);
#define W5_CAP015_ROTATED_ENU_R95_APPROX_VALID (false)
static const uint64_t W5_CAP015_ROTATED_ENU_SEP_M_BITS = UINT64_C(0x40037b1db3f8be7c);
static const uint64_t W5_CAP015_ROTATED_ENU_DRMS_M_BITS = UINT64_C(0x40052a7fa9d2f8ea);
static const uint64_t W5_CAP015_ROTATED_ECEF_CEP_M_BITS = UINT64_C(0x40010ced31708aac);
static const uint64_t W5_CAP015_ROTATED_ECEF_R95_M_BITS = UINT64_C(0x4012cc309b07ab24);
#define W5_CAP015_ROTATED_ECEF_R95_APPROX_VALID (false)
static const uint64_t W5_CAP015_ROTATED_ECEF_SEP_M_BITS = UINT64_C(0x40037b1db3f8be7c);
static const uint64_t W5_CAP015_ROTATED_ECEF_DRMS_M_BITS = UINT64_C(0x40052a7fa9d2f8ea);
static const uint64_t W5_CAP015_KINEMATIC_CEP_M_BITS = UINT64_C(0x40010ced31708aac);
static const uint64_t W5_CAP015_KINEMATIC_R95_M_BITS = UINT64_C(0x4012cc309b07ab24);
#define W5_CAP015_KINEMATIC_R95_APPROX_VALID (false)
static const uint64_t W5_CAP015_KINEMATIC_SEP_M_BITS = UINT64_C(0x40037b1db3f8be7c);
static const uint64_t W5_CAP015_KINEMATIC_DRMS_M_BITS = UINT64_C(0x40052a7fa9d2f8ea);
#define W5_CAP015_NON_PSD_OK (false)
static const char W5_CAP015_NON_PSD_ERROR_VARIANT[] = "NotPositiveSemidefinite";
#define W5_CAP015_NON_PSD_ERROR_VARIANT_LEN ((size_t)23)
#define W5_CAP015_NON_PSD_KIND SIDEREON_ERROR_METRICS_ERROR_KIND_NOT_POSITIVE_SEMIDEFINITE

/* sidereon_core::sidereal: GPS repeat period and the two-sample filter.
 */
static const uint64_t W5_CAP015_SIDEREAL_GPS_PERIOD_S_BITS = UINT64_C(0x40f5094172b020c5);
static const bool W5_CAP015_SIDEREAL_UNDER_COVERED[2] = { 1, 1 };
#define W5_CAP015_SIDEREAL_UNDER_COVERED_COUNT ((size_t)2)

/* sidereon_core::geodetic_time_series::velocity_midas, default options.
 */
static const uint64_t W5_CAP015_MIDAS_RATE_ENU_M_PER_YR_BITS[3] = { UINT64_C(0x3f847ae147ae147b), UINT64_C(0xbf947ae147ae147b), UINT64_C(0x3f747ae147ae147b) };
#define W5_CAP015_MIDAS_RATE_ENU_M_PER_YR_BITS_COUNT ((size_t)3)

/* sidereon_core::clock_stability power-law slopes and the one-point fit.
 */
static const uint64_t W5_CAP015_WHITE_FM_ADEV_SLOPE_BITS = UINT64_C(0xbfe0000000000000);
static const uint64_t W5_CAP015_WHITE_FM_MDEV_SLOPE_BITS = UINT64_C(0xbfe0000000000000);
#define W5_CAP015_WHITE_FM_VARIANCE_TAU_EXPONENT (-1)
#define W5_CAP015_POWER_LAW_OCTAVE_COUNT (1)
#define W5_CAP015_POWER_LAW_OCTAVE_DOMINANCE_KIND SIDEREON_POWER_LAW_OCTAVE_DOMINANCE_KIND_FLAGGED
#define W5_CAP015_POWER_LAW_OCTAVE_FLAG SIDEREON_POWER_LAW_OCTAVE_FLAG_UNDER_SAMPLED

/* sidereon_core::ephemeris::fit_precise_ephemeris_sample_orbit on the two
 * samples cap015_smoke.c forms.
 */
#define W5_CAP015_SPARSE_FIT_COUNT (1)
#define W5_CAP015_SPARSE_FIT_COVARIANCE_KIND SIDEREON_ORBIT_FIT_COVARIANCE_KIND_UNBOUNDED
#define W5_CAP015_SPARSE_FIT_TIER SIDEREON_OBSERVABILITY_TIER_ZERO_REDUNDANCY
#define W5_CAP015_SPARSE_LEDGER_COUNT (1)
#define W5_CAP015_SPARSE_LEDGER_N (2)
#define W5_CAP015_SPARSE_LEDGER_LOW_SAMPLE_COUNT (true)

/* sidereon_core::quality::wtest_noncentrality_components(0.001, 0.20).
 */
static const uint64_t W5_CAP015_WTEST_DELTA0_BITS = UINT64_C(0x40108751cbd0bec7);
static const uint64_t W5_CAP015_WTEST_LAMBDA0_BITS = UINT64_C(0x4031131c0d9309e7);

/* sidereon_core::quality::reliability_design, default options.
 */
#define W5_CAP015_RELIABILITY_OBS_COUNT (3)
#define W5_CAP015_RELIABILITY_DOF (1)
#define W5_CAP015_RELIABILITY_N_UNCHECKABLE (1)
static const uint64_t W5_CAP015_RELIABILITY_SUM_REDUNDANCY_BITS = UINT64_C(0x3ff0000000000001);
static const uint64_t W5_CAP015_RELIABILITY_REDUNDANCY_BITS[3] = { UINT64_C(0x0000000000000000), UINT64_C(0x3fe0000000000001), UINT64_C(0x3fe0000000000001) };
#define W5_CAP015_RELIABILITY_REDUNDANCY_BITS_COUNT ((size_t)3)
static const bool W5_CAP015_RELIABILITY_UNCHECKABLE[3] = { 1, 0, 0 };
#define W5_CAP015_RELIABILITY_UNCHECKABLE_COUNT ((size_t)3)
static const bool W5_CAP015_RELIABILITY_HAS_MDB[3] = { 0, 1, 1 };
#define W5_CAP015_RELIABILITY_HAS_MDB_COUNT ((size_t)3)
static const bool W5_CAP015_RELIABILITY_HAS_EXTERNAL_ENU[3] = { 0, 0, 0 };
#define W5_CAP015_RELIABILITY_HAS_EXTERNAL_ENU_COUNT ((size_t)3)
static const bool W5_CAP015_RELIABILITY_HAS_BIAS_TO_NOISE[3] = { 0, 1, 1 };
#define W5_CAP015_RELIABILITY_HAS_BIAS_TO_NOISE_COUNT ((size_t)3)

/* sidereon_core::sbas_pl K multipliers and protection levels for the five
 * rows cap015_smoke.c builds.
 */
static const uint64_t W5_CAP015_SBAS_PRECISION_K_H_BITS = UINT64_C(0x4018000000000000);
static const uint64_t W5_CAP015_SBAS_PRECISION_K_V_BITS = UINT64_C(0x401551eb851eb852);
static const uint64_t W5_CAP015_SBAS_ENROUTE_K_H_BITS = UINT64_C(0x4018b851eb851eb8);
static const uint64_t W5_CAP015_SBAS_ENROUTE_K_V_BITS = UINT64_C(0x401551eb851eb852);
static const uint64_t W5_CAP015_SBAS_HPL_M_BITS = UINT64_C(0x40222104f73926ad);
static const uint64_t W5_CAP015_SBAS_VPL_M_BITS = UINT64_C(0x402b540117293c0f);

#endif /* SIDEREON_W5_CAP015_PINS_H */
