/* sidereon-core revision 8694648892d8ab065d94014e2e21d6cd5054818e */
/* Generated by tests/valgen (bin w5_extras) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W5_EXTRAS_PINS_H
#define SIDEREON_W5_EXTRAS_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


/* sidereon_core::astro::rf, chained as test_rf chains it.
 */
static const uint64_t W5_EXTRAS_RF_FSPL_BITS = UINT64_C(0x406770c46ba2efaa);
static const uint64_t W5_EXTRAS_RF_EIRP_BITS = UINT64_C(0x4044000000000000);
static const uint64_t W5_EXTRAS_RF_CN0_BITS = UINT64_C(0x405504dd8f208712);
static const uint64_t W5_EXTRAS_RF_LINK_MARGIN_BITS = UINT64_C(0x404889bb1e410e24);
static const uint64_t W5_EXTRAS_RF_WAVELENGTH_BITS = UINT64_C(0x3fc85b8b06a70079);
static const uint64_t W5_EXTRAS_RF_DISH_GAIN_BITS = UINT64_C(0x403dbd80e1a4955e);

/* sidereon_core::frequencies and combinations for GPS L1/L2.
 */
static const uint64_t W5_EXTRAS_GPS_L1_HZ_BITS = UINT64_C(0x41d779c018000000);
static const uint64_t W5_EXTRAS_GPS_L2_HZ_BITS = UINT64_C(0x41d24aec20000000);
static const uint64_t W5_EXTRAS_GPS_L1_WAVELENGTH_M_BITS = UINT64_C(0x3fc85b8b06a70079);
static const uint64_t W5_EXTRAS_GLONASS_G1_CHANNEL_0_HZ_BITS = UINT64_C(0x41d7df2520000000);
static const uint64_t W5_EXTRAS_GPS_DEFAULT_SPP_HZ_BITS = UINT64_C(0x41d779c018000000);
static const uint64_t W5_EXTRAS_GAMMA_BITS = UINT64_C(0x40045da686c28e3c);
static const uint64_t W5_EXTRAS_NOISE_AMPLIFICATION_BITS = UINT64_C(0x4007d3777c503ebc);
static const uint64_t W5_EXTRAS_IONOSPHERE_FREE_BITS = UINT64_C(0x417312cfffffffff);
static const uint64_t W5_EXTRAS_IONOSPHERE_FREE_PHASE_M_BITS = UINT64_C(0x417312cfffffffff);

/* sidereon_core::carrier_phase scalars.
 */
static const uint64_t W5_EXTRAS_PHASE_METERS_BITS = UINT64_C(0x417225d7747a35d3);
static const uint64_t W5_EXTRAS_GEOMETRY_FREE_BITS = UINT64_C(0x0000000000000000);
static const uint64_t W5_EXTRAS_WIDE_LANE_WAVELENGTH_BITS = UINT64_C(0x3feb94d5e5a6844d);
static const uint64_t W5_EXTRAS_NARROW_LANE_CODE_BITS = UINT64_C(0x417312d000000000);
static const uint64_t W5_EXTRAS_MELBOURNE_WUBBENA_BITS = UINT64_C(0xc14511cfff2cf870);
static const uint64_t W5_EXTRAS_WIDE_LANE_CYCLES_BITS = UINT64_C(0xc14871ea5bf35c1c);
static const uint64_t W5_EXTRAS_CODE_MINUS_CARRIER_BITS = UINT64_C(0x412d9f1170b945a0);

/* sidereon_core::signal and quality scalars.
 */
#define W5_EXTRAS_CA_CHIP_PRN1_INDEX0 (-1)
static const uint64_t W5_EXTRAS_COHERENT_LOSS_BITS = UINT64_C(0x3feef60402b643f6);
static const uint64_t W5_EXTRAS_COHERENT_LOSS_DB_BITS = UINT64_C(0xbfc2594c66a7d641);
static const uint64_t W5_EXTRAS_SNR_POST_DB_BITS = UINT64_C(0x403c02a30498eb10);
static const uint64_t W5_EXTRAS_PSEUDORANGE_VARIANCE_BITS = UINT64_C(0x3fdcccccccccccce);
static const uint64_t W5_EXTRAS_CHI2_INV_BITS = UINT64_C(0x4025a7b6c0cc8b3c);

/* sidereon_core::quality::raim on test_raim's residuals, unit weights.
 * The reduced chi-square and RMS are the binding's (src/raim.rs,
 * raim_result_to_c and residual_rms_m) over the engine's statistic.
 */
#define W5_EXTRAS_RAIM_FAULT_DETECTED (false)
static const uint64_t W5_EXTRAS_RAIM_TEST_STATISTIC_BITS = UINT64_C(0x3fe5333333333333);
#define W5_EXTRAS_RAIM_HAS_THRESHOLD (true)
static const uint64_t W5_EXTRAS_RAIM_THRESHOLD_BITS = UINT64_C(0x4025a7b6c0cc8b3c);
#define W5_EXTRAS_RAIM_HAS_REDUCED_CHI_SQUARE (true)
static const uint64_t W5_EXTRAS_RAIM_REDUCED_CHI_SQUARE_BITS = UINT64_C(0x3fe5333333333333);
static const uint64_t W5_EXTRAS_RAIM_RMS_M_BITS = UINT64_C(0x3fd74bddb3926321);
#define W5_EXTRAS_RAIM_DOF (1)
#define W5_EXTRAS_RAIM_TESTABLE (true)
#define W5_EXTRAS_RAIM_NORMALIZED_RESIDUAL_COUNT (5)
#define W5_EXTRAS_RAIM_HAS_WORST_SAT (true)
static const char W5_EXTRAS_RAIM_WORST_SAT[] = "G03";
#define W5_EXTRAS_RAIM_WORST_SAT_LEN ((size_t)3)
static const char W5_EXTRAS_RAIM_FIRST_NORMALIZED_SAT[] = "G01";
#define W5_EXTRAS_RAIM_FIRST_NORMALIZED_SAT_LEN ((size_t)3)
static const uint64_t W5_EXTRAS_RAIM_FIRST_NORMALIZED_RESIDUAL_BITS = UINT64_C(0x3fd999999999999a);

/* sidereon_core::quality::raim on the same residuals over variances
 * 0.09, 0.16, 0.25, 0.36, 0.49 m^2 under the default Solution weights.
 */
static const uint64_t W5_EXTRAS_RAIM_VARIANCES_BITS[5] = { UINT64_C(0x3fb70a3d70a3d70a), UINT64_C(0x3fc47ae147ae147b), UINT64_C(0x3fd0000000000000), UINT64_C(0x3fd70a3d70a3d70a), UINT64_C(0x3fdf5c28f5c28f5c) };
#define W5_EXTRAS_RAIM_VARIANCES_BITS_COUNT ((size_t)5)
#define W5_EXTRAS_RAIM_SOLUTION_FAULT_DETECTED (false)
static const uint64_t W5_EXTRAS_RAIM_SOLUTION_TEST_STATISTIC_BITS = UINT64_C(0x400d9c71c71c71c8);
static const uint64_t W5_EXTRAS_RAIM_SOLUTION_FIRST_NORMALIZED_RESIDUAL_BITS = UINT64_C(0x3ff5555555555556);
#define W5_EXTRAS_RAIM_SOLUTION_WITHOUT_VARIANCES_REFUSED (true)

/* SurfaceMet::default and the Saastamoinen/Niell troposphere at 0.5 rad.
 */
static const uint64_t W5_EXTRAS_MET_PRESSURE_HPA_BITS = UINT64_C(0x408faa0000000000);
static const uint64_t W5_EXTRAS_MET_TEMPERATURE_K_BITS = UINT64_C(0x4072026666666666);
static const uint64_t W5_EXTRAS_MET_RELATIVE_HUMIDITY_BITS = UINT64_C(0x3fe0000000000000);
static const uint64_t W5_EXTRAS_ZENITH_DRY_M_BITS = UINT64_C(0x400276f0695ed68c);
static const uint64_t W5_EXTRAS_ZENITH_WET_M_BITS = UINT64_C(0x3fb604c12e54e8d6);
static const uint64_t W5_EXTRAS_MAPPING_DRY_BITS = UINT64_C(0x40009e7bd5a35647);
static const uint64_t W5_EXTRAS_MAPPING_WET_BITS = UINT64_C(0x4000a79a0b8f28fb);
static const uint64_t W5_EXTRAS_SLANT_DELAY_BITS = UINT64_C(0x4013e5310eb609ff);

/* sidereon_core::tides at 2020-06-24 12 h.
 */
static const uint64_t W5_EXTRAS_SOLID_EARTH_TIDE_M_BITS[3] = { UINT64_C(0x3fc7d8325c8c6f93), UINT64_C(0x3fb11892f1c4f04d), UINT64_C(0x3fb8dff97f6fcba0) };
#define W5_EXTRAS_SOLID_EARTH_TIDE_M_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_OCEAN_TIDE_ZERO_BLQ_M_BITS[3] = { UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000) };
#define W5_EXTRAS_OCEAN_TIDE_ZERO_BLQ_M_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_POLE_TIDE_M_BITS[3] = { UINT64_C(0xbf4125252a109391), UINT64_C(0xbf45ade990c61fc0), UINT64_C(0xbf44ab8593202176) };
#define W5_EXTRAS_POLE_TIDE_M_BITS_COUNT ((size_t)3)

/* sidereon_core::astro angles, eclipse and Sun/Moon ephemerides.
 */
static const uint64_t W5_EXTRAS_SUN_ANGLE_DEG_BITS = UINT64_C(0x4066800000000000);
static const uint64_t W5_EXTRAS_MOON_ANGLE_DEG_BITS = UINT64_C(0x4066800000000000);
static const uint64_t W5_EXTRAS_SUN_ELEVATION_DEG_BITS = UINT64_C(0x4056800000000000);
static const uint64_t W5_EXTRAS_PHASE_ANGLE_DEG_BITS = UINT64_C(0x4066800000000000);
static const uint64_t W5_EXTRAS_EARTH_ANGULAR_RADIUS_DEG_BITS = UINT64_C(0x40506aa7bd84cf91);
static const uint64_t W5_EXTRAS_ECLIPSE_SHADOW_FRACTION_BITS = UINT64_C(0x0000000000000000);
#define W5_EXTRAS_ECLIPSE_STATUS SIDEREON_ECLIPSE_STATUS_SUNLIT
static const uint64_t W5_EXTRAS_SUN_ECI_021_M_BITS[3] = { UINT64_C(0x421909b6eb2cbaa0), UINT64_C(0xc23ee5153e71a686), UINT64_C(0xc22ac91e5c13070c) };
#define W5_EXTRAS_SUN_ECI_021_M_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_MOON_ECI_021_M_BITS[3] = { UINT64_C(0xc1a6b7ce3c7d665b), UINT64_C(0x41b1e3eaad2a2126), UINT64_C(0x41a265ff3e3b101b) };
#define W5_EXTRAS_MOON_ECI_021_M_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_SUN_ECI_BATCH_M_BITS[6] = { UINT64_C(0x4218ace85a89c0b2), UINT64_C(0xc23ee8d314393260), UINT64_C(0xc22acd4230008616), UINT64_C(0xc2011511205c6687), UINT64_C(0x4240364c5e33d816), UINT64_C(0x422c1c94d9494c85) };
#define W5_EXTRAS_SUN_ECI_BATCH_M_BITS_COUNT ((size_t)6)
static const uint64_t W5_EXTRAS_MOON_ECI_BATCH_M_BITS[6] = { UINT64_C(0xc1b163925b933186), UINT64_C(0xc1afcaa4fa57acad), UINT64_C(0xc192153ea903eeb9), UINT64_C(0xc1af0771c7967d25), UINT64_C(0x41ac9e3ecd3524e1), UINT64_C(0x419f1a69c6be1c5c) };
#define W5_EXTRAS_MOON_ECI_BATCH_M_BITS_COUNT ((size_t)6)
static const uint64_t W5_EXTRAS_SUN_ECEF_BATCH_M_BITS[6] = { UINT64_C(0x423f841e0d2043d8), UINT64_C(0x41dd00d16872e789), UINT64_C(0xc22acce695cc9f88), UINT64_C(0x424015df5baf3786), UINT64_C(0xc2124be7c2247862), UINT64_C(0x422c1c97140bd6f5) };
#define W5_EXTRAS_SUN_ECEF_BATCH_M_BITS_COUNT ((size_t)6)
static const uint64_t W5_EXTRAS_MOON_ECEF_BATCH_M_BITS[6] = { UINT64_C(0x41a8f2b6f07b0564), UINT64_C(0xc1b3fc87c8b643b1), UINT64_C(0xc192144fa2de3f16), UINT64_C(0x41b13124086f5035), UINT64_C(0x41a87c2db94302d0), UINT64_C(0x419f1ae7a3a5e448) };
#define W5_EXTRAS_MOON_ECEF_BATCH_M_BITS_COUNT ((size_t)6)

/* Gibbs, Herrick-Gibbs, Battin and the conjunction functions on the
 * Vallado-style inputs test_iod_lambert_conjunction passes.
 */
static const uint64_t W5_EXTRAS_GIBBS_V2_BITS[3] = { UINT64_C(0x0000000000000000), UINT64_C(0x40161fe50d8ba65a), UINT64_C(0xc014c468e6847d53) };
#define W5_EXTRAS_GIBBS_V2_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_HGIBBS_V2_BITS[3] = { UINT64_C(0xc019c42793ede3c8), UINT64_C(0x400e38712bcc6860), UINT64_C(0xbffb8771d99cba40) };
#define W5_EXTRAS_HGIBBS_V2_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_LAMBERT_V1_BITS[3] = { UINT64_C(0xbfebd3e3a1e586ba), UINT64_C(0x40195732c3364c49), UINT64_C(0x0000000000000000) };
#define W5_EXTRAS_LAMBERT_V1_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_LAMBERT_V2_BITS[3] = { UINT64_C(0xc00b3f7a4959dfa8), UINT64_C(0x4015a5e0292d8081), UINT64_C(0x0000000000000000) };
#define W5_EXTRAS_LAMBERT_V2_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_ENCOUNTER_MISS_KM_BITS = UINT64_C(0x3fa9999f90a16604);
static const uint64_t W5_EXTRAS_ENCOUNTER_RELATIVE_SPEED_KM_S_BITS = UINT64_C(0x402e002bb0afb780);
static const uint64_t W5_EXTRAS_COLLISION_PC_BITS = UINT64_C(0x3f8325223e846429);
static const uint64_t W5_EXTRAS_COLLISION_MISS_KM_BITS = UINT64_C(0x3fa9999f90a16604);

/* sidereon_core::astro::time::civil on 2020-06-25 12:00:00.
 */
static const uint64_t W5_EXTRAS_CIVIL_J2000_S_BITS = UINT64_C(0x41c34352c0000000);
static const uint64_t W5_EXTRAS_SPLIT_JD_J2000_S_BITS = UINT64_C(0x0000000000000000);
static const int64_t W5_EXTRAS_CIVIL_ROUND_TRIP[6] = { 2020, 6, 25, 12, 0, 0 };
#define W5_EXTRAS_CIVIL_ROUND_TRIP_COUNT ((size_t)6)

/* carrier_phase::smooth_code and smooth_iono_free_code, default slip
 * options, window cap 100; an absent value is NaN as the binding writes it.
 */
static const uint64_t W5_EXTRAS_SMOOTH_P_M_BITS[4] = { UINT64_C(0x417312d000000000), UINT64_C(0x417312dbe0000000), UINT64_C(0x417312e7c0000000), UINT64_C(0x417312f3a0000000) };
#define W5_EXTRAS_SMOOTH_P_M_BITS_COUNT ((size_t)4)
static const size_t W5_EXTRAS_SMOOTH_WINDOW[4] = { 1, 1, 1, 1 };
#define W5_EXTRAS_SMOOTH_WINDOW_COUNT ((size_t)4)
static const bool W5_EXTRAS_SMOOTH_RESET[4] = { 0, 1, 1, 1 };
#define W5_EXTRAS_SMOOTH_RESET_COUNT ((size_t)4)
static const uint64_t W5_EXTRAS_IONO_FREE_SMOOTH_P_M_BITS[4] = { UINT64_C(0x417312cfffffffff), UINT64_C(0x417312d6a87dbf26), UINT64_C(0x417312dd50fb7e4b), UINT64_C(0x417312e3f9793d72) };
#define W5_EXTRAS_IONO_FREE_SMOOTH_P_M_BITS_COUNT ((size_t)4)
static const uint64_t W5_EXTRAS_IONO_FREE_P_IF_M_BITS[4] = { UINT64_C(0x417312cfffffffff), UINT64_C(0x417312d6a87dbf26), UINT64_C(0x417312dd50fb7e4b), UINT64_C(0x417312e3f9793d72) };
#define W5_EXTRAS_IONO_FREE_P_IF_M_BITS_COUNT ((size_t)4)
static const uint64_t W5_EXTRAS_IONO_FREE_L_IF_M_BITS[4] = { UINT64_C(0x41721ea910ee5be8), UINT64_C(0x41721eb4f0ec6faf), UINT64_C(0x41721ec0d0ea8377), UINT64_C(0x41721eccb0e8973f) };
#define W5_EXTRAS_IONO_FREE_L_IF_M_BITS_COUNT ((size_t)4)
static const uint64_t W5_EXTRAS_ECCENTRIC_ANOMALY_RAD_BITS = UINT64_C(0x3fe0279f2dd929e9);
#define W5_EXTRAS_ECCENTRIC_ANOMALY_ITERATIONS (3)

/* sidereon_core::astro::cdm on fixtures/cdm/ccsds_example2.{kvn,xml}; an
 * absent number is NaN as the binding writes it.
 */
static const uint64_t W5_EXTRAS_CDM_MISS_DISTANCE_M_BITS = UINT64_C(0x4086580000000000);
static const uint64_t W5_EXTRAS_CDM_RELATIVE_SPEED_M_S_BITS = UINT64_C(0x40ccd50000000000);
static const uint64_t W5_EXTRAS_CDM_COLLISION_PROBABILITY_BITS = UINT64_C(0x3f09596d599fae87);
static const uint64_t W5_EXTRAS_CDM_HARD_BODY_RADIUS_M_BITS = UINT64_C(0x7ff8000000000000);
static const uint64_t W5_EXTRAS_CDM_OBJECT1_POSITION_BITS[3] = { UINT64_C(0x40a41431b280f12c), UINT64_C(0x40a1894f4f93bc0a), UINT64_C(0x40b8897f7b7c7821) };
#define W5_EXTRAS_CDM_OBJECT1_POSITION_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_CDM_OBJECT1_VELOCITY_BITS[3] = { UINT64_C(0x4011acd1ee300512), UINT64_C(0x4013558d8a1f5bc3), UINT64_C(0xc00c36d56f4c82d4) };
#define W5_EXTRAS_CDM_OBJECT1_VELOCITY_BITS_COUNT ((size_t)3)
static const uint64_t W5_EXTRAS_CDM_OBJECT1_COVARIANCE_RTN_BITS[6] = { UINT64_C(0x4044b5c28f5c28f6), UINT64_C(0xc0212872b020c49c), UINT64_C(0x40a3ca0000000000), UINT64_C(0xc0372147ae147ae1), UINT64_C(0x402ab851eb851eb8), UINT64_C(0x4051beb851eb851f) };
#define W5_EXTRAS_CDM_OBJECT1_COVARIANCE_RTN_BITS_COUNT ((size_t)6)
#define W5_EXTRAS_CDM_KVN_TEXT_LEN (4006)
static const char W5_EXTRAS_CDM_TCA[] = "2010-03-13T22:37:52.618";
#define W5_EXTRAS_CDM_TCA_LEN ((size_t)23)
static const char W5_EXTRAS_CDM_OBJECT1_REF_FRAME[] = "EME2000";
#define W5_EXTRAS_CDM_OBJECT1_REF_FRAME_LEN ((size_t)7)
static const char W5_EXTRAS_CDM_OBJECT2_COVARIANCE_METHOD[] = "CALCULATED";
#define W5_EXTRAS_CDM_OBJECT2_COVARIANCE_METHOD_LEN ((size_t)10)
static const char W5_EXTRAS_CDM_OBJECT1_MANEUVERABLE[] = "YES";
#define W5_EXTRAS_CDM_OBJECT1_MANEUVERABLE_LEN ((size_t)3)
#define W5_EXTRAS_CDM_OBJECT1_HAS_VELOCITY_COVARIANCE (true)
#define W5_EXTRAS_CDM_OBJECT2_HAS_VELOCITY_COVARIANCE (true)
#define W5_EXTRAS_CDM_XML_OK (true)
static const char W5_EXTRAS_CDM_XML_ERROR_VARIANT[] = "";
#define W5_EXTRAS_CDM_XML_ERROR_VARIANT_LEN ((size_t)0)

/* RinexClock::parse(fixtures/clk/synthetic_rinex_clock.clk) and the writer.
 */
#define W5_EXTRAS_RINEX_CLOCK_SATELLITE_COUNT (2)
#define W5_EXTRAS_RINEX_CLOCK_TEXT_LEN (631)
#define W5_EXTRAS_CIVIL_TO_GPS_AVAILABLE (true)
static const uint64_t W5_EXTRAS_CIVIL_TO_GPS_SECONDS_BITS = UINT64_C(0x41d307aae0000000);

/* GRG SP3 G01 at its middle epoch and one DGNSS base observation formed
 * as test_sp3_coupled forms it.
 */
static const uint64_t W5_EXTRAS_G01_MID_POSITION_M_BITS[3] = { UINT64_C(0x416445abe3a5e353), UINT64_C(0xc172b643c570a3d7), UINT64_C(0xc16b67ae7547ae15) };
#define W5_EXTRAS_G01_MID_POSITION_M_BITS_COUNT ((size_t)3)
#define W5_EXTRAS_G01_MID_HAS_CLOCK (true)
static const uint64_t W5_EXTRAS_G01_MID_CLOCK_S_BITS = UINT64_C(0x3ef06410e60d9e39);
#define W5_EXTRAS_DGNSS_CORRECTION_COUNT (1)
#define W5_EXTRAS_DGNSS_CORRECTED_COUNT (1)
#define W5_EXTRAS_DGNSS_DROPPED_COUNT (0)

/* broadcast_comparison::compare and compare_window for G01 at the COD SP3
 * middle epoch, as test_broadcast_comparison forms the epochs.
 */
#define W5_EXTRAS_COMPARE_OK (true)
#define W5_EXTRAS_COMPARE_OVERALL_COUNT (1)
#define W5_EXTRAS_COMPARE_SATELLITE_COUNT (1)
#define W5_EXTRAS_COMPARE_WINDOW_OK (true)
#define W5_EXTRAS_COMPARE_WINDOW_OVERALL_COUNT (2)

#endif /* SIDEREON_W5_EXTRAS_PINS_H */
