/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/valgen (bin w5_sp3_exact) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W5_SP3_EXACT_PINS_H
#define SIDEREON_W5_SP3_EXACT_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


/* parse_exact_sp3 of the GRG product for 2020-06-24, 01D, 15M, agency GRGS.
 */
#define W5_SP3_EXACT_GRG_LOAD_OK (true)
#define W5_SP3_EXACT_GRG_LOAD_COVERAGE SIDEREON_EXACT_SP3_COVERAGE_HALF_OPEN
#define W5_SP3_EXACT_GRG_EPOCH_COUNT (96)
#define W5_SP3_EXACT_GRG_DECLARED_EPOCH_COUNT (96)
#define W5_SP3_EXACT_GRG_DECLARED_START_PRESENT (true)
static const uint64_t W5_SP3_EXACT_GRG_DECLARED_START_J2000_S_BITS = UINT64_C(0x41c34255a0000000);
static const uint64_t W5_SP3_EXACT_GRG_FIRST_EPOCH_J2000_S_BITS = UINT64_C(0x41c34255a0000000);
#define W5_SP3_EXACT_GRG_VALIDATE_OK (true)
#define W5_SP3_EXACT_GRG_VALIDATE_COVERAGE SIDEREON_EXACT_SP3_COVERAGE_HALF_OPEN

/* parse_exact_sp3 of the GRG prefix with each terminal record of
 * fixtures/sp3-terminal-record-v1.json, in corpus order: success, coverage,
 * and the refusal text the binding appends to its message.
 */
#define W5_SP3_EXACT_TERMINAL_CASE_COUNT (19)
static const char *const W5_SP3_EXACT_TERMINAL_NAMES[19] = { "bare_lf", "bare_crlf", "bare_no_separator", "one_space_lf", "gfz_37_spaces_lf", "esa_77_spaces_lf", "esa_77_spaces_crlf", "esa_77_spaces_no_separator", "over_policy_width", "tab_padding", "eofx", "eof_space_x", "leading_space", "lone_cr", "double_cr_before_lf", "absent", "ascii_blank_tail", "tab_tail", "data_tail" };
static const bool W5_SP3_EXACT_TERMINAL_OK[19] = { 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 };
#define W5_SP3_EXACT_TERMINAL_OK_COUNT ((size_t)19)
static const bool W5_SP3_EXACT_TERMINAL_HALF_OPEN[19] = { 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 };
#define W5_SP3_EXACT_TERMINAL_HALF_OPEN_COUNT ((size_t)19)
static const char *const W5_SP3_EXACT_TERMINAL_ERRORS[19] = { "", "", "", "", "", "", "", "", "SP3 product contains a malformed EOF record at line 7319 (81 bytes)", "SP3 product contains a malformed EOF record at line 7319 (4 bytes)", "SP3 product contains a malformed EOF record at line 7319 (4 bytes)", "SP3 product contains a malformed EOF record at line 7319 (5 bytes)", "SP3 product contains a malformed EOF record at line 7319 (4 bytes)", "SP3 product contains a malformed EOF record at line 7319 (4 bytes)", "SP3 product contains a malformed EOF record at line 7319 (4 bytes)", "SP3 product is missing its EOF record", "", "SP3 product contains nonblank records after EOF", "SP3 product contains nonblank records after EOF" };

/* ExactSp3Request construction from literal tokens and from catalog
 * identities.
 */
#define W5_SP3_EXACT_REQUEST_24H_OK (false)
static const char W5_SP3_EXACT_REQUEST_24H_ERROR_VARIANT[] = "NonCanonicalSampleToken";
#define W5_SP3_EXACT_REQUEST_24H_ERROR_VARIANT_LEN ((size_t)23)
#define W5_SP3_EXACT_REQUEST_07D_OK (true)
static const char W5_SP3_EXACT_REQUEST_07D_ERROR_VARIANT[] = "";
#define W5_SP3_EXACT_REQUEST_07D_ERROR_VARIANT_LEN ((size_t)0)
#define W5_SP3_EXACT_REQUEST_IGS_SP3_IDENTITY_OK (true)
static const char W5_SP3_EXACT_REQUEST_IGS_SP3_IDENTITY_ERROR_VARIANT[] = "";
#define W5_SP3_EXACT_REQUEST_IGS_SP3_IDENTITY_ERROR_VARIANT_LEN ((size_t)0)
#define W5_SP3_EXACT_REQUEST_IGS_NAV_IDENTITY_OK (false)
static const char W5_SP3_EXACT_REQUEST_IGS_NAV_IDENTITY_ERROR_VARIANT[] = "WrongProductFamily";
#define W5_SP3_EXACT_REQUEST_IGS_NAV_IDENTITY_ERROR_VARIANT_LEN ((size_t)18)
#define W5_SP3_EXACT_GFZ_IDENTITY_LOAD_OK (true)
#define W5_SP3_EXACT_GFZ_IDENTITY_LOAD_COVERAGE SIDEREON_EXACT_SP3_COVERAGE_HALF_OPEN
#define W5_SP3_EXACT_GFZ_LITERAL_LOAD_OK (false)
static const char W5_SP3_EXACT_GFZ_LITERAL_LOAD_ERROR_VARIANT[] = "DeclaredStartMismatch";
#define W5_SP3_EXACT_GFZ_LITERAL_LOAD_ERROR_VARIANT_LEN ((size_t)21)

/* Sp3::parse of the truncated IGS product, then validate_exact_sp3 for
 * 2026-04-30, 01D, 15M, agency IGS.
 */
#define W5_SP3_EXACT_TRUNCATED_EPOCH_COUNT (11)
#define W5_SP3_EXACT_TRUNCATED_DECLARED_EPOCH_COUNT (96)
#define W5_SP3_EXACT_TRUNCATED_VALIDATE_OK (false)
static const char W5_SP3_EXACT_TRUNCATED_VALIDATE_ERROR_VARIANT[] = "DeclaredEpochCountMismatch";
#define W5_SP3_EXACT_TRUNCATED_VALIDATE_ERROR_VARIANT_LEN ((size_t)26)
#define W5_SP3_EXACT_MALFORMED_LOAD_OK (false)
static const char W5_SP3_EXACT_MALFORMED_LOAD_ERROR_VARIANT[] = "Parse";
#define W5_SP3_EXACT_MALFORMED_LOAD_ERROR_VARIANT_LEN ((size_t)5)

/* Sp3::to_sp3_string of FINE_BASE_SP3.
 */
#define W5_SP3_EXACT_FINE_BASE_WRITE_OK (false)
static const char W5_SP3_EXACT_FINE_BASE_WRITE_ERROR_VARIANT[] = "PrecisionNotRepresentable";
#define W5_SP3_EXACT_FINE_BASE_WRITE_ERROR_VARIANT_LEN ((size_t)25)
static const char W5_SP3_EXACT_FINE_BASE_FIELD[] = "pos/vel base";
#define W5_SP3_EXACT_FINE_BASE_FIELD_LEN ((size_t)12)
#define W5_SP3_EXACT_FINE_BASE_COLUMNS (10)
#define W5_SP3_EXACT_FINE_BASE_DECIMALS (7)
static const uint64_t W5_SP3_EXACT_FINE_BASE_NUMBER_BITS = UINT64_C(0x3ff4000002af31dc);

/* merge of CLOCK_ONLY_SP3 with itself, min_agree 1, clock_min_common 1.
 */
#define W5_SP3_EXACT_MERGE_EPOCH_AGREEMENT_COUNT (1)
#define W5_SP3_EXACT_MERGE_SATELLITES (0)
#define W5_SP3_EXACT_MERGE_POSITION_RMS_PRESENT (false)
#define W5_SP3_EXACT_MERGE_POSITION_MAX_PRESENT (false)
#define W5_SP3_EXACT_MERGE_CLOCK_RMS_PRESENT (true)
static const uint64_t W5_SP3_EXACT_MERGE_CLOCK_RMS_S_BITS = UINT64_C(0x0000000000000000);
#define W5_SP3_EXACT_MERGE_CLOCK_MAX_PRESENT (true)
static const uint64_t W5_SP3_EXACT_MERGE_CLOCK_MAX_S_BITS = UINT64_C(0x0000000000000000);
#define W5_SP3_EXACT_SUMMARY_POSITION_RMS_PRESENT (false)
#define W5_SP3_EXACT_SUMMARY_POSITION_MAX_PRESENT (false)
#define W5_SP3_EXACT_SUMMARY_CLOCK_RMS_PRESENT (true)
static const uint64_t W5_SP3_EXACT_SUMMARY_CLOCK_RMS_S_BITS = UINT64_C(0x0000000000000000);
#define W5_SP3_EXACT_SUMMARY_CLOCK_MAX_PRESENT (true)
static const uint64_t W5_SP3_EXACT_SUMMARY_CLOCK_MAX_S_BITS = UINT64_C(0x0000000000000000);

#endif /* SIDEREON_W5_SP3_EXACT_PINS_H */
