/* sidereon-core revision e2fb3dfdc392d23087ed8aa1ee028a0056b4021b */
/* Generated by tests/valgen (bin w5_wave2) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W5_WAVE2_PINS_H
#define SIDEREON_W5_WAVE2_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


/* sidereon_core::geodesic::geodesic_inverse and geodesic_direct on geodtest_one.dat.
 */
static const uint64_t W5_WAVE2_GEODESIC_INVERSE_DISTANCE_M_BITS = UINT64_C(0x4161ed1cc1641878);
static const uint64_t W5_WAVE2_GEODESIC_INVERSE_INITIAL_AZIMUTH_DEG_BITS = UINT64_C(0x406604072b591ce8);
static const uint64_t W5_WAVE2_GEODESIC_INVERSE_FINAL_AZIMUTH_DEG_BITS = UINT64_C(0x4065eab2a75aa740);
static const uint64_t W5_WAVE2_GEODESIC_DIRECT_LATITUDE_DEG_BITS = UINT64_C(0xc0481506d32bf4ec);
static const uint64_t W5_WAVE2_GEODESIC_DIRECT_LONGITUDE_DEG_BITS = UINT64_C(0x40170ca4166fa898);
static const uint64_t W5_WAVE2_GEODESIC_DIRECT_FINAL_AZIMUTH_DEG_BITS = UINT64_C(0x4065eab2a75aa740);

/* sidereon_core::frame_catalog::catalog_entry(ITRF2020, ETRF2020) and transform.
 */
static const uint64_t W5_WAVE2_FRAME_ENTRY_REFERENCE_EPOCH_YEAR_BITS = UINT64_C(0x409f7c0000000000);
#define W5_WAVE2_FRAME_ENTRY_HAS_PROVENANCE (true)
static const uint64_t W5_WAVE2_FRAME_TRANSFORM_POSITION_M_BITS[3] = { UINT64_C(0x414ebafafaaf96ab), UINT64_C(0x4112bd96385aba5f), UINT64_C(0x4152c42cbd90ac4e) };
#define W5_WAVE2_FRAME_TRANSFORM_POSITION_M_BITS_COUNT ((size_t)3)
#define W5_WAVE2_FRAME_TRANSFORM_HAS_VELOCITY (true)
static const uint64_t W5_WAVE2_FRAME_TRANSFORM_VELOCITY_M_PER_YEAR_BITS[3] = { UINT64_C(0xbf1d0a95d661cf80), UINT64_C(0x3f1b61fff5a13200), UINT64_C(0x3f2e8d9b41c88c40) };
#define W5_WAVE2_FRAME_TRANSFORM_VELOCITY_M_PER_YEAR_BITS_COUNT ((size_t)3)

/* GeoidGrid::from_egm2008_raster_window then undulation_deg(37.7749, -122.4194).
 */
static const uint64_t W5_WAVE2_EGM2008_UNDULATION_M_BITS = UINT64_C(0xc04014ef7b122a23);

/* sidereon_core::astro::tdm::parse_kvn(annex_e_18.kvn).
 */
#define W5_WAVE2_TDM_SEGMENT_COUNT (2)
#define W5_WAVE2_TDM_RECORD_COUNT (20)
#define W5_WAVE2_TDM_FIRST_OBSERVABLE SIDEREON_TDM_OBSERVABLE_OTHER

/* sidereon_core::ephemeris::fit_sp3_ecef_precise_orbit(G01), default options.
 */
#define W5_WAVE2_ECEF_FIT_COUNT (1)
#define W5_WAVE2_ECEF_FIT_COVARIANCE_KIND SIDEREON_ORBIT_FIT_COVARIANCE_KIND_ESTIMATED

/* Satellite::propagate_with_decay_latch: 1450 min on an empty latch, then 1440
 * and 1450 min on a cleared latch.
 */
#define W5_WAVE2_DECAY_EMPTY_1450_OK (true)
static const char W5_WAVE2_DECAY_EMPTY_1450_ERROR_VARIANT[] = "";
#define W5_WAVE2_DECAY_EMPTY_1450_ERROR_VARIANT_LEN ((size_t)0)
#define W5_WAVE2_DECAY_1440_OK (false)
static const char W5_WAVE2_DECAY_1440_ERROR_VARIANT[] = "Decayed";
#define W5_WAVE2_DECAY_1440_ERROR_VARIANT_LEN ((size_t)7)
#define W5_WAVE2_DECAY_HAS_FIRST_FAILING_EPOCH (true)
static const uint64_t W5_WAVE2_DECAY_FIRST_FAILING_EPOCH_MIN_BITS = UINT64_C(0x4096800000000000);
#define W5_WAVE2_DECAY_AFTER_1450_OK (false)
static const char W5_WAVE2_DECAY_AFTER_1450_ERROR_VARIANT[] = "Decayed";
#define W5_WAVE2_DECAY_AFTER_1450_ERROR_VARIANT_LEN ((size_t)7)

/* sidereon_core::atmosphere::troposphere::tropo_mapping(Niell) at 1 degree.
 */
#define W5_WAVE2_TROPO_LOW_ELEVATION_OK (false)
static const char W5_WAVE2_TROPO_LOW_ELEVATION_ERROR_VARIANT[] = "InvalidInput";
#define W5_WAVE2_TROPO_LOW_ELEVATION_ERROR_VARIANT_LEN ((size_t)12)
static const uint64_t W5_WAVE2_TROPO_MIN_ELEVATION_RAD_BITS = UINT64_C(0x3faacee9f37bebd6);

/* sidereon_core::astro::events::eclipse shadow fractions.
 */
static const uint64_t W5_WAVE2_ECLIPSE_LEGACY_BITS = UINT64_C(0x0000000000000000);
static const uint64_t W5_WAVE2_ECLIPSE_SPHERICAL_BITS = UINT64_C(0x0000000000000000);
static const uint64_t W5_WAVE2_ECLIPSE_OBLATE_BITS = UINT64_C(0x0000000000000000);

/* sidereon_core::quality::wtest_noncentrality_components(0.001, 0.20).
 */
static const uint64_t W5_WAVE2_WTEST_DELTA0_BITS = UINT64_C(0x40108751cbd0bec7);
static const uint64_t W5_WAVE2_WTEST_LAMBDA0_BITS = UINT64_C(0x4031131c0d9309e7);

#endif /* SIDEREON_W5_WAVE2_PINS_H */
