/* sidereon-core revision 47eaf24e39afa71168670664e88361ed41011bc2 */
/* Generated by tests/valgen (bin w6_ccsds_serialize) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_CCSDS_SERIALIZE_PINS_H
#define SIDEREON_W6_CCSDS_SERIALIZE_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* OEM segment counts of the KVN and XML fixtures. */
#define W6_CCSDS_OEM_KVN_SEGMENTS ((size_t)1)
#define W6_CCSDS_OEM_XML_SEGMENTS ((size_t)1)
/* IONEX map epochs. */
#define W6_CCSDS_IONEX_EPOCHS ((size_t)2)
/* RINEX observation header version. */
static const uint64_t W6_CCSDS_RINEX_VERSION_BITS = UINT64_C(0x4008666666666666);

#endif /* SIDEREON_W6_CCSDS_SERIALIZE_PINS_H */
