/* sidereon-core revision 47eaf24e39afa71168670664e88361ed41011bc2 */
/* Generated by tests/valgen (bin w6_constellation) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_CONSTELLATION_PINS_H
#define SIDEREON_W6_CONSTELLATION_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Catalog number of satellite 0. */
static const char W6_CONST_CATALOG0[] = "25544";
/* Fleet TEME states, satellite-major, km and km/s. */
static const uint64_t W6_CONST_POSITION_BITS[24] = { UINT64_C(0x40b8ba0cb0bd0366), UINT64_C(0xc0a05b5dcccf1b89), UINT64_C(0x409399648854658d), UINT64_C(0x40b8c7b4cc797a90), UINT64_C(0xc09c023ac28bd7c8), UINT64_C(0x40990733d7e125b4), UINT64_C(0x40b8b82feaa8065a), UINT64_C(0xc0972cbfbfcd53f0), UINT64_C(0x409e5775c5e39dff), UINT64_C(0x40b88b907fe580cb), UINT64_C(0xc0923bfbbad53262), UINT64_C(0x40a1c1f233ae0386), UINT64_C(0x40b8ba0cb0bd0366), UINT64_C(0xc0a05b5dcccf1b89), UINT64_C(0x409399648854658d), UINT64_C(0x40b8c7b4cc797a90), UINT64_C(0xc09c023ac28bd7c8), UINT64_C(0x40990733d7e125b4), UINT64_C(0x40b8b82feaa8065a), UINT64_C(0xc0972cbfbfcd53f0), UINT64_C(0x409e5775c5e39dff), UINT64_C(0x40b88b907fe580cb), UINT64_C(0xc0923bfbbad53262), UINT64_C(0x40a1c1f233ae0386) };
static const uint64_t W6_CONST_VELOCITY_BITS[24] = { UINT64_C(0x3fde1e1316609b45), UINT64_C(0x4013c4ed69580ce2), UINT64_C(0x40175fd520e19912), UINT64_C(0xbf8fcd3fec5e59fb), UINT64_C(0x40145d90c815d1c7), UINT64_C(0x4016ef54c010bbdf), UINT64_C(0xbfe00cd18dfee170), UINT64_C(0x4014de396035c63b), UINT64_C(0x401663c01dd99da4), UINT64_C(0xbfef8762a1f8a9c6), UINT64_C(0x4015464f2f43021a), UINT64_C(0x4015bdbd44c54b11), UINT64_C(0x3fde1e1316609b45), UINT64_C(0x4013c4ed69580ce2), UINT64_C(0x40175fd520e19912), UINT64_C(0xbf8fcd3fec5e59fb), UINT64_C(0x40145d90c815d1c7), UINT64_C(0x4016ef54c010bbdf), UINT64_C(0xbfe00cd18dfee170), UINT64_C(0x4014de396035c63b), UINT64_C(0x401663c01dd99da4), UINT64_C(0xbfef8762a1f8a9c6), UINT64_C(0x4015464f2f43021a), UINT64_C(0x4015bdbd44c54b11) };
/* Satellites above -90 deg at the first epoch. */
#define W6_CONST_VISIBLE_COUNT ((size_t)2)
/* Look-angle arcs: arc 0 length and every value, satellite-major. */
#define W6_CONST_LOOK_ARC0_LEN ((size_t)4)
#define W6_CONST_LOOK_VALUE_COUNT ((size_t)8)
static const uint64_t W6_CONST_LOOK_AZIMUTH_DEG_BITS[8] = { UINT64_C(0x406ebc751053d012), UINT64_C(0x406eba29d7bb7178), UINT64_C(0x406eb75a02ac35a2), UINT64_C(0x406eb3d736959ab2), UINT64_C(0x406ebc751053d012), UINT64_C(0x406eba29d7bb7178), UINT64_C(0x406eb75a02ac35a2), UINT64_C(0x406eb3d736959ab2) };
static const uint64_t W6_CONST_LOOK_ELEVATION_DEG_BITS[8] = { UINT64_C(0xc03a4156b89b85a7), UINT64_C(0xc038214126d7b04f), UINT64_C(0xc035f87c6a1c0ed8), UINT64_C(0xc033c5014e084fca), UINT64_C(0xc03a4156b89b85a7), UINT64_C(0xc038214126d7b04f), UINT64_C(0xc035f87c6a1c0ed8), UINT64_C(0xc033c5014e084fca) };
static const uint64_t W6_CONST_LOOK_RANGE_KM_BITS[8] = { UINT64_C(0x40b94453adc13745), UINT64_C(0x40b7cc85fda2ac07), UINT64_C(0x40b64e696b01c1f5), UINT64_C(0x40b4ca71e5641e3d), UINT64_C(0x40b94453adc13745), UINT64_C(0x40b7cc85fda2ac07), UINT64_C(0x40b64e696b01c1f5), UINT64_C(0x40b4ca71e5641e3d) };
/* Ground tracks: track 0 length and every point, satellite-major. */
#define W6_CONST_TRACK0_LEN ((size_t)4)
#define W6_CONST_TRACK_VALUE_COUNT ((size_t)8)
static const uint64_t W6_CONST_TRACK_LAT_RAD_BITS[8] = { UINT64_C(0x3fc7f33f6acbabc9), UINT64_C(0x3fceb27010eeaf63), UINT64_C(0x3fd2b1136ea2706c), UINT64_C(0x3fd5ff2786639fc1), UINT64_C(0x3fc7f33f6acbabc9), UINT64_C(0x3fceb27010eeaf63), UINT64_C(0x3fd2b1136ea2706c), UINT64_C(0x3fd5ff2786639fc1) };
static const uint64_t W6_CONST_TRACK_LON_RAD_BITS[8] = { UINT64_C(0xbfed6f736d614f40), UINT64_C(0xbfec2a9158dbc490), UINT64_C(0xbfeadc5ff2cdf7cb), UINT64_C(0xbfe98287c5895470), UINT64_C(0xbfed6f736d614f40), UINT64_C(0xbfec2a9158dbc490), UINT64_C(0xbfeadc5ff2cdf7cb), UINT64_C(0xbfe98287c5895470) };
static const uint64_t W6_CONST_TRACK_HEIGHT_M_BITS[8] = { UINT64_C(0x4118d56cb70ee329), UINT64_C(0x4118d725246ddab7), UINT64_C(0x4118da2cdc5898b6), UINT64_C(0x4118de65c2bfd0a0), UINT64_C(0x4118d56cb70ee329), UINT64_C(0x4118d725246ddab7), UINT64_C(0x4118da2cdc5898b6), UINT64_C(0x4118de65c2bfd0a0) };
/* Fleet passes over one day with the default pass-finder options. */
#define W6_CONST_PASS_COUNT ((size_t)14)

#endif /* SIDEREON_W6_CONSTELLATION_PINS_H */
