/* sidereon-core revision e2fb3dfdc392d23087ed8aa1ee028a0056b4021b */
/* Generated by tests/valgen (bin w6_core_caps) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_CORE_CAPS_PINS_H
#define SIDEREON_W6_CORE_CAPS_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* clock_reference_offset of the product against itself and its alignment, min_common 3. */
#define W6_CC_OFFSET_COUNT ((size_t)96)
static const uint64_t W6_CC_OFFSET0_BITS = UINT64_C(0x0000000000000000);
#define W6_CC_OFFSET0_SATELLITES ((size_t)75)
#define W6_CC_ALIGNED_OFFSET_COUNT ((size_t)96)
/* Reduced orbit fit of G01 (circular secular, 00:00-03:00, 900 s) and drift to 04:00. */
static const uint64_t W6_CC_FIT_ELEMENT_BITS[11] = { UINT64_C(0x4179298a3ec62e3e), UINT64_C(0x0000000000000000), UINT64_C(0x3fef6f09b17da52a), UINT64_C(0x3fefbb64e1a510b9), UINT64_C(0xbe4288bb753977d6), UINT64_C(0xbe40bb91a1f3d1a6), UINT64_C(0xbfe7684187e1ff07), UINT64_C(0x3f236312628afa44), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000) };
#define W6_CC_FIT_N_SAMPLES ((size_t)13)
#define W6_CC_FIT_REQUESTED ((size_t)13)
static const uint64_t W6_CC_FIT_RMS_BITS = UINT64_C(0x40f62c28f5f14672);
static const uint64_t W6_CC_FIT_MAX_BITS = UINT64_C(0x410583ed06567145);
static const uint64_t W6_CC_DRIFT_MAX_BITS = UINT64_C(0x410583ed065663f0);
static const uint64_t W6_CC_DRIFT_RMS_BITS = UINT64_C(0x40f81c91cbbc4b8a);
#define W6_CC_DRIFT_REQUESTED ((size_t)17)
/* DGNSS inputs: receive time, satellites and base/rover pseudoranges. */
static const uint64_t W6_CC_DGNSS_T_RX_BITS = UINT64_C(0x41c3425ca8000000);
#define W6_CC_DGNSS_COUNT ((size_t)18)
static const char *const W6_CC_DGNSS_SATS[18] = { "E01", "E02", "E03", "E04", "E05", "E07", "E08", "E09", "E11", "E12", "E13", "E14", "E15", "E18", "E19", "E21", "E24", "E25" };
static const uint64_t W6_CC_DGNSS_BASE_PR_BITS[18] = { UINT64_C(0x417e6c8787cdcfba), UINT64_C(0x417b7841eb581449), UINT64_C(0x417fe0cdf3bc77dd), UINT64_C(0x417e5bae088a417b), UINT64_C(0x41811dc18b9222e7), UINT64_C(0x41776a7678c7a3d7), UINT64_C(0x4179a6af53e327a4), UINT64_C(0x417fd504e7657b05), UINT64_C(0x417dd3c34917a961), UINT64_C(0x4178aa7a42f51135), UINT64_C(0x417aa76680b1bf4e), UINT64_C(0x41815a66759b3bdb), UINT64_C(0x417eee0911263132), UINT64_C(0x4173e5a363debf35), UINT64_C(0x41792bfd31c88566), UINT64_C(0x417d5021aa6d1abc), UINT64_C(0x417c4d3d9676eef8), UINT64_C(0x417cc496f33ce4f0) };
static const uint64_t W6_CC_DGNSS_ROVER_PR_BITS[18] = { UINT64_C(0x417e6c8bd80bd26a), UINT64_C(0x417b783cf34ed26a), UINT64_C(0x417fe0c9a830cf0d), UINT64_C(0x417e5bb28b4f31bc), UINT64_C(0x41811dc0c85bb1f8), UINT64_C(0x41776a739ad2a608), UINT64_C(0x4179a6aa24a30465), UINT64_C(0x417fd506aad5ea69), UINT64_C(0x417dd3c295355e16), UINT64_C(0x4178aa7addb70aa7), UINT64_C(0x417aa76715cbacac), UINT64_C(0x41815a6535d96f49), UINT64_C(0x417eee086263057c), UINT64_C(0x4173e5a77bd60280), UINT64_C(0x41792c0221564a14), UINT64_C(0x417d5023fee5451e), UINT64_C(0x417c4d3eaf51fe5b), UINT64_C(0x417cc4945fa2b55b) };
/* DGNSS solution. */
static const uint64_t W6_CC_DGNSS_BASELINE_VECTOR_BITS[3] = { UINT64_C(0x404dfffd88ef0000), UINT64_C(0x4048fffd80820000), UINT64_C(0x403e000a766c0000) };
static const uint64_t W6_CC_DGNSS_BASELINE_BITS = UINT64_C(0x4054ea9f185400ca);
static const uint64_t W6_CC_DGNSS_POSITION_BITS[3] = { UINT64_C(0x41314150fffb11de), UINT64_C(0xc1526df8c0013fbf), UINT64_C(0x414e793b00053b36) };
#define W6_CC_DGNSS_DROPPED ((size_t)0)
/* ANTEX antennas. */
#define W6_CC_ANTEX_ANTENNAS ((size_t)10)
/* ANTEX encode: text length, its FNV-1a 64 hash, and the antennas read back. */
#define W6_CC_ANTEX_ENCODED_LEN ((size_t)356033)
#define W6_CC_ANTEX_ENCODED_FNV1A UINT64_C(0xe3bcc0e7ab6c657e)
#define W6_CC_ANTEX_REREAD_ANTENNAS ((size_t)10)
/* RINEX observation helpers, epoch 0. */
static const uint64_t W6_CC_OBS_VERSION_BITS = UINT64_C(0x4008666666666666);
#define W6_CC_OBS_CODE_COUNT ((size_t)90)
static const char W6_CC_OBS_CODE0[] = "C1C";
#define W6_CC_OBS_EPOCH_COUNT ((size_t)2)
#define W6_CC_OBS_EPOCH0_SATS ((size_t)43)
#define W6_CC_OBS_VALUE_COUNT ((size_t)720)
static const char W6_CC_OBS_VALUE0_SAT[] = "G02";
#define W6_CC_OBS_PR_COUNT ((size_t)39)
static const char W6_CC_OBS_PR0_SAT[] = "G02";
static const uint64_t W6_CC_OBS_PR0_BITS = UINT64_C(0x4178a663dbeb851f);
#define W6_CC_OBS_PHASE_COUNT ((size_t)174)
static const char W6_CC_OBS_PHASE0_CODE[] = "L1C";

#endif /* SIDEREON_W6_CORE_CAPS_PINS_H */
