/* sidereon-core revision e2fb3dfdc392d23087ed8aa1ee028a0056b4021b */
/* Generated by tests/valgen (bin w6_exact_cache) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_EXACT_CACHE_PINS_H
#define SIDEREON_W6_EXACT_CACHE_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* ExactCacheSingleFlightOptions::default(), in milliseconds. */
#define W6_EXACT_CACHE_POLL_INTERVAL_MS UINT64_C(50)
#define W6_EXACT_CACHE_HEARTBEAT_INTERVAL_MS UINT64_C(5000)
#define W6_EXACT_CACHE_LIVENESS_TIMEOUT_MS UINT64_C(30000)
#define W6_EXACT_CACHE_WAIT_TIMEOUT_MS UINT64_C(1800000)

#endif /* SIDEREON_W6_EXACT_CACHE_PINS_H */
