/* sidereon-core revision 47eaf24e39afa71168670664e88361ed41011bc2 */
/* Generated by tests/valgen (bin w6_full_coverage) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_FULL_COVERAGE_PINS_H
#define SIDEREON_W6_FULL_COVERAGE_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Two-body and J2 accelerations at the test state. */
static const uint64_t W6_FCOV_TWOBODY_BITS[3] = { UINT64_C(0xbf7e57e3be6ac7a1), UINT64_C(0x3f54faf0d9f7e91d), UINT64_C(0xbf568a6eaab5b8de) };
static const uint64_t W6_FCOV_J2_BITS[3] = { UINT64_C(0xbee07d96c8564cc7), UINT64_C(0x3eb6cddac0311f91), UINT64_C(0xbed4be654c44c07a) };
/* Doppler range rate and ratio, and the L1 shift. */
static const uint64_t W6_FCOV_RANGE_RATE_BITS = UINT64_C(0x3ffe4ddea47f99f8);
static const uint64_t W6_FCOV_RATIO_BITS = UINT64_C(0xbeda7f9f78b447a9);
static const uint64_t W6_FCOV_SHIFT_RANGE_RATE_BITS = UINT64_C(0x3ffe4ddea47f99f8);
static const uint64_t W6_FCOV_SHIFT_HZ_BITS = UINT64_C(0xc0c3708c435e8905);
static const uint64_t W6_FCOV_SHIFT_RATIO_BITS = UINT64_C(0xbeda7f9f78b447a9);
/* RTN-to-ECI covariance (row major) and the input's symmetry and PSD verdicts. */
static const uint64_t W6_FCOV_ECI_COV_BITS[9] = { UINT64_C(0x3ff1e04186cb1a97), UINT64_C(0x3fce6f5449a05b84), UINT64_C(0xbfd5496293a36718), UINT64_C(0x3fce6f5449a05b85), UINT64_C(0x3ffe7c5aafb84791), UINT64_C(0x3fbaf5d24f49de20), UINT64_C(0xbfd5496293a36717), UINT64_C(0x3fbaf5d24f49de1c), UINT64_C(0x4007d1b1e4be4eed) };
#define W6_FCOV_SYMMETRIC true
#define W6_FCOV_PSD true
/* Time metadata. */
static const char W6_FCOV_GPST_ABBREV[] = "GPST";
static const uint64_t W6_FCOV_LEAP_2020_BITS = UINT64_C(0x4042800000000000);
#define W6_FCOV_LEAP_ENTRIES ((size_t)28)
#define W6_FCOV_LEAP_SOURCE_LEN ((size_t)51)
#define W6_FCOV_UT1_ENTRIES ((size_t)19906)
#define W6_FCOV_UT1_SOURCE_LEN ((size_t)52)
static const uint64_t W6_FCOV_UT1_FIRST_JD_TT_BITS = UINT64_C(0x4142a0ea4010c1d7);
static const uint64_t W6_FCOV_UT1_LAST_JD_TT_BITS = UINT64_C(0x4142c7cac01a3d1a);
#define W6_FCOV_UT1_COVERS_MIDPOINT true
/* GNSS week arithmetic. */
#define W6_FCOV_NORMALIZED_WEEK 101
static const uint64_t W6_FCOV_NORMALIZED_TOW_BITS = UINT64_C(0x4014000000000000);
#define W6_FCOV_UNROLLED_WEEK 2149
#define W6_FCOV_WEEK_EPOCH_PRESENT true
#define W6_FCOV_WEEK_EPOCH_JDN INT64_C(2444245)
#define W6_FCOV_WEEK_2020_06_24_PRESENT true
#define W6_FCOV_WEEK_2020_06_24 2111
#define W6_FCOV_SOW_PRESENT true
static const uint64_t W6_FCOV_SOW_BITS = UINT64_C(0x41100c2c00000000);
#define W6_FCOV_SOW_MONTH13_REFUSED true
#define W6_FCOV_SOW_FEB29_2021_REFUSED true
#define W6_FCOV_SOW_HOUR24_REFUSED true
#define W6_FCOV_WEEK_FEB30_PRESENT false
static const uint64_t W6_FCOV_SPLIT_WEEK_BITS = UINT64_C(0x4008000000000000);
static const uint64_t W6_FCOV_SPLIT_SOW_BITS = UINT64_C(0x4045000000000000);
/* Coverage grid at the first epoch: cell (0, 0), mask, counts, max elevation at -90 deg. */
#define W6_FCOV_CELL_OK true
static const uint64_t W6_FCOV_CELL_AZ_BITS = UINT64_C(0x4074c785bb25724c);
static const uint64_t W6_FCOV_CELL_EL_BITS = UINT64_C(0xc04350db4e2390c1);
static const uint64_t W6_FCOV_CELL_RANGE_BITS = UINT64_C(0x40c0d07927e68988);
static const bool W6_FCOV_MASK[2] = { true, true };
static const size_t W6_FCOV_COUNTS[2] = { 1, 1 };
static const uint64_t W6_FCOV_MAX_EL_BITS[2] = { UINT64_C(0xc04350db4e2390c1), UINT64_C(0xc0354d0f0cb00d22) };
/* Constellation helpers. */
#define W6_FCOV_GSAT210_PRESENT true
#define W6_FCOV_GSAT210_PRN 1
#define W6_FCOV_GLONASS730_PRESENT true
#define W6_FCOV_GLONASS730_SLOT 1
#define W6_FCOV_FDMA1_PRESENT true
#define W6_FCOV_FDMA1_CHANNEL 1
/* Strict SP3-id validation of G03 G05 G13 G19, and the base vs NAVCEN-merged diff. */
#define W6_FCOV_STRICT_IDS_OK true
#define W6_FCOV_DIFF_CHANGED true
#define W6_FCOV_DIFF_ADDED ((size_t)0)
#define W6_FCOV_DIFF_REMOVED ((size_t)0)
#define W6_FCOV_DIFF_NORAD_REASSIGNED ((size_t)0)
#define W6_FCOV_DIFF_SP3_ID_CHANGED ((size_t)0)
#define W6_FCOV_DIFF_SVN_CHANGED ((size_t)3)
#define W6_FCOV_DIFF_FDMA_CHANGED ((size_t)0)
#define W6_FCOV_DIFF_ACTIVITY_CHANGED ((size_t)0)
#define W6_FCOV_DIFF_USABILITY_CHANGED ((size_t)1)
#define W6_FCOV_SAME_DIFF_CHANGED false
/* validate_against_sp3 of the merged catalog against the GRG SP3. */
#define W6_FCOV_SP3_VALID false
#define W6_FCOV_SP3_INACTIVE_COUNT ((size_t)1)
static const unsigned short W6_FCOV_SP3_INACTIVE_PRNS[] = { 19 };
static const unsigned int W6_FCOV_SP3_INACTIVE_SYSTEMS[] = { SIDEREON_GNSS_SYSTEM_GPS };
#define W6_FCOV_SP3_DUPLICATE_PRN_COUNT ((size_t)0)
#define W6_FCOV_SP3_DUPLICATE_NORAD_COUNT ((size_t)0)
#define W6_FCOV_SP3_MISSING_COUNT ((size_t)0)
static const char *const W6_FCOV_SP3_MISSING_IDS[] = { "" };
#define W6_FCOV_SP3_EXTRA_COUNT ((size_t)27)
static const char *const W6_FCOV_SP3_EXTRA_IDS[] = { "G01", "G02", "G06", "G07", "G08", "G09", "G10", "G11", "G12", "G14", "G15", "G16", "G17", "G18", "G19", "G20", "G21", "G22", "G24", "G25", "G26", "G27", "G28", "G29", "G30", "G31", "G32" };
/* Piecewise SP3 fit (G01, 3600 s segments) and its drift to 04:00. */
#define W6_FCOV_PW_SP3_REQUESTED ((size_t)13)
#define W6_FCOV_PW_SP3_USED ((size_t)15)
#define W6_FCOV_PW_SP3_SEGMENTS ((size_t)3)
static const uint64_t W6_FCOV_PW_SP3_DRIFT_MAX_BITS = UINT64_C(0x40f076f9855c0026);
static const uint64_t W6_FCOV_PW_SP3_DRIFT_RMS_BITS = UINT64_C(0x40dc64700f041d30);
/* Piecewise TLE fit (2018-07-03 19:30-22:30, 600 s, 3600 s segments). */
#define W6_FCOV_PW_TLE_REQUESTED ((size_t)19)
#define W6_FCOV_PW_TLE_USED ((size_t)21)
#define W6_FCOV_PW_TLE_DRIFT_OK true

#endif /* SIDEREON_W6_FULL_COVERAGE_PINS_H */
