/* sidereon-core revision 8694648892d8ab065d94014e2e21d6cd5054818e */
/* Generated by tests/valgen (bin w6_publication) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_PUBLICATION_PINS_H
#define SIDEREON_W6_PUBLICATION_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* predicted_ionex_line_candidates(2026-09-23, no sample), as JSON. */
static const char W6_PUBLICATION_CANDIDATES_JSON[] = "[{\"center\":\"cod_prd1\",\"date\":\"2026-09-23\",\"sample\":\"01H\",\"issue\":null,\"filename\":\"COD0OPSP0D_20262660000_01D_01H_GIM.INX\",\"url\":\"https://www.aiub.unibe.ch/download/CODE/IONO/PRD/COD0OPSP0D_20262660000_01D_01H_GIM.INX.gz\"},{\"center\":\"cod_prd2\",\"date\":\"2026-09-23\",\"sample\":\"01H\",\"issue\":null,\"filename\":\"COD0OPSP1D_20262660000_01D_01H_GIM.INX\",\"url\":\"https://www.aiub.unibe.ch/download/CODE/IONO/PRD/COD0OPSP1D_20262660000_01D_01H_GIM.INX.gz\"}]";
/* newest_published_product over the recorded listing, per line, as JSON. */
static const char W6_PUBLICATION_NEWEST_COD_PRD1_JSON[] = "{\"date\":\"2026-09-22\",\"issue\":\"0000\",\"filename\":\"COD0OPSP0D_20262650000_01D_01H_GIM.INX\",\"observed_at\":\"2026-09-22T10:00:02Z\"}";
static const char W6_PUBLICATION_NEWEST_COD_PRD2_JSON[] = "{\"date\":\"2026-09-23\",\"issue\":\"0000\",\"filename\":\"COD0OPSP1D_20262660000_01D_01H_GIM.INX\",\"observed_at\":\"2026-09-22T10:00:02Z\"}";
/* parse_archive_listing refuses the error page (true) or reads it (false). */
#define W6_PUBLICATION_ERROR_PAGE_REFUSED true
/* publication_listing_urls(gfz_ult, SP3, 2026-08-04), as JSON. */
static const char W6_PUBLICATION_LISTING_URLS_JSON[] = "[\"https://isdc-data.gfz.de/gnss/products/ultra/w2430/\",\"https://isdc-data.gfz.de/gnss/products/ultra/w2429/\"]";
/* product_solution_class(wum_nrt, SP3). */
#define W6_PUBLICATION_WUM_NRT_SOLUTION_CLASS SIDEREON_SOLUTION_CLASS_NEAR_REAL_TIME

#endif /* SIDEREON_W6_PUBLICATION_PINS_H */
