/* sidereon-core revision e2fb3dfdc392d23087ed8aa1ee028a0056b4021b */
/* Generated by tests/valgen (bin w6_precise_samples) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_PRECISE_SAMPLES_PINS_H
#define SIDEREON_W6_PRECISE_SAMPLES_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Sample count and the interior sample the test predicts around. */
#define W6_PS_SAMPLE_COUNT ((size_t)7200)
static const char W6_PS_MID_SAT[] = "G01";
static const uint64_t W6_PS_MID_EPOCH_BITS = UINT64_C(0x41c342aa00000000);
/* Range predictions from the SP3. */
static const uint64_t W6_PS_SP3_RANGE_BITS[3] = { UINT64_C(0x417b60dc30e33963), UINT64_C(0x417b2ff73f2c1a14), UINT64_C(0x417afe7d45fe49ee) };
static const uint64_t W6_PS_SP3_TRANSMIT_BITS[3] = { UINT64_C(0x41c342a969f3be1e), UINT64_C(0x41c342a9fff3d402), UINT64_C(0x41c342aa95f3ea29) };
static const bool W6_PS_SP3_HAS_CLOCK[3] = { true, true, true };
static const uint64_t W6_PS_SP3_CLOCK_BITS[3] = { UINT64_C(0x3ef0637cab2377bd), UINT64_C(0x3ef06410da18bf16), UINT64_C(0x3ef064a36bc922fc) };
static const uint64_t W6_PS_SP3_SAT_POS_BITS[9] = { UINT64_C(0x41635a86e84669ac), UINT64_C(0xc17272e1081ea1b4), UINT64_C(0xc16cc9f0a60a974c), UINT64_C(0x41644588597a5b60), UINT64_C(0xc172b642fb4649bc), UINT64_C(0xc16b67cbc03630f7), UINT64_C(0x4165233fcd676e2e), UINT64_C(0xc172f7bdb746f840), UINT64_C(0xc169f8306a7a2641) };
/* Range predictions from the source rebuilt from the copied-out samples. */
static const uint64_t W6_PS_SAMPLES_RANGE_BITS[3] = { UINT64_C(0x417b60dc30e33963), UINT64_C(0x417b2ff73f2c1a14), UINT64_C(0x417afe7d45fe49ee) };
static const uint64_t W6_PS_SAMPLES_TRANSMIT_BITS[3] = { UINT64_C(0x41c342a969f3be1e), UINT64_C(0x41c342a9fff3d402), UINT64_C(0x41c342aa95f3ea29) };
static const bool W6_PS_SAMPLES_HAS_CLOCK[3] = { true, true, true };
static const uint64_t W6_PS_SAMPLES_CLOCK_BITS[3] = { UINT64_C(0x3ef0637cab2377bd), UINT64_C(0x3ef06410da18bf17), UINT64_C(0x3ef064a36bc922fd) };
static const uint64_t W6_PS_SAMPLES_SAT_POS_BITS[9] = { UINT64_C(0x41635a86e84669ac), UINT64_C(0xc17272e1081ea1b4), UINT64_C(0xc16cc9f0a60a974c), UINT64_C(0x41644588597a5b60), UINT64_C(0xc172b642fb4649bc), UINT64_C(0xc16b67cbc03630f7), UINT64_C(0x4165233fcd676e2e), UINT64_C(0xc172f7bdb746f840), UINT64_C(0xc169f8306a7a2641) };
/* from_samples refuses an empty set and a single-sample satellite (true). */
#define W6_PS_EMPTY_REFUSED true
#define W6_PS_LONE_REFUSED true

#endif /* SIDEREON_W6_PRECISE_SAMPLES_PINS_H */
