/* sidereon-core revision e2fb3dfdc392d23087ed8aa1ee028a0056b4021b */
/* Generated by tests/valgen (bin w6_robustness) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_ROBUSTNESS_PINS_H
#define SIDEREON_W6_ROBUSTNESS_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Clean FDE: iterations, excluded satellites, used satellites. */
#define W6_ROB_CLEAN_ITERATIONS ((size_t)0)
#define W6_ROB_CLEAN_EXCLUDED_COUNT ((size_t)0)
static const char *const W6_ROB_CLEAN_EXCLUDED[1] = { "" };
#define W6_ROB_CLEAN_USED_COUNT ((size_t)9)
static const char *const W6_ROB_CLEAN_USED[9] = { "G05", "G07", "G09", "G13", "G15", "G18", "G27", "G28", "G30" };
/* FDE with the first used satellite biased by 200 m. */
static const char W6_ROB_BAD_SAT[] = "G05";
#define W6_ROB_CORRUPT_ITERATIONS ((size_t)1)
#define W6_ROB_CORRUPT_EXCLUDED_COUNT ((size_t)1)
static const char *const W6_ROB_CORRUPT_EXCLUDED[1] = { "G05" };
#define W6_ROB_CORRUPT_USED_COUNT ((size_t)8)
static const char *const W6_ROB_CORRUPT_USED[8] = { "G07", "G09", "G13", "G15", "G18", "G27", "G28", "G30" };
/* The accepted corrupted-run solution's detection test. */
#define W6_ROB_CORRUPT_RAIM_FAULT_DETECTED false
#define W6_ROB_CORRUPT_RAIM_TESTABLE true
static const uint64_t W6_ROB_CORRUPT_RAIM_TEST_STATISTIC_BITS = UINT64_C(0x3ff66616fecd0107);
/* FDE with no exclusion budget on the corrupted run: unresolved. */
#define W6_ROB_UNRESOLVED_REASON SIDEREON_FDE_UNRESOLVED_REASON_EXCLUSION_BUDGET_EXHAUSTED
#define W6_ROB_UNRESOLVED_EXCLUDED_COUNT ((size_t)0)
static const char *const W6_ROB_UNRESOLVED_EXCLUDED[1] = { "" };
#define W6_ROB_UNRESOLVED_FAULT_DETECTED true
static const uint64_t W6_ROB_UNRESOLVED_TEST_STATISTIC_BITS = UINT64_C(0x40da0482b48a6952);
#define W6_ROB_UNRESOLVED_USED_COUNT ((size_t)9)
static const char *const W6_ROB_UNRESOLVED_USED[9] = { "G05", "G07", "G09", "G13", "G15", "G18", "G27", "G28", "G30" };
/* Robust (max_outer 2) GRG solve metadata. */
#define W6_ROB_ROBUST_OUTER_ITERATIONS ((size_t)1)
#define W6_ROB_ROBUST_HAS_SCALE true
static const uint64_t W6_ROB_ROBUST_SCALE_BITS = UINT64_C(0x400cf2dcc10c816f);
/* Coarse-search (24 seeds) GRG solve from the geocenter. */
static const uint64_t W6_ROB_COARSE_POSITION_BITS[3] = { UINT64_C(0x41511b0a63f4948d), UINT64_C(0x4120cd6408329d13), UINT64_C(0x41511e646761efcb) };
/* Fallback source kinds: no precise product, then the 2026 wrong-epoch SP3. */
#define W6_ROB_FALLBACK_EMPTY_KIND SIDEREON_FIX_SOURCE_KIND_BROADCAST
#define W6_ROB_FALLBACK_WRONG_EPOCH_KIND SIDEREON_FIX_SOURCE_KIND_BROADCAST

#endif /* SIDEREON_W6_ROBUSTNESS_PINS_H */
