/* sidereon-core revision 47eaf24e39afa71168670664e88361ed41011bc2 */
/* Generated by tests/valgen (bin w6_rtk_rinex) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_RTK_RINEX_PINS_H
#define SIDEREON_W6_RTK_RINEX_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Single-frequency static RINEX RTK baseline. */
static const uint64_t W6_RTKR_STATIC_FLOAT_BASELINE_BITS[3] = { UINT64_C(0xbfef8dac549dd4e0), UINT64_C(0xbfe528ffe8c6a1a5), UINT64_C(0x3ff117af59d283d0) };
static const uint64_t W6_RTKR_STATIC_FIXED_BASELINE_BITS[3] = { UINT64_C(0xbfef895fef6098d2), UINT64_C(0xbfe4e3deec4d0c35), UINT64_C(0x3ff115e70bda0082) };
#define W6_RTKR_STATIC_AMBIGUITY_COUNT ((size_t)11)
#define W6_RTKR_STATIC_N_OBSERVATIONS ((size_t)2058)
#define W6_RTKR_STATIC_INTEGER_STATUS SIDEREON_RTK_INTEGER_STATUS_NOT_FIXED
#define W6_RTKR_STATIC_HAS_RATIO true
static const uint64_t W6_RTKR_STATIC_RATIO_BITS = UINT64_C(0x3ffd9f9e26860106);
#define W6_RTKR_STATIC_SPLIT_ARC_COUNT ((size_t)4)
#define W6_RTKR_STATIC_AMBIGUITY_ID_COUNT ((size_t)11)
/* Static reference-station metadata, first diagnostic and mode report. */
#define W6_RTKR_REF_MODE SIDEREON_STATIC_REFERENCE_STATION_MODE_CARRIER_FIXED
#define W6_RTKR_REF_FIX_STATUS SIDEREON_STATIC_REFERENCE_FIX_STATUS_CARRIER_FIXED
#define W6_RTKR_REF_HAS_CARRIER true
#define W6_RTKR_REF_HAS_CODE false
#define W6_RTKR_REF_HAS_GEODETIC true
#define W6_RTKR_REF_DIAGNOSTIC_COUNT ((size_t)24)
#define W6_RTKR_REF_CARRIER_DIAGNOSTIC_COUNT ((size_t)24)
#define W6_RTKR_REF_MODE_REPORT_COUNT ((size_t)1)
#define W6_RTKR_REF_CARRIER_INTEGER_STATUS SIDEREON_RTK_INTEGER_STATUS_FIXED
#define W6_RTKR_REF_HAS_CARRIER_RATIO true
#define W6_RTKR_REF_DIAG0_MODE SIDEREON_STATIC_REFERENCE_STATION_MODE_CARRIER_FIXED
#define W6_RTKR_REF_DIAG0_USED_SATS ((size_t)9)
#define W6_RTKR_REF_DIAG0_HAS_CODE_RMS true
#define W6_RTKR_REF_DIAG0_HAS_PHASE_RMS true
#define W6_RTKR_REF_REPORT0_MODE SIDEREON_STATIC_REFERENCE_STATION_MODE_CARRIER_FIXED
#define W6_RTKR_REF_REPORT0_STATUS SIDEREON_STATIC_REFERENCE_MODE_STATUS_SOLVED
#define W6_RTKR_REF_REPORT0_USED_EPOCHS ((size_t)24)
#define W6_RTKR_REF_REPORT0_SKIPPED_EPOCHS ((size_t)0)
#define W6_RTKR_REF_REPORT0_USED_MEASUREMENTS ((size_t)432)
#define W6_RTKR_REF_REPORT0_HAS_ERROR false
/* Wide-lane-fixed static RINEX RTK baseline and metadata. */
static const uint64_t W6_RTKR_WL_FLOAT_BASELINE_BITS[3] = { UINT64_C(0xbfefe0fc68289410), UINT64_C(0xbfe5c58f05dc9fba), UINT64_C(0x3ff106a86f04bbd3) };
static const uint64_t W6_RTKR_WL_FIXED_BASELINE_BITS[3] = { UINT64_C(0xbfef6be70a1e4c29), UINT64_C(0xbfe4d1177a54ecbb), UINT64_C(0x3ff0ff8c16c0e61e) };
#define W6_RTKR_WL_AMBIGUITY_COUNT ((size_t)7)
#define W6_RTKR_WL_N_OBSERVATIONS ((size_t)1608)
#define W6_RTKR_WL_INTEGER_STATUS SIDEREON_RTK_INTEGER_STATUS_FIXED
#define W6_RTKR_WL_HAS_RATIO true
static const uint64_t W6_RTKR_WL_RATIO_BITS = UINT64_C(0x4031728ec0947a7f);
#define W6_RTKR_WL_FIXED true
#define W6_RTKR_WL_AMBIGUITY_CYCLE_COUNT ((size_t)7)

#endif /* SIDEREON_W6_RTK_RINEX_PINS_H */
