/* sidereon-core revision 8694648892d8ab065d94014e2e21d6cd5054818e */
/* Generated by tests/valgen (bin w6_ssr_size_policy) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_SSR_SIZE_POLICY_PINS_H
#define SIDEREON_W6_SSR_SIZE_POLICY_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* The RTCM 1060 frame: G30 radial orbit correction 10.0001 m. */
static const unsigned char W6_SSR_SIZE_FRAME[] = {
    0xd3, 0x00, 0x23, 0x42, 0x45, 0x43, 0x8a, 0x00, 0xc0, 0x02, 0x44, 0x17, 0x96, 0x81, 0x86, 0xa1,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x19, 0xec, 0xf9,
};
#define W6_SSR_SIZE_FRAME_LEN ((size_t)41)
#define W6_SSR_SIZE_WEEK 2425
static const uint64_t W6_SSR_SIZE_TOW_S_BITS = UINT64_C(0x41150e2800000000);
static const uint64_t W6_SSR_SIZE_QUERY_J2000_S_BITS = UINT64_C(0x41c8ebdda5000000);
static const uint64_t W6_SSR_SIZE_STALENESS_S_BITS = UINT64_C(0x405e000000000000);
static const char W6_SSR_SIZE_SATELLITE[] = "G30";
static const char W6_SSR_SIZE_NAV[] = "ssr/BRDC00WRD_S_20261820000_G30_G31.rnx";
/* Strict: the correction is refused and its size reported. */
#define W6_SSR_SIZE_STRICT_HAS_STATE false
static const uint64_t W6_SSR_SIZE_ORBIT_M_BITS = UINT64_C(0x4024000d1b71758e);
static const uint64_t W6_SSR_SIZE_CLOCK_M_BITS = UINT64_C(0x0000000000000000);
#define W6_SSR_SIZE_EXCEEDS_LIMIT true
/* Lenient: the correction is applied and reported. */
static const uint64_t W6_SSR_SIZE_LENIENT_POSITION_ECEF_M_BITS[3] = { UINT64_C(0xc1582314c77b491f), UINT64_C(0x416e23e172c68d71), UINT64_C(0xc17330922b4352f5) };
static const uint64_t W6_SSR_SIZE_LENIENT_CLOCK_S_BITS = UINT64_C(0x3f325b1258adaeff);
static const uint64_t W6_SSR_SIZE_REPORT_ORBIT_M_BITS = UINT64_C(0x4024000d1b71758e);
static const uint64_t W6_SSR_SIZE_REPORT_CLOCK_M_BITS = UINT64_C(0x0000000000000000);
#define W6_SSR_SIZE_REPORT_PROVIDER_ID 9
#define W6_SSR_SIZE_REPORT_SOLUTION_ID 1
static const uint64_t W6_SSR_SIZE_REPORT_ORBIT_REF_EPOCH_J2000_S_BITS = UINT64_C(0x41c8ebdda5000000);
static const uint64_t W6_SSR_SIZE_REPORT_CLOCK_REF_EPOCH_J2000_S_BITS = UINT64_C(0x41c8ebdda5000000);
static const uint64_t W6_SSR_SIZE_REPORT_T_J2000_S_BITS = UINT64_C(0x41c8ebdda5000000);

#endif /* SIDEREON_W6_SSR_SIZE_POLICY_PINS_H */
