/* sidereon-core revision 592ca2bd293177bcd901286080baa6350522020f */
/* Generated by tests/valgen (bin w6_sbas_prn) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_SBAS_PRN_PINS_H
#define SIDEREON_W6_SBAS_PRN_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* sbas_prn_to_sat(120), rendered as the binding renders it (to_string). */
static const char W6_SBAS_PRN_120_TOKEN[] = "S20";
#define W6_SBAS_PRN_120_TOKEN_LEN ((size_t)3)
/* sbas_prn_to_sat(119): whether a satellite is named. */
#define W6_SBAS_PRN_119_MAPPED false

#endif /* SIDEREON_W6_SBAS_PRN_PINS_H */
