/* sidereon-core revision 8694648892d8ab065d94014e2e21d6cd5054818e */
/* Generated by tests/valgen (bin w6_track) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_TRACK_PINS_H
#define SIDEREON_W6_TRACK_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* 1D filter from position 0, velocity 1, unit covariance, q 0.1; predict 1 s. */
static const uint64_t W6_TRACK_SPIKE_PREDICTED_POSITION_BITS[1] = { UINT64_C(0x3ff0000000000000) };
static const uint64_t W6_TRACK_SPIKE_PREDICTED_COVARIANCE_BITS[4] = { UINT64_C(0x4000444444444444), UINT64_C(0x3ff0cccccccccccd), UINT64_C(0x3ff0cccccccccccd), UINT64_C(0x3ff199999999999a) };
/* Innovation of a 100 m spike with 0.01 m^2 variance, and the gated update at 0.95. */
static const uint64_t W6_TRACK_SPIKE_INNOVATION_BITS[1] = { UINT64_C(0x4058c00000000000) };
static const uint64_t W6_TRACK_SPIKE_INNOVATION_COVARIANCE_BITS[1] = { UINT64_C(0x400058bf258bf258) };
static const uint64_t W6_TRACK_SPIKE_NIS_BITS = UINT64_C(0x40b2bc93006ae909);
#define W6_TRACK_SPIKE_IN_GATE false
#define W6_TRACK_SPIKE_HAS_UPDATE false
static const uint64_t W6_TRACK_SPIKE_GATE_NIS_BITS = UINT64_C(0x40b2bc93006ae909);
static const uint64_t W6_TRACK_SPIKE_GATE_THRESHOLD_BITS = UINT64_C(0x400ebb4ec31e7ef6);
static const uint64_t W6_TRACK_SPIKE_AFTER_POSITION_BITS[1] = { UINT64_C(0x3ff0000000000000) };
static const uint64_t W6_TRACK_SPIKE_AFTER_COVARIANCE_BITS[4] = { UINT64_C(0x4000444444444444), UINT64_C(0x3ff0cccccccccccd), UINT64_C(0x3ff0cccccccccccd), UINT64_C(0x3ff199999999999a) };
/* Recorded and smoothed epochs, and the last smoothed position. */
#define W6_TRACK_SPIKE_RECORDED_COUNT ((size_t)2)
#define W6_TRACK_SPIKE_SMOOTHED_COUNT ((size_t)2)
static const uint64_t W6_TRACK_SPIKE_LAST_SMOOTHED_POSITION_BITS[1] = { UINT64_C(0x3ff0000000000000) };
/* 3D ECEF filter from the origin, unit covariance, velocity variance 25, q 0.05. */
/* Update of a fix at (1, 0, 0) m with 0.25 m^2 variances. */
#define W6_TRACK_FIX_UPDATED_FRAME SIDEREON_TRACK_COORDINATE_FRAME_ECEF
#define W6_TRACK_FIX_INNOVATION_DIMENSION ((size_t)3)
static const uint64_t W6_TRACK_FIX_NIS_BITS = UINT64_C(0x3fa37e0cfeb35477);
static const uint64_t W6_TRACK_FIX_UPDATED_POSITION_BITS[3] = { UINT64_C(0x3fefb207cc0532ad), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000) };
/* Recorded and smoothed epochs, the first epoch's RTS gain and covariance. */
#define W6_TRACK_FIX_RECORDED_COUNT ((size_t)2)
#define W6_TRACK_FIX_SMOOTHED_COUNT ((size_t)2)
#define W6_TRACK_FIX_FIRST_HAS_GAIN true
#define W6_TRACK_FIX_FIRST_GAIN_LEN ((size_t)36)
static const uint64_t W6_TRACK_FIX_FIRST_COVARIANCE_BITS[36] = { UINT64_C(0x3feec81f3014cacb), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0xbfee74f44df833c0), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x3feec81f3014cacb), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0xbfee74f44df833c0), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x3feec81f3014cacb), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0xbfee74f44df833c0), UINT64_C(0xbfee74f44df833c0), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x3ff34a1231617640), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0xbfee74f44df833c0), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x3ff34a1231617640), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0xbfee74f44df833c0), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x3ff34a1231617640) };
#define W6_TRACK_FIX_LAST_GAIN_LEN ((size_t)0)

#endif /* SIDEREON_W6_TRACK_PINS_H */
