/* sidereon-core revision 8694648892d8ab065d94014e2e21d6cd5054818e */
/* Generated by tests/valgen (bin w6_window_continuity) from sidereon-core. Every value is
 * sidereon-core's own result for the inputs the smoke program uses; a
 * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun
 * tests/run_generators.sh. */
#ifndef SIDEREON_W6_WINDOW_CONTINUITY_PINS_H
#define SIDEREON_W6_WINDOW_CONTINUITY_PINS_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* StencilExtent::for_sp3 of the seam-injected product. */
static const uint64_t W6_WINDOW_STENCIL_BEFORE_S_BITS = UINT64_C(0x40a9c80000000000);
static const uint64_t W6_WINDOW_STENCIL_AFTER_S_BITS = UINT64_C(0x40a9c80000000000);
/* Continuity verdict JSON for the INSIDE_DAY window. */
static const char W6_WINDOW_VERDICT_INSIDE_DAY_JSON[] = "{\"decision\":\"accept\",\"accepted\":true,\"influencing_defects\":[],\"influencing_splices\":[],\"all_defects\":[{\"kind\":\"speed_bound\",\"satellite\":\"G01\",\"from_j2000_s\":646358400.0,\"to_j2000_s\":646358700.0,\"magnitude\":11758.65486992499,\"bound\":6111.346339724744,\"interval_s\":300.0,\"displacement_m\":3527596.460977497,\"implied_speed_m_s\":11758.65486992499,\"bound_m_s\":6111.346339724744}],\"all_splices\":[]}";
/* Continuity verdict JSON for the STRADDLING window. */
static const char W6_WINDOW_VERDICT_STRADDLING_JSON[] = "{\"decision\":\"refuse\",\"accepted\":false,\"influencing_defects\":[{\"kind\":\"speed_bound\",\"satellite\":\"G01\",\"from_j2000_s\":646358400.0,\"to_j2000_s\":646358700.0,\"magnitude\":11758.65486992499,\"bound\":6111.346339724744,\"interval_s\":300.0,\"displacement_m\":3527596.460977497,\"implied_speed_m_s\":11758.65486992499,\"bound_m_s\":6111.346339724744}],\"influencing_splices\":[],\"all_defects\":[{\"kind\":\"speed_bound\",\"satellite\":\"G01\",\"from_j2000_s\":646358400.0,\"to_j2000_s\":646358700.0,\"magnitude\":11758.65486992499,\"bound\":6111.346339724744,\"interval_s\":300.0,\"displacement_m\":3527596.460977497,\"implied_speed_m_s\":11758.65486992499,\"bound_m_s\":6111.346339724744}],\"all_splices\":[]}";
/* Continuity verdict JSON for the STENCIL_BOUNDARY window. */
static const char W6_WINDOW_VERDICT_STENCIL_BOUNDARY_JSON[] = "{\"decision\":\"refuse\",\"accepted\":false,\"influencing_defects\":[{\"kind\":\"speed_bound\",\"satellite\":\"G01\",\"from_j2000_s\":646358400.0,\"to_j2000_s\":646358700.0,\"magnitude\":11758.65486992499,\"bound\":6111.346339724744,\"interval_s\":300.0,\"displacement_m\":3527596.460977497,\"implied_speed_m_s\":11758.65486992499,\"bound_m_s\":6111.346339724744}],\"influencing_splices\":[],\"all_defects\":[{\"kind\":\"speed_bound\",\"satellite\":\"G01\",\"from_j2000_s\":646358400.0,\"to_j2000_s\":646358700.0,\"magnitude\":11758.65486992499,\"bound\":6111.346339724744,\"interval_s\":300.0,\"displacement_m\":3527596.460977497,\"implied_speed_m_s\":11758.65486992499,\"bound_m_s\":6111.346339724744}],\"all_splices\":[]}";
/* Continuity verdict JSON for the OUTSIDE_STENCIL window. */
static const char W6_WINDOW_VERDICT_OUTSIDE_STENCIL_JSON[] = "{\"decision\":\"accept\",\"accepted\":true,\"influencing_defects\":[],\"influencing_splices\":[],\"all_defects\":[{\"kind\":\"speed_bound\",\"satellite\":\"G01\",\"from_j2000_s\":646358400.0,\"to_j2000_s\":646358700.0,\"magnitude\":11758.65486992499,\"bound\":6111.346339724744,\"interval_s\":300.0,\"displacement_m\":3527596.460977497,\"implied_speed_m_s\":11758.65486992499,\"bound_m_s\":6111.346339724744}],\"all_splices\":[]}";
/* The merge report's continuity verdict JSON over epochs 24..72. */
static const char W6_WINDOW_MERGE_VERDICT_JSON[] = "null";
/* next_issue_due(igs_ult, SP3, 2026-08-04T02:59:59), as JSON. */
static const char W6_WINDOW_NEXT_ISSUE_JSON[] = "{\"identity\":{\"family\":\"sp3\",\"analysis_center\":\"igs_ult\",\"publisher\":\"IGS\",\"solution_class\":\"ultra_rapid\",\"campaign\":\"OPS\",\"filename_version\":0,\"date\":\"2026-08-03\",\"issue\":\"0000\",\"span\":\"02D\",\"sample\":\"15M\",\"official_filename\":\"IGS0OPSULT_20262150000_02D_15M_ORB.SP3\",\"format\":\"SP3\",\"format_version\":null,\"prediction_horizon_days\":null},\"due_at\":\"2026-08-04T03:00:00Z\",\"covers\":{\"observed\":{\"from\":\"2026-08-03T00:00:00Z\",\"until\":\"2026-08-04T00:00:00Z\"},\"predicted\":{\"from\":\"2026-08-04T00:00:00Z\",\"until\":\"2026-08-05T00:00:00Z\"}}}";
/* next_issue_due(wum_nrt, SP3, 2026-08-04T00:00:00) is refused (true). */
#define W6_WINDOW_WUM_NRT_NEXT_ISSUE_REFUSED true

#endif /* SIDEREON_W6_WINDOW_CONTINUITY_PINS_H */
