// One-off generator: parse the committed reference RINEX-3 observation file (the
// crx2rnx-decoded ESBC obs trim) via sidereon-core and emit rinex_fixture.h, so
// the C RINEX-OBS smoke test reproduces the engine's parsed version, epoch count,
// and sampled observation values bit-for-bit. The .rnx file itself is the golden;
// this just transcribes a deterministic sample of what the engine parses from it.

use sidereon_core::rinex::observations::RinexObs;

const RNX_FILE: &str = "ESBC00DNK_R_20201770000_01D_30S_MO_trim.rnx";

fn rnx_text() -> String {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../../../sidereon/crates/sidereon-core",
        "/tests/fixtures/obs/ESBC00DNK_R_20201770000_01D_30S_MO_trim.rnx"
    );
    std::fs::read_to_string(path).expect("read reference RINEX obs fixture")
}

fn bits(x: f64) -> String {
    format!("UINT64_C({:#018x})", x.to_bits())
}

fn main() {
    let text = rnx_text();
    let obs = RinexObs::parse(&text).expect("parse reference RINEX obs");

    // Deterministic sample: walk epochs in order; for each epoch take the first
    // satellite (ascending id) and the first observation code with a present
    // value, until a handful of samples are collected.
    struct Sample {
        epoch_index: usize,
        sat: String,
        code: String,
        value: f64,
    }
    // Cap samples per epoch so every epoch contributes, which exercises the C
    // accessor's epoch indexing for each epoch (not just epoch 0).
    const PER_EPOCH: usize = 8;
    let mut samples: Vec<Sample> = Vec::new();
    for (epoch_index, epoch) in obs.epochs().iter().enumerate() {
        let mut this_epoch = 0usize;
        for (sat, values) in epoch.sats.iter() {
            if this_epoch >= PER_EPOCH {
                break;
            }
            let codes = match obs.obs_codes(sat.system) {
                Some(codes) => codes,
                None => continue,
            };
            // Take the first present value for this satellite, sampling across
            // satellites to exercise several codes/systems within the epoch.
            for (idx, value) in values.iter().enumerate() {
                if let (Some(v), true) = (value.value, idx < codes.len()) {
                    samples.push(Sample {
                        epoch_index,
                        sat: sat.to_string(),
                        code: codes[idx].clone(),
                        value: v,
                    });
                    this_epoch += 1;
                    break;
                }
            }
        }
    }
    assert!(samples.len() >= 8, "expected several observation samples");
    assert!(
        samples.iter().any(|s| s.epoch_index > 0),
        "expected samples from more than one epoch"
    );

    let mut o = String::new();
    o.push_str("/* Generated by tests/rinexgen from the committed reference RINEX-3\n");
    o.push_str(" * observation fixture (crx2rnx-decoded ESBC obs trim) via sidereon-core.\n");
    o.push_str(" * The C smoke test parses the same .rnx (and the decoded .crx) and asserts\n");
    o.push_str(" * the engine's version, epoch count, and sampled observation values\n");
    o.push_str(" * bit-for-bit. Do not edit by hand; rerun the generator. */\n");
    o.push_str("#ifndef SIDEREON_RINEX_FIXTURE_H\n#define SIDEREON_RINEX_FIXTURE_H\n\n");
    o.push_str("#include <stdint.h>\n#include <stddef.h>\n\n");
    o.push_str(&format!("#define RINEX_OBS_FILE \"{RNX_FILE}\"\n"));
    o.push_str(&format!("static const uint64_t RINEX_VERSION_BITS = {};\n", bits(obs.header().version)));
    o.push_str(&format!("#define RINEX_EPOCH_COUNT {}\n\n", obs.epochs().len()));

    o.push_str("typedef struct {\n");
    o.push_str("    size_t epoch_index;\n");
    o.push_str("    const char *sat;\n");
    o.push_str("    const char *code;\n");
    o.push_str("    uint64_t value_bits;\n");
    o.push_str("} RinexObsSample;\n\n");
    o.push_str(&format!("#define RINEX_SAMPLE_COUNT {}\n", samples.len()));
    o.push_str("static const RinexObsSample RINEX_SAMPLES[RINEX_SAMPLE_COUNT] = {\n");
    for s in &samples {
        o.push_str("    {\n");
        o.push_str(&format!("        .epoch_index = {},\n", s.epoch_index));
        o.push_str(&format!("        .sat = \"{}\",\n", s.sat));
        o.push_str(&format!("        .code = \"{}\",\n", s.code));
        o.push_str(&format!("        .value_bits = {},\n", bits(s.value)));
        o.push_str("    },\n");
    }
    o.push_str("};\n\n");
    o.push_str("#endif /* SIDEREON_RINEX_FIXTURE_H */\n");

    print!("{o}");
    eprintln!("version {} epochs {} samples {}", obs.header().version, obs.epochs().len(), samples.len());
}
