//! Helpers the valgen binaries share. Each binary prints one C header to
//! stdout; see Cargo.toml.

/// The sidereon-core revision checked against this crate's locked graph by
/// tests/run_generators.sh.
pub const CORE_REVISION: &str = include_str!("../../CORE_REVISION");

/// The binding's tests directory (bindings/c/tests).
pub const TESTS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/..");

/// Fixture tree supplied by the source-validated runner, or locked metadata's
/// package tree when this binary is run directly.
pub fn core_fixtures() -> String {
    if let Ok(path) = std::env::var("SIDEREON_CORE_FIXTURES") {
        return path;
    }
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());
    let output = std::process::Command::new(cargo)
        .args([
            "metadata",
            "--locked",
            "--format-version",
            "1",
            "--manifest-path",
            concat!(env!("CARGO_MANIFEST_DIR"), "/Cargo.toml"),
        ])
        .output()
        .expect("run cargo metadata");
    assert!(output.status.success(), "cargo metadata failed");
    let metadata: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("cargo metadata JSON");
    let manifest = metadata["packages"]
        .as_array()
        .expect("packages")
        .iter()
        .find(|package| package["name"] == "sidereon-core")
        .and_then(|package| package["manifest_path"].as_str())
        .expect("sidereon-core in cargo metadata")
        .to_string();
    let dir = std::path::Path::new(&manifest)
        .parent()
        .expect("sidereon-core crate directory")
        .join("tests")
        .join("fixtures");
    dir.to_str().expect("UTF-8 fixture path").to_string()
}

/// A binding test fixture path, relative to bindings/c/tests.
pub fn tests_path(relative: &str) -> String {
    format!("{TESTS}/{relative}")
}

/// Read a text file, panicking with its path.
pub fn read(path: &str) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|err| panic!("read {path}: {err}"))
}

/// Read a file's bytes, panicking with its path.
pub fn read_bytes(path: &str) -> Vec<u8> {
    std::fs::read(path).unwrap_or_else(|err| panic!("read {path}: {err}"))
}

/// `UINT64_C(0x...)`, the exact bit pattern of a double.
pub fn bits(value: f64) -> String {
    format!("UINT64_C({:#018x})", value.to_bits())
}

/// A C string literal holding `text` exactly (ASCII only).
pub fn c_string(text: &str) -> String {
    let mut out = String::from("\"");
    for c in text.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c if c.is_ascii() && !c.is_ascii_control() => out.push(c),
            c => panic!("character {c:?} outside the C literal set"),
        }
    }
    out.push('"');
    out
}

/// The text of the C string literals that follow `marker` in the C source
/// file `source` (a path), up to the next `;`: the adjacent literals joined,
/// with `\n`, `\"` and `\\` escapes read.
pub fn c_string_literals(source: &str, marker: &str) -> String {
    let source = read(source);
    let start = source
        .find(marker)
        .unwrap_or_else(|| panic!("{marker} in C source"));
    let end = start + source[start..].find(';').expect("end of literal");
    let mut text = String::new();
    let mut chars = source[start + marker.len()..end].chars();
    let mut in_literal = false;
    while let Some(c) = chars.next() {
        match (in_literal, c) {
            (false, '"') => in_literal = true,
            (true, '"') => in_literal = false,
            (true, '\\') => match chars.next().expect("escaped character") {
                'n' => text.push('\n'),
                't' => text.push('\t'),
                'r' => text.push('\r'),
                other => text.push(other),
            },
            (true, c) => text.push(c),
            (false, _) => {}
        }
    }
    text
}

/// Start a generated header: the revision comment, a generated-by note and
/// the include guard with the standard includes.
pub fn header_start(bin: &str, guard: &str) {
    println!("/* sidereon-core revision {} */", CORE_REVISION.trim());
    println!("/* Generated by tests/valgen (bin {bin}) from sidereon-core. Every value is");
    println!(" * sidereon-core's own result for the inputs the smoke program uses; a");
    println!(" * double is its exact IEEE-754 bit pattern. Do not edit by hand; rerun");
    println!(" * tests/run_generators.sh. */");
    println!("#ifndef {guard}");
    println!("#define {guard}");
    println!();
    println!("#include <stdbool.h>");
    println!("#include <stddef.h>");
    println!("#include <stdint.h>");
    println!();
}

/// Close the include guard `header_start` opened.
pub fn header_end(guard: &str) {
    println!();
    println!("#endif /* {guard} */");
}
