// One-off generator: reproduce sidereon-core's velocity range_rate golden
// scenario (velocity.rs module test) and emit velocity_fixture.h for the C
// smoke test. The synthesized observations are deterministic functions of the
// committed SP3 fixture + the test constants, computed via the engine's own
// `predict`, so the C binding feeding these same values reproduces the engine's
// frozen solution bit-for-bit.

use sidereon_core::constants::{C_M_S, F_L1_HZ};
use sidereon_core::ephemeris::Sp3;
use sidereon_core::observables::{predict, PredictOptions};
use sidereon_core::GnssSatelliteId;
use sidereon_core::GnssSystem;
use sidereon_core::velocity::{
    range_rate_to_doppler, solve, VelocityObservable, VelocityObservation, VelocitySolveOptions,
};

const T_RX_J2000_S: f64 = 646_272_000.0;
const RECEIVER: [f64; 3] = [4_500_000.0, 500_000.0, 4_500_000.0];
const V_TRUE: [f64; 3] = [12.0, -7.0, 3.0];
const DRIFT_TRUE: f64 = 1.0e-9;
const SP3_FILE: &str = "GRG0MGXFIN_20201760000_01D_15M_ORB.SP3";

fn sp3_fixture() -> Sp3 {
    // Resolve the committed core SP3 fixture relative to this generator crate,
    // through the sibling engine checkout the binding is built against.
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../../../sidereon/crates/sidereon-core",
        "/tests/fixtures/sp3/GRG0MGXFIN_20201760000_01D_15M_ORB.SP3"
    );
    let bytes = std::fs::read(path).expect("read SP3 fixture");
    Sp3::parse(&bytes).expect("parse SP3 fixture")
}

fn visible_gps(sp3: &Sp3) -> Vec<GnssSatelliteId> {
    let planning = PredictOptions {
        light_time: false,
        ..PredictOptions::default()
    };
    sp3.satellites()
        .iter()
        .copied()
        .filter(|sat| sat.system == GnssSystem::Gps)
        .filter(|sat| {
            predict(sp3, *sat, RECEIVER, T_RX_J2000_S, planning)
                .map(|obs| obs.elevation_deg >= 5.0)
                .unwrap_or(false)
        })
        .collect()
}

fn synth_range_rate(sp3: &Sp3, sat: GnssSatelliteId) -> f64 {
    let obs = predict(sp3, sat, RECEIVER, T_RX_J2000_S, PredictOptions::default())
        .expect("predict synthetic observation");
    let e_dot = obs.los_unit[0] * V_TRUE[0] + obs.los_unit[1] * V_TRUE[1] + obs.los_unit[2] * V_TRUE[2];
    obs.range_rate_m_s - e_dot + C_M_S * DRIFT_TRUE
}

fn bits(x: f64) -> String {
    format!("UINT64_C({:#018x})", x.to_bits())
}

fn main() {
    let sp3 = sp3_fixture();
    let sats = visible_gps(&sp3);
    assert!(sats.len() >= 4);

    // Range-rate observations.
    let rr_obs: Vec<VelocityObservation> = sats
        .iter()
        .map(|&sat| VelocityObservation {
            satellite_id: sat,
            value: synth_range_rate(&sp3, sat),
            carrier_hz: F_L1_HZ,
            sat_clock_drift_s_s: 0.0,
        })
        .collect();

    let rr_sol = solve(&sp3, &rr_obs, RECEIVER, T_RX_J2000_S, VelocitySolveOptions::default())
        .expect("range-rate solve");

    // Doppler observations: per-sat GLONASS-channel carriers, mirroring the
    // core test's doppler_path golden.
    let dop_obs: Vec<VelocityObservation> = rr_obs
        .iter()
        .enumerate()
        .map(|(idx, obs)| {
            let k = (idx % 14) as i8 - 7;
            let carrier_hz = sidereon_core::frequencies::rinex_band_frequency_hz(
                GnssSystem::Glonass,
                '1',
                Some(k),
            )
            .expect("GLONASS G1 channel carrier");
            VelocityObservation {
                satellite_id: obs.satellite_id,
                value: range_rate_to_doppler(obs.value, carrier_hz).expect("rr->doppler"),
                carrier_hz,
                sat_clock_drift_s_s: 0.0,
            }
        })
        .collect();
    let dop_sol = solve(
        &sp3,
        &dop_obs,
        RECEIVER,
        T_RX_J2000_S,
        VelocitySolveOptions {
            observable: VelocityObservable::Doppler,
            ..VelocitySolveOptions::default()
        },
    )
    .expect("doppler solve");

    let mut o = String::new();
    o.push_str("/* Generated by tests/velgen from sidereon-core's velocity\n");
    o.push_str(" * range_rate/doppler golden scenario (velocity.rs module test). The C\n");
    o.push_str(" * smoke test feeds these engine-synthesized observations through the C\n");
    o.push_str(" * ABI and asserts the engine's frozen velocity solution bit-for-bit. Do\n");
    o.push_str(" * not edit by hand; rerun the generator. */\n");
    o.push_str("#ifndef SIDEREON_VELOCITY_FIXTURE_H\n#define SIDEREON_VELOCITY_FIXTURE_H\n\n");
    o.push_str("#include <stdint.h>\n#include <stddef.h>\n\n");
    o.push_str(&format!("#define VEL_SP3_FILE \"{SP3_FILE}\"\n"));
    o.push_str(&format!("static const uint64_t VEL_T_RX_J2000_S_BITS = {};\n", bits(T_RX_J2000_S)));
    o.push_str(&format!(
        "static const uint64_t VEL_RECEIVER_BITS[3] = {{ {}, {}, {} }};\n\n",
        bits(RECEIVER[0]),
        bits(RECEIVER[1]),
        bits(RECEIVER[2])
    ));
    o.push_str(&format!("static const uint64_t VEL_F_L1_HZ_BITS = {};\n\n", bits(F_L1_HZ)));

    o.push_str(&format!("#define VEL_OBS_COUNT {}\n", rr_obs.len()));
    o.push_str("static const char *const VEL_SAT_IDS[VEL_OBS_COUNT] = {\n");
    for ob in &rr_obs {
        o.push_str(&format!("    \"{}\",\n", ob.satellite_id));
    }
    o.push_str("};\n\n");
    o.push_str("static const uint64_t VEL_RANGE_RATE_BITS[VEL_OBS_COUNT] = {\n");
    for ob in &rr_obs {
        o.push_str(&format!("    {},\n", bits(ob.value)));
    }
    o.push_str("};\n\n");
    o.push_str("static const uint64_t VEL_DOPPLER_BITS[VEL_OBS_COUNT] = {\n");
    for ob in &dop_obs {
        o.push_str(&format!("    {},\n", bits(ob.value)));
    }
    o.push_str("};\n");
    o.push_str("static const uint64_t VEL_DOPPLER_CARRIER_BITS[VEL_OBS_COUNT] = {\n");
    for ob in &dop_obs {
        o.push_str(&format!("    {},\n", bits(ob.carrier_hz)));
    }
    o.push_str("};\n\n");

    let emit_sol = |o: &mut String, name: &str, sol: &sidereon_core::velocity::VelocitySolution| {
        o.push_str(&format!(
            "static const uint64_t {name}_VELOCITY_BITS[3] = {{ {}, {}, {} }};\n",
            bits(sol.velocity_m_s[0]),
            bits(sol.velocity_m_s[1]),
            bits(sol.velocity_m_s[2])
        ));
        o.push_str(&format!("static const uint64_t {name}_SPEED_BITS = {};\n", bits(sol.speed_m_s)));
        o.push_str(&format!(
            "static const uint64_t {name}_CLOCK_DRIFT_BITS = {};\n",
            bits(sol.clock_drift_s_s)
        ));
        o.push_str(&format!("#define {name}_USED_COUNT {}\n", sol.used_sats.len()));
        o.push_str(&format!("static const char *const {name}_USED_IDS[{name}_USED_COUNT] = {{\n"));
        for s in &sol.used_sats {
            o.push_str(&format!("    \"{}\",\n", s));
        }
        o.push_str("};\n");
        o.push_str(&format!(
            "static const uint64_t {name}_RESIDUAL_BITS[{name}_USED_COUNT] = {{\n"
        ));
        for (_, r) in &sol.residuals_m_s {
            o.push_str(&format!("    {},\n", bits(*r)));
        }
        o.push_str("};\n\n");
    };
    emit_sol(&mut o, "VEL_RR", &rr_sol);
    emit_sol(&mut o, "VEL_DOP", &dop_sol);

    o.push_str("#endif /* SIDEREON_VELOCITY_FIXTURE_H */\n");

    print!("{o}");
    eprintln!("range-rate velocity {:?} speed {} drift {}", rr_sol.velocity_m_s, rr_sol.speed_m_s, rr_sol.clock_drift_s_s);
}
