// One-off generator: reproduce the inputs of sidereon-core's
// broadcast_spp_fallback_arc integration test (ESBC00DNK DOY177 GPS C1C first
// epoch) and emit broadcast_fixture.h for the C smoke test. The observations and
// solve-input scalars are extracted from the committed RINEX observation fixture
// via the engine's own parser, so the C binding feeding these same values, the
// committed broadcast NAV, and the committed SP3 products reproduces the engine's
// broadcast/fallback behavior.

use sidereon_core::astro::time::model::JulianDateSplit;
use sidereon_core::observables::j2000_seconds_from_split;
use sidereon_core::rinex::observations::{
    observation_values, ObsEpochTime, ObservationFilter, RinexObs,
};
use sidereon_core::GnssSystem;

const CORE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../../../sidereon/crates/sidereon-core/tests/fixtures"
);

const NAV_FILE: &str = "ESBC00DNK_R_20201770000_01D_MN.rnx";
const PRECISE_SP3_FILE: &str = "COD0MGXFIN_20201770000_01D_05M_ORB.SP3";
const PRIOR_SP3_FILE: &str = "GAP_G01_20201760000_15M.sp3";
const WRONG_EPOCH_SP3_FILE: &str = "IGS0OPSFIN_20261200945_02H30M_15M_ORB.SP3";
const OBS_FILE: &str = "ESBC00DNK_R_20201770000_01D_30S_MO_trim.rnx";

// Labeled broadcast-vs-precise single-epoch position delta bound (meters). This
// is the physical broadcast signal-in-space accuracy delta, not a bit-exact
// claim; the core integration test documents and asserts the same 20 m bound.
const BROADCAST_VS_PRECISE_POSITION_BOUND_M: f64 = 20.0;

fn civil_to_julian_split(epoch: ObsEpochTime) -> JulianDateSplit {
    let year = i64::from(epoch.year);
    let month = i64::from(epoch.month);
    let day = i64::from(epoch.day);
    let a = (14 - month) / 12;
    let y = year + 4800 - a;
    let m = month + 12 * a - 3;
    let jdn = day + (153 * m + 2) / 5 + 365 * y + y / 4 - y / 100 + y / 400 - 32_045;
    let jd_whole = jdn as f64 - 0.5;
    let day_seconds =
        f64::from(epoch.hour) * 3600.0 + f64::from(epoch.minute) * 60.0 + epoch.second;
    JulianDateSplit::new(jd_whole, day_seconds / 86_400.0).expect("valid split Julian date")
}

fn bits(x: f64) -> String {
    format!("UINT64_C({:#018x})", x.to_bits())
}

fn main() {
    let obs_text =
        std::fs::read_to_string(format!("{CORE}/obs/{OBS_FILE}")).expect("read ESBC OBS fixture");
    let obs = RinexObs::parse(&obs_text).expect("parse ESBC observation file");
    let epoch = obs.epochs().first().expect("at least one obs epoch");

    let split = civil_to_julian_split(epoch.epoch);
    let t_rx_j2000_s =
        j2000_seconds_from_split(split.jd_whole, split.fraction).expect("valid split");
    let sod = f64::from(epoch.epoch.hour) * 3600.0
        + f64::from(epoch.epoch.minute) * 60.0
        + epoch.epoch.second;
    let day_of_year = 177.0 + sod / 86_400.0;

    let filter = ObservationFilter::from_entries([(GnssSystem::Gps, vec!["C1C".to_string()])]);
    let values = observation_values(&obs, epoch, &filter).expect("observation values");
    let mut sats: Vec<String> = Vec::new();
    let mut pseudoranges: Vec<f64> = Vec::new();
    for (sat, rows) in values {
        if sat.system != GnssSystem::Gps {
            continue;
        }
        if let Some(code_m) = rows.iter().find(|r| r.code == "C1C").and_then(|r| r.value) {
            sats.push(sat.to_string());
            pseudoranges.push(code_m);
        }
    }
    assert!(
        sats.len() >= 5,
        "need a redundant GPS set, got {}",
        sats.len()
    );

    let approx = obs.header().approx_position_m.expect("APPROX POSITION XYZ");
    let initial_guess = [approx[0], approx[1], approx[2], 0.0];

    // Surface met values matching the core integration test's GPS C1C config.
    let pressure_hpa = 1013.25;
    let temperature_k = 288.15;
    let relative_humidity = 0.5;

    let mut o = String::new();
    o.push_str("/* Generated by tests/fbgen from sidereon-core's\n");
    o.push_str(" * broadcast_spp_fallback_arc integration-test inputs (ESBC00DNK DOY177 GPS\n");
    o.push_str(" * C1C first epoch). The C smoke test feeds these engine-extracted\n");
    o.push_str(" * observations and solve inputs, the committed broadcast NAV, and the\n");
    o.push_str(" * committed SP3 products through the C ABI and asserts the engine's\n");
    o.push_str(" * broadcast/fallback source + staleness provenance. Do not edit by hand;\n");
    o.push_str(" * rerun the generator. */\n");
    o.push_str("#ifndef SIDEREON_BROADCAST_FIXTURE_H\n#define SIDEREON_BROADCAST_FIXTURE_H\n\n");
    o.push_str("#include <stdint.h>\n#include <stddef.h>\n\n");

    o.push_str(&format!("#define BC_NAV_FILE \"{NAV_FILE}\"\n"));
    o.push_str(&format!("#define BC_PRECISE_SP3_FILE \"{PRECISE_SP3_FILE}\"\n"));
    o.push_str(&format!("#define BC_PRIOR_SP3_FILE \"{PRIOR_SP3_FILE}\"\n"));
    o.push_str(&format!("#define BC_WRONG_EPOCH_SP3_FILE \"{WRONG_EPOCH_SP3_FILE}\"\n\n"));

    o.push_str(&format!(
        "static const double BC_VS_PRECISE_POSITION_BOUND_M = {BROADCAST_VS_PRECISE_POSITION_BOUND_M:?};\n\n"
    ));

    o.push_str(&format!(
        "static const uint64_t BC_T_RX_J2000_S_BITS = {};\n",
        bits(t_rx_j2000_s)
    ));
    o.push_str(&format!(
        "static const uint64_t BC_T_RX_SOD_S_BITS = {};\n",
        bits(sod)
    ));
    o.push_str(&format!(
        "static const uint64_t BC_DOY_BITS = {};\n",
        bits(day_of_year)
    ));
    o.push_str(&format!(
        "static const uint64_t BC_INITIAL_GUESS_BITS[4] = {{ {}, {}, {}, {} }};\n",
        bits(initial_guess[0]),
        bits(initial_guess[1]),
        bits(initial_guess[2]),
        bits(initial_guess[3])
    ));
    o.push_str(&format!(
        "static const uint64_t BC_PRESSURE_HPA_BITS = {};\n",
        bits(pressure_hpa)
    ));
    o.push_str(&format!(
        "static const uint64_t BC_TEMPERATURE_K_BITS = {};\n",
        bits(temperature_k)
    ));
    o.push_str(&format!(
        "static const uint64_t BC_RELATIVE_HUMIDITY_BITS = {};\n\n",
        bits(relative_humidity)
    ));

    o.push_str(&format!("#define BC_OBS_COUNT {}\n", sats.len()));
    o.push_str("static const char *const BC_SAT_IDS[BC_OBS_COUNT] = {\n");
    for sat in &sats {
        o.push_str(&format!("    \"{sat}\",\n"));
    }
    o.push_str("};\n\n");
    o.push_str("static const uint64_t BC_PSEUDORANGE_BITS[BC_OBS_COUNT] = {\n");
    for pr in &pseudoranges {
        o.push_str(&format!("    {},\n", bits(*pr)));
    }
    o.push_str("};\n\n");

    o.push_str("#endif /* SIDEREON_BROADCAST_FIXTURE_H */\n");

    print!("{o}");
    eprintln!(
        "fbgen: {} GPS C1C obs, t_rx_j2000_s={t_rx_j2000_s}, sod={sod}",
        sats.len()
    );
}
